### ISSUE TITLE
Postgresql support in Exposed

### ISSUE THREAD

**Issue by TCDooM** [JetBrains/Exposed#1]
Hi,
we are trying to make Exposed work with Postgresql... looks like the select and insert queries work, but the creat methods fail due to "show tables" commnad that is not supported...
Postgresql needs some other command for finding the existing tables...
can you please help, Thanks.

ok, fixef it, don't know if it's right but:

fun Table.exists (): Boolean {
    val tableName = this.tableName
    var sql = "show tables"
    var resultSet:java.sql.ResultSet? = null
    if (Session.get().vendor == DatabaseVendor.PostgreSQL) {
        sql = "SELECT tablename FROM pg_catalog.pg_tables"
    }
    resultSet = Session.get().connection.createStatement()?.executeQuery(sql)

    if (resultSet != null) {
        while (resultSet!!.next()) {
            val existingTableName = resultSet!!.getString(1)
            if (existingTableName?.equalsIgnoreCase(tableName) ?: false) {
                return true
            }
        }
    }

    return false
}

**Comment by sdeleuze** [comment]
:+1: for that one, supporting MySQL/PostgreSQL/H2 databases would cover most user needs I guess.
