### ISSUE TITLE
Entity with ID consisting of two columns

### ISSUE THREAD

**Issue by 1fexd** [JetBrains/Exposed#1009]
Hello,

how can I create an `Entity` which encapsulates an ID which consists of two (or more) columns?
I can only pass one Id to `Entity`, but for many-to-many relations with an extra column, the primary key/id would consist of multiple columns, so this would be very useful.

**Comment by SeekDaSky** [comment]
Hi, 

   There is a documentation for that use case [here](https://github.com/JetBrains/Exposed/wiki/DAO#many-to-many-reference). Here is a sample code that works for me to insert a many-to-many reference without fetching the DAOs first.

```kotlin
//given a table named ManyToManyTable that has two columns (id1 and id2) that are the primary key and
//that reference two tables (ReferenceTable1 and ReferenceTable2).
ManyToManyTable.insert{
    this[ManyToManyTable.id1] = EntityID(id1Value,ReferenceTable1)
    this[ManyToManyTable.id2] = EntityID(id2Value,ReferenceTable2)
}
```

**Comment by gringofe** [comment]
When I try to do that, it says `No set method providing array access` for both `id` columns

**Comment by SeekDaSky** [comment]
That's weird, I checked again an I don't have this error, maybe double check your entity mapping ?
