### ISSUE TITLE
Can't add a new batch because columns:  don't have default values. DB defaults don't support in batch inserts

### ISSUE THREAD

**Issue by gringofe** [JetBrains/Exposed#1014]
Hello,

when I try to insert something in a many to many table with an extra column, it just throws the exception above.
I am using MySQL.

My tables look like this:
```
object ManyToManys : UUIDTable("many_to_manys") {
    val table1 = reference("table1", Tables1)
    val table2 = reference("table2", Tables2)
    val position = integer("position")

    override val primaryKey = PrimaryKey(table1, position)
}

class ManyToMany(id: EntityID<UUID>) : UUIDEntity(id) {
    companion object : EntityClass<UUID, ManyToMany>(ManyToManys)

    var table1 by Table1 referencedOn ManyToManys.table1
    var table2 by Table2 referencedOn ManyToManys.table2
    var position by ManyToManys.position
}
```

(I am using this disgusting UUID hack [since Exposed does not support many to many tables with extra columns](https://github.com/JetBrains/Exposed/issues/928))

when I try to insert via

```
ManyToMany.new {
    this.table1 = myTable1
    this.table2 = myTable2
    this.position = myPos
}
```

it crashes with ```org.jetbrains.exposed.sql.statements.BatchDataInconsistentException: Can't add a new batch because columns: many_to_manys.`position` don't have default values. DB defaults don't support in batch inserts``` eventhough I have supplied a position.

**Comment by gringofe** [comment]
Just found the issue: I inserted `myTable1` in the same `transaction` as the insert for `ManyToMany`. I don't know how I am supposed to rollback the changes if I need to use two transactions, but now it works.

**Comment by Tapac** [comment]
This strange, if you create both entities in a single transaction they should persist normally:
```kotlin
transaction {
  val myTable1 = MyTable.new {}
  val myTable2 = MyTable.new {}
  ManyToMany.new {
    this.table1 = myTable1
    this.table2 = myTable2
    this.position = myPos
  }
}
```

**Comment by gringofe** [comment]
Didn't work.

**Comment by stalexxx** [comment]
Having same issue with decimal type

**Comment by Tapac** [comment]
@gringofe , @stalexxx , please share a reproducible sample project on GitHub and I'll debug it.

**Comment by maffelbaffel** [comment]
Had the same Problem because a column was not specified as `nullable` e.g. `description`
```
object Projects : UUIDTable() {
    val title = varchar("title", 32)
    val description = varchar("description", 255)
}
class Project(id: EntityID<UUID>) : UUIDEntity(id) {
    companion object : UUIDEntityClass<Project>(Projects)

    var title by Projects.title
    var description by Projects.description
}
```

Added a project using `Project.new` in my service without setting a value for `description`:
```
transaction {
        Project.new {
            title = model.title
        }
}
```

Changed `description` to nullable with `val description = varchar("description", 255).nullable()`. 
That resolved my problem.

**Comment by evrpg** [comment]
I had a similar situation, in my case using the DSL insert function worked fine but using the ORM new function did not.

Changing the column with the default value in the DB to .nullable() did the trick in the ORM even though it is declared as not null in the DB.
