### ISSUE TITLE
Is Exposed supports async interface ?

### ISSUE THREAD

**Issue by tinycedar** [JetBrains/Exposed#102]
With the release of Kotlin coroutine, we're able to write concurrently executed coroutines even within the same thread. So I am wondering whether Exposed supports async inteface or not ?

**Comment by Tapac** [comment]
jdbc layer works only in synchronous way, so there is not much benefits to replace it with coroutines.
Some DBMS supports async protocols which require to use non-jdbc driver and not always covers ANSI SQL standard, but we are aware of to it and thinking of implementing async-module in parallel with base Exposed.

**Comment by tinycedar** [comment]
@Tapac where can I find any plan of async-module implementation ?

**Comment by Tapac** [comment]
@tinycedar , sad but it's not stated anywhere at the moment. It requires a huge refactoring of existed code base, so we have no real estimations on this.
