### ISSUE TITLE
Confusing slice api distincts same expressions

### ISSUE THREAD

**Issue by mustafin** [JetBrains/Exposed#1020]
I need to be able to insert same expressions in multiple columns using insert from select

Example: 
`Users.insert(Users.slice(Users.name, Users.description, datetimeLiteral(now), datetimeLiteral(now)).select{ ... })`

I need to use `Slice(this, columns)` manually since slice method have distinct columns
`fun slice(vararg columns: Expression<*>): FieldSet = Slice(this, columns.distinct())`

**Comment by Tapac** [comment]
Could you try use `.alias` as a workaround?
