### ISSUE TITLE
documentation: how do cases work within a slice?

### ISSUE THREAD

**Issue by MMShep97** [JetBrains/Exposed#1026]
My question is related to `CaseWhenElse`, and `CaseWhen`, (and specifically how they work with `slice()` in my case). Essentially, how does the logic work within a slice?

### Follow-up information & question(s)
I'm under the impression that the below code is what we want to achieve a similar result with a sql statement (a `case when`). We want the sliced value to be different based on specific conditions.

Based on the below code, we have the expressions (i.e. `if adWeek eq false`), how do we assign those to our table variables to be sliced? It isn't completed, just to show some of the structure.

```

            query = sls
                .join(el, JoinType.CROSS)
                .slice(
                        CaseWhenElse(
                                (
                                CaseWhen(el[Table.valToBeChanged])
                                .When(EqOp(el[EmailList.adWeek], Op.FALSE), `'VALUE TO BE ASSIGNED'` <-- as an expression assigned to the table above?)
                                .Else(
                                    CaseWhen(el[Table.valToBeChanged])
                                    .When(EqOp(el[EmailList.adWeek], Op.TRUE),'VALUE TO BE ASSIGNED' <-- as an expression))
                                ),
                               // <-- default expression val

                     )
                )
```

edit: the related sql
```
Insert Into #tempTable(
	value1,
        value2,
        date1,
        date2)
Select Distinct
	value1
	value2,
	case when  ..... = 0 
		then convert(.......business logic)
		else convert(.......business logic)
		end,
	case when .... = 0
		then convert(.......business logic)
		else convert(.......business logic)
		end
```
edit: looked at #742 (still confused but slightly related)

**Comment by Tapac** [comment]
Maybe I'm not quite understand but is this what you want? :
```kotlin
val case1 = Expression.build { 
    case().
       When(Table.valToBeChanged eq EmailList.adWeek, dateParam(DateTime.now())).
       Else(dateParam(_otherDateValue))
}

**Comment by MMShep97** [comment]
I think somewhat - I'm wanting to utilize a method `getAdWeekDate` within the `when` and `else` bringing in the values from `el[EmailList.adWeek]` and `sls[SharedLocationStore.adBreak]`... is there a way to convert them from Columns? I tried casting as ints but that obviously failed ;D
```
            val case1 = Expression.build {
                Case(sls[SharedLocationStore.adBreak])
                    .When(el[EmailList.adWeek] eq false,
                        intParam(DateUtil.getAdWeekDate(true, false, sls[SharedLocationStore.adBreak]!! as Int, runDate))
                    )
                    .Else(
                        intParam(DateUtil.getAdWeekDate(true, true, sls[SharedLocationStore.adBreak]!! as Int, runDate))
                    )
            }

            val case2 = Expression.build {
                Case(sls[SharedLocationStore.adBreak])
                        .When(el[EmailList.adWeek] eq false,
                                intParam(DateUtil.getAdWeekDate(false, false, sls[SharedLocationStore.adBreak]!! as Int, runDate))
                        )
                        .Else(
                                intParam(DateUtil.getAdWeekDate(false, true, sls[SharedLocationStore.adBreak]!! as Int, runDate))
                        )
            }
```

```
                .slice(
                        sls[SharedLocationStore.storeListId],
                        el[EmailList.emailListId],
                        case1,
                        case2
                     )
```

I want the casewhen to be in the slice. Let me know if this is possible or if I'm talking nonsense. My full select is this:
```
`Select Distinct
	eli_eliid,
	sli_sliid,
	case when eli_adweek = 0
		then convert(int,convert(char(10),dateadd(day,-(datepart(dw,@today)) - 6,@today),112))
		else convert(int,convert(char(10),dateadd(day, lst_ad_break - 8 - datepart(dw,@today),@today),112))
		end,
	case when eli_adweek = 0
		then convert(int,convert(char(10),dateadd(day,6 + (-(datepart(dw,@today)) - 6),@today),112))
		else convert(int,convert(char(10),dateadd(day, 6 + (lst_ad_break - 8 - datepart(dw,@today)),@today),112))
		end
`
```
I'm not sure how to perform the logic in the case when and then have that outputted to the columns from the slice.

**Comment by Tapac** [comment]
What types are `sls` and `el` in your examples?

When you compose your query with Exposed you should operate only values available in a database.
`sls[SharedLocationStore.storeListId]` looks like getting value from some ResultRow.

If you cast something in your code to java types it won't reflect on a query.

**Comment by MMShep97** [comment]
`sls` and `el` were the aliases for our queries.

I confused myself going this route, and most likely was trying to use it with the incorrect use-case. Ended up not having to go this route.

Thank you for your timely responses and help!
