### ISSUE TITLE
Transaction.exec fails when the provided SQL string starts with whitespace

### ISSUE THREAD

**Issue by Ribesg** [JetBrains/Exposed#103]
In short, this does not currently work:
````kotlin
transaction.exec("""
    ALTER TABLE foo
    ADD CONSTRAINT bar
        CHECK (kek=TRUE);
""")
````
This fails [here](https://github.com/JetBrains/Exposed/blob/38d6971fdb8826a540174756d862af85b31cbd91/src/main/kotlin/org/jetbrains/exposed/sql/Transaction.kt#L83) and maybe at different locations, I'm not sure so I'm not opening a PR. One or more `String.trim()` calls are missing, at least where I pointed before the `startsWith` call.

**Comment by Tapac** [comment]
Thank you for reporting. Fixed in master. Will be available soon at bintray
