### ISSUE TITLE
Update github releases

### ISSUE THREAD

**Issue by AllanWang** [JetBrains/Exposed#1034]
As of now, the last tag/release is 0.25.1, vs 0.27.1 on bintray. Is it possible for us to update the tags here?

**Comment by Tapac** [comment]
@AllanWang , that's strange as the tag is here:
```
>git tag --merged origin/master | grep '0.27.1'
0.27.1
```

**Comment by AllanWang** [comment]
![image](https://user-images.githubusercontent.com/6251823/92568746-7b5af080-f234-11ea-8097-6cd4ed012387.png)

It doesn't seem to be on github. Searching for it doesn't net anything either

**Comment by AllanWang** [comment]
Is this project mirrored? Is github the origin?

**Comment by Tapac** [comment]
My fault - I didn't know that Intellij IDEA doesn't push tags by default. It should be solved now. I'll double-check it next time.
