### ISSUE TITLE
Add inline alias function for enumeration

### ISSUE THREAD

**Issue by CommanderTvis** [JetBrains/Exposed#1036]
It would be nice to have more idiomatic alias for enumeration:

```kotlin
public fun <reified T : Enum<T>> Table.enumeration(name: String): Column<T> = enumeration(name, T::class)
```

**Comment by bog-walk** [comment]
[Version 0.38.1](https://github.com/JetBrains/Exposed/blob/main/docs/ChangeLog.md#0381) introduced reified versions of the [enumeration functions](https://github.com/JetBrains/Exposed/blob/main/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt#L608).

If there are any issues with the functions, please consider reporting them on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763).
