### ISSUE TITLE
Can't insert into MySQL table without auto index

### ISSUE THREAD

**Issue by TheChilliPL** [JetBrains/Exposed#1038]
I'm trying to insert a simple row into a table:
```kotlin
                        transaction {
                            GuildPrefixTable.insert {
                                it[id]._value = event.guild.idLong
                                it[prefix] = ""//event.guild.idLong
                            }
                        }
```
it doesn't throw an error but it never actually inserts anything (even if I remove the line setting it[id]._value.
The table is defined as:
```kotlin
object GuildPrefixTable : LongIdTable("guild_prefix") {
    val prefix = text("prefix")
}
class GuildPrefix(id: EntityID<Long>) : LongEntity(id) {
    companion object : LongEntityClass<GuildPrefix>(GuildPrefixTable)
    var prefix by GuildPrefixTable.prefix
}
```
and in MySQL, the table is just `id` (bigint(20), not automatic primary key), `prefix` (tinytext)

**Comment by Tapac** [comment]
You shouldn't set `_value` and just set value to a column like:
` it[id] = event.guild.idLong`

**Comment by TheChilliPL** [comment]
It throws an error about being unable to convert Long to UniqueKey<Long> or so

**Comment by Tapac** [comment]
Which Exposed version do you use?

**Comment by TheChilliPL** [comment]
0.24.1, as was in [*Getting Started* on the Wiki](../wiki/Getting-Started#gradle-kotlin-script), should I use a newer one?

**Comment by Tapac** [comment]
Yes, please with the latest version.

**Comment by TheChilliPL** [comment]
Seems like it does work, thank you!
I'd update the version given on the Getting Started page, it'd help beginners “fix” issues like this one
