### ISSUE TITLE
<select()> doesn't always return rows in order of creation

### ISSUE THREAD

**Issue by neelkamath** [JetBrains/Exposed#1042]
On all the Exposed versions I've tried, including 0.27.1, `select()` and `selectAll()` occasionally don't return rows in order of creation, so I have to manually sort them. Is this expected behavior?

For example, if there are three rows with the primary keys 1, 2, and 3; sometimes they'll be returned as 3, 1, 2 instead. It's difficult to reproduce.

**Comment by Tapac** [comment]
Yes. it's expected behavior as an row order depends on a database implementation and table storage engine. If you need specific order please use [orderBy](https://github.com/JetBrains/Exposed/wiki/DSL#order-by).
