### ISSUE TITLE
Using PrimaryKey fails with h2.Database

### ISSUE THREAD

**Issue by Rotzlucky** [JetBrains/Exposed#1051]
Duplicate of https://github.com/JetBrains/Exposed/issues/841

To reproduce check out https://github.com/Rotzlucky/ExposedH2Example

uses:
`
kotlin_version=1.3.72
ktor_version=1.1.3
exposed_version=0.27.1
h2_version=1.4.197
`

When running the application you get the error message:

`org.jetbrains.exposed.exceptions.ExposedSQLException: org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE USERS ALTER COLUMN ID VARCHAR(190) PRIMARY[*] KEY"; SQL statement:
ALTER TABLE USERS ALTER COLUMN ID VARCHAR(190) PRIMARY KEY [42000-197]`

Error goes away after removing the primaryKey statement from User.kt

Exception doesn't occur when connecting to mysql or sqlite

In an older project, still on exposed 0.13.5 (which brings its own dependency of h2(1.4.197)), the exception doesn't occur either.

**Comment by Tapac** [comment]
Please consider updating to h2 1.4.197 and check the issue again.

**Comment by Rotzlucky** [comment]
Hey!
Thx for the response. But that is the exact version I'm using in the above example.

**Comment by Tapac** [comment]
It fixed in master, will be released soon (this week I guess).
