### ISSUE TITLE
SQLITE use createMissingTablesAndColumns edit table error

### ISSUE THREAD

**Issue by hizhengfu** [JetBrains/Exposed#1058]
[SQLITE_ERROR] SQL error or missing database (too many terms in compound SELECT)
compile group: 'org.xerial', name: 'sqlite-jdbc', version: '3.32.3.2'
kotlin:1.4.0
exposed:0.27.1

**Comment by Tapac** [comment]
Could you please share a tables mapping on which you call `createMissingTablesAndColumns `?

**Comment by hizhengfu** [comment]
`import org.jetbrains.exposed.sql.*
import org.jetbrains.exposed.sql.transactions.transaction

val TestTable = object : Table("test_table") {
    val id = integer("id")
    val name = varchar("name", length = 42)
    val time = long("time").uniqueIndex()

    override val primaryKey = PrimaryKey(id)
}

val Test1Table = object : Table("test_table") {
    val id = integer("id")
    val name = varchar("name", length = 42)
    val time = long("time").uniqueIndex()
    val remarks = text("remarks")

    override val primaryKey = PrimaryKey(id)
}


fun main() {
    Database.connect("jdbc:sqlite:test.db", driver = "org.sqlite.JDBC")

    transaction{
        addLogger(StdOutSqlLogger)

        SchemaUtils.create(TestTable)
        SchemaUtils.createMissingTablesAndColumns(Test1Table)
    }
}`

**Comment by Tapac** [comment]
I've got another error when  running your code:
`[SQLITE_ERROR] SQL error or missing database (Cannot add a NOT NULL column with default value NULL)`
And the fix is to add default value for `remarks`:
`val remarks = text("remarks").default("")`

**Comment by joc-a** [comment]
Hi @hizhengfu, is this still an issue?

**Comment by hizhengfu** [comment]
There's no problem with the test now。
