### ISSUE TITLE
Specify custom TransactionManager instead of ThreadLocalTransactionManager when using `transaction`

### ISSUE THREAD

**Issue by wardhapk** [JetBrains/Exposed#1061]
Is it possible to mention a specific implementation of TransactionManager when using the transaction keyword -
```
transaction {}
```

**Comment by Tapac** [comment]
You can define your specific Transaction manager when call `Database.connect` and then use that database in a transaction block:
```kotlin 
        val db = Database.connect(dataSource) {
            CustomTransactionManager()
        }
        transaction(db) {
            //...
        }
```

**Comment by bog-walk** [comment]
Please reopen this issue if the problem requires more answers.
