### ISSUE TITLE
update with multiple and conditions not working

### ISSUE THREAD

**Issue by TheReprator** [JetBrains/Exposed#1064]
Hi Guyz,

First thanks for this great library, but right now i am stuck in a issue,  whose link is as follows,     
https://stackoverflow.com/questions/64196526/update-with-multiple-and-conditions-with-exposed-ktor

It will be a great, if i get some sort of solution here.

**Comment by TheReprator** [comment]
@yaegor @yole  @topka @kuzuha  Sorry for bothering u guyz, but the following issue is closed
https://github.com/JetBrains/Exposed/issues/1029

but still i am facing this issue with 0.27.1,

**Comment by yole** [comment]
None of the guys you've bothered have anything to do with the issue you're experiencing.

**Comment by Tapac** [comment]
@TheReprator , the issue was released in 0.28.1.
