### ISSUE TITLE
Update GitHub Releases

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/Exposed#1066]
The newest version and tag is 0.27.1, but on GitHub the last release is 0.25.1.
Please update the GitHub releases also on a new release. It is also possible to automate this with GitHub Actions, running on a new tag.

**Comment by Tapac** [comment]
https://github.com/JetBrains/Exposed/tags
Please check the tags for releases. We don't use GitHub releases.

**Comment by hfhbd** [comment]
I do, that's why I noticed the difference. But please then remove all GitHub releases.

**Comment by Tapac** [comment]
I added Releases since 0.25.1 till the last 0.28.1 and will try not to forget to add new releases to Github

**Comment by hfhbd** [comment]
@Tapac Please add the tag 0.29.1 (and the release as well) :)

**Comment by Tapac** [comment]
Sorry, forgot to press publish on Release draft. fixed
