### ISSUE TITLE
Connect with extended properties.

### ISSUE THREAD

**Issue by KennethanCeyer** [JetBrains/Exposed#107]
Hi there.

I am using Kotlin 1.1.1 to make JDBC middle ware RESTful server.

But there's an issue to set `Extended Properties` to connect JDBC.

We are using AWS Athena by database.

So we will connect the server as follows.

```kotlin
Database.connect(
    "jdbc:awsathena://athena.us-east-1.amazonaws.com:443", 
    "com.amazonaws.athena.jdbc.AthenaDriver",
    "ID",
    "PW"
)
```

However we also need to set `s3_staging_dir` property as follow [this documentation](http://docs.aws.amazon.com/athena/latest/ug/connect-with-jdbc.html).

How do i set `Extended Properties` to use Exposed?

Thank you.

**Comment by Tapac** [comment]
@KennethanCeyer , from your link
>You can configure the following options for the JDBC driver. With version 1.0.1 of the driver, you can also pass parameters using the standard JDBC URL syntax, for example jdbc:awsathena://athena.us-west-1.amazonaws.com:443?max_error_retries=20&connection_timeout=20000

**Comment by KennethanCeyer** [comment]
Hello @Tapac 



I solved this issue to append the flag to end of connection url.

"jdbc:~~?s3_staging_dir=~~"

Thank you quick reply.
