### ISSUE TITLE
DatasourceHealthIndicator consumes all the DB connections from the pool when used with Exposed Spring Boot starter

### ISSUE THREAD

**Issue by antonlakida** [JetBrains/Exposed#1077]
In one of our services we are using Exposed as query mapping framework.
Lately we found out that on our environments where the Actuator health 
check is used, application eventually runs out of free DB connections.

We tried to reproduce it and it looks like the `DataSourceHealthIndicator`
does not return the connection to the pool, but only when used together 
with Exposed.

This is tested with Kotlin 1.3-1.4, Exposed 0.26.2-0.28.1

[Example project](https://github.com/antonlakida/connection-leak) that reproduces the issue

**Comment by Tapac** [comment]
Thank you for providing the example project as it helps to localize the problem.

It fixed in master and will be available with the next release.
