### ISSUE TITLE
Suport DUAL table

### ISSUE THREAD

**Issue by SchweinchenFuntik** [JetBrains/Exposed#1081]
is it possible to support this type of table (query)?

example:
```SQL
-- Oracle 
SELECT 1 + 2 FROM DUAl;

-- PostgreSQL
SELECT 1 + 2;
```

Many databases support it or it is possible to emulate it (SQLite)

**Comment by SchweinchenFuntik** [comment]
> PSQL for Table.Dual.

never added for postgres, although it can calculate values without a table.
why is PG not supported?

**Comment by Tapac** [comment]
@SchweinchenFuntik why it's not supported? It works on all supported databases but only Oracle requires it to be explicit.

**Comment by SchweinchenFuntik** [comment]
yes I'm stupid. I read the code incorrectly
