### ISSUE TITLE
Eclipse DSL and DAO examples: "Check your module classpath for missing or conflicting dependencies"

### ISSUE THREAD

**Issue by sp33dy** [JetBrains/Exposed#1082]
Hi there,

I've been forced into the Java 8 to 11 upgrade; something changed in Eclipse this weekend that meant I need to bite the bullet. I've been struggling with gett Exposed working for me over the past couple of days. I'm seeing this type of error:

```
C:\Users\xxx\OneDrive\Documents\Eclipse Workspaces\TestExposed\TestExposed\src\main\kotlin\DSL.kt
	ERROR: Cannot access 'java.io.Serializable' which is a supertype of 'kotlin.Int'. Check your module classpath for missing or conflicting dependencies (97, 34)
	ERROR: Cannot access 'java.io.Serializable' which is a supertype of 'kotlin.Int'. Check your module classpath for missing or conflicting dependencies (97, 34)
```

The DSL.kt is the file found in the github home page. The same type of error message appears for the DAO too. My set-up:

Eclipse: 2020-09 (4.17.0)
Kotlin Plugin: 0.8.21
OpenJDK 15

The above error message occurs for the code after the "join with the foreign key".  It appears to be linked with getting the Id. If I comment out the lines, all is well (in this and the following select):

```
 (Users innerJoin Cities).slice(Users.name, Users.cityId, Cities.name).
                select { Cities.name.eq("St. Petersburg") or Users.cityId.isNull()}.forEach {
//            if (it[Users.cityId] != null) {
//                println("${it[Users.name]} lives in ${it[Cities.name]}")
//           }
//           else {
//                println("${it[Users.name]} lives nowhere")
//           }
        }

```
Is there any direction/advice/suggestion you could offer me? I see many other language error warnings when I compile the DAO example. Once I figure this out, I can upgrade my project, which fails for these dependency issues. 

I've been a Java and Eclipse user for many years, but I JUST don't understand where to look for this type of problem. I'm hoping a configuration value or I need to drop down a package is the answer???? Thanks for your help.

p.s. I configured Maven set this way:

```
	<repositories>
		<repository>
			<id>jcenter</id>
			<name>jcenter</name>
			<url>https://jcenter.bintray.com</url>
		</repository>
	</repositories>

	<dependencies>
		<dependency>
			<groupId>org.jetbrains.kotlin</groupId>
			<artifactId>kotlin-stdlib</artifactId>
			<version>1.4.0</version>
		</dependency>
		<dependency>
			<groupId>org.jetbrains.exposed</groupId>
			<artifactId>exposed-core</artifactId>
			<version>0.28.1</version>
		</dependency>
		<dependency>
			<groupId>org.jetbrains.exposed</groupId>
			<artifactId>exposed-dao</artifactId>
			<version>0.28.1</version>
		</dependency>
		<dependency>
			<groupId>org.jetbrains.exposed</groupId>
			<artifactId>exposed-jdbc</artifactId>
			<version>0.28.1</version>
		</dependency>
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<version>1.4.200</version>
		</dependency>
	</dependencies>

```

**Comment by sp33dy** [comment]
In desperation, I've installed and started to learn how to use IDEA (just feels horrible compared to Eclipse; but I guess that's linked to the decade of use; for many different projects). The example compiles there, so I'm assuming this is probably linked to the kotlin plugin??? The plugin has been great till now, so that's a darn shame! I'm sure someone clever will figure out what the problem is. In the meantime, I will get my wife's app up and running (for her business) in IDEA until this is resolved and move back when it is. Any help would be really appreciated.

**Comment by Tapac** [comment]
Looks like it's not IDEA/Eclipse or Exposed problem but [Kotlin](https://youtrack.jetbrains.com/issue/KT-31052) itself.
Could you try to upgrade kotlin version to 1.4.10 and check will it help or not?
