### ISSUE TITLE
Read Foreign Key ID value without fetching Referenced table

### ISSUE THREAD

**Issue by trebor74hr** [JetBrains/Exposed#1085]
I will start with example:
```
object PersonRepo : IntIdTable(columnName= "PERSON_ID") {
    val firstName = varchar("FIRST_NAME", length=50).nullable()
    val lastName = varchar("LAST_NAME", length=50).nullable()
    ...

class Person(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<Person>(PersonRepo)

    var firstName by PersonRepo.firstName
    var lastName by PersonRepo.lastName
    ...

object WebUserRepo : IntIdTable() {
    val person = reference("PERSON_ID", PersonRepo).nullable()
    val username = varchar("USERNAME", length=50).nullable()
    ...

class WebUser(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<WebUser>(WebUserRepo)

    var person by Person optionalReferencedOn WebUserRepo.person
    var username by WebUserRepo.username
    ...
```

My task is when I read one WebUser I want to check the value of WEB_USER.PERSON_ID column value. Currently I  found only one way to check:
```
val webUser = WebUser.find {...}.first()
if (webUser?.person?.id==100) ...
```
The command webUser?.person will initiate new SQL command to fetch required information from Person table. But the value of foreign key WEBUSER.PERSON_ID already has this value, but I have found no way to read it directly. 

I would suggest to have something like: 
`if (webUser?.personId==100) ...
`
what would read WEBUSER.PERSON_ID value and would not issue any additional SQL command from PERSON table.

**Comment by trebor74hr** [comment]
Double submitted - see #1086

**Comment by neetkee** [comment]
Have you tried `WebUser.readValues[WebUserRepo.person]`?
