### ISSUE TITLE
Read Foreign Key ID value without reading it from Referenced table

### ISSUE THREAD

**Issue by trebor74hr** [JetBrains/Exposed#1086]
I will start with example:
```
object PersonRepo : IntIdTable(columnName= "PERSON_ID") {
    val firstName = varchar("FIRST_NAME", length=50).nullable()
    val lastName = varchar("LAST_NAME", length=50).nullable()
    ...

class Person(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<Person>(PersonRepo)

    var firstName by PersonRepo.firstName
    var lastName by PersonRepo.lastName
    ...

object WebUserRepo : IntIdTable() {
    val person = reference("PERSON_ID", PersonRepo).nullable()
    val username = varchar("USERNAME", length=50).nullable()
    ...

class WebUser(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<WebUser>(WebUserRepo)

    var person by Person optionalReferencedOn WebUserRepo.person
    var username by WebUserRepo.username
    ...
```

My task is when I read one WebUser I want to check the value of WEB_USER.PERSON_ID column value. Currently I  found only one way to check:
```
val webUser = WebUser.find {...}.first()
if (webUser?.person?.id==100) ...
```
The command webUser?.person will initiate new SQL command to fetch required information from Person table. But the value of foreign key WEBUSER.PERSON_ID already has this value, but I have found no way to read it directly. 

I would suggest to have something like: 
`if (webUser?.personId==100) ...
`
what would read WEBUSER.PERSON_ID value and would not issue any additional SQL command from PERSON table.

**Comment by neetkee** [comment]
Have you tried webUser.readValues[WebUserRepo.person]?

**Comment by Tapac** [comment]
First of all, it's strange as I can see from the code there is an early return for the case when the ref is null:
```kotlin
        val refValue = reference.getValue(o, desc)
        return when {
            refValue == null -> null
```
Also, you can define separate personId field and check against it:
```kotlin
val personId by WebUserRepo.person
```

**Comment by trebor74hr** [comment]
A bit late reply :) but this worked: 

`val personId by WebUserRepo.person`

and then I used it like this:
```
val webUser = WebUser.find {...}.first()
if (webUser?.personId==100) ...
```

Thanks!
