### ISSUE TITLE
Index Hints (FORCE INDEX)

### ISSUE THREAD

**Issue by adamu** [JetBrains/Exposed#1089]
Hello. I would like to use Mysql's [index hints](https://dev.mysql.com/doc/refman/8.0/en/index-hints.html), like this (simplified):

```sql
SELECT * FROM my_table FORCE INDEX(PRIMARY)...
```

Is there a way to do this with Exposed?  I tried reading through #118 to see if it was possible, but that seems to be talking about executing fully custom SQL. I just want to add an index hint to an existing Exposed query chain.

Thanks.

**Comment by adamu** [comment]
The correct way is probably to add this functionality to `Query`, but I've worked around this for now by overriding [`Table.describe()`](https://github.com/JetBrains/Exposed/blob/e0a7e63aaa99bd0ec3fa4b79542af8bcb42c96a1/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt#L329) in my table object, which causes `FORCE INDEX` to be injected [here](https://github.com/JetBrains/Exposed/blob/e0a7e63aaa99bd0ec3fa4b79542af8bcb42c96a1/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Query.kt#L103):

```kotlin
override fun describe(s: Transaction, queryBuilder: QueryBuilder) {
    super.describe(s, queryBuilder)
    if (queryBuilder.toString().startsWith("SELECT")) {
        queryBuilder.append(" FORCE INDEX(PRIMARY) ")
    }
}
```

Obviously this is not a long-term solution.

**Comment by bog-walk** [comment]
Using MySQL-specific index hints will become possible in upcoming version 0.53.0 which opens the `Query` class for customization. An example of how to take advantage of the now public `copyTo()`, by creating a custom `Query` subclass for these index hints, has been added to [the site documentation](https://github.com/JetBrains/Exposed/pull/2173/files#diff-af25c948a8575fa83507d6fd0c359d4f613777fe1ed4f5a92f3e2f3f023e1b14R832), which will be synced as part of the upcoming release.
