### ISSUE TITLE
Support for MongoDB?

### ISSUE THREAD

**Issue by GGorAA** [JetBrains/Exposed#1091]
Will be there support for MongoDB in Exposed?

**Comment by gringofe** [comment]
No, this is a SQL library and MongoDB is NoSQL. Consider researching relational vs non-relational databases

**Comment by Tapac** [comment]
@GGorAA , sorry but @gringofe is right - it's impossible to adapt Exposed to work with NoSQL databases.
But you can try to use (kmongo)[https://litote.org/kmongo/] or [kotlin-nosql](https://github.com/cheptsov/kotlin-nosql)
