### ISSUE TITLE
Expose number of inserted and updated rows

### ISSUE THREAD

**Issue by spand** [JetBrains/Exposed#1094]
It seems exposed already has access to number of inserted rows in `InsertStatement`. It would be nice if this could be exposed maybe even as a property `UpdateBuilder.affectedsRow: Int` as a generic property for both inserted and updated rows.

My initial use case for having access to number of inserted rows was to find out if an `insertIgnore {}` failed or not.

**Comment by bog-walk** [comment]
As of version 0.33.1, `InsertStatement` received the `insertedCount` field, which makes accessible the number of inserted rows.

If this is a feature you still believe is worth extending to updated rows, please consider opening a feature request on [YouTrack](
https://youtrack.jetbrains.com/newIssue?project=EXPOSED&c=Type%20Feature
), with a use case example.
