### ISSUE TITLE
Incorrect state for TransactionManager.manager after calling closeAndUnregister

### ISSUE THREAD

**Issue by ZeDavi** [JetBrains/Exposed#1100]
Hi,

I found an unexpected behavior regarding the companion object in `TransactionManager`, that I think might be a bug. 
How to reproduce:

1. Call `Database.connect(dataSource)`
2. Call `transaction(db, statement)` – this will result in the `inTopLevelTransaction(...)` function being called which ends with a `TransactionManager.resetCurrent(null)` call.
3. Call `TransactionManager.closeAndUnregister(database)` (the one that was returned from step 1.)
4. Call `Database.connect(dataSource)` a second time for a new `dataSource`

Now, `TransactionManager.manager` will return the initial `NotInitializedManager` instance, instead of the transaction manager that was created during step 4.

That is because inside the `closeAndUnregister` function in step 3., a value is removed from `managers`, afterwards the current transaction manager is calculated using `managers.first` which returns the bottom `NotInitializedManager`. Therefore `currentThreadManager.remove()` is not called and the current thread manager stays incorrect.

A workaround is calling `TransactionManager.resetCurrent(null)` right after step 3.

**Comment by RationalityFrontline** [comment]
Encountered same problem, thanks for the workaround, hope this simple issue could get fixed soon.

**Comment by Tapac** [comment]
Fixed in master. Thanks for the report.
