### ISSUE TITLE
ExpressionWithColumn<T>.isNull() is not resolved

### ISSUE THREAD

**Issue by yevhenii8** [JetBrains/Exposed#1107]
I write an expression step by step and then combine them in slice(). I don't need `SqlExpressionBuilder` to be specified explicitly in most cases:
```
        val learnedColumn = Sum(
                case().When(WordTable.rate eq 100, intParam(1)).Else(intParam(0)),
                IntegerColumnType()
        )

        val unlearnedColumn = Sum(
                case().When(WordTable.rate neq 100, intParam(1)).Else(intParam(0)),
                IntegerColumnType()
        )
  
        val resultRow = WordTable.slice(learnedColumn, unlearnedColumn)
                .selectAll()
                .first()
```

But It doesn't work with `isNull()` expression:

```
        // fails
        val testIsNullOp1 = Sum(
                    case().When(WordTable.tags.isNull(), intParam(1)).Else(intParam(0)),
                    IntegerColumnType()
            )

        // works correctly
        val testIsNullOp2 = with(SqlExpressionBuilder) {
            Sum(
                    case().When(WordTable.tags.isNull(), intParam(1)).Else(intParam(0)),
                    IntegerColumnType()
            )
        }
```

The expressions above are for example only. It doesn't seem to be a big deal, but a little bit unexpected. Could anyone clarify this ?

**Comment by Tapac** [comment]
The main idea was to create a scope where Exposed functions will be available to not pollute the global namespace.
You can use `Expression.build{}` or `Op.build{} ` instead of `with(SqlExpressionBuilder)` to make you code a bit cleaner.

**Comment by yevhenii8** [comment]
The issue was about inconsistency - some Exposed functions were available in the global namespace whereas some not. It was unclear why I could use `neq` in the global scope and couldn't `isNull()`.
As for 0.29.1 this example is not relevant anymore. Now `isNull()` can be used the same way as `neq` and `eq`. So the issue could be closed.

Thank you!
