### ISSUE TITLE
SELECT single record

### ISSUE THREAD

**Issue by alizarei95** [JetBrains/Exposed#1111]
Hey guys, is there any way to select only one record with kotlin exposed? Currently I'm using below code to select a user from DB, but is there any function like selectSingle() to get an object (not list) ?

```
fun getUser(userId: Int): User? {

    var user: User? = null

    transaction {
        user = UserTable.select { UserTable.id eq userId }.limit(1).map { User.fromRow(it) }[0]
    }

    return user
}
```

It is not duplicate issue , I have not found any solution in issues

**Comment by hfazai** [comment]
You can use `single()` method:
````KOTLIN
fun getUser(userId: Int): User? {

    var user: User? = null

    val user = transaction {
       user = UserTable.select { UserTable.id eq userId }.limit(1).single().let { User.fromRow(it) }
    }

    return user
}
````
**PS** : `single()` will throw `NoSuchElementException` if there is no result and `IllegalArgumentException` if there is more than one resulted row.

also you can ommit the user variable 
````KOTLIN
fun getUser(userId: Int): User = 
        transaction {
                UserTable.select { UserTable.id eq userId }.limit(1).single().let { User.fromRow(it) }
        }
````
