### ISSUE TITLE
How can I orderBy the result of a query from two different tables?

### ISSUE THREAD

**Issue by jrogstad** [JetBrains/Exposed#1115]
I have a Table_A with a has many association to Table_B and Table_C. I'd like to sum up integer columns in each Table_B and Table_C for rows whose parent is found in Table_A into a single result and orderBy this value. Is this possible in Exposed? 

So something like:

```
TableA.selectAll()
  .orderBy( //some query to get a value representing TableB.sales.sum() + TableC.sales.sum())
```

**Comment by Tapac** [comment]
Please try to create an expression and use it in `orderBy`:
```kotlin
val sumExpression = Expression.build { TableB.sales.sum() + TableC.sales.sum() }
orderBy(sumExpression)
```

But I think that your question is more complex. Can you write the query you want to execute in pure SQL?

**Comment by bog-walk** [comment]
If the problem  requires more answers, please consider reopening this issue on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763). If you do so, please also provide more details so we can attempt to assist you further, namely an example showing your table mappings and how you would achieve your expected result using raw SQL.
