### ISSUE TITLE
(Auto) Reconnect to database

### ISSUE THREAD

**Issue by teremyx** [JetBrains/Exposed#1119]
Hi. 
I'm connecting to my database at the start of the program:
`        val config = HikariConfig().apply {
            jdbcUrl = DatabaseConfig.jdbcUrl //"jdbc:mysql://localhost/dbname"
            driverClassName = "com.mysql.cj.jdbc.Driver"
            username = DatabaseConfig.DATABASE_USER
            password = DatabaseConfig.DATABASE_PASSWORD
            maximumPoolSize = 10
        }
        val dataSource = HikariDataSource(config)
        Database.connect(dataSource)`

How can I automatically reconnect if a connection is lost or try connecting (in the background) if no connection can be established?
Is it wise to have a background thread or coroutine running that checks for a connection and automatically reconnects?

**Comment by jnfeinstein** [comment]
I believe Hikari takes care of this seamlessly, no?  I think this is an abstraction layer below Exposed.  My $0.02.

**Comment by Tapac** [comment]
@teremyx , just like @jnfeinstein said - Hikari should handle all of the cases and throws exceptions if connection was closed or unavailable.
