### ISSUE TITLE
How to create a Database for temporary using?

### ISSUE THREAD

**Issue by way-zer** [JetBrains/Exposed#1125]
I am working on a data migrating function. needing to create a connection to old database.
But it effect the global default database.

example code
```kotlin
transaction {
   println(db.name) //print global database
}
val new = Database.connect(....)
transaction {
   println(db.name) //print new database (the default have be effected)
}
```
the Exposed version is 0.24.1 (I don't find fix in release)

**Comment by GiantTreeLP** [comment]
You can simply specify the database in the `transaction` method like so: `transaction(new) { }`

**Comment by way-zer** [comment]
> You can simply specify the database in the `transaction` method like so: `transacion(new) { }`

Yes I can, but my question is that modify the default database in other transaction.

**Comment by Tapac** [comment]
It's expected behavior. Every call of `Database.connect` will make the last connected DB the current. 
As @GiantTreeLP stated you have to define two databases `old and new` and store them in some variables and then use them as a `transaction` parameter to specify which DB to use in the transaction.

**Comment by jnfeinstein** [comment]
I too would love to be able to create a connection w/o affecting the global default.  Especially with Spring there can be little control over the order in which multiple connections are initialized.  All it takes is one slip-up and a developer vaporizes production data.  🙁

**Comment by way-zer** [comment]
> It's expected behavior. Every call of `Database.connect` will make the last connected DB the current.
> As @GiantTreeLP stated you have to define two databases `old and new` and store them in some variables and then use them as a `transaction` parameter to specify which DB to use in the transaction.

In my use case, there are a global database, all transaction should use the global one as default. And i don't want to special it every time because only a little code use another, such as temporarily migrate data from another.

As the name is, ```Database.connect``` is just connect a database, make the global change may cause mistake.

So may create another ```Database.connect``` that don't effect global?

**Comment by jnfeinstein** [comment]
>So may create another Database.connect that don't effect global? Or explicit api that set the global database with highest priority.

Precisely.  My instinct would be `Database.connect(default = false)` and/or
```
val database = Database.connect(...).apply {
  Transaction.defaultDatabase = this
}
```
This would allow you to explicitly set the default database.  As for me, I do not want a default at all, preferring them to be accessed explicitly by references to ensure the correct database is selected.
