### ISSUE TITLE
id not in record set

### ISSUE THREAD

**Issue by leolaudouard** [JetBrains/Exposed#1132]
Hi, I defined this table:

```
object ExampleTable : IdTable<String>() {
    val exampleColumn: Column<String> = varchar("exampleColumn", 40)
    override val id: Column<EntityID<String>> = exampleColumn.entityId()
}
```

However, when calling

`transaction { ExampleTable.selectAll().map { it[ExampleTable.exampleColumn] }`

I get an exception  `ExampleTable.exampleColumn is not in record set`

I can use `transaction { ExampleTable.selectAll().map { it[ExampleTable.id].value }`
But I think it will be error-prone

Might be linked to https://github.com/JetBrains/Exposed/issues/820

If it can help here is a failing unit test

```
@Test
fun `test id and column have different names`() {
    val exampleTable = object : IdTable<String>() {
        val exampleColumn = varchar("example_column", 200)
        override val id = exampleColumn.entityId()
    }

    withTables(exampleTable) {
        val value = "value"
        exampleTable.insert {
            it[exampleColumn] = value
        }

        val resultValues: List<String> = exampleTable.selectAll().map { it[exampleTable.exampleColumn] }

        assertEquals(value, resultValues.first())
    }
}
```

**Comment by Tapac** [comment]
Thank you for the report. Fixed in master.
