### ISSUE TITLE
What is the proper way to query a many to many relation

### ISSUE THREAD

**Issue by wpoulin** [JetBrains/Exposed#1134]
I kinda new with Kotlin and I'm trying to do a query a create an object that contains a list. I have read stuff about eager loading but I'm not quite sure it can be applied to my case. Here's an example

```
object MovieTable : Table() {
    val id = integer("id").autoIncrement().primaryKey()
    val title = text("title")
}

object GenreTable : Table() {
    val id = integer("id").autoIncrement().primaryKey()
    val title = text("title")
}

object MovieGenreTable : Table() {
    val movie = reference("movie_id", MovieTable.id, ReferenceOption.CASCADE).primaryKey()
    val genre = reference("genre_id", GenreTable.id, ReferenceOption.CASCADE).primaryKey()
}

data class Movie(
    val id: Int,
    val title: String,
    val genres: List<Genre>
)

data class Genre (
    val id: Int,
    val title: String
)


```
is there a better way to query a movie with all its genre without having to do 2 queries ( n+1)

```
    fun fetchMovie(title: String) : Movie? {
        return transaction(db) {
            val genre = GenreTable.innerJoin(MovieGenreTable)
                    .innerJoin(MovieTable)
                    .slice(GenreTable.columns)
                    .select { MovieTable.title.eq(title) }
                    .map { it.toGenre() }
            MovieTable
                    .innerJoin (MovieGenreTable)
                    .innerJoin (GenreTable)
                    .select { MovieTable.title.eq(title) }
                    .firstOrNull()
                    ?.toMovie(genre)
        }
    }
    
    fun ResultRow.toMovie(genres: List<Genre>): Movie = Movie(
        id = this[MovieTable.id],
        title = this[MovieTable.title],
        genres = genres
)

fun ResultRow.toGenre(): Genre = Genre(
        id = this[GenreTable.id],
        title = this[GenreTable.title]
)
```

There has to be something I have done wrong ? Could I iterate over the result and create a movie object with all its genres ?

**Comment by Tapac** [comment]
You can but it will fetch all movie fields for every result row + the code becomes a bit uglier (for my taste):
```kotlin
 GenreTable.innerJoin(MovieGenreTable)
         .innerJoin(MovieTable)
         .select { MovieTable.title.eq(title) }
         .groupBy({ it.toMovie(emptyList()) }) { it.toGenre() }
         .entries.firstOrNull()?.let { (movie, genres) ->
               movie.copy(genres = genres)
         }
```

**Comment by wpoulin** [comment]
The more list will be contained in the data class movie the uglier it will become... Lets say I would like to do it for the movies instead of one, is there an other way rather than fetching all movies, loop to get movie id and then map it one by one ?

**Comment by wpoulin** [comment]
> You can but it will fetch all movie fields for every result row + the code becomes a bit uglier (for my taste):
> 
> ```kotlin
>  GenreTable.innerJoin(MovieGenreTable)
>          .innerJoin(MovieTable)
>          .select { MovieTable.title.eq(title) }
>          .groupBy({ it.toMovie(emptyList()) }) { it.toGenre() }
>          .entries.firstOrNull()?.let { (movie, genres) ->
>                movie.copy(genres = genres)
>          }
> ```

The more list will be contained in the data class movie the uglier it will become... Lets say now the Movie would also contains a list of actors, it will only gets uglier right ? I know I got to innerJoin both actor table but how will I be able to map it. I'm trying to figure out how this solution can scale. With that query, I think I won't be able to get a movie if there isn't genre right ?

            GenreTable.innerJoin(MovieGenreTable)
                    .innerJoin(MovieTable)
                    .selectAll()
                    .groupBy({ it.toMovie(emptyList()) }) { it.toGenre() }
                    .entries.map {
                        (movie, genres) ->
                        movie.copy(genres = genres)
                    }
