### ISSUE TITLE
Request : A good documentation website

### ISSUE THREAD

**Issue by kaushalyap** [JetBrains/Exposed#1139]
Currently there is only a wiki and its sparse, devs need good documentation with more complex examples in order for Exposed to be widely adopted. Sadly this request is not in [roadmap](https://github.com/JetBrains/Exposed/blob/master/docs/ROADMAP.md) either.

**Comment by Tapac** [comment]
We already working on new documentation. Stay tuned.

**Comment by bog-walk** [comment]
An update about documentation:

We are actively working towards improving KDocs throughout the codebase, as well as enhancing and publishing all Wiki documentation and samples to an Exposed website.

If you're interested, here is a [link](https://blog.jetbrains.com/kotlin/2023/08/exposed-moving-forward/) to the most recent official blog post regarding our plans moving forward.
