### ISSUE TITLE
Connect to mysql database

### ISSUE THREAD

**Issue by KevinJannis** [JetBrains/Exposed#114]
Hi,

I keep getting issues connecting to a simple mysql database. The error I get is the following: 
`Table name pattern can not be NULL or empty`

I can fix that error by adding the following to the jdbc connection string: 
`nullNamePatternMatchesAll=true`

Except that this gives me the following error:
`java.lang.NumberFormatException: For input string: "YES"`

I can see that the following queries are being run:

```
SQL: SELECT Busy.busy FROM Busy FOR UPDATE
SQL: INSERT INTO Busy (busy) VALUES (true)
SQL: DELETE FROM Busy
```

The code I used is the following:

```
object Database {
    private val jdbc = "jdbc:mysql://root:root@localhost:8889/shoppin-kotlin?nullNamePatternMatchesAll=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    private val driver = "com.mysql.cj.jdbc.Driver"

    private val connection = Database.connect(jdbc, driver)

    fun init() {
        val transaction = TransactionManager.currentOrNew(Connection.TRANSACTION_REPEATABLE_READ)

        transaction.logger.addLogger(StdOutSqlLogger)

        SchemaUtils.createMissingTablesAndColumns(Product, Product2)

        transaction.commit()

        println("Database initiated.")
    }
}
```

Any idea what is wrong with this?
I think it is using the wrong dialect for some reason?

On a sidenote, is there still active development on this library?

Thanks,

K.

**Comment by KevinJannis** [comment]
I found out that there is a query made to the `information_scheme.COLUMNS` table.
When I change `SchemaUtils.createMissingTablesAndColumns` to just `SchemaUtils.create` all works fine.

K.

**Comment by Tapac** [comment]
@KevinJannis , what version of Mysql DB and jdbc driver do you use?
createMissingTablesAndColumns function use information_scheme to retrieve column/index information from it.
