### ISSUE TITLE
NotSerializableException on select with a one-to-many in a DAO

### ISSUE THREAD

**Issue by aleperaltabazas** [JetBrains/Exposed#1141]
Hi! I've been having some weird troubles with a one-to-many relation in my schema. Inserts seem to work fine, but when I try to query them, be it with `find` or `all`, I get the following error:
```kotlin
org.h2.jdbc.JdbcSQLDataException: Serialization failed, cause: "java.io.NotSerializableException: org.jetbrains.exposed.dao.DaoEntityID" [90026-200]
```

I don't feel knowledgeable enough, neither in Kotlin nor in this framework, but it seems to me that it's trying to deserialize a Long as an Entity and it's failing.

Here's the [schema](https://github.com/aleperaltabazas/dex-tracker/tree/71bed0a5c84f95eb6ea4bbfbfc87e889b13a42c9/dex-tracker-backend/src/main/kotlin/com/github/aleperaltabazas/dex/db/schema/User.kt), the [DAO](https://github.com/aleperaltabazas/dex-tracker/tree/71bed0a5c84f95eb6ea4bbfbfc87e889b13a42c9/dex-tracker-backend/src/main/kotlin/com/github/aleperaltabazas/dex/db/dao/User.kt) and here's the line which [throws the exception](https://github.com/aleperaltabazas/dex-tracker/blob/71bed0a5c84f95eb6ea4bbfbfc87e889b13a42c9/dex-tracker-backend/src/test/kotlin/com/github/aleperaltabazas/dex/db/schema/SessionSchemaTest.kt#L53). I know it's a nested one-to-many relation, but doesn't seem to be the problem; even with just one-to-many it breaks.

I tried this as well with the Star Wars film example in the wiki, and it also failed with the same error. Perhaps there's something I'm not getting, I would gladly take some help on that.

Cheers!

**Comment by Tapac** [comment]
Hello, @aleperaltabazas , thank you for the report. 
I will try to fix the issue, but as a workaround, you can replace
`long(...).references(...)` with `reference(..., ...)`
like:
```kotlin
// before
long("user_id").references(UsersTable.id)
// after
reference("user_id", UsersTable.id)
```

**Comment by bog-walk** [comment]
Please see the [updated DAO wiki](https://github.com/JetBrains/Exposed/wiki/DAO#referencing) for more details about the following referencing suggestions.

As noted previously, a few changes will make the relations work:
```kt
// replace all similar in table
val userId = long("user_id").references(UsersTable.id)
// with
val userId = reference("user_id", UsersTable)

// replace all similar reference columns in dao
var userId by PokedexTable.userId
// with
var userId by UsersDAO referencedOn PokedexTable.userId

// no change needed for use of "referrersOn" in dao

// then in SessionSchemaTest.kt
val user = UsersDAO.new {
    username = "ethan"
}
// replace similar reference value insertions
userId = user.id.value
// with corresponding stored value
userId = user

// finally
UsersDAO.all().with(UsersDAO::pokedex, PokedexDAO::pokemon)
    .forEach { pl ->
        println("${pl.username} has a ${pl.pokedex.singleOrNull()?.region} pokedex")
}
// ethan has a johto pokedex
```

Please reopen this issue if the problem returns with current version 0.41.1.
