### ISSUE TITLE
IdTable no create PromaryKey [H2]

### ISSUE THREAD

**Issue by SchweinchenFuntik** [JetBrains/Exposed#1143]
exposed version - 0.28.1
kotlin version - 1.4.21
h2 version - 1.4.199

```kotlin 

object Persons : IntIdTable() {
    val firstName = varchar("first_name", 255)
    val lastName = varchar("last_name", 255)
    val familyName = varchar("family_name", 255)
}

//
transaction {
    SchemaUtils.create(Persons)
}
```

**result:**
```sql
create table PERSONS
(
	ID INTEGER auto_increment,
	FIRST_NAME VARCHAR(255) not null,
	LAST_NAME VARCHAR(255) not null,
	FAMILY_NAME VARCHAR(255) not null
);
```

creates only unique index

**Comment by Tapac** [comment]
How do you check that the PK wasn't created?
Can you execute `SHOW COLUMNS FROM PERSONS;` and ensure that there is no `PRI` in `KEY` column?

**Comment by SchweinchenFuntik** [comment]
strange, I checked at home, I have a key, I look in `datagrip`. `SHOW COLUMNS FROM PERSONS;` - also shows that the key is set.

another question - how to make autoincrement cyclical? Using schema description Exposed
