### ISSUE TITLE
Time only support

### ISSUE THREAD

**Issue by rmpt** [JetBrains/Exposed#1148]
It would be nice to support time only columns, like Postgresql time.

**Comment by bog-walk** [comment]
Time-only columns are possible using `time()`, which registers a [`KotlinLocalTimeColumnType`](https://github.com/JetBrains/Exposed/blob/master/docs/ChangeLog.md#0311) (or a corresponding module column type). The TIME data type started having support in [version 0.31.1](https://github.com/JetBrains/Exposed/blob/master/docs/ChangeLog.md#0311).
