### ISSUE TITLE
Dynamic schema table creation with preserving static typing - impossible?

### ISSUE THREAD

**Issue by RdeWilde** [JetBrains/Exposed#1151]
Is it possible to prefer static typing while dynamically creating a table?

For example (won't work):
```
val products = IntIdTable("product")
products.registerColumn<String>("name", VarCharColumnType());
products.registerColumn<Float>("price", DecimalColumnType(10, 2));
SchemaUtils.create (products)

products.insert {
    it[name] = "Toys"  // << this won't work as 'name' is unknown
    it[price] = 2.50
}
```
The columns 'name' and 'price' are unknown as they don't reference to a property. 
Any way to resolve this?

I want to create the schema structure based off my protobuf models, so that's why I want to create the table and column programmatically.

**Comment by Tapac** [comment]
Look similar to #702

**Comment by Tapac** [comment]
In your case, you have to find the proper column by name:
```
val columnName = products.columns.first{ it.name == "name" } 
```

**Comment by RdeWilde** [comment]
Not really the typesafe way that I was looking for, but thanks for your suggestion :-)
