### ISSUE TITLE
Support prepared parametrized statements

### ISSUE THREAD

**Issue by zeljkot** [JetBrains/Exposed#116]
I do not see a way to prepare a statement and execute it multiple times with different parameters. Statement must be rebuilt for each call. Please provide such functionality.

**Comment by programaths** [comment]
Hi, there is a way :

```kotlin
         val db=config.databases["**redacted**"]!!
        Database.connect(db.dsn,db.driver,db.user,db.password)
        transaction {
            val ps=prepareStatement("Insert into foo(bar) values (?)")
            for(i in 0..10) {
                ps.setInt(1, i)
                ps.execute()
            }
        }
```

As you can see, `ps` is reused.

**Comment by raderio** [comment]
@zeljkot maybe you can wrap the call into a function? so you can add parameters to function.

**Comment by bog-walk** [comment]
To prepare a statement and execute it multiple times, you could also take advantage of the different `exec()` overrides, for example:
```kt
object Tester : Table("tester") {
    val testAge = integer("age")
}

transaction {
    // ...
    val agesToInsert = listOf(18, 19, 20)
    val insertStatement = "INSERT INTO tester (age) VALUES (?)"

    agesToInsert.forEach { age ->
        exec(
            stmt = insertStatement,
            args = listOf(IntegerColumnType() to age),
            explicitStatementType = StatementType.INSERT
        )
    }

    Tester.selectAll().count() // 3
}
```
If the statement to prepare is complicated or you want Exposed to generate it, you could technically retrieve the SQL string using `prepareSQL()`:
```kt
val insertStatement = Tester.insert { it[testAge] = 18 }.prepareSQL(this, prepared = true)
```
**Note:** Depending on the `Statement` class used, this might execute the statement first once before assigning the string to the variable `insertStatement`.

If these answers and the ones before it have missed the point entirely or you believe the support with current version 0.42.1 is lacking, please don't hesitate to open an issue on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763). If you do so, please also consider providing more details of your use case, how the current support is lacking, and what the desired enhancements are.
