### ISSUE TITLE
Please consider moving to maven central

### ISSUE THREAD

**Issue by bastman** [JetBrains/Exposed#1160]
Hi Tapac,

it looks like jcenter/bintray will be shutdown by 1st May.
Could you please consider publishing artifacts to maven central?

Thanks a lot :)

related article: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by nhubbard** [comment]
I'm not exactly sure what the plan is, but someone else has opened an issue on JetBrains' central issue tracker [here](https://youtrack.jetbrains.com/issue/MP-3403).

Please correct me if this is the wrong issue in the YouTrack server!
