### ISSUE TITLE
Support JSON and JSONB types in Postgres

### ISSUE THREAD

**Issue by gpasq** [JetBrains/Exposed#1172]
Supporting the JSON and JSONB types would be very welcome.

https://www.postgresql.org/docs/13/datatype-json.html

**Comment by vp-mazekine** [comment]
Agree, it is highly expected

**Comment by BorzdeG** [comment]
duplicate #127 ?

**Comment by pqt** [comment]
> duplicate #127 ?

It is, kind of blown away it's a 4-year-old already.
