### ISSUE TITLE
keep columns' order

### ISSUE THREAD

**Issue by guai** [JetBrains/Exposed#1185]
Hi
In JPA there is no way to defune column order, so hibernate eg orders them alphabetically. Which is not what many DBA like to see
I didn't find that column order to be strictly enforced in Exposed either.
It would be nice to have it. To be able to get columns positional number, to set it explicitly, to check if it matches DB schema, and maybe even reorder them automatically via alter table

**Comment by joc-a** [comment]
Hi @guai. Does this recent [fix](https://github.com/JetBrains/Exposed/pull/2159/files#:~:text=sortedBy%20%7B%20it.first%20%7D-,val%20result%20%3D%20valuesAndDefaults.toList(),-listOf(result).) also fix your issue? If not, please create an issue on [YouTrack](https://youtrack.jetbrains.com/issues/EXPOSED). Thank you.
