### ISSUE TITLE
Delete from using (inner) join

### ISSUE THREAD

**Issue by andrejbrummelhuis** [JetBrains/Exposed#1189]
As fas as I can see, there is currently no support for creating a delete with inner join using the DSL.

For example:

DELETE table1 FROM table1 INNER JOIN table2 on table1.table2_id = table2.id WHERE table2.some_field = 333;

Same result could be achieved using subQuery but this can cause MySQL to create an inefficient query plan.

**Comment by Coneys** [comment]
Any updates about this feature? Or any workaround beside raw query generation?

**Comment by Nek-12** [comment]
Any updates on this?

**Comment by rasharab** [comment]
Postgresql has USING semantics for this use case.
This is a pretty core need for us, we'll have to implement it on our own I suppose.

**Comment by rasharab** [comment]
This i an awesome change @bog-walk. :)
How do we push for a release of your change.

**Comment by bog-walk** [comment]
Hi @rasharab Our release schedule is every month, at the end of the month. So this feature will be included in the upcoming version 0.55.0 in ~ 2 weeks time.
