### ISSUE TITLE
Cannot use `bool` column types on Oracle database

### ISSUE THREAD

**Issue by mrobakowski** [JetBrains/Exposed#119]
This is related to the commented line here: https://github.com/JetBrains/Exposed/blob/master/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt#L347

```kotlin
    override fun valueFromDB(value: Any) = when (value) { // value is "1"
        is Number -> value.toLong() != 0L
        is String -> value.toBoolean() // "1".toBoolean() === false
    // REVIEW
//        is String -> currentDialect.dataTypeProvider.booleanFromStringToBoolean(value)
        else -> value.toString().toBoolean()
    }
```
Exposed writes `"1"` to the database to represent truth, but then, when reading from database, it interprets `"1"` as `false`. The code that is commented out is actually correct and does what we want (at least on Oracle).

**Comment by Tapac** [comment]
Fixed and covered with test in master

**Comment by romrell4** [comment]
I'm seeing related issues when using bools in Oracle DBs. But the error I'm getting it when trying to use the `not` equality operator. It tries to create the SQL: `select * from PAID_PARKING where NOT SENT_TO_PS;` when SENT_TO_PS is a number field in Oracle. Any work around for this aside from just changing the exposed Table definition to be an integer?
