### ISSUE TITLE
How to "Delete from table if value in another table"?

### ISSUE THREAD

**Issue by devplayg** [JetBrains/Exposed#1191]
Is there any way to express this query using the DSL API?

    delete from Table1 where no  = (select id from Table2 where name = 'somevalue');

**Comment by Tapac** [comment]
```kotlin
Table1.deleteWhere {
   Table1.no eqSubQuery Table2.slice(Table2.id).select { Table2.name eq "somevalue" } 
}

**Comment by bog-walk** [comment]
Please reopen this issue if the problem requires more answers.
