### ISSUE TITLE
Filtration

### ISSUE THREAD

**Issue by AndreyZS** [JetBrains/Exposed#1193]
Good afternoon, please tell me how to implement filtering?
1. The entrance receives:
```kotlin
    data class Test(var name: String,var operator: String,var value:String)
```
Where name is the name of the column, operation is the filter rule. Value - meaning itself
2. Could get the column name
```kotlin
 var column = table.columns.find { it.name == test.name }
```
But the problem is I can't use it
```
query.andWhere { column eq 1}
```
Tell me how to implement my idea ?

**Comment by DarkXanteR** [comment]
`query.andWhere { column as Column<Any?> eq 1}`
