### ISSUE TITLE
`this@select is not captured` during debug evaluation

### ISSUE THREAD

**Issue by CrownlessX** [JetBrains/Exposed#1198]
Trying to debug my logic, but faced quite strage issue:
When I'm evaluating query with `.select{}` 
`MyTable.select { MyTable.editDate.greater(DateTime.now().minusWeeks(2))}.forEach { println(it) }`
I have no result, but **'this@select' is not captured**
No such issue with using of selectAll()

When I'm running this query from function - no issues. It executed properly
`fun forTest() = MyTable.select { MyTable.editDate.greater(DateTime.now().minusWeeks(2))}.forEach { println(it) }`

Intellij 2019.3
```
<dependency>
    <groupId>org.jetbrains.exposed</groupId>
    <artifactId>exposed-spring-boot-starter</artifactId>
    <version>0.17.3</version>
</dependency>
```

**Comment by Tapac** [comment]
Should fixed in Intellij 2021.1, Please check https://youtrack.jetbrains.com/issue/KTIJ-455
