### ISSUE TITLE
exposed-core: Bugs in ISqlExpressionBuilder.coalesce() typings

### ISSUE THREAD

**Issue by sachindshinde** [JetBrains/Exposed#1199]
There are two bugs we've noticed in [`ISqlExpressionBuilder#coalesce()`](https://github.com/JetBrains/Exposed/blob/0.30.1/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt#L337):
- There's a type argument `R` that's not used anywhere.
- The typing of the resulting `Coalesce` object is `Coalesce<T?, S, T?>`. This forces the output to be `Function<T?>`, i.e. a SQL function that returns nullable type `T`. Note that if the `alternative` expression is non-nullable, the SQL function won't ever output null, but using `ISqlExpressionBuilder#coalesce()` will still return `Function<T?>`. We've worked around the last point by calling the `Coalesce` constructor directly.

**Comment by glasser** [comment]
Specifically, it looks like changing the type to `Coalesce<T?, S, T?>` to `Coalesce<T?, S, R>` fixes the issue.

As an example, before upgrading from 0.17.3 to 0.30.1, we were able to have this code:

```
				val actionsSum: Expression<Int> = Expression.build {
					coalesce(
						Sum(
							case()
								.When(
									ActionsTable.action eq Action.JOIN_ACCOUNT,
									intLiteral(1)
								)
								.When(
									ActionsTable.action eq Action.LEAVE_ACCOUNT,
									intLiteral(-1)
								)
								.Else(intLiteral(0)),  // for NULL due to left join
							IntegerColumnType()
						),
						intLiteral(0)
					)
				}
```

Note that the `intLiteral(0)` is never null, so declaring this as `Express<Int>` was valid. With 0.30.1, this doesn't compile (but it works if we change `coalesce` to `Coalesce`). This appears to have been a regression in https://github.com/JetBrains/Exposed/pull/786
