### ISSUE TITLE
Entity queried from database after creation on any prop access 

### ISSUE THREAD

**Issue by crazyproger** [JetBrains/Exposed#12]
Found some non-obvious behavior: when creating `Entity` by `EntityClass.new` with all fields population,  then accessing any prop at first time leads to querying this entity from DB. This last query was unexpected for me if I populate all props upon creation.

Internally this is because upon save `Entity._readValues` backing field is null and written doesn't cached in it. 
I think `Entity` should cache inserted values and return them without additional queries...or maybe I've missed something and this behavior considered as normal?

**Comment by Tapac** [comment]
You are absolutely right about excessive query to retrieve just inserted values for new entities.
We fixed that in d5bef3c5b74428369ce1c44748a03cc26d7ae1f3 , feel free to test and thank you for attention.
