### ISSUE TITLE
Doesn't support "mysql-connector-java 5"?

### ISSUE THREAD

**Issue by MeowRay** [JetBrains/Exposed#1203]
![image](https://user-images.githubusercontent.com/29674595/114527714-de08e480-9c7a-11eb-85dd-9c7575ba2353.png)
![image](https://user-images.githubusercontent.com/29674595/114527805-f7119580-9c7a-11eb-9fc9-4bd176afb1a6.png)

**Comment by Tapac** [comment]
You use VERY (from 2010-12-06) version (5.1.14) of MySQL connector, please update it to 5.1.49.

**Comment by MeowRay** [comment]
Many minecraft servers are using spigot 1.8.8 (mysql-connector-5.1.14)
It works well after mapping driveName

https://github.com/JetBrains/Exposed/pull/1205

**Comment by MeowRay** [comment]
> You use VERY (from 2010-12-06) version (5.1.14) of MySQL connector, please update it to 5.1.49.

Many minecraft servers are using spigot 1.8.8 (mysql-connector-5.1.14)
It works well after mapping driveName

https://github.com/JetBrains/Exposed/pull/1205
