### ISSUE TITLE
Regression: Clientside length validation in ColumnType breaks otherwise harmless where clause

### ISSUE THREAD

**Issue by spand** [JetBrains/Exposed#1204]
Commit ffcc91ab738877f0373b5217acd0b5d1cacc262d introduced client side validation of values and it now breaks otherwise harmless where clauses. This has already been noted by comments on #993.

I am not sure I agree that this should happen client side (now the database and exposed table objects can no longer diverge.. something really useful in migrations ops-wise). If anything it seems to relate to a lack of support in Postgres which seems to make the case that it should be a dialect specific behavior instead.

One might think this could then be fixed by constant folding the where clauses to avoid calling `notNullValueToDB` with an invalid value but I dont think its that easy.

**Comment by Tapac** [comment]
Thank you for the report. The validation moved to a separate function and will be executed only on updates/inserts.
