### ISSUE TITLE
Sequence is not used when specifying via autoIncrement

### ISSUE THREAD

**Issue by simonnepomuk** [JetBrains/Exposed#1209]
I'm trying to create a table and the corresponding DAO like this:
```
object Roles: IdTable<Int>("roles") {
    override val id = integer("id").autoIncrement("role_id_seq").entityId()
    val name = varchar("name", 255)
}

class Role(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<RoleKotlin>(Roles)
    var name by Roles.name
}
```
When I try to insert a new entity via `
transaction {
    Role.new {
        name = "new entity"
    }
}` I get the following exception:
```
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "roles_pkey"
  Detail: Key (id)=(16) already exists.
```
I checked the sequence with `select last_value from pg_sequences where sequencename like 'role_id_seq';
` and the last value is 41. 

Am I creating the Table or Entity in a wrong way or is this an issue with Exposed? Thanks in advance and feel free to contact me if you need any more info :)

**Comment by micHar** [comment]
For anyone that wanders here somehow. Had this issue in `0.37.3`, works fine in `0.38.2`. Postgres
