### ISSUE TITLE
Exposed replaces entries when a UNIQUE INDEX collision occurs, instead of crashing

### ISSUE THREAD

**Issue by CLOVIS-AI** [JetBrains/Exposed#1212]
In a MariaDB database shell:
```sql
# Create a table
CREATE TABLE IF NOT EXISTS Profiles (id INT AUTO_INCREMENT PRIMARY KEY, email VARCHAR(50) NOT NULL, name VARCHAR(50) NOT NULL);

# We want the email field to be unique
ALTER TABLE Profiles ADD CONSTRAINT Profiles_email_unique UNIQUE (email);

# Insert two profiles with the same email (which should be unique)
INSERT INTO Profiles (email, name) VALUES ('some random email.fr', 'my full name');
INSERT INTO Profiles (email, name) VALUES ('some random email.fr', 'my full name');
```
As expected, this gives:
```[23000][1062] (conn=3) Duplicate entry 'some random email.fr' for key 'Profiles_email_unique'```

Exposed has different behavior, however.

```kotlin
// Remove the Profiles database before executing this.

object Profiles : IntIdTable() {
	val email = varchar("email", 50).uniqueIndex()
	val fullName = varchar("name_full", 50)
}

SchemaUtils.create(Profiles)

repeat(2) {
	val id =  Profiles.insertAndGetId { profile ->
		profile[this.email] = "some random email.fr"
		profile[this.fullName] = "my full name"
	}
}
```

Instead of the `insert` failing the second time with an exception, the previous entry is deleted and the new one takes it place, with no warning nor exception.

According the Exposed's logs, however, it executes exactly the same commands as the manual version:
```sql
CREATE TABLE IF NOT EXISTS Profiles (id INT AUTO_INCREMENT PRIMARY KEY, email VARCHAR(50) NOT NULL, name_full VARCHAR(50) NOT NULL)
ALTER TABLE Profiles ADD CONSTRAINT Profiles_email_unique UNIQUE (email)
INSERT INTO Profiles (email, name_full) VALUES ('some random email.fr', 'my full name')
INSERT INTO Profiles (email, name_full) VALUES ('some random email.fr', 'my full name')
```

It looks like Exposed is doing a `INSERT … ON DUPLICATE KEY UPDATE`, but it doesn't say it does in the debug logs, which sounds weird to me.

Versions:
- Kotlin 1.4.31
- Exposed 0.29.1
- MariaDB 10.5.9-1 (ArchLinux package, to my knowledge using the default configuration, don't hesitate to ask me if you need to see some config files)

**Comment by Tapac** [comment]
It's not like that for sure because there is no `ON DUPLICATE KEY UPDATE` support in Exposed at the moment.

Is the only Profiles table in a database? Maybe Exposed run queries against Profiles from another schema?

**Comment by CLOVIS-AI** [comment]
This is the only Profiles table, and it's also the only schema. The code does edit the database, and I can see the edits in IntelliJ, so I don't think it's a wrong-schema issue.

I'm using the default MariaDB configuration for ArchLinux (https://wiki.archlinux.org/index.php/MariaDB), but I don't have the expertise with MariaDB required to go through the setup and find what's wrong. Even then, it wouldn't make much sense, because executing the request from IDEA with the same schema & everything gives a different result, so there's definitely something going on with my code or Exposed :/

**Comment by CLOVIS-AI** [comment]
So, the good news is that I was able to run my code on Kali Linux and it runs (well, fails) as expected, so it's not an Exposed bug and it's definitely my MariaDB configuration, somehow.

Feel free to close this ticket, however I'd be really interested if you have any pointers that could help me fix it (I'm a beginner with database setup, all help is welcome :bow:)

**Comment by Tapac** [comment]
The only thing I can imagine is the problem in some case-sensitivity identifiers options in DB.
