### ISSUE TITLE
Use connection pool instead of creating new connections for each transaction

### ISSUE THREAD

**Issue by dya-tel** [JetBrains/Exposed#122]
Exposed 0.8
MariaDB 10.2
MySQL Connector 6.0.6 / MariaDB Connector 2.0.2

I have two threads (one is read-only and the second one is read-write), which are making requests to the database, and that works perfectly fine until separate transactions are very frequent. In that case, both JDBC drivers throw an exception as they can't establish a connection due to the lack of free sockets, if I'm not mistaken.

Stacktrace for MySQL Connector: <https://pastebin.com/Ps8X2x00>
Stacktrace for MariaDB Connector: <https://pastebin.com/h6Jfr7c9>

Moreover, connection pool should theoretically improve the performance.

**Comment by Tapac** [comment]
You can take any connection pool you like and just use `Database.connect(dataSource)` instead of `Database.connect(jdbcUrl,...)`

**Comment by dya-tel** [comment]
Yep, that works. Though I was kind of expecting that this functionality should be built-in.
Thanks for the help.
