### ISSUE TITLE
select query throws "can't be stored to database column because exceeds length"

### ISSUE THREAD

**Issue by asule90** [JetBrains/Exposed#1222]
I don't think it should throw exception on select query

someone else has reported it here https://github.com/JetBrains/Exposed/issues/993#issuecomment-692650003

and im still experiencing it on postgresql
![image](https://user-images.githubusercontent.com/10544636/116957177-6b12ec80-acc1-11eb-89b4-f7d5f7746aeb.png)

**Comment by Tapac** [comment]
Fixed in master, will be released soon.
