### ISSUE TITLE
Using Entity.flush does not alert EntityHook subscribers

### ISSUE THREAD

**Issue by KennethWussmann** [JetBrains/Exposed#1225]
Hey,

I'm using EntityHooks to maintain an `updatedAt` column on my entities and need the `updatedAt` value during the same transaction where the entity was updated. As the EntityHooks are only called on commit, I added a [`Entity.flush()`](https://github.com/JetBrains/Exposed/blob/master/exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/Entity.kt#L160-L188) call to force Exposed to flush the outstanding update & so the `updatedAt` hook to take effect. 

**Expected behaviour**
Looking at the code of the [`flush()`](https://github.com/JetBrains/Exposed/blob/master/exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/Entity.kt#L160-L188) function it adds an update event to the queue. I expected calling `flush()` with outstanding updates will also notify EntityHook subscribers.

I added a test repo here to showcase the expected behaviour: https://github.com/KennethWussmann/exposed-entity-flush-hook-bug/blob/main/src/test/kotlin/exposedissue/EntityHookTest.kt#L18-L59

**Actual behaviour**
Calling `flush()` doesn't notify EntityHook subscribers, even though it commits `UPDATE` statements to the database.

I also added a test to show how it currently looks like: https://github.com/KennethWussmann/exposed-entity-flush-hook-bug/blob/main/src/test/kotlin/exposedissue/EntityHookTest.kt#L61-L103

Version used: `0.31.1`

Thank you!

**Comment by Tapac** [comment]
Fixed in master. Events will be fired just after the entity created/updated/deleted not before the transaction commit.
