### ISSUE TITLE
Typo "After" -> "Before" in wiki "Getting Started'

### ISSUE THREAD

**Issue by tsukakei** [JetBrains/Exposed#1226]
Hi Teams,

I found a typo in a "[Getting Started](https://github.com/JetBrains/Exposed/wiki/Getting-Started)" wiki page.

Configurations for Maven is commented as below, but it should say not `Versions after 0.30.1`, but `Versions before 0.30.1`.

```
<!-- Versions after 0.30.1 -->
<repositories>
    <repository>
        <id>jcenter</id>
        <name>jcenter</name>
        <url>https://jcenter.bintray.com</url>
    </repository>
</repositories>
```

I read [this article about contributing](https://github.com/JetBrains/Exposed/wiki/Contributing#how-to-improve-wiki-pages), but it seems to be outdated.
(Actually, https://github.com/Tapac/exposed-wiki seems to be outdated.)
So, I created this issue. 

Thanks!

**Comment by Tapac** [comment]
@tsukakei , thank you for the notice. The type was fixed and https://github.com/Tapac/exposed-wiki was actualized
