### ISSUE TITLE
How to get next auto_increment value before an INSERT

### ISSUE THREAD

**Issue by mahramane** [JetBrains/Exposed#1230]
```
Users.insert {
 it[id] = //next id
            it[name] = "Something"
        }
```

**Comment by Tapac** [comment]
auto_increment value is generated by the database in a time it inserts a new row so it's impossible to get it BEFORE.
But why do you need it?

**Comment by bog-walk** [comment]
As an extra, some databases, like MySQL, seem to provide [different](https://dev.mysql.com/doc/refman/8.0/en/information-schema-tables-table.html) [options](https://dev.mysql.com/doc/refman/8.0/en/show-table-status.html) that you could execute.

Potentially related, Exposed does support creation of a [custom sequence](https://github.com/JetBrains/Exposed/wiki/DSL#sequence) & using its `nextVal()` as `id`.

Please reopen this issue the problem requires more answers.
