### ISSUE TITLE
wrong version of kotlin-reflect in core module

### ISSUE THREAD

**Issue by goekhantopcu** [JetBrains/Exposed#1243]
I get these warnings (after updgrading to kotlin 1.5.0) when I build my project

`Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    C:/Users/Artillero/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.4.32/ce852b166d97f0f1991b5130c2bb02e2ef6c554e/kotlin-reflect-1.4.32.jar (version 1.4)
    C:/Users/Artillero/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.5.0/65fbc439df2e4aad1f3769762d54534f1b564090/kotlin-stdlib-jdk8-1.5.0.jar (version 1.5)
    C:/Users/Artillero/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.5.0/f61904618ea7be07a66e0545ffe8dc2c70a19b77/kotlin-stdlib-jdk7-1.5.0.jar (version 1.5)
    C:/Users/Artillero/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.5.0/29dae2501ca094416d15af0e21470cb634780444/kotlin-stdlib-1.5.0.jar (version 1.5)
    C:/Users/Artillero/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.5.0/4080d69efca5e39e9b4972f125e40f1607bd6460/kotlin-stdlib-common-1.5.0.jar (version 1.5)`

These are the dependencies i use
![Screenshot 2021-05-18 223306](https://user-images.githubusercontent.com/64787457/118720137-85a0a600-b829-11eb-85e4-9bdaa01f4961.png)

**Comment by Tapac** [comment]
the (*) mark means that the dependency was updated, so it's your code uses kotlin 1.5 while Exposed 0.31.1 is still depending on 1,4,32.
You can either add kotlin-reflect with 1.5 into your build.gradle or wait for the next Exposed released with 1.5

**Comment by JailBreakerTV** [comment]
i tought Exposed 0.31.1 uses already kotlin 1.5

[https://github.com/JetBrains/Exposed/blob/master/build.gradle.kts](url)

**Comment by Tapac** [comment]
No, the 0.31.1 version was before that change
