### ISSUE TITLE
Related to 1171, warning causes whole app to stop

### ISSUE THREAD

**Issue by trnchawla** [JetBrains/Exposed#1245]
Please look at the last comments I made recently on this ticket: https://github.com/JetBrains/Exposed/issues/1171

I had added the required details, please let me know if you need anything else.

**Comment by Tapac** [comment]
Do you have a high-load app?

**Comment by trnchawla** [comment]
> Do you have a high-load app?

Nope, am the only one hitting this api via postman. After 2-3 times issue comes up.

**Comment by trnchawla** [comment]
@Tapac I was earlier using impossible jdbc driver version 0.8.6. I updated the version to 0.8.7 then this issue is not causing the whole server to go down but warnings are still coming. Today I switched to org.postgresql:postgresql:42.2.20 driver and am not seeing this issue.

@Tapac can you please do one favour to me? I attached code snipped for 3 functions, can you please review it and tell me if there is something wrong with approach of using exposed apis?

**Comment by Tapac** [comment]
@trnchawla , is it still reproducable with recent Exposed version?

**Comment by bog-walk** [comment]
Please reopen this issue if the problem persists with current version 0.41.1.

If it does and if possible, please confirm whether the warnings shown are the same as before and what database version is being used.
