### ISSUE TITLE
PostgreSQL-Error when using uppercase letters for column name

### ISSUE THREAD

**Issue by msrd0** [JetBrains/Exposed#125]
In PostgreSQL, statement like

```sql
SELECT foo.anExample FROM foo
```

are equivalent to

```sql
SELECT foo.anexample FROM foo
```

If the kotlin application isn't the only one to access the database this will lead to issues. Please enquote the name like this

```sql
SELECT foo."anExample" FROM foo
```

so that PostgreSQL doesn't automatically convert the name to lowercase.

I tested with Kotlin 1.1.2-5 and Exposed 0.8 with gradle

**Comment by Tapac** [comment]
Should be fixed in master.
