### ISSUE TITLE
TransactionScope throws NullPointerException when attepting to commit

### ISSUE THREAD

**Issue by holger420** [JetBrains/Exposed#1250]
I attempted to make every Ktor pipeline its own transaction for atomicity.
My code:

```Kotlin
this.intercept(ApplicationCallPipeline.Monitoring) {
    val transaction = manager.newTransaction(manager.defaultIsolationLevel)
    proceed()
    transaction.commit()
    transaction.close()
}
```

Thanks to coroutines the transaction I wanted to commit didn't match with what `TransactionManager.currentOrNull()` gave and it sometimes ended up being null. Resulting in [this line](https://github.com/JetBrains/Exposed/blob/18b3100eb578e7215e69b5e82a5658a14ea2ca88/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/transactions/TransactionScope.kt#L21) in Exposed throwing a NullPointerException.

I managed to solve the issue by using suspended transactions like this:

```Kotlin
this.intercept(ApplicationCallPipeline.Monitoring) {
    newSuspendedTransaction {
        proceed()
    }
}
```

The problem is that Exposed still allows a NullPointerException to be thrown.

**Comment by Tapac** [comment]
Is the problem in NPE or that it throws at all? I can replace it with IllegalStateException when transactionScope used outside the transaction.

**Comment by holger420** [comment]
The problem is in the NPE
