### ISSUE TITLE
Sqlite INTEGER type

### ISSUE THREAD

**Issue by mahramane** [JetBrains/Exposed#1255]
Hi, I want to create a table in the sqlite database.

schema : 

```
object SqliteAccountsTest : LongIdTable("tbl_accounts") {
    val name = text("name").default("")
    val parentId = integer("parent_id").default(0)
    val detailType = integer("detail_type").default(1)
    val lock = integer("lock").default(0)
    val selection = integer("selection").default(1)
}
```

sql output:

```
CREATE TABLE "tbl_accounts" (
	"id"	INTEGER,
	"name"	TEXT NOT NULL DEFAULT '',
	"parent_id"	INT NOT NULL DEFAULT 0,
	"detail_type"	INT NOT NULL DEFAULT 1,
	"lock"	INT NOT NULL DEFAULT 0,
	"selection"	INT NOT NULL DEFAULT 1,
	PRIMARY KEY("id" AUTOINCREMENT)
);
```

How to put INTEGER instead of INT in SQL?
please help me.

**Comment by Tapac** [comment]
Why do you need that? AFAIK all integer times represented as INTEGER in SQLite. Please check the [doc](https://www.sqlite.org/datatype3.html#affinity_name_examples)

**Comment by mahramane** [comment]
> Why do you need that? AFAIK all integer times represented as INTEGER in SQLite. Please check the [doc](https://www.sqlite.org/datatype3.html#affinity_name_examples)

Because the database created by Exposed will be used in an Android application.  And room orm library in Android only supports Text, INTEGER, BLOB and REAL.

**Comment by Tapac** [comment]
I'm 99% sure that it will work fine as INT is an alias for INTEGER (please check the documentation p.3.1.1)
