### ISSUE TITLE
No transaction in context when Entity.findById() is used (with multiple databases)

### ISSUE THREAD

**Issue by PedroStrabeli** [JetBrains/Exposed#1260]
I'm working with more than 1 SQLite databases in my project, and I connect to those with transaction (db) { ... }, db being a variable connecting to the right database on my DAO object.

When I'm going for an update, I have the id of the object to be updated, do I go:

```
fun update(): BookEntity {
        val entity = BookEntity.findById(id)
        if (entity != null) {
            val self = this
            transaction(db) {
                entity.name = self.name
                entity.genre = self.genre
                entity.description = self.description
                commit()
            }
            return entity
        } else {
            throw IllegalEntityOperationException("update", "Entity not found")
        }
    }
```

This is a method of my BookDAO class, which works much like the Entity itself, but encapsulates CRUD operations and others such as a select count, select single object, insertBatch... and so on, so my code is a little more organized.

When my program goes though the first line, it throws the `No transaction in context` exception. Why does it? And I can't wrap this operation in a transaction...  I really didn't want to use DSL to solve this, but I'm seeing myself forced to do so. Is there a way to fix this problem?  thanks.

**Comment by Tapac** [comment]
`findById()` have to load an entity from a database so it requires a transaction, just move your `transaction` at first line of a function. 
Also, you don't need the explicit commit here if the entire transaction will be finished inside the function.

**Comment by PedroStrabeli** [comment]
@Tapac thank you for your response. I have tried that before and it failed, it was accusing that my entity didn't have the `findById` in the companion object, but now it seems to work.

Oh yeah, and thanks for the remark on the `commit()`. I removed it
