### ISSUE TITLE
Defining ReferenceOption from parent

### ISSUE THREAD

**Issue by ESchouten** [JetBrains/Exposed#1261]
Is there any way I can set the childs' ReferenceOption.Cascade from the parent entity?
The child table is referenced from multiple tables, and I want to avoid optionally referencing each of the tables at the child level
Example:
```
object Person : UUIDTable() {
    val name = varchar("name", 255)
    val address = reference("address", Address)
}

object Company : UUIDTable() {
    val name = varchar("name", 255)
    val address = reference("address", Address)
}

object Address : UUIDTable() {
    val number = varchar("number", 255)
    val street = varchar("street", 255)
    val city = varchar("city", 255)
    val zipcode = varchar("zipcode", 255)
    val country = varchar("country", 255)
}
```

**Comment by bog-walk** [comment]
Hi @ESchouten Apologies if I'm misunderstanding but is the goal to avoid doing this for multiple child tables that all reference the same parent table and require the same referential action?
```kt
object Person : UUIDTable() {
    val name = varchar("name", 255)
    val address = reference("address", Address, onDelete = ReferenceOption.CASCADE, onUpdate = ReferenceOption.CASCADE)
}

object Company : UUIDTable() {
    val name = varchar("name", 255)
    val address = reference("address", Address, onDelete = ReferenceOption.CASCADE, onUpdate = ReferenceOption.CASCADE)
}

// more child tables that reference Address
```

If so, there is no such way to define the referential action from a single location in the parent table object. A foreign key constraint is defined on a child table and its `CREATE` statement is entirely dependent on the individual Exposed table object.

The closest I can offer to minimise redundant code is to implement a custom column function for the relevant child tables:
```kt
fun <T : Comparable<T>> Table.referenceWithCascade(
    name: String,
    foreign: IdTable<T>,
    fkName: String? = null
): Column<EntityID<T>> = reference(name, foreign, ReferenceOption.CASCADE, ReferenceOption.CASCADE, fkName)

object Person : UUIDTable() {
   val name = varchar("name", 255)
   val address = referenceWithCascade("address", Address)
}

object Company : UUIDTable() {
    val name = varchar("name", 255)
    val address = referenceWithCascade("address", Address)
}
```

The logic in that function could be extended to provide a specific `ReferenceOption` based on the provided value of `foreign`, so it could be used to provide different actions for different parent tables.

Hope this helps!

**Comment by bog-walk** [comment]
Please consider reopening this issue on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763) if the problem requires more answers, so we can attempt to help you further.
