### ISSUE TITLE
No way to create unique constraint

### ISSUE THREAD

**Issue by lily-es** [JetBrains/Exposed#1262]
As of right now, from what I can tell, there is no way to create a UNIQUE CONSTRAINT with exposed. Only the option for a UNIQUE INDEX exists. Any plans to support UNIQUE CONSTRAINT in the future?

**Comment by Tapac** [comment]
Can you point to a doc for the exact constraint (is it `CHECK` constraint on a field or something different)?

**Comment by lily-es** [comment]
Here is an example. Its just a standard constraint available in SQL, just like primary key, foreign key constraints
https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-table-table-constraint-transact-sql?view=sql-server-ver15

**Comment by bog-walk** [comment]
Unless I'm misunderstanding, doing the following in SQLServer seems to work:
```kt
val tester = object : Table("tester") {
    val column1 = varchar("column_1", 32).uniqueIndex()
}

// generates SQL
CREATE TABLE "tester" (column_1 VARCHAR(32) NOT NULL)
ALTER TABLE "tester" ADD CONSTRAINT table_column_1_unique UNIQUE (column_1)
```

Please consider reopening this issue on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763) if the problem requires more answers or if the generated statement is incorrect in some way.
