### ISSUE TITLE
No execute update issue

### ISSUE THREAD

**Issue by SeonCheol** [JetBrains/Exposed#1269]
I use DAO API to update database.

In test phase, it works very well. But in production phase, it didn't work. 

my code is as below.
```kotlin
object Organizations : LongIdTable(name = "abc", columnName = "abc") {
    var name = varchar("def", 30) // Column<String>
    val alternateName = varchar("ghi", 30)
}

class OrganizationEntity(id: EntityID<Long>) : LongEntity(id) {
    companion object : LongEntityClass<OrganizationEntity>(Organizations)

    var name by Organizations.name
    val alternateName by Organizations.alternateName

    fun update(org: Organization): OrganizationEntity {
        this.updateName(org)
        return this
    }

    private fun updateName(org: Organization) {
        if (org.name.isNullOrBlank()) {
            return
        }
        this.name = org.name
    }

}

fun main {
        transaction {
            OrganizationEntity.findById(org.id!!.toLong())!!.apply {
                this.update(org)
            }
        }
}
```

in production, the update sometimes works, and most of update didn't work.

when I check the log, I saw the UPDATE query printed. 

Can you help me?

My program environment is as follow.

DB: PostgreSQL
Use Library: 
```gradle
implementation "org.jetbrains.exposed:exposed-core:0.32.1"    
implementation "org.jetbrains.exposed:exposed-dao:0.32.1"   
implementation "org.jetbrains.exposed:exposed-jdbc:0.32.1"
```
kotlin version: 1.4.32

**Comment by bog-walk** [comment]
I wasn't able to reproduce any update issue using the code example above with current version 0.43.0, as `name` would be correctly updated while `alternateName` remained unchanged (`val`). Granted I had to fill in some gaps, like how `Organization` is defined, how inserts are done, and how you check that updates work. 

If the problem does persist or you'd like more answers, please consider reopening this issue on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763), so we can attempt to assist you further. If you do so, please also consider providing the details requested above.
