### ISSUE TITLE
Json(b) data type support

### ISSUE THREAD

**Issue by Tapac** [JetBrains/Exposed#127]
Databases which support json(b) columns:

1. Mysql 5.7+
2. PostgreSQL
3. Oracle

**Comment by quangIO** [comment]
I wrote an extension for PostgreSQL, which supports basic read and write operations in case someone needs it: [jsonb.kt](https://gist.github.com/quangIO/a623b5caa53c703e252d858f7a806919)

**Comment by boonshift** [comment]
I added on a little bit on what @quangIO did... hopefully something like this or better will be supported by Exposed. [jsonb.kt](https://gist.github.com/boonshift/65edda0782137d2b3825f2ddc1d93fe3), [main.kt](https://gist.github.com/boonshift/79be440eb1b90119205b41c839924135) and [db.kt](https://gist.github.com/boonshift/aa7f777800a65f6c8fcba9972005b792)

**Comment by alacoste** [comment]
If anyone is running into issues with a ClassCastException to PGobject, I had the issue as well, see: https://gist.github.com/quangIO/a623b5caa53c703e252d858f7a806919#gistcomment-2902133

Completely beginner in this framework, so please correct me if I'm terribly wrong!

**Comment by AlexMiroshnikov** [comment]
@Tapac Any updates on the topic? Plans/roadmaps/merge requests/anything? 😊

**Comment by Tapac** [comment]
@AlexMiroshnikov, I will add it to a roadmap, but I want to escape using stong dependency to `jackson` or another json parsing library, so have to think about how to implement it properly.

**Comment by AlexanderTar** [comment]
> @AlexMiroshnikov, I will add it to a roadmap, but I want to escape using stong dependency to `jackson` or another json parsing library, so have to think about how to implement it properly.

May I suggest using semi-official [kotlinx.serialization](https://github.com/Kotlin/kotlinx.serialization) library?

**Comment by Rubyj** [comment]
@quangIO @boonshift Seems like these answers are a little out of date for the most current version of Kotlin. Does anyone have any updated code?

**Comment by yat90** [comment]
@Rubyj I made some changes to the Code of @boonshift to get it work for me, see [jsonb.kt](https://gist.github.com/yat90/78a110e28ab274fae30f53e94031cda1)

**Comment by Rubyj** [comment]
@yat90 This is great. Thanks!

**Comment by Rubyj** [comment]
@yat90 I had to make a few edits so it would pass ktlint. You can find those included [jsonb.kt](https://gist.github.com/Rubyj/fdcc7f1606f5f415edabd13ceea258fb)

**Comment by Rubyj** [comment]
@yat90 How is your column used? I am unable to do something like 

```
object Schema : Table(name = "schema") {
    val id = varchar("id", 50)
    override val primaryKey: PrimaryKey = PrimaryKey(id)
    val definition = jsonb("definition") //Type inference failed
}
```

**Comment by yat90** [comment]
@Rubyj Here is how I used it.

My Table Definition looks like 
```
class Product(id: EntityID<UUID>) : UUIDEntity(id) {
    companion object : UUIDEntityClass<Product>(ProductTable)
    var key by ProductTable.key
    var defaultParams by ProductTable.defaultParams
}

object ProductTable : UUIDTable("product") {
    val key = varchar("key", 50)
    val defaultParams = jsonb("default_params", MutableMap::class.java, Gson(), true)
    override val primaryKey = PrimaryKey(id, name = "product_pk")
}
```

And I'm inserting like this

```
var paramsMap: MutableMap<String, Any> = HashMap<String, Any>()
paramsMap.put("foo", "bar)

transaction {
    Product.new {
        key = UUID.randomUUID().toString()
        defaultParams = paramsMap
    }
}
```

As you can see in the code of @boonshift he has some different functions for MariaDB Support and for the PostgreSQL Support in his code. One of the different is the SQL Type and the `toSQL` function.

I think you have to adjust the SQL Type and the `toQueryBuilder` function that it can work with H2 Databases.

**Comment by ib-jamesp** [comment]
@yat90, thanks for posting your code, could you utilize the same for persisting a json array to a jsonb field? I've been looking at how to persist and retrieve however seem to get type issues.

**Comment by nvta-sbiyyala** [comment]
@ib-jamesp I was persist a `json array` to `jsonb`, verified its queryable

_On a separate note_: I prefer using `jackson` over `gson` as the parsing library - 
Here's a `jackson` version of @yat90 's solution (Thank you!) - 
https://gist.github.com/nvta-sbiyyala/fa327d449d98f37dacead7241af2c683

**Comment by ib-jamesp** [comment]
Thanks @nvta-sbiyyala, I ended up adding support for passing an interface into the jsonb field so that we were not coupled to a specific JSON parser (as mentioned by Tapac [here](https://github.com/JetBrains/Exposed/issues/127#issuecomment-558352712)). We are now parsing the json field by type.

```
fun <T : Any> Table.jsonb(name: String, jsonParser: IJsonParser, nullable: Boolean): Column<T> {
    return registerColumn<T>(name, ParsedJsonColumnType<T>(jsonParser, nullable))
}

class ParsedJsonColumnType<out T : Any>(private val parser: IJsonParser, override var nullable: Boolean) : IColumnType {
    override fun setParameter(stmt: PreparedStatementApi, index: Int, value: Any?) {
        val obj = PGobject()
        obj.type = "jsonb"
        if (value != null)
            obj.value = parser.toJson(value)
        stmt[index] = obj
    }

    @Suppress("TooGenericExceptionCaught", "TooGenericExceptionThrown")
    override fun valueFromDB(value: Any): Any = when (value) {
        is HashMap<*, *> -> value
        is Map<*, *> -> value
        else -> {
            value as PGobject
            try {
                val json = value.value
                parser.fromJson(json)!! // this will throw null reference on purpose
            } catch (e: Exception) {
                e.printStackTrace()
                throw RuntimeException("Can't parse JSON: $value")
            }
        }
    }
    override fun notNullValueToDB(value: Any): Any = parser.toJson(value)
    override fun nonNullValueToString(value: Any): String = "'${parser.toJson(value)}'"
    override fun sqlType() = "jsonb"
}

// Interface
interface IJsonParser {
    fun fromJson(json: String): Any?
    fun toJson(source: Any): String
}

// Implementation of jsonb field with parser as 'MetaData' is abstract class with Type embedded
val classTypeMetadata = jsonb<MetaData>("meta_data", MetaDataParser(), true)

```

I would rather have the parsers abstracted away from our code in case we ever replace the implementation.

**Comment by nvta-sbiyyala** [comment]
Thanks @ib-jamesp ! Tested the `Jackson` implementation -
```
class JacksonParser<T>(
    private val klass: Class<T>,
    private val jsonMapper: ObjectMapper = jacksonObjectMapper()
) : IJsonParser {

    override fun fromJson(json: String): T = jsonMapper.readValue<T>(json, klass)

    override fun toJson(source: Any): String = jsonMapper.writeValueAsString(source)
}

```

**Comment by qoomon** [comment]
I've adjusted the other examples a little and add JsonParser Implementations for kotlinx.serialization, Gson and Jackson

```kotlin
package me.qoomon.examples

import com.fasterxml.jackson.databind.ObjectMapper
import com.google.gson.Gson
import kotlinx.serialization.KSerializer
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonConfiguration
import org.jetbrains.exposed.sql.statements.api.PreparedStatementApi
import org.postgresql.util.PGobject

import kotlinx.serialization.serializerByTypeToken
import org.jetbrains.exposed.sql.*
import org.jetbrains.exposed.sql.Function

class JsonColumnType<out T : Any>(
    private val klass: Class<T>,
    private val parser: JsonParser,
    override var nullable: Boolean
) : ColumnType() {
    override fun sqlType() = "jsonb"

    override fun setParameter(stmt: PreparedStatementApi, index: Int, value: Any?) {
        stmt[index] = PGobject().apply {
            this.type = sqlType()
            this.value = value as String?
        }
    }

    override fun valueFromDB(value: Any): Any = when (value) {
        is PGobject -> parser.parse(klass, value.value)
        is Map<*, *> -> value
        is HashMap<*, *> -> value
        else -> throw IllegalArgumentException("Unexpected value type ${value::class}")
    }

    @Suppress("UNCHECKED_CAST")
    override fun notNullValueToDB(value: Any): Any = parser.stringify(klass, value as T)

    @Suppress("UNCHECKED_CAST")
    override fun nonNullValueToString(value: Any): String = "'${parser.stringify(klass, value as T)}'"
}

class JsonKey(val key: String) : Expression<String>() {
    init {
        if (!key.matches(Regex("\\w+"))) throw IllegalArgumentException("Only simple json key allowed. Found '$key'")
    }

    override fun toQueryBuilder(queryBuilder: QueryBuilder) = queryBuilder { append(key) }
}

fun <T : Any> Table.jsonb(name: String, klass: Class<T>, parser: JsonParser, nullable: Boolean): Column<T> {
    return registerColumn(name, JsonColumnType(klass, parser, nullable))
}

inline fun <reified T> Column<Map<*, *>>.json(jsonKey: JsonKey): Function<T> {
    val columnType = when (T::class) {
        Int::class -> IntegerColumnType()
        String::class -> VarCharColumnType()
        Boolean::class -> BooleanColumnType()
        else -> throw java.lang.RuntimeException("Column type ${T::class} not supported for json field.")
    }

    return JsonValue(this, jsonKey, columnType)
}


class JsonValue<T>(
    val expression: Expression<*>,
    val jsonKey: JsonKey,
    override val columnType: IColumnType
) : Function<T>(columnType) {
    override fun toQueryBuilder(queryBuilder: QueryBuilder) =
        queryBuilder { append("CAST((${expression.toQueryBuilder(queryBuilder)} ->> '${jsonKey.key}') AS ${columnType.sqlType()})") }
}

interface JsonParser {
    fun <T> parse(klass: Class<T>, string: String): T
    fun <T> stringify(klass: Class<T>, value: T): String
}

class KotlinxJsonParser(val json: Json = Json(JsonConfiguration.Stable)) : JsonParser {
    override fun <T> parse(klass: Class<T>, string: String): T = json.parse(klass.serializer(), string)
    override fun <T> stringify(klass: Class<T>, value: T): String = json.stringify(klass.serializer(), value)

    private val serializerMap = HashMap<Class<*>, KSerializer<Any>>()

    @Suppress("UNCHECKED_CAST")
    private fun <T> Class<T>.serializer() = serializerMap.getOrPut(this, {
        serializerByTypeToken(this)
    }) as KSerializer<T>
}

class GsonJsonParser(val gson: Gson = Gson()) : JsonParser {
    override fun <T> parse(klass: Class<T>, string: String): T = gson.fromJson(string, klass)
    override fun <T> stringify(klass: Class<T>, value: T): String = gson.toJson(value, klass)
}

class JacksonJsonParser(val objectMapper: ObjectMapper = ObjectMapper()) : JsonParser {
    override fun <T> parse(klass: Class<T>, string: String): T = objectMapper.readValue<T>(string, klass)
    override fun <T> stringify(klass: Class<T>, value: T): String = objectMapper.writeValueAsString(value)
}
```

**Comment by brezinajn** [comment]
@qoomon The `Class<T>` based approach would be problematic if you wanted to serialize for example List of something, wouldn't it? Wouldn't this be a better pattern?
```Kotlin
fun <T : Any> Table.json(name: String, kSerializer: KSerializer<T>, json: Json): Column<T> =
    this.json(name = name, stringify = { json.stringify(kSerializer, it) }, parse = { json.parse(kSerializer, it) })

fun <T : Any> Table.json(name: String, stringify: (T) -> String, parse: (String) -> T): Column<T> =
    registerColumn(name, JsonColumnType(stringify, parse))

class JsonColumnType<T : Any>(private val stringify: (T) -> String, private val parse: (String) -> T) : ColumnType() {
    override fun sqlType(): String = "json"
    override fun valueFromDB(value: Any) = parse(value as String)

    @Suppress("UNCHECKED_CAST")
    override fun notNullValueToDB(value: Any) = stringify(value as T)

    override fun valueToString(value: Any?): String = when (value) {
        is Iterable<*> -> notNullValueToDB(value)
        else -> super.valueToString(value)
    }
}
```
Also do we really need the `JsonParser` interface?

**Comment by qoomon** [comment]
@brezinajn I agree

**Comment by qoomon** [comment]
here is my latest version https://gist.github.com/qoomon/70bbbedc134fd2a149f1f2450667dc9d

**Comment by ib-jamesp** [comment]
@brezinajn / @qoomon The only reason I included a JsonParser was to keep away from a specific implementation of a json serializing package (Gson vs Jackson vs add your one here). Awesome work though as there are definite positives to your implementations!

**Comment by toastyblast** [comment]
I'm making use of the solution made by @Rubyj from [this comment](https://github.com/JetBrains/Exposed/issues/127#issuecomment-590985569), when I found it several weeks ago. It's been working great for retrieving a JSONB field from my PostgreSQL 11 container. However, today I needed to add a case where I insert data with Kotlin Exposed to the DB, not just selecting from it anymore. This table too has a JSONB field, but whenever I try to push data to it, I get the following error:
```
Exception in thread "DefaultDispatcher-worker-5" org.jetbrains.exposed.exceptions.ExposedSQLException: org.postgresql.util.PSQLException: ERROR: column "payload" is of type jsonb but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 157
SQL: [INSERT INTO Revisions (acknowledged_at, created_at, gatling_run_id, latest_attempt_at, message_id, payload, status, topic_name) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
<Error stack...>
```

I understand the error, I think, but I'm not sure what's causing it. I saw a somewhat similar issue in [this comment](https://github.com/JetBrains/Exposed/issues/127#issuecomment-590997573) from @Rubyj and [this comment](https://github.com/JetBrains/Exposed/issues/127#issuecomment-591311889) from @yat90 but I can't seem to get mine to work. See the relevant code here:

revision_table.sql:
```
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE revisions (
    message_id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    gatling_run_id uuid,
    created_at TIMESTAMPTZ NOT NULL,
    latest_attempt_at TIMESTAMPTZ NOT NULL,
    acknowledged_at TIMESTAMPTZ,
    topic_name VARCHAR(256) NOT NULL,
    payload JSONB NOT NULL,
    status SMALLINT DEFAULT 1
)
```

revision.kt:
```
object Revisions : Table() {
    val messageID: Column<UUID> = uuid("message_id").autoGenerate().primaryKey()
    val createdAt: Column<DateTime> = datetime("created_at")
    val latestAttemptAt: Column<DateTime> = datetime("latest_attempt_at")
    val acknowledgedAt: Column<DateTime?> = datetime("acknowledged_at").nullable()
    val gatlingRunID: Column<UUID?> = uuid("gatling_run_id").nullable()
    val topicName: Column<String> = varchar("topic_name", 256)
    val payload = jsonb("payload", Map::class.java, Gson(), false)
    val status: Column<Short> = short("status").default(1)
}

data class Revision(
    val messageID: UUID,
    val createdAt: DateTime,
    val latestAttemptAt: DateTime,
    val acknowledgedAt: DateTime?,
    val gatlingRunId: UUID?,
    val topicName: String,
    val payload: Map<*, *>,
    val status: Short = 1
)
```

RevisionService.kt (only the relevant function):
```
object RevisionService {
    suspend fun logNewRevision(sendDate: DateTime, topic: String, message: Map<*, *>, runID: UUID? = null): UUID = dbQueryGatId(runID) {
        Revisions.insert {
            it[createdAt] = sendDate
            it[latestAttemptAt] = sendDate
            it[topicName] = topic
            it[payload] = message
            it[status] = 1
            it[gatlingRunID] = runID
        }[Revisions.messageID]
    }

    // ...
}
```

The only class that uses the function, DataOutMsgHandler.kt:
```
class DataOutMsgHandler(
    topicName: String,
    parentApp: String
) : OutgoingMsgHandler(topicName, parentApp) {
    override suspend fun handle(payload: Map<String, *>, properties: Map<String, Any>): Map<String, Any?> {
        val rawRunId = properties["run_id"] as String?
        var runUUID: UUID? = <Check rawRunID and parse to UUID>

        val messageId = RevisionService.logNewRevision(DateTime.now(), topicName, payload, runUUID)

        return mapOf(
            "action_flag" to ActionFlags.SEND.name,
            "message_id" to messageId,
            "gatling_run_id" to rawRunId
        )
    }
}
```

I hope someone here knows what may be causing this issue, because I'm stuck on it.

**Comment by qoomon** [comment]
I think it is because of the mapping from string to var char, it should rather be mapped to TextColumnType()
```
inline fun <reified T> Column<Map<*, *>>.json(jsonKey: JsonKey): Function<T> {
    val columnType = when (T::class) {
        Int::class -> IntegerColumnType()
        String::class -> VarCharColumnType()
        Boolean::class -> BooleanColumnType()
        else -> throw java.lang.RuntimeException("Column type ${T::class} not supported for json field.")
    }

    return json(jsonKey, columnType)
}```

**Comment by toastyblast** [comment]
@qoomon thank you for your swift response! I tried it out just now.

Sadly I'm still getting the exact same error from my previous comment. I thought maybe the inclusion of a DateTime might be causing an issue, so I tried adding that as well:
```
inline fun <reified T> Column<Map<*, *>>.json(jsonKey: JsonKey): Function<T> {
    val columnType = when (T::class) {
        Boolean::class -> BooleanColumnType()
        Int::class -> IntegerColumnType()
        Float::class -> FloatColumnType()
        Double::class -> DoubleColumnType()
        DateTime::class -> DateColumnType(true)
        String::class -> TextColumnType()
        else -> throw IllegalArgumentException("Type ${T::class} not supported for json fields.")
    }

    return json(jsonKey, columnType)
}
```
But I had no luck with that either, still getting the same error...

I also tried copying the code from your gist with your implementation you linked, but I can't get it to work due to your override fun setParameter. For me, the super.setParameter expects `stmt` to be `PreparedStatement` not `PerparedStatementApi`. Additionally, `ColumnType` doesn't have a `fun setParameter` for me (`IColumnType` only does, which `ColumnType` inherits) so the override in your example doesn't work. Even if I change your code to inherit `IColumnType` instead, the `stmt` being the wrong type issue still applies.

**Comment by qoomon** [comment]
@toastyblast I just verified that it is compiling. I don't know what's going wrong on you side.
However I had another idea what might causing your problem. Do you teach you JSON parse to handle(serialize and deserialize) `DateTime`?
May you can write a tiny test so I can have a look at that reproduce your error?

**Comment by toastyblast** [comment]
@qoomon I'm currently not doing anything of the sort, as far as I'm aware. I'm using Gson to do the parsing, and I don't know how to make that handle my JodaTime DateTime objects (as far as I'm aware that should just use JodaTime's toString and print out the ISO standard timestamp, but I don't know) - Do you have any idea of this?

Also, I find that odd with the compilation, maybe you have some additional libraries I don't have, or different versions than what I put in my previous comment, I have no clue.

**Comment by qoomon** [comment]
you could make use of this lib https://github.com/gkopff/gson-jodatime-serialisers

**Comment by Rubyj** [comment]
@qoomon @toastyblast The discrepancies between your errors looks like, to me, you are both using different versions of kotlin

**Comment by toastyblast** [comment]
It's nearing midnight for me, so I'll check out the library tomorrow, @qoomon 

As for Kotlin, I'm running one of the latest versions, don't know exactly which one but the project started a few months ago, and I got the latest at the time. I'll drop that tomorrow as well, if need be!

**Comment by toastyblast** [comment]
After some more testing I think what is causing the issue is PSQL simply not recognising the incoming string as being JSON/JSONB castable, due to the error clearly stating it's seeing it as a VARCHAR (character variable) and not JSONB. The timestamp issue @qoomon thought up I thought was promising too, but on review I realised my `payload` map never had `DateTime`s in them. I still attempted your idea however, of adding that library, but again it had no effect since I never included timestamps anyways.

In the end I've decided to change my table's JSONB field to TEXT and simply store my JSON-valid string. The application that queries this table never actually accesses the JSON anyways, it was more me trying to be more specific. And if the querying application does need the strings as JSON in the future, it can simply parse them itself and process them, it doesn't need them to be stored as JSON for this, since it is never going to query the DB on fields of the payload anyways.

Still, thanks for the help guys, particularly @qoomon and @Rubyj ! The issue does stand, but I hope nobody runs into it in the future. I for one have no clue how to fix or prevent it except for just storing my valid json string in a TEXT field, until Exposed natively supports JSON & JSONB.

**Comment by jeffgnpc** [comment]
@qoomon Thanks for sharing your code.  I have included it my project and I'm able to create simple CRUD operations.  I see you have add `json` and `contains` methods, but I can't understand how they are suppose to be used.   Can you please include examples of how those are suppose to be used?  Thanks.

**Comment by qoomon** [comment]
with `json` you can select nested json field, it will be casted to given type.
* `....json<String>("foo", "bar")` will result in a `JsonValue<String>` with value of json path `foo.bar`. With that `Function<String>` you can do whatever comparison you can do with normal String field as well like `....like(pattern)`
* `....json<Any>("foo", "bar")` will return a `JsonValue<Any>`. For this `Function<Any>` I created a extension function `contains` to check if a field exists in an json object or a value exists in an json array. it utilize the `?` postgres operator for json objects, see https://www.postgresql.org/docs/9.4/functions-json.html

e.g. 
```kotlin
data class Role(val name: String, val permissions: List<Permission> = emptyList())

object UsersTable : UUIDTable("users") {
    val name = varchar("name", 50).index()
    val role = jsonb("role", Role.serializer())
}

val user = UserEntity.find {
    UsersTable.role.json<Any>("permissions").contains("auth")
}.firstOrNull()
```

**Comment by jnfeinstein** [comment]
@qoomon the gist works well.  I opted to require `Column<String>` forcing the caller to serialize the data themselves.  My persistence layer is not in the business of having opinions regarding serialization, it just puts the data where it needs to be.

I'm now searching for the proper incantation to create an index on the JSONB data.  I have tried:
```
    init {
        index(false, Column<String>(this, "(details ->> 'user_id')", VarCharColumnType()))
    }
```
resulting in:
```
CREATE INDEX "subscription_(details ->> 'user_id')" ON "subscription" ("(details ->> 'user_id')")
```
which obviously does not work. 😄

**Comment by qoomon** [comment]
@jnfeinstein may you can give a full example (as an git repository ) and the expected result?

**Comment by jnfeinstein** [comment]
Sure, I'll prepare one.  In the meantime, the working syntax is:
```
// This works
CREATE INDEX subscription_details_userId ON "subscription" ((details ->> 'userId'))
// This also works
CREATE INDEX "subscription_details_userId" ON "subscription" (((details->>'userId')::uuid))
```
I'm not sure Exposed supports this, due to [this](https://github.com/JetBrains/Exposed/blob/master/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt#L708) line, which forces the column names to be quoted.

**Comment by qoomon** [comment]
I think you are right, due to this [line](https://github.com/JetBrains/Exposed/blob/master/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt#L708) it is not possible right now :-(

**Comment by edeak** [comment]
@Tapac do you guys have any updates on this?

**Comment by sabiou** [comment]
co asking

**Comment by OlivierMary** [comment]
Hi there,

@qoomon I test your class and I didn't understand how to make a clause where with jsonb.

How to make this select:
`SELECT * FROM users WHERE metadata->>'country' = 'FR'` ?

Thks for your help.

**Comment by qoomon** [comment]
@OlivierMary Hi it was just a prove of concept. I don't know if it's still working, probably not.

**Comment by OlivierMary** [comment]
@qoomon ok, so no way to make a select like this ? 
I easily insert, and select by id with your class it's just where clause the problem :s will have to whitch to other framework if can't.

**Comment by OlivierMary** [comment]
If somebody need it I do it with :

```kotlin
fun <T:Any> String.execAndMap(transform : (ResultSet) -> T) : List<T> {
    return TransactionManager.current().exec(this) { rs ->
        sequence {
            while (rs.next()) {
                yield(transform(rs))
            }
        }.toList()
    }?:throw IllegalArgumentException("Invalid SQL '${this}'.")
}
```
usage
```kotlin
                val metadatas: List<Metadata> =
                    "SELECT metadata FROM users WHERE metadata->>'country' = 'FR';".execAndMap { rs ->
                        format.decodeFromString(rs.getString("metadata"))
                    }
```

**Comment by sounlucky** [comment]
would love to see an update

**Comment by Displee** [comment]
Update pls

**Comment by orpheus** [comment]
2022 update?

**Comment by brezinajn** [comment]
I can provide code we're using for few years in production (mysql and mssql) and without a problem. It's very easy to extend for different serialization solutions. It'd be nicer to have a first party support from the library and it's missing most of the capabilities, but hey, better than nothing.

``` Kotlin
inline fun <reified T : Any> Table.json(
    name: String,
    kSerializer: KSerializer<T> = serializer(),
    json: Json
): Column<T> =
    this.json(
        name = name,
        stringify = { json.encodeToString(kSerializer, it) },
        parse = { json.decodeFromString(kSerializer, it) },
    )

fun <T : Any> Table.json(name: String, stringify: (T) -> String, parse: (String) -> T): Column<T> =
    registerColumn(name, JsonColumnType(stringify, parse))

class JsonColumnType<T : Any>(private val stringify: (T) -> String, private val parse: (String) -> T) : ColumnType() {
    override fun sqlType(): String = "json"
    override fun valueFromDB(value: Any) = parse(value as String)

    @Suppress("UNCHECKED_CAST")
    override fun notNullValueToDB(value: Any) = stringify(value as T)

    override fun valueToString(value: Any?): String = when (value) {
        is Iterable<*> -> notNullValueToDB(value)
        else -> super.valueToString(value)
    }
}
```

``` Kotlin

inline infix fun <reified T> Column<out Collection<T>>.contains(elem: T) =
    contains(elem, Json, serializer())

inline fun <reified T> Column<out Collection<T>>.contains(elem: T, json: Json, serializer: KSerializer<T>) = Op.build {
    JsonContains(this@contains, elem) { json.encodeToString(serializer, it) } eq true
}

fun <T> Column<out Collection<T>>.contains(elem: T, serialize: (T) -> String) = Op.build {
    JsonContains(this@contains, elem, serialize) eq true
}

// there is probably a better way of doing this
class JsonContains<out T>(
    private val column: Column<out Collection<T>>,
    private val value: T,
    private val serialize: (T) -> String,
) : Function<Boolean>(BooleanColumnType()) {
    override fun toQueryBuilder(queryBuilder: QueryBuilder) = queryBuilder {
        append("JSON_CONTAINS(")
        append(column)
        append(',')
        append("'")
        append(serialize(value))
        append("'")
        append(")")
    }
}
```

**Comment by vladtrc** [comment]
> I can provide code we're using for few years in production (mysql and mssql) and without a problem. It's very easy to extend for different serialization solutions. It'd be nicer to have a first party support from the library and it's missing most of the capabilities, but hey, better than nothing.
> 
> ```kotlin
> inline fun <reified T : Any> Table.json(
>     name: String,
>     kSerializer: KSerializer<T> = serializer(),
>     json: Json
> ): Column<T> =
>     this.json(
>         name = name,
>         stringify = { json.encodeToString(kSerializer, it) },
>         parse = { json.decodeFromString(kSerializer, it) },
>     )
> 
> fun <T : Any> Table.json(name: String, stringify: (T) -> String, parse: (String) -> T): Column<T> =
>     registerColumn(name, JsonColumnType(stringify, parse))
> 
> class JsonColumnType<T : Any>(private val stringify: (T) -> String, private val parse: (String) -> T) : ColumnType() {
>     override fun sqlType(): String = "json"
>     override fun valueFromDB(value: Any) = parse(value as String)
> 
>     @Suppress("UNCHECKED_CAST")
>     override fun notNullValueToDB(value: Any) = stringify(value as T)
> 
>     override fun valueToString(value: Any?): String = when (value) {
>         is Iterable<*> -> notNullValueToDB(value)
>         else -> super.valueToString(value)
>     }
> }
> ```
> 
> ```kotlin
> inline infix fun <reified T> Column<out Collection<T>>.contains(elem: T) =
>     contains(elem, Json, serializer())
> 
> inline fun <reified T> Column<out Collection<T>>.contains(elem: T, json: Json, serializer: KSerializer<T>) = Op.build {
>     JsonContains(this@contains, elem) { json.encodeToString(serializer, it) } eq true
> }
> 
> fun <T> Column<out Collection<T>>.contains(elem: T, serialize: (T) -> String) = Op.build {
>     JsonContains(this@contains, elem, serialize) eq true
> }
> 
> // there is probably a better way of doing this
> class JsonContains<out T>(
>     private val column: Column<out Collection<T>>,
>     private val value: T,
>     private val serialize: (T) -> String,
> ) : Function<Boolean>(BooleanColumnType()) {
>     override fun toQueryBuilder(queryBuilder: QueryBuilder) = queryBuilder {
>         append("JSON_CONTAINS(")
>         append(column)
>         append(',')
>         append("'")
>         append(serialize(value))
>         append("'")
>         append(")")
>     }
> }
> ```

could you make a PR to make it official?

**Comment by kresohr** [comment]
Any update on this?

**Comment by brezinajn** [comment]
> could you make a PR to make it official?
The thing is not all supported databases support json. This code works really just for mysql. I don't really currently have capacity to resolve this for all databases. If somebody wants to tackle that task feel free to use my code.

**Comment by voytovichs** [comment]
🙏

**Comment by xtexChooser** [comment]
Agree, it is needed and useful.

**Comment by xtexChooser** [comment]
Here is my implementation: [gist.github.com/xtexChooser/5ead6ff7f7b419c57efaa59cf2fef492](https://gist.github.com/xtexChooser/5ead6ff7f7b419c57efaa59cf2fef492).

This supports serializing JSON as TEXT as needed.

**Comment by nhalase** [comment]
If it's helpful for anyone, when I switched to using the Exposed DAO implementation, the solutions here no longer worked.

Using the DAO code was returning `Map<*, *>` rather than `PGobject` in some cases. I'm not sure if this is a bug, but it was hard to replicate and easier to fix in the `valueFromDB` method.

```kotlin
override fun valueFromDB(value: Any): Any {
    return when (value) {
        is PGobject -> parse(value.value ?: "")
        is Map<*, *> -> value
        is List<*> -> value
        is Set<*> -> value
        is Array<*> -> value
        else -> {
            println("unhandled value type: ${value::class}")
            value
        }
    }
}
```

**Comment by maggie-weber** [comment]
Can we get an official comment on whether this is being worked on? It's obviously a feature that many people have asked for which makes the lack of communication frustrating.

**Comment by xidsyed** [comment]
jsonb is widely supported, so it should happen soon enough

**Comment by arnabkd** [comment]
Just wanted to +1 this and say that this was probably the biggest factor in making me decide *not* to use this library when starting on a new hobby project. That is a shame, because this is exactly where I would want to use something quick and not build everything from scratch.

**Comment by hopingsteam** [comment]
Also wondering when the new release will be available to the public

**Comment by bog-walk** [comment]
@hopingsteam The release is now available.

**Comment by Alina-Valea-Forter** [comment]
I'm using release 0.42.0 from the Maven repo, but I can't find the new json() and jsonb() functions in there.

**Comment by bog-walk** [comment]
@Alina-Valea-Forter The new JSON column types and their related functions exist in their own module now, `exposed-json`, requiring an additional dependency in `build.gradle.kts`.

Please see the wiki for further details about the [data types](https://github.com/JetBrains/Exposed/wiki/DataTypes) and [how to use them](https://github.com/JetBrains/Exposed/wiki/DataTypes#how-to-use-json-and-jsonb-types).

If there are any issues or requests for enhancements, please don't hesitate to submit a ticket on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763).

**Comment by sundaycrafts** [comment]
The above links are no longer available, but future readers can find the usage in the tests of the [source code](https://github.com/JetBrains/Exposed/blob/main/exposed-json/src/test/kotlin/org/jetbrains/exposed/sql/json/JsonTestsData.kt#L155) (this link may also become outdated in the future, but you could infer the location of the code from the URL path). Below is a current example of how json(b) is used in the test code:

```kotlin
// define json(b) types for columns
@Serializable
data class DataHolder(val user: User, val logins: Int, val active: Boolean, val team: String?)

@Serializable
data class User(val name: String, val team: String?)

@Serializable
data class UserGroup(val users: List<User>)

// use columns in tables
object JsonTable : IntIdTable("j_table") {
    val jsonColumn = json<DataHolder>("j_column", Json.Default)
}

object JsonBTable : IntIdTable("j_b_table") {
    val jsonBColumn = jsonb<DataHolder>("j_b_column", Json.Default)
}

// entities
class JsonEntity(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<JsonEntity>(JsonTable)

    var jsonColumn by JsonTable.jsonColumn
}

class JsonBEntity(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<JsonBEntity>(JsonBTable)

    var jsonBColumn by JsonBTable.jsonBColumn
}

// json array tables
object JsonArrays : IntIdTable("j_arrays") {
    val groups = json<UserGroup>("groups", Json.Default)
    val numbers = json<IntArray>("numbers", Json.Default)
}

object JsonBArrays : IntIdTable("j_b_arrays") {
    val groups = jsonb<UserGroup>("groups", Json.Default)
    val numbers = jsonb<IntArray>("numbers", Json.Default)
}
```

**Comment by bog-walk** [comment]
@sundaycrafts Thank you for bringing this up and for sharing examples.

All Exposed wiki docs have been moved to [GitHub pages](https://jetbrains.github.io/Exposed/home.html). For future reference, this link is also available in the 'About' section of the repo's [main page](https://github.com/JetBrains/Exposed).

Here is the new link for [how to use the json data type](https://jetbrains.github.io/Exposed/data-types.html#how-to-use-json-and-jsonb-types).

**Comment by abdul-wahab-qbatch** [comment]
> @Rubyj Here is how I used it.
> 
> My Table Definition looks like
> 
> ```
> class Product(id: EntityID<UUID>) : UUIDEntity(id) {
>     companion object : UUIDEntityClass<Product>(ProductTable)
>     var key by ProductTable.key
>     var defaultParams by ProductTable.defaultParams
> }
> 
> object ProductTable : UUIDTable("product") {
>     val key = varchar("key", 50)
>     val defaultParams = jsonb("default_params", MutableMap::class.java, Gson(), true)
>     override val primaryKey = PrimaryKey(id, name = "product_pk")
> }
> ```
> 
> And I'm inserting like this
> 
> ```
> var paramsMap: MutableMap<String, Any> = HashMap<String, Any>()
> paramsMap.put("foo", "bar)
> 
> transaction {
>     Product.new {
>         key = UUID.randomUUID().toString()
>         defaultParams = paramsMap
>     }
> }
> ```
> 
> As you can see in the code of @boonshift he has some different functions for MariaDB Support and for the PostgreSQL Support in his code. One of the different is the SQL Type and the `toSQL` function.
> 
> I think you have to adjust the SQL Type and the `toQueryBuilder` function that it can work with H2 Databases.

I'm getting this error 
Unresolved reference: jsonb

**Comment by sschuberth** [comment]
> Unresolved reference: jsonb

@abdul-wahab-qbatch you need to add a dependency on the `exposed-json` Maven artifact and `import org.jetbrains.exposed.sql.json`.

**Comment by asllani94** [comment]
Anyone that could make this work with `0.50.0 `version
