### ISSUE TITLE
Better customisation of sequences

### ISSUE THREAD

**Issue by rtc11** [JetBrains/Exposed#1280]
Today the sequence will start on 0:
https://github.com/JetBrains/Exposed/blob/d59247283dc8c1af019e3e2a8c75c7519d1fdb6d/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt#L1045

Would be nice to support customisation of the sequence:

```kotlin
    override val id = integer("id").autoIncrement(name = "awesome_seq", startWith = 1_000_000).entityId()
```

I have to start my sequences with a higher start value like 1_000_000.

I could use Flyway to solve this easily, but then the DDLs from exposed and flyway will differ. I really dont want to be this dependent on Flyway as I dont see how they will stay relevant for much longer (in the kotlin world)

**Comment by bog-walk** [comment]
Hi @rtc11 , in the event that you are using a database that supports `CREATE SEQUENCE` operation (like PostgreSQL), you could set this up yourself if you're in a bind. Something like this for example:
```kt
object Tester : IdTable<Int>("tester") {
    override val id = integer("id").autoIncrement("large_starter_seq").entityId()
    override val primaryKey = PrimaryKey(id)
}

transaction {
    // ...
    val seq = Sequence("large_starter_seq", startWith = 1_000_000)
    SchemaUtils.createSequence(seq)
    SchemaUtils.create(Tester)

    repeat(5) {
        Tester.insert { }
        // INSERT INTO tester (id) VALUES (NEXTVAL('large_starter_seq'))
    }

    Tester.selectAll().map { it[tester.id] }
    // [1000000, 1000001, 1000002, 1000003, 1000004]

    SchemaUtils.drop(Tester)
}
```
I'm still going to tag this as a nice-to-have enhancement for all other db, so a delayed thank you for this suggestion!

**Comment by bog-walk** [comment]
It will be possible to provide a custom sequence instance to `autoIncrement()` in the upcoming version 0.54.0.
