### ISSUE TITLE
`timestamp` column modifying timestamp both in queries and after `wrapRow`

### ISSUE THREAD

**Issue by damien-roche** [JetBrains/Exposed#1287]
I am using PostgreSQL and `timestamp` column type in my table definition.

Timestamp column in DB: "timestamp without time zone"

Example value in DB: "2021-06-28 04:00:00"
Example value from `ResultRow`: same as above!

Example value AFTER `wrapRow`: "2021-06-27T21:00:00Z" (my local timezone is +7)
Same kind of modification happens during a query if I pass `Instant` to for e.g. `select`.

So Exposed isn't just amending the timezone when it wraps the row, it's also falsely reporting it as UTC.

I assume it is something around this: https://github.com/JetBrains/Exposed/blob/f4d4fe334ebff11f9ce1469bb24796511ca8680a/exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/java-time/JavaDateColumnType.kt#L170

Would appreciate any suggestions.

Example code:

```kotlin
object MyTable : IntIdTable("my_table") {
    val createdAt = timestamp("created_at")
}

class MyTableEntity(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<MyTableEntity>(MyTable)
    var createdAt by MyTable.createdAt
}

MyTable.selectAll().map { MyTableObject.wrapRow(it) }
MyTable.select { MyTable.createdAt greaterEq Instant.now() }
```

**Comment by damien-roche** [comment]
Going to close as not sure this is an actual issue, though it didn't behave as I would expect. Whenever I use `timestamp` and `Instant` I expect no time offsets at any point.

I've "fixed" this by setting default system timezone to UTC.

**Comment by adamu** [comment]
I ran into this too. It seems that Exposed assumes the DB column is in `ZoneId.systemDefault()`'s timezone. Here is where it converts the `Instant`:

https://github.com/JetBrains/Exposed/blob/b33e26501e0218279417bfd27e0e5b160db2c9aa/exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/java-time/JavaDateColumnType.kt#L99-L103

Where `DEFAULT_DATE_TIME_STRING_FORMATTER` is:

https://github.com/JetBrains/Exposed/blob/b33e26501e0218279417bfd27e0e5b160db2c9aa/exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/java-time/JavaDateColumnType.kt#L18-L20

In my case, the column is in UTC, so not sure what to do about this (besides changing the system timezone).
