### ISSUE TITLE
How to cast max(datetime) to string

### ISSUE THREAD

**Issue by Shashank-Nous** [JetBrains/Exposed#1291]
I'm trying to fetch max(datetime) column as string. Please refer to the code snippet

Fetch Function
```kotlin
fun fetchMaxDateasString(id: String): String? {
        return transaction(readDb) {
            val maxDate = BatchTable.Date.max()
            BatchTable.slice(maxDate).selectAll()
                .limit(1)
                .firstOrNull()
                ?.getOrNull(maxDate)
        }
    }
```

Table definition
```kotlin
object BatchTable : Table("batch") {
    val id = varchar("id", 32)
    val Date = dateAsString("Date")
    override val primaryKey = PrimaryKey(id)
}
```

DateasString ColumnType
```kotlin
class DateAsStringColumnType : ColumnType() {
    override fun sqlType(): String = currentDialect.dataTypeProvider.dateTimeType()
    override fun readObject(rs: ResultSet, index: Int): Any? {
        return rs.getString(index)
    }
}
fun Table.dateAsString(name: String): Column<String> = registerColumn(name, DateAsStringColumnType())


```
This throws me ClassCastException, Cannot cast Timestamp to String

**Comment by Tapac** [comment]
Can you please provide a stacktrace and on which database you had it?

**Comment by madana-i** [comment]
@Shashank-Nous 
You may have to define DateAsStringColumnType like this
```
class DateAsStringColumnType : ColumnType() {
    companion object {
        private val DATETIME_FORMATTER = DateTimeFormatter.ofPattern("Your Format")
    }

    override fun sqlType(): String = currentDialect.dataTypeProvider.dateTimeType()

    override fun setParameter(stmt: PreparedStatementApi, index: Int, value: Any?) {
        if (value is String) {
            stmt.set(index, Instant.from(DATETIME_FORMATTER.parse(value)))
        }
    }

    override fun readObject(rs: ResultSet, index: Int): String =
        DATETIME_FORMATTER.format(rs.getTimestamp(index).toInstant())
}
```

**Comment by bog-walk** [comment]
Please consider reopening this issue on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763) if the problem requires more answers than the 1 provided above, so we can attempt to assist you properly. If you do so, please also provide the requested details above (database being used + stacktrace), as well as the following:
- your current custom column definition (or the built-in column type you'd prefer to use, if applicable)
- the format that you're providing data for insertion (and which datetime module is being used as a dependency, if applicable)
