### ISSUE TITLE
Support range types for Postgres

### ISSUE THREAD

**Issue by rsromanowski** [JetBrains/Exposed#1298]
Postgres has many built-in range types for fields: https://www.postgresql.org/docs/current/rangetypes.html

PostgreSQL comes with the following built-in range types:
- int4range — Range of integer
- int8range — Range of bigint
- numrange — Range of numeric
- tsrange — Range of timestamp without time zone
- tstzrange — Range of timestamp with time zone
- daterange — Range of date

**Comment by OlivierCavadenti** [comment]
I will take a look of this issue soon.

**Comment by pratikdotexe** [comment]
@OlivierCavadenti Did you take a look?

**Comment by philipchang-RL** [comment]
@OlivierCavadenti Was there ever a resolution for these supported range types in exposed? I tried implementing my own custom column types in exposed to support tstzrange however, the exposed JDBC driver complains when trying to insert a tstzrange formatted string into the tstzrange formatted column. Here is an example of the error: `ERROR: column "_valid_period" is of type tstzrange but expression is of type character varying
`
