### ISSUE TITLE
Provide Reactive SQL support

### ISSUE THREAD

**Issue by sdeleuze** [JetBrains/Exposed#13]
Using https://github.com/alaisi/postgres-async-driver, it could be nice to provide Reactive SQL support, or at least make it possible to use Exposed to generate SQL that can be used as a String input parameter in `postgres-async-driver` (maybe this is already possible).

Any thoughts?

**Comment by Tapac** [comment]
As I can see postgres-async-driver is not jdbc compatible driver, so you can't use it with Exposed Database/Session/Queries.
So as workaround, if you still want to use Exposed mapping and query dsl, you can add top-level extension function :
```kotlin 
fun com.github.pgasync.DB.queryRows(q: kotlin.sql.Query) = queryRows(q.toSQL(QueryBuilder(false)))
```
or something more suitable for chaining
```kotlin 
fun kotlin.sql.Query.queryRows(db: com.github.pgasync.DB) = db.queryRows(toSQL(QueryBuilder(false)))
```
