### ISSUE TITLE
Support ORDER BY SIGN(column) and ABS(column)

### ISSUE THREAD

**Issue by martinpaoloni** [JetBrains/Exposed#1301]
It would be nice if we could order query results by sign or absolute value of a numeric column.
Something like:

```kotlin
return Account
    .find {
        Accounts.accountType.eq(accountType)
    }.orderBy(Accounts.balance.sign() to SortOrder.ASC, Accounts.balance.abs() to SortOrder.ASC)
    .toList()
```

Which should translate to something like:
```sql
SELECT ...
FROM ACCOUNT
WHERE ACCOUNT_TYPE = ...
ORDER BY SIGN(BALANCE) ASC, ABS(BALANCE) ASC
```

Apologies if this feature already exists and I failed to find it in the documentation.

Thanks in advance!

**Comment by Tapac** [comment]
Different math and trigonometrical functions were added. WIll be released soon.
