### ISSUE TITLE
Add support for postgres citext

### ISSUE THREAD

**Issue by Flaxoos** [JetBrains/Exposed#1304]
https://www.postgresql.org/docs/current/citext.html

Please add support for postgres type citext that allows using case insensitive text

**Comment by Danat** [comment]
I am leaving it here In case if someone has the same problem with reading `citext` columns. 
I used `binary` column type then I decode it to String by `.decodeToString()`.

**Comment by acadeau** [comment]
Hey,

I just want to share a piece of code I use for citext column: 
```kotlin
class CitextColumnType: StringColumnType() {
    override fun valueFromDB(value: Any): Any = when (value) {
        is PGobject -> value.toString()
        else -> super.valueFromDB(value)
    }

    override fun sqlType(): String = "citext"
}

fun Table.citext(name: String) = registerColumn<String>(name, CitextColumnType())
```
This is not perfect, but it works.

**Comment by apollopattern** [comment]
@acadeau's solution above worked great for us for reading, but as soon as we tried to create a model we got "PSQLException: ERROR: type "citext" does not exist." Which seems odd to me, I browse the database with TablePlus and that's exactly how it describes that field. (data_type == citext.)

**Comment by acadeau** [comment]
> @acadeau's solution above worked great for us for reading, but as soon as we tried to create a model we got "PSQLException: ERROR: type "citext" does not exist." Which seems odd to me, I browse the database with TablePlus and that's exactly how it describes that field. (data_type == citext.)

Strange, It looks like that `citext` extension is not present, but if you say that field is described as it, it should be created. 
Did you try to recreate extension just in case (e.g `CREATE EXTENSION citext;`)?
However, it could be just a case sensitivity problem, can you try `sqlType(): String = "CITEXT"`.

I admit that I don't really know if it will work 😄 .

Also which Postgres version do you use?
