### ISSUE TITLE
LocalDate with UTC timezone instead of system default

### ISSUE THREAD

**Issue by toth-istvan-zoltan** [JetBrains/Exposed#1305]
As of now, LocalDate is converted into milliseconds with the system default timezone: [JavaDateColumnType.kt](https://github.com/JetBrains/Exposed/blob/master/exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/java-time/JavaDateColumnType.kt)

This does not work in our use case where:

- we use Exposed on servers,  on Android devices, on Raspberry PI devices,
- we transfer SQLite databases between these.

With system default timezone there is no guarantee that the day will be the same on different devices.

Using UTC for the millisecond conversion would solve this problem, but changing the current behaviour might break existing installations.

What would be the best way to add the option to use UTC? If it can be a general solution I'll put  it into a pull request of course.

Thank you for your help.

**Comment by Cleidiano** [comment]
The change to use UTC instead `ZoneId.systemDefault()` will be great.
