### ISSUE TITLE
Table name conflicting with SQL syntax

### ISSUE THREAD

**Issue by BreimerR** [JetBrains/Exposed#1306]
```kotlin
object Table : IntIdTable("groups") {
    val name = varchar("name", 50)
    val description = varchar("description", 200)
    val parent = reference("parent", Table).nullable()
}
```
On table creation with MySQL(Ver 8.0.26-0 for Linux on x86_64) database

This throws an error in SQL.

Figured its naming conflict updated to; ​

```kotlin
object Table : IntIdTable("`groups`") {
   ​val name = varchar("name", 50)
   ​val description = varchar("description", 200)
   ​val parent = reference("parent", Table,)nullable()
}
```

Throws ``` `groups`_parent_id_fk ``` since backticks were transferred to FK name as is

**Comment by bog-walk** [comment]
@BreimerR In MySQL "groups" is as you suggested a [reserved keyword](https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-8-0-detailed-G). Testing with current version 0.41.1, there is no need to include backticks yourself in the table name as quotes are generated as needed by [`IdentifierManagerApi`](https://github.com/JetBrains/Exposed/blob/master/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/api/IdentifierManagerApi.kt). 

The issue I'm having trouble resolving is the line `val parent = reference("parent", Table).nullable()`. Is `Table` here a placeholder for another previously created table? If it isn't, it's clashing with Exposed's base class `Table()` and the object.

If it is just a stand in, and if the problem still persists in the current version, please include the specific exception that is being thrown, as well as the complete parent reference mapping, so we can attempt to reproduce the problem.

**Comment by bog-walk** [comment]
If the issue persists, please consider reporting it on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763), along with the requested information above.
