### ISSUE TITLE
Add support for creating comparables in ID Tables

### ISSUE THREAD

**Issue by uinnn** [JetBrains/Exposed#1308]
Sometimes I run into a very common problem, which is the `IdTable` asking for a comparable for my class, and in certain cases it's just impossible to add because the class doesn't implement the `Comparable`. It would be very useful for you to add the possibility of adding a way to create custom comparables directly in `IdTable`, thus making a class that didn't have a `Comparable` to be used in `IdTable`.

Let's assume this class (from a library)
```kt
class Location // constructors, properties, functions ...
```

It's impossible to i add in a IdTable because it doesn't implement a Comparable
```kt
abstract class LocationTable : IdTable<Location>() // error
```

My only idea of ​​working (currently) is to create another class that implements a Comparable, but clearly it's not cool to create a single class for a reason that doesn't implement the interface

So, I would very much like you to add support for creating Comparables from a class without having to extend it.

**Comment by Tapac** [comment]
The `Comparable` in IdTable is required as it represents the `EntityID` which should be comparable or it will not be possible to use functions like `greater/less/etc` and also easily compare ids on two entities like `entity1.id < entity2.id`.
Why not to implement Comparable in your class and what's more interesting here is how `Location` will be represented in a database (what column type it will use) ?

**Comment by uinnn** [comment]
I can't implement `Comparable` in the `Location` class because I don't have access to it, it's written in a public API (bukkit for Minecraft plugin).

The `Location` class would be represented as a string, being encoded by a serializer and being decoded again by the serializer (JSON string)

**Comment by Tapac** [comment]
If you talk about https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Location.html and you want to store it in a database then you should either create table with `world, x, y, z` columns or if you want to store it as some kind of a json then simple `text/varchar` column should be used. 
Exposed Table is a representation of SQL table in code, database knows nothing about Location, so you have to use existing types to replicate your class.

**Comment by uinnn** [comment]
I will try it, thanks!
