### ISSUE TITLE
exposed-spring-boot-starter:0.31.2 cannot find

### ISSUE THREAD

**Issue by LarryJung** [JetBrains/Exposed#1310]
in the REAMD.me at spring-starter module, 

https://github.com/JetBrains/Exposed/blob/master/exposed-spring-boot-starter/README.md

'org.jetbrains.exposed:exposed-spring-boot-starter:0.31.2'

cannot find module. but 0.31.1 is ok

**Comment by Tapac** [comment]
Thank you for your notice. It should be 0.32.1, now fixed
