### ISSUE TITLE
DSL Low performance?

### ISSUE THREAD

**Issue by MeowRay** [JetBrains/Exposed#1312]
Single-thread exposed query of indexed columns performance is 400qps
Native SQL is ~5000qps
![image](https://user-images.githubusercontent.com/29674595/128661832-53d328da-3166-4cf1-a6af-fc8d09b8197d.png)
![image](https://user-images.githubusercontent.com/29674595/128661529-1e6a3fc4-993d-4b7e-b195-214f1aa11566.png)
![image](https://user-images.githubusercontent.com/29674595/128661281-7e582c32-35d8-4603-b60e-c8ae5e5a2e50.png)
![image](https://user-images.githubusercontent.com/29674595/128661894-c0127b64-3e9e-46a5-9eb7-e0e4755cd511.png)

**Comment by Tapac** [comment]
Can you please share your test as a github project to allow checking it under profiler?

**Comment by MeowRay** [comment]
> Can you please share your test as a github project to allow checking it under profiler?

This is a very simple test, but the result is not ideal. What did I do wrong?

https://github.com/MeowRay/ExposedSimpleTest

**Comment by zeganstyl** [comment]
Yes, there is overhead in Exposed.
Look at [Transaction.exec()](https://github.com/JetBrains/Exposed/blob/f7286d759cc88e8a751c86eb65709aad6b6d4b17/exposed/src/main/kotlin/org/jetbrains/exposed/sql/Transaction.kt#L91), also [here](https://github.com/JetBrains/Exposed/blob/f7286d759cc88e8a751c86eb65709aad6b6d4b17/exposed/src/main/kotlin/org/jetbrains/exposed/sql/Transaction.kt#L124) and [Statement.executeIn](https://github.com/JetBrains/Exposed/blob/f7286d759cc88e8a751c86eb65709aad6b6d4b17/exposed/src/main/kotlin/org/jetbrains/exposed/sql/statements/Statement.kt#L31), you will see that it searches statement type, then it creates Statement object, measures time, iterates over arguments, etc. Many operations.
And when I checked this code:
```kotlin
transaction(database) {
connection.prepareStatement("INSERT INTO TEST_TABLE (\"KEY\", \"VALUE\") VALUES ($it, true)", false).executeUpdate()
}
```
preformance has almost doubled.
But also look at [transaction](https://github.com/JetBrains/Exposed/blob/f7286d759cc88e8a751c86eb65709aad6b6d4b17/exposed/src/main/kotlin/org/jetbrains/exposed/sql/transactions/ThreadLocalTransactionManager.kt#L60), there is also overhead with TransactionManager.
And when I checked this:
```kotlin
val con = TransactionManager.defaultDatabase!!.connector()
repeat(10000) {
    con.prepareStatement("INSERT INTO TEST_TABLE (\"KEY\", \"VALUE\") VALUES ($it, true)", false).executeUpdate()
}
```
preformance became as in testNative2, where `connection.autoCommit = true`.

I don't want to say that Exposed is bad. He is realy good at application prototyping.
May be Exposed should have mode where he builds SQL strings one time, caches them, injects arguments and passes them directly to driver connection?

**Comment by Tapac** [comment]
Indeed, I've checked your sample project and have few points:
1. You use raw statements while Exposed works with Prepared statements which can be slower to prepare (as they require an additional call to DB) but much safer and works well when prepared statements cache is turned on (like `cachePrepStmts=true&useServerPrepStmts=true` for MySQL connection string).
2. Also, when when you execute every insert inside `transaction` block it creates a new transaction that also has an overhead. You can try to move `transaction above `repeat` block.
3.

**Comment by Tapac** [comment]
@zeganstyl , the problem here is that Exposed works with different databases and it adds an overhead to ensure how to build statements for the database as they have different SQL notations.
Also, both `native` tests don't use setting values to prepared statements. It also adds overhead on driver level.

Caching statements are driver responsibility as you can store statement for MySQL and them try to execute it for PostgreSQL and then it fails.

**Comment by Tapac** [comment]
@MeowRay can you please apply the patch from https://gist.github.com/Tapac/f9093fa5c6d9125557b21a5448a5aff7 as  I do not have a permission to push to your repo.

I had tested it against H2 and it has output like:
```
native > insert time: 512ms, select time: 166ms
native2 > insert time: 450ms, select time: 503ms
exposed > insert time: 1976ms, select time: 1001ms
exposed2 > insert time: 335ms, select time: 365ms
```

**Comment by zeganstyl** [comment]
I have compared Exposed with Hibernate.
Hibernate is faster than Exposed, in some tests even twice.
https://github.com/zeganstyl/ExposedSimpleTest

**Comment by Tapac** [comment]
@zeganstyl , thank you for your test project it was very helpful and I found few bottlenecks to fix.
One more thing, please change:
```kotlin
    val database = Database.connect(url)
```
to
```kotlin
    val pool = JdbcConnectionPool.create(url, "", "");
    val database = Database.connect(pool)
```
as native tests use the same connection and hibernate uses connection pool, so the huge amount of time in Exposed tests spent in connection initialization.

**Comment by zeganstyl** [comment]
@Tapac, I have added connection pool and now Exposed works faster, and it is faster than Hibernate in insert test.

**Comment by Tapac** [comment]
It should be even better after the next release :)
