### ISSUE TITLE
Add support for DISTINCT in STRING_AGG functions for PostgreSQL

### ISSUE THREAD

**Issue by christxph** [JetBrains/Exposed#1313]
Hi,

Exposed does not support using the `DISTINCT` keyword in `STRING_AGG` functions for Postgres (`groupConcat` in Exposed) as it's explicitly disable in `PostgreSQL.kt#L36`:
https://github.com/JetBrains/Exposed/blob/5908c4021000cbab03a376d0391113ad0d50a0b0/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt#L36

However, Postgres supports using `DISTINCT` in `STRING_AGG` functions for a while now (couldn't find the exact version).

Does anything speak against implementing this in Exposed?

Thanks.

**Comment by Tapac** [comment]
Thank you for the info as I wasn't able to find such information in the official doc, also Order by clause is supported too.
