### ISSUE TITLE
How can i set null to Else condition on CaseWhen Expression?

### ISSUE THREAD

**Issue by lucasortigoso** [JetBrains/Exposed#1315]
Hello,

I need to put NULL value on else condition on Case When expression like below. How can i do that? 

` SqlExpressionBuilder.case()
                .When(
                    TblOne.foo.isNotNull(), wrapAsExpression<DateTime>(TblTwo.slice(TblTwo.createdDate.max()).select { TblTwo.foo eq TblOne.foo })
                )
                .Else(***how to put null here****)`

**Comment by Tapac** [comment]
`Op.nullOp()` added to cover the case. Will be released soon
