### ISSUE TITLE
Question: ClientDefault - access to an another column?

### ISSUE THREAD

**Issue by marek-hanzal** [JetBrains/Exposed#1323]
Is possible to access in clientDefault method in UUIDTable value of column later being inserted?

I want to generate hash of the input internally:
![image](https://user-images.githubusercontent.com/13855126/130080466-7f82477f-6d9d-4ef0-bfdf-db48543fa871.png)

Thanks for the answer!

**Comment by bog-walk** [comment]
If the value of the column later being inserted can be accessed using some SQL syntax, as part of the prepared insert statement, then `defaultExpression()` is the way to go.
If you mean the literal value that is set in every `insert` lambda block, then no, the `defaultValue` parameter would need to somehow take that value or the insert statement itself as the argument.

To accomplish this, either a custom insert needs to be implemented for the specific table, so it performs any internal logic on whatever data is provided to `insert()` before/when column-value assignment occurs.
Or a custom `InsertStatement` could be implemented that specifically overrides `valuesAndDefaults()` to add the necessary logic when `column.defaultValueFun != null`, for example.
