### ISSUE TITLE
Question issue: Kotlin DSL

### ISSUE THREAD

**Issue by hfazai** [JetBrains/Exposed#1324]
I see that there is two ways to design a kotlin DSL : 

1st way: Here you need to import `select` for every usage.

````KOTLIN
class Table { }

fun Table.select (init: T.() -> Unit) { }
````

2nd way: The advantage here is that you dont need to import `select`.

````KOTLIN
class Table {
  fun select (init: T.() -> Unit) { }
}
````

My question is why functional programming is prefered in Kotlin DSL while you can use the second way to get rid of the imports?

**Comment by Tapac** [comment]
It's a complicated question. My vision is that class functions should be used when it relates to class behavior and extensions should be used when it's something what `uses` class intstance. 

Also, class functions add more problems when used for open classes/interfaces, if you check `select` is an extention of `FieldSet` interface. If the `select` was an `FieldSet` function it's required to be implemented either in an interface (that looks dirty) or in each direct inheritor.

One more thing, when you use an extention function you only have access to public API of a class and it helps a lot in an design.

**Comment by hfazai** [comment]
Hi @Tapac,

That seems very reasonable :+1:  Thanks alot for the answer!
