### ISSUE TITLE
Subquery in an insert statement

### ISSUE THREAD

**Issue by hfazai** [JetBrains/Exposed#1327]
Is it possible to build this sql statement using Exposed ? :

`INSERT INTO TAB1(ID) VALUES ((SELECT ID FROM TAB2))`

**Comment by Tapac** [comment]
I think you use :
```kotlin
Tab1.insert(Tab2.slice(Tab2.id).selectAll(), listOf(Tab1.id))
```

**Comment by Tapac** [comment]
Also, there is `wrapAsExpression` function which can be used like (part of `InsertTests.testInsertWithColumnExpression`):
```kotlin
val expr1 = tbl1.string1.trim().substring(2, 4)
tbl2.insert {
   it[string2] = wrapAsExpression(tbl1.slice(expr1).select { tbl1.id eq id })
}
```

**Comment by hfazai** [comment]
Ah I wasn't aware we had these ways. So I think i should close #1328 ?
