### ISSUE TITLE
Entity hook for DSL

### ISSUE THREAD

**Issue by gfuller1** [JetBrains/Exposed#1329]
I was looking around and it appears there's an entity hook for DAO but not for DSL. I was curious why this is the case or if I'm overlooking something obvious (I'm not super familiar with the library). If I wanted to create a "entity hook" for DSL that tracked when entities were created/updated/deleted what would be the recommended approach for that or is that not possible?

**Comment by Tapac** [comment]
If you want to track DSL changes there is StatementInterceptor for that. What do you mean by track entities in DSL?

**Comment by gfuller1** [comment]
I mean just tracking changes to the database in general. That StatementInterceptor should work for what I'm trying to do and it looks like it captures both DAO and DSL changes which is nice. Thanks!
