### ISSUE TITLE
Error while using Exposed

### ISSUE THREAD

**Issue by TONY-All** [JetBrains/Exposed#1332]
I wrote two classes like that:
```kotlin
package cc.maxmc.maxmfa.data

import org.jetbrains.exposed.dao.UUIDEntity
import org.jetbrains.exposed.dao.UUIDEntityClass
import org.jetbrains.exposed.dao.id.EntityID
import org.jetbrains.exposed.dao.id.UUIDTable
import java.util.*

object SecretTable : UUIDTable() {
    val name = varchar("name", 50)
    val secret = text("secret")
}

class PlayerData(uid: EntityID<UUID>) : UUIDEntity(uid) {
    companion object : UUIDEntityClass<PlayerData>(SecretTable)

    var name by SecretTable.name
    var secret by SecretTable.secret
}
```
And When I using them like that:
```kotlin
val data = PlayerData.findById(uid) ?: return@transaction
```
This will be happened.
```
[11:05:02 WARN]: Caused by: java.lang.NullPointerException
[11:05:02 WARN]: 	at org.jetbrains.exposed.dao.EntityClass.<init>(EntityClass.kt:19)
[11:05:02 WARN]: 	at org.jetbrains.exposed.dao.UUIDEntityClass.<init>(UUIDEntity.kt:9)
[11:05:02 WARN]: 	at org.jetbrains.exposed.dao.UUIDEntityClass.<init>(UUIDEntity.kt:9)
[11:05:02 WARN]: 	at cc.maxmc.maxmfa.data.PlayerData$Companion.<init>(DAO.kt:21)
[11:05:02 WARN]: 	at cc.maxmc.maxmfa.data.PlayerData$Companion.<init>(DAO.kt)
```

**Comment by Tapac** [comment]
Are you sure that it fails on that code? From the stacktrace I can tell that Exposed wasn't able to find primary constructor on enclosing class (PlayerData).

**Comment by TONY-All** [comment]
yes... I printed a log and primerConstructor is null

**Comment by Tapac** [comment]
Is the code you provide is the exactly the same on which you had an exception?

**Comment by TONY-All** [comment]
yup

**Comment by Tapac** [comment]
So you use any post-processing tools or maybe obfuscation like proguard/zkm?

**Comment by TONY-All** [comment]
> Do you use any post-processing tools or maybe obfuscation like proguard/zkm?

yes... I relocate kotlin.* to kotlin1510.*

**Comment by Tapac** [comment]
It can be a problem as Exposed uses reflection, is it possible to check the code without relocation?

**Comment by Tapac** [comment]
I don't know any working ways to relocate kotlin stdlib (please share if you have some insights) but for Exposed and kotlin-reflect you can try to use [exposed-gradle-plugin](https://github.com/JetBrains/exposed-intellij-plugin/blob/master/exposed-gradle-plugin/README.md#shadow-plugin-relocate-extension-for-kotlin-classes)
