### ISSUE TITLE
Group by with sum

### ISSUE THREAD

**Issue by lucasrafagnin** [JetBrains/Exposed#1334]
Hi,

I'm writing the following SQL in my database:

<img width="542" alt="Captura de Tela 2021-09-02 às 21 49 36" src="https://user-images.githubusercontent.com/5746225/131934119-74e40ed9-09bd-4275-93be-bb657a723fa0.png">

and converted to Exposed as follows:

<img width="674" alt="Captura de Tela 2021-09-02 às 21 49 25" src="https://user-images.githubusercontent.com/5746225/131934368-d49db719-e741-4ac4-87b8-b9e465bd8f41.png">

but the result was:

`DEBUG Exposed - SELECT SUM(history.gain), MONTH(history.`date`) FROM history WHERE (history.user_id = 1) AND (history.`date` BETWEEN '2020-01-01' AND '2020-12-31')`

so any idea why group by is being ignored?

Thanks in advance

**Comment by guredd** [comment]
Seems groupBy is from Kotlin SDK, not from Exposed, check, how it is imported.

**Comment by lucasrafagnin** [comment]
Thank you @guredd, my mistake!
