### ISSUE TITLE
SchemaUtils.createMissingTablesAndColumns

### ISSUE THREAD

**Issue by Bqckword** [JetBrains/Exposed#1336]
I'm using SQLite

When I do "SchemaUtils.createMissingTablesAndColumns(PlayerDataTable)"

I get the following exception: https://sourceb.in/wKTgFweY48

I was wondering why that is?

**Comment by Tapac** [comment]
Can you specify the database on which it fails and also please attach tables mapping to check

**Comment by bog-walk** [comment]
Please reopen this issue if the problem persists with current version 0.41.1.

If it does and if possible, please share more table details so we can attempt to reproduce the problem.
