### ISSUE TITLE
Inline transaction

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/Exposed#1345]
```kotlin
val user: User
transaction {
   user = Users[42] // not possible due to potential reassigment
}
```
Solution:
- `inline` transaction
- Use contracts

Which solution do you prefer?

**Comment by Tapac** [comment]
You can simply write 
```kotlin
val user = transaction {
    Users[42]
}
```
but if you need to assign to val then only way is to define your own `transaction` function with contract and call Exposed `transaction` with repetition attempt 1.

**Comment by hfhbd** [comment]
@Tapac Thanks, the sample was (again) too small :D Yes, transaction returns the last value.

So you don't want to annotate/inline `transaction` in `core`?

**Comment by Tapac** [comment]
It won't help as `transaction`'s `statement` can't be marked with `InvocationKind.AT_MOST_ONCE` and it will prohibit.
You can try something like:
```kotlin
@OptIn(ExperimentalContracts::class)
inline fun <T> transactionCallOnce(db: Database?, noinline statement: Transaction.() -> T): T {
    contract {
        callsInPlace(statement, InvocationKind.EXACTLY_ONCE)
    }
    return transaction(db.transactionManager.defaultIsolationLevel, 1, db, statement)
}

val user: User
transactionCallOnce {
   user = Users[42]
}
```
IDEA highlights that `inline` here can affect performance so you can remove `inline` and `noinline` and it still should work.

**Comment by hfhbd** [comment]
Because it could be re-executed after a failure? Or why it cant be marked as `InvocationKind.EXACTLY_ONCE`?

**Comment by Tapac** [comment]
Yep, there is `repetitionAttempt` param in `transacation`.

**Comment by hfhbd** [comment]
Ah, okay, so there is no possibility due to retrying on failures. Thanks for the explanation.
