### ISSUE TITLE
How does Database.connect release? 

### ISSUE THREAD

**Issue by junhwong** [JetBrains/Exposed#135]
Exposed has a connection pool? 
How does `Database.connect` release? 
How to use with HikariCP(or similar to this frame)?

**Comment by msrd0** [comment]
I use this code to use HikariCP:

```kotlin
val dataSource : HikariDataSource
	
constructor()
{
	val url = "jdbc:postgresql://" + props("db.host") + ":" + props("db.port") + "/" + props("db.name")
	Class.forName("org.postgresql.Driver")
	
	val cfg = HikariConfig()
	cfg.jdbcUrl = url
	cfg.username = props("db.username")
	cfg.password = props("db.password")
	dataSource = HikariDataSource(cfg)
	Database.connect(dataSource)
	
	logger.info("DB: Connected to $url")
}
```

**Comment by junhwong** [comment]
@msrd0 your code just init a HikariCP instance,  but not related to destructor.
i.g. in web app. pre request a thread call ?
```kt
transaction {
        logger.addLogger(StdOutSqlLogger)
        ...
    }
```

all request use just one connection?

**Comment by msrd0** [comment]
I remember I've read once that Exposed closes all connections after the transactions, which means that they are returned to the HikariCP pool. #122 and #123 might be interesting.

I am executing this on the start of every program and use the same instance until the program finishes. I do not see any reason for a destructor, but maybe I got you wrong?
