### ISSUE TITLE
 Field loaded from many-to-many relation disappears once the new entity object leaves the transaction

### ISSUE THREAD

**Issue by sigma-libra** [JetBrains/Exposed#1350]
I have the current many-to-many-relation between employees and their roles (keys and indexes are handled externally by the migration tool):

```

object RoleTable: UUIDTable("role") {
  val role = text("role_name")
}

class RoleEntity(id: EntityID<UUID>) : UUIDEntity(id)  {
  var role by RoleTable.role

  companion object : UUIDEntityClass<RoleEntity>(RoleTable)
}

object EmployeeTable : UUIDTable("employee") {
  val name = text("name")
}

class EmployeeEntity(id: EntityID<UUID>) : UUIDEntity(id) {
  var name by EmployeeTable.name
  var roles by RoleEntity via EmployeeRoleTable

  companion object : UUIDEntityClass<EmployeeEntity>(EmployeeTable)
}

object EmployeeRoleTable: Table("employeeRole") {
  val employeeId = reference("employee_id", EmployeeTable) //part of primary key
  val roleId = reference("role_id", RoleTable) //part of primary key
}

```

When I create a new employee, I want to also save their roles and return the stored employeeEntity object, including the roles.

```
  private fun newEmployeeEntity(
    name: String,
    roles: List<String>
  ): EmployeeEntity {

    transaction {

    val roleEntities = roles.map { 
      RoleEntity.new(UUID.randomUUID()) { this.role = role } 
    }

    val createdEmployee = EmployeeEntity.new(UUID.randomUUID()) {
      name = name
      roles = SizedCollection(roleEntities)
    }
    
    return createdEmployee
  }
}
```
If I check the value of createdEmployee.roles within the transaction, it contains an object of type LazySizedCollection. If I hit it with .toList or load(EmployeeEntity::roles), it resolves to a list of roleEntites as expected. But as soon as I leave the transaction, the value of roles in the returned entity becomes null.

How do I keep the list of roleEntities when I leave the transaction?

**Comment by Tapac** [comment]
https://github.com/JetBrains/Exposed/issues/281#issuecomment-925968534

**Comment by SabrinaKall** [comment]
Reopening because this setting the `keepLoadedReferencesOutOfTransaction` turns out only to work for new(), not for updates:

If I want to update the employee roles like so:

```
  private fun updateEmployeeEntity(
    employee: EmployeeEntity
    newRoles: List<RoleEntity>
  ): EmployeeEntity {

    transaction {
      employee.roles = SizedCollection(newRoles)
      // here the roles are updated
    }
    // here they are still the old ones
    employee.load(EmployeeEntity::roles)
    // still the old ones
    employee.flush()
    // still no change
    return createdEmployee
  }
}
```

Am I missing something here?

**Comment by Tapac** [comment]
It's impossible to call `load/flush` outside the transaction block. But I'll check your example.

**Comment by SabrinaKall** [comment]
> It's impossible to call `load/flush` outside the transaction block. But I'll check your example.

Sorry, the example is a to approximation of what I'm doing, I closed the transaction in the wrong place. It should be like this;
```

private fun updateEmployeeEntity(
    employee: EmployeeEntity
    newRoles: List<String>
  ): EmployeeEntity {

    transaction {
      val roleEntities = newRoles.map { role ->
        RoleEntity.new(UUID.randomUUID()) { this.role = role } 
      }
    
      employee.roles = SizedCollection(roleEntities)
      // here the roles are updated

    employee.load(EmployeeEntity::roles) // this changes nothing
    employee.flush() // this returns false and changes nothing
   }
    // this still has the old roles
    return createdEmployee
  }
}
```

**Comment by Tapac** [comment]
@SabrinaKall , I wasn't able to reproduce it in test. Please check [that commit](https://github.com/JetBrains/Exposed/commit/b34c59f5f2e3567a97e9ae98a79ced90dd66ff6d#diff-de40da48c1914b91fc95943fc19c76f4dfa43b83ad5a1bc4e7a92f0fe09a77f7R233)

**Comment by bog-walk** [comment]
I also was not able to reproduce the issue using the test above (returned entity had updated role fields) with current version 0.43.0.

If the problem still persists, please consider reopening this issue on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763) along with any reproducible table object, entity mappings, and custom functions, so we can attempt to investigate further.
