### ISSUE TITLE
Mariadb and Exposed

### ISSUE THREAD

**Issue by FranktheWhite** [JetBrains/Exposed#1357]
Hello, 
I am a newbie with kotlin and exposed. I tried an example from  the author Michael Kofler. I had an Mariadb 10.6.4 server and set up a Groovy Gradle project. All modules are implemented and shown under the modules in project structure.  

i began the main fun with 

import org.jetbrains.exposed.sql.*

fun main(args: Array<String>) {
val db = Database.connect("jdbc:mysl://frank-VivoBook/",
    driver="com.mysql.cj.jdbc.Driver",
    user="test1%localhost", password="Password01")
}

and the error was ->

Exception in thread "main" java.lang.IllegalStateException: Can't resolve dialect for connection: jdbc:mysl://frank-VivoBook/
	at org.jetbrains.exposed.sql.Database$Companion.getDialectName(Database.kt:224)
	at org.jetbrains.exposed.sql.Database$Companion.connect(Database.kt:206)
	at org.jetbrains.exposed.sql.Database$Companion.connect$default(Database.kt:195)
	at MainKt.main(Main.kt:9)

is Database.conect the flase method to begin the connect to an SQL Server or is the driver not suitable ?

 implementation("org.jetbrains.exposed:exposed-core:$exposedVersion")
    implementation("org.jetbrains.exposed:exposed-dao:$exposedVersion")
    implementation("org.jetbrains.exposed:exposed-jdbc:$exposedVersion")
    implementation("org.jetbrains.exposed:exposed-java-time:$exposedVersion")
    implementation("mysql:mysql-connector-java:8.0.26")

any comments on that

thanx
Frank

**Comment by Tapac** [comment]
You have typo in you connection string, it should be "jdbc:mys**q**l://frank-VivoBook/"

**Comment by FranktheWhite** [comment]
Watt? Wot?? Whaaat? oh, no...oh noooo! I spent hours to find the error. I need new glasses. Unbelievable :-). Thanx for your help, it runs ....

**Comment by jonatasrd** [comment]
Take a break, have some coffee =D
