### ISSUE TITLE
Doc vs Code DatabaseConfig.defaultFetchSize

### ISSUE THREAD

**Issue by stengvac** [JetBrains/Exposed#1358]
Hello,

after upgrade to exposed version 0.35.1 I have copied DB config from

`https://github.com/JetBrains/Exposed/blob/master/docs/ChangeLog.md#0351` there is default value `defaultFetchSize = -1 // unlimited` which cause in my case for PostgreSQL selects exception `org.postgresql.util.PSQLException: Fetch size must be a value greater to or equal to 0.` In code is default value null which is working fine. Zero or positive values also work fine.

Is that copy&paste mistake in doc or is there other reason for -1 value?

**Comment by Tapac** [comment]
@stengvac , thank you for letting me know, it's indeed a copy-paste problem. The change log was updated with null as a default value.
