### ISSUE TITLE
referrersOn with tables with different primary key types

### ISSUE THREAD

**Issue by rwhite226** [JetBrains/Exposed#136]
Exposed doesn't seem to let me link tables via referrersOn that use different types of primary keys. For example changing the example dao so that cities is a LongIdTable like this causes the compile to fail.

object Users : IntIdTable() {
    val name = varchar("name", 50).index()
    val city = reference("city", Cities)
    val age = integer("age")
}

object Users : IntIdTable() {
    val name = varchar("name", 50).index()
    val city = reference("city", Cities)
    val age = integer("age")
}

object Cities: LongIdTable() {
    val name = varchar("name", 50)
}

class User(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<User>(Users)
    var name by Users.name
    var city by City referencedOn Users.city
    var age by Users.age
}

class City(id: EntityID<Long>) : LongEntity(id) {
    companion object : LongEntityClass<City>(Cities)
    var name by Cities.name
    val users by User referrersOn Users.city
}

Am I missing something about referrersOn?

**Comment by Tapac** [comment]
I think Exposed doesn't have such "linkage" delegate. There is backReferencedOn, which make almost the same, but for only 1-to-1 relationship. 

As workaround you may use ```val users get() = User.find { Users.city eq id }```, but we will discuss and possilbly add new delegate function for your case.

**Comment by Tapac** [comment]
@rwhite226 , you was right - there was bug with generics on referrersOn/optionalReferrersOn functions which prevents from creating such reference.
It was fixed in master and will be released soon.
