### ISSUE TITLE
Ordering on References

### ISSUE THREAD

**Issue by kfud** [JetBrains/Exposed#1362]
Hi Exposed team!

We've been using Exposed on our project this past year, it's great, we love it. Only we've run into an issue with ordering references, take these to examples: 

```
class SomeEntity(id: EntityID<Int>) : IntEntity(id) {

    private var _anEntityList by AnEntity via AnEntityTable
    private val _anotherEntityList by AnotherEntity referrersOn AnotherEntityTable.foreignKeyId

...

}
```
When SomeEntity is loaded the reference will also be queried if you access them, there's just not really an easy or clean way to order them, they are basically ordered by the database natural order by default, which is bad in our case. I've tried some along the lines of:

```
    var anotherEntityList: List<AnotherEntity>
        get() = _anotherEntityList.orderBy(...).toList()

```
by this leads to "Can't order already loaded data" errors if you try to access the variables more than once.

I finally solved this by wrapping the property delegates for 'via' and 'refferersOn' to only add the orderBy the first time the SizedIterable is queried:

```
infix fun <ParentID : Comparable<ParentID>, Parent : Entity<ParentID>, ChildID : Comparable<ChildID>, Child : Entity<ChildID>, REF> Referrers<ParentID, Parent, ChildID, Child, REF>.orderBy(orderByExpression: Pair<Column<REF>, SortOrder>): ReadOnlyProperty<Parent, SizedIterable<Child>> {
    return OrderedRefferes( this, orderByExpression )
}

class OrderedRefferes<ParentID : Comparable<ParentID>, Parent : Entity<ParentID>, ChildID : Comparable<ChildID>, Child : Entity<ChildID>, REF>(val delegate: Referrers<ParentID, Parent, ChildID, Child, REF>, val orderByExpression: Pair<Expression<*>, SortOrder> ):
    ReadOnlyProperty<Parent, SizedIterable<Child>> {

    private var loaded = false;

    override fun getValue(thisRef: Parent, property: KProperty<*>): SizedIterable<Child> {
        var result = delegate.getValue(thisRef, property)
        if ( !loaded ) {
            result = result.orderBy(orderByExpression)
            loaded = true
        }
        return result
    }
}
```

which gives you something like:
```
    private val _anotherEntityList by AnotherEntity referrersOn AnotherEntityTable.foreignKeyId orderBy (AnotherEntity.id to SortOrder.ASC)

```
the only issue is that I'd rather just add the order by expression to the original query created in the Refferers (and InnerLinkTable) delegate, and avoid the whole "loaded" checks, but since it's not an open class, I can't. 

Do you guys have any ideas? Maybe I'm doing it wrong? Ideally I don't want to drop down to the DSL to solve this, because this solution already looks pretty nice, what do you think?

Kind regards,

- Kris

**Comment by Tapac** [comment]
I think it's very ok to extend all current references (also, `via`) with the optional `orderBy: Pair<Expression<*>, SortOrder>` parameter.
It will be nice if you can make a PR.

**Comment by kfud** [comment]
Yeah, no problem, I'll throw one together. Thanks!
