### ISSUE TITLE
Union of queries with differently derived columns loses the derived columns

### ISSUE THREAD

**Issue by dinoklein-ls** [JetBrains/Exposed#1373]
Here's a simplified SQL query to represent the problem I've encountered:

```SQL
SELECT T1.id, T1.amount * 10 AS value FROM T1
UNION ALL
SELECT T1.id, T1.amount * 100 AS value FROM T1
 ```

Then lets say have this code to fetch the data:
```kotlin
val q1: Query
val q2: Query
val data = q1.unionAll(q2).alias("data").selectAll()
```

When inspecting the data returned, only the ID field is present, while the derived column is omitted.

The generated SQL that is logged by exposed is basically like this:
```SQL
SELECT "data".id FROM (
-- union query per above
) AS "data"
```

Hence, the derived columns, while present in the subqueries, were completely omitted from the top-level select.
I have noticed when I was dumping data from each query individually that the full formula for each derived column was part of its name/structure, hence leading me to believe that columns are not matched based on their type, and ultimately excluded from the union's column set based on a perceived mismatch -- but this is conjecture on my part.

That said, there is a gap here in being able to fetch data, and a question on how one would fetch the data if it were present, but that was already raised as issue #1253.

This was observed with version 0.35.3.

**Comment by dinoklein-ls** [comment]
@Tapac can you write a few words on how to fetch the data a union-ed column that has two different expression definitions? Will either "expression" object work to fetch it?

**Comment by Tapac** [comment]
@dinoklein-ls, you can check related tests [here](https://github.com/JetBrains/Exposed/blob/fd5d4bef9baf2b56e722bd3d690071b0dd20ca1f/exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/UnionTests.kt#L242).
It will work with the next release (0.36.2)
