### ISSUE TITLE
Inconsistent transaction behavior

### ISSUE THREAD

**Issue by brezinajn** [JetBrains/Exposed#1376]
On mysql having:
``` Kotlin
object TransactionTestTable: LongIdTable(){
    val foo = integer("foo").check { it greater 0 }
}
```
when I do
``` Kotlin
newSuspendedTransaction {
    TransactionTestTable.insert { it[foo] = 1 }
    throw IllegalStateException("FAIL")
}
```
the transaction performs a rollback correctly and nothing gets inserted into the table
but when I do
``` Kotlin
newSuspendedTransaction {
    TransactionTestTable.insert { it[foo] = 1 }
    TransactionTestTable.insert { it[foo] = 0 }
}
```
the transaction still fails, but the first value gets inserted in the database.

**Comment by Tapac** [comment]
I wasn't able to reproduce. Can you check [my commit](https://github.com/JetBrains/Exposed/commit/e0dbe17879f0c84635070f34c94f4201f9289c46) with tests for your case and comment on it?

Also, what DB do you use?

**Comment by brezinajn** [comment]
Using mysql. Your test looks like it should repro the bug exactly. I'm gonna create minimal repro project. Probably should have done that in the first place.

**Comment by Tapac** [comment]
What MySQL version do you use? As `CHECK` supported only since 8.0.16 version

**Comment by brezinajn** [comment]
`8.0.18-google`

**Comment by brezinajn** [comment]
Problem was: `useLocalTransactionState: true`. Closing. Thanks
