### ISSUE TITLE
Disable logTimeSpent on SchemaUtils#createMissingTablesAndColumns

### ISSUE THREAD

**Issue by WillFP** [JetBrains/Exposed#1378]
I'm completely stumped when it comes to preventing SchemaUtils#createMissingTablesAndColumns from logging anything to the stdout. It's extremely annoying and the information is completely useless to me. I can't replace the logger to make .info do nothing, I can't tell Exposed to just not log things in the first place - all I want to do is create the missing tables and columns without spamming console.

**Comment by WillFP** [comment]
Janky solution:
val clazz = Class.forName("org.jetbrains.exposed.sql.SQLLogKt")
val field = clazz.getDeclaredField("exposedLogger")
field.isAccessible = true
field.set(null, NeuteredLogger())

NeuteredLogger is just a logger that does literally nothing

**Comment by WillFP** [comment]
`
// Get Exposed to shut the hell up
        exposedLogger::class.java.getDeclaredField("logger").apply { isAccessible = true }
            .apply {
                get(exposedLogger).apply {
                    this.javaClass.getDeclaredMethod("setLevel", Level::class.java)
                        .invoke(this, Level.OFF)
                }
            }
`

Janky fix for anyone else who hates the logging

**Comment by Tapac** [comment]
`withLogs` parameter for all SchamaUtils functions will be available on the next release.

**Comment by WillFP** [comment]
createMissingTablesAndColumns still logs because the withLogs parameter isn't passed on to addMissingColumnsStatements (SchemaUtils, line 305)
