### ISSUE TITLE
Entity Cache not Updated on Commit

### ISSUE THREAD

**Issue by bbrinx** [JetBrains/Exposed#1380]
After upgrading to 36.1 from 35.3 it seems like the cache invalidation behavior changed, leading to breaking changes for us. Existing tests are failing now since the cache is not updated on commit. The problem we're facing is having tests wrap a method with its own transaction. 

The following test used to work and now fails. 

```kotlin
fun deleteExampleEntity(entityId: EntityID<Int>) {
    primaryDatabase.transaction {
            ExampleEntity.findById(entityId)?.delete()
    }
}
```

```kotlin
@Test
fun `should work` = transaction(db) {
    val newEntityId = ExampleEntity.new {
        value = 1
    }.id

    assertNotNull(ExampleEntity.findById(newEntityId))

    deleteExampleEntity()
    commit()

    assertNull(ExampleEntity.findById(newEntityId))
}
```

It looks like this behavior was changed [here](https://github.com/JetBrains/Exposed/commit/6b2b2fd76d5419fa6b51cba246cb048539052914). What was the motivation here? 

And if this is the desired behavior, what would be the best way to implement tests? Right now it seems the only way would be to change every test to use separate transactions like this, which in my opinion would be unnecessarily verbose

```kotlin
@Test
fun `should work`() {
    transaction(db) {
        val newEntityId = ExampleEntity.new {
            value = 1
        }.id
        assertNotNull(ExampleEntity.findById(newEntityId))
    }

    deleteExampleEntity()

    transaction(db) {
        assertNull(ExampleEntity.findById(newEntityId))
    }
}
```

**Comment by Tapac** [comment]
I wasn't able to reproduce your problem, please check [the commit](28b02b745e44799d889ee9fdac8700dac9078724). 
Is `primaryDatabase` in `deleteExampleEntity` is equal to db?
If not then you create an entity in one transaction while deleting it in another before committing

**Comment by bbrinx** [comment]
You're right, my example did not reproduce the issue. However I was able to reproduce the issue [here](https://github.com/bbrinx/Exposed/blob/1ec5e5fc2a857359197ce2bfe24776ec61b8f60c/exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityBugsRegressionTest.kt#L158). In this case it's by using a suspended transaction. I am also seeing this issue with non-suspended transaction in my code but can't reproduce yet, I hope this will help pin point the problem.

**Comment by Tapac** [comment]
In your test, you delete an entity in another thread. The outer transaction has its own cache where an entity still exists and `find` returns it from the cache.

**Comment by bbrinx** [comment]
That makes sense. But it seems clearing the cache on commit helped in this case. What do you suggest to do now that commit doesn't clear the cache anymore?

**Comment by bog-walk** [comment]
@bbrinx If you need to manually clear the cache in your tests, please use `Transaction.entityCache.clear(flush = false)`. Applying this to the outer transaction in your failing test allows it to pass.
