### ISSUE TITLE
Older exposed versions are not available

### ISSUE THREAD

**Issue by tothlp** [JetBrains/Exposed#1381]
We currently use older (0.11.x, 0.12.x) versions of Exposed in our projects and we encountered a major problem. The official exposed repository ([https://dl.bintray.com/kotlin/exposed/](https://dl.bintray.com/kotlin/exposed/) ) can not provide the necessary jar files, as every request gets a Forbidden error. Unfortunately, aquiring these artifacts from jcenter is not possible anymore either.

Is there a way to get these jar files from somewhere?

**Comment by Tapac** [comment]
That's sad but we can't republish old artifacts into mavenCentral and bintray/jcenter are not [working anymore](https://blog.gradle.org/jcenter-shutdown).
You can try to move from 0.12.x to the latest Exposed (check [migration guide](https://github.com/JetBrains/Exposed/wiki/Migration-Guide)) or if you don't want to change code in place of modules and so on - check the latest version [0.17.x](https://search.maven.org/artifact/org.jetbrains.exposed/exposed/0.17.14/jar) (before module split) on maven central
