### ISSUE TITLE
Capitalized table name

### ISSUE THREAD

**Issue by appcommerce** [JetBrains/Exposed#1382]
The spelling of the table name is ignored.
Example: 
`object MyTable: UUIDTable("MyTable")`
The framework will create a table, but the table name will be with a lowercase letter
If you use 
`object MyTable: UUIDTable("\"MyTable\"")`
then 
```
transaction{
    SchemeUtils.create(MyTable)
}
```
generate error:
`org.postgresql.util.PSQLException: ERROR: zero-length delimited identifier at or near """" `

**Comment by bog-walk** [comment]
Ignoring capital letters in table names is a PostgreSQL [naming convention](https://www.postgresql.org/docs/7.0/syntax525.htm) upheld by the database itself.

In current version 0.41.1, using double-quotes (like in your example) to retain the capitalized table name works without throwing an exception. Please reopen this issue if the problem returns.
