### ISSUE TITLE
Is this project released?

### ISSUE THREAD

**Issue by bazhe** [JetBrains/Exposed#14]
How can I get any documents for this project?
I want to use kotlin in my project to take the role of DAO layer, and want to use this project, but actually I don't know how can I install this project, should I copy all the src into my project or there is any way to add them by maven ?

**Comment by metawave** [comment]
This project is released (v 0.3 at the moment) to bintray: https://bintray.com/kotlin/exposed/exposed/view. In Maven Central you won't find it (yet?). You might want to look on the link above how to configure you're environment if you use maven/ivy or gradle as dependency management systems.

**Comment by shafirov** [comment]
Quite correct, thanks for answer @metawave
