### ISSUE TITLE
StatementInterceptor lacks transaction on afterCommit/afterRollback

### ISSUE THREAD

**Issue by FrederikHeber** [JetBrains/Exposed#1401]
In the [StatementInterceptor.kt](https://github.com/JetBrains/Exposed/blob/6b2b2fd76d5419fa6b51cba246cb048539052914/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/StatementInterceptor.kt), there are two functions potentially called at the end of a transaction:
`fun afterCommit() {}`
and
`fun afterRollback() {}`.

However, their signature does not contain the transaction: How is it possible to implement behavior where we need to distinguish between the cases of a particular transaction having been successfully committed or not?

Could one extend these function signatures to also pass `transaction: Transaction`? This would allow to build a state associated with the `transaction.id` and use that in the rollback or commit case.

**Comment by bog-walk** [comment]
Fixed by #1531
