### ISSUE TITLE
Display insert ID in Log created by SQLLogger

### ISSUE THREAD

**Issue by mahramane** [JetBrains/Exposed#1403]
I save the logs created by Exposed to a table when I change the database.
But when using the insert method, the autoincrement ID column is not inside the created log.

for example:

```
Transactions.insert {
     it[description] = "test"
}
```
Log output:
`INSERT INTO tbl_transactions (description) VALUES ("test");`

But I want this output:
`INSERT INTO tbl_transactions (id, description) VALUES (1, "test");`

**Comment by Tapac** [comment]
It's impossible as the autoincrement id is generated on a database side, and the SQL you see is exactly the same that was executed.

**Comment by mahramane** [comment]
> It's impossible as the autoincrement id is generated on a database side, and the SQL you see is exactly the same that was executed.

Returns the ID to me when I use insertAndGetId. I just need to insert it into the output of the log.

**Comment by Tapac** [comment]
SQLLogger logs the executed statement not a "fake", so it's the only way is to implement your own SQLLogger or StatementInterceptor and log it in the way you like
