### ISSUE TITLE
Duration not saved correctly

### ISSUE THREAD

**Issue by idoflax** [JetBrains/Exposed#1408]
Trying to save a duration value seems to be saving it as a long:
```
Transaction attempt #0 failed: org.postgresql.util.PSQLException: ERROR: column "duration" is of type interval but expression is of type bigint
```

when the coulmn type is postgres interval:
```
ADD COLUMN duration INTERVAL NOT NULL default interval '1 month';
```

```
val duration = duration("duration")
```

the duration call above calls this function in `org.jetbrains.exposed.sql.javatime`
```
fun Table.duration(name: String): Column<Duration> = registerColumn(name, JavaDurationColumnType())
```

update:
the problem is that it actually intentionally saves it as long, but it should save it as interval, should it not?

**Comment by Tapac** [comment]
@idoflax , duration is the amount of time and the interval is time between two dates. In Exposed duration represented as amount of nanoseconds.
