### ISSUE TITLE
About autoIncrement id generate？

### ISSUE THREAD

**Issue by jlf1103** [JetBrains/Exposed#141]
fun new(id: ID?, init: T.() -> Unit): T {
        val entityId = EntityID(id, table)
        val prototype: T = createInstance(entityId, null)
        prototype.klass = this
        prototype._readValues = ResultRow.create(dependsOnColumns)
        if (id != null) {
            prototype.writeValues.put(table.id as Column<Any?>, entityId)
        }
        prototype.init()
        warmCache().scheduleInsert(this, prototype)
        return prototype
    }

I can't understand how to auto generate the primaryKey value, Who can tell me where is code

**Comment by Tapac** [comment]
You don't need to make any calls to receive auto-generated PK. It will be set to the entity after next touch to id field. Magic is hidden in flushInserts method.
