### ISSUE TITLE
how to use ifnull in exposed

### ISSUE THREAD

**Issue by mahramane** [JetBrains/Exposed#1414]
How can I implement the following SQL code in Exposed?

`SELECT ifnull(name, "-") FROM tbl_users;`

I do not know how to write `ifnull`.
please guide me.

**Comment by bog-walk** [comment]
@mahramane Based on the functionality of IFNULL() in MySQL for example, you could use a string custom function, like so:
```kt
val ifNull = CustomStringFunction("IFNULL", tbl_users.name, stringLiteral("-"))
tbl_users.slice(ifNull).selectAll()
```
Or use [`CustomFunction` directly](https://github.com/JetBrains/Exposed/wiki/Functions#custom-functions) if you need more flexibility with expression type.

An alternative is to use an SQL standard, COALESCE(), which Exposed supports, to return the first non-null argument:

```kt
tbl_users.slice(coalesce(tbl_users.name, stringLiteral("-"))).selectAll()
```

**Comment by bog-walk** [comment]
Please reopen this issue if the problem requires more answers.

**Comment by mahramane** [comment]
hi
I use `coalesce ` and it works.
