### ISSUE TITLE
insertAndGetId throws exception

### ISSUE THREAD

**Issue by darmstrong1** [JetBrains/Exposed#1416]
Hi, I am calling `insertAndGetId` when I insert a row into a table that has a UUID for the ID that automatically increments using SQL Server's `NEWSEQUENTIALID()`.
When I do this, instead of returning me the new ID, it throws an exception with the message:
`<classname>.<columnname> is not in record set`
I then created a random UUID and passed that in as the ID when I called `insertAndGetId` and then the call succeeded and returned the random UUID I had created.
Is `insertAndGetId` supposed to only work and return the ID if you explicitly send it one?
Is the problem something to do with me using a UUID as the ID and not an INT?
I figure the answers are probably NO to the first and YES to the second, but wanted to make sure.

**Comment by bog-walk** [comment]
@darmstrong1 Could you please confirm if this issue persists with current version 0.41.1? Attempting to reproduce the problem with a basic table and client-side auto-generator inserts and returns each new UUID without an exception:
```kt
val foo = object : IdTable<UUID>("foo") {
        override val id = uuid("id").entityId().clientDefault { EntityID(UUID.randomUUID(), this) }
        override val primaryKey = PrimaryKey(id)
}
```
`insertAndGetId()` should not have an issue with UUID, but NEWSEQUENTIALID() may be what's causing problems.

Looking into it, the function seems to need to be defined as default in CREATE TABLE and requires a default insert to not throw an exception about invalid use in a scalar expression. Depending on the implementation, Exposed might not be generating the correct insert statement (or even create statement). Could you please provide details about how your table is created to use the function?

**Comment by bog-walk** [comment]
If the problem does persist, please consider reopening this issue on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763) with the details requested above, so we can attempt to investigate further.
