### ISSUE TITLE
Is there any functionality for protecting against SQL Injection? 

### ISSUE THREAD

**Issue by AberrantFox** [JetBrains/Exposed#142]
Apologies, early edit - If someone could point towards the corresponding file or just indicate if using the DSL/DAO protects against injection, or if there are some parser methods or something. I assume that it does not but I thought I may as well ask. 

Thanks in advance 👍

**Comment by Tapac** [comment]
Exposed uses jdbc PreparedStatement with parameters, which means that all escaping and sanitizing will be made by jdbc-driver.

**Comment by AberrantFox** [comment]
Perfect, thank you.
