### ISSUE TITLE
Log / Capture Query Timings

### ISSUE THREAD

**Issue by raharrison** [JetBrains/Exposed#1424]
Is there any way to capture query duration/timing data as a way to assess overall performance? Potentially extending the current `StdOutSqlLogger` to also output the time duration of each statement? The current logger seems to utilize a statement interceptor, but this looks to only execute after execution and not wrap it in order to capture the duration.

Just looking for something simple on top of the current logs e.g:

`SQL: SELECT Cities.id, Cities.name FROM Cities  TIME: 27ms`

**Comment by bog-walk** [comment]
@raharrison The `Transaction` class comes with a debug mode, which populates certain properties with query duration data. You can access these properties directly in the transaction block or pass them to your own custom logger implementation, depending on how you need the data output:
```kt
transaction {
    debug = true // this must be set to capture the data

    ItemTable.selectAll().toList()

    println(duration)
    // 13 -> total ms spent executing so far
    println(statements)
    // [8ms] SELECT item_table.id, item_table.item_name FROM item_table -> string of prev executed statements + duration
    println(statementStats)
    // {SELECT item_table.id, item_table.item_name FROM item_table=(1, 8)} -> map of prev exec statements to count + duration
}
```

Setting `debug = false` at any point later in the transaction would disable tracking of these stats.

If you encounter any issues/limitations with this debug mode, please consider reporting them on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763).
