### ISSUE TITLE
Exposed crashes with MySQL enums

### ISSUE THREAD

**Issue by ayrat555** [JetBrains/Exposed#143]
Mysql enums start with 1, but Exposed inserts 0 for the first element of enum.

I found temporary fix: you should create first unused element of enum class

```
enum class UploadStatus {
    BLANK, // mysql enums start with 1, so Exposed crashes
    IN_PROGRESS,
    COMPLETED
}
```

But now I can't read value from this column in ResultRow

**Comment by Tapac** [comment]
@ayrat555 , could you, please, provide example (sql query to create table and Exposed mapping + test for it)?
