### ISSUE TITLE
Packages Before 0.30.1 on jcenter.bintray.com are no longer avaiable

### ISSUE THREAD

**Issue by tomcz7** [JetBrains/Exposed#1434]
The old Packages Before 0.30.1 that should be located at jcenter.bintray.com cannot be accessed anymore.
Due to that news https://blog.gradle.org/jcenter-shutdown
do you have any solution to be ale to access that old releases?

**Comment by Tapac** [comment]
First of all, you can build it from sources and store in some local/in-company package manager. Or use the jitpack.io (https://jitpack.io/#JetBrains/Exposed)

**Comment by bog-walk** [comment]
Please reopen this issue if the problem requires more answers.
