### ISSUE TITLE
Can't create arbitrary-size BINARY column in SQLite

### ISSUE THREAD

**Issue by timmc** [JetBrains/Exposed#1443]
SQLite does not impose any length limit on binary data, so I would expect to be able to use arbitrary-size binary columns. However, `binary()` columns are disallowed for SQLite (only permitted for Oracle and PostgreSQL, according to the docstring).

`binary(n)` is permitted, but doesn't make much sense because SQLite doesn't itself have any column size validation (although I believe Exposed will do that enforcement).

Should SQLite be added to the list of dialects that support unlimited-size binary?

(I can also use `blob()` columns, which seem more appropriate since that's SQLite's own name for binary-represented data, but I currently am running up against https://github.com/JetBrains/Exposed/issues/1442 so having more options might be nice...)

**Comment by Tapac** [comment]
`binary` column will be backed with `BLOB` column type. Fix will be available since 0.38.2
