### ISSUE TITLE
Select statement returns full package name + object

### ISSUE THREAD

**Issue by johnkanon** [JetBrains/Exposed#1445]
Hi, I'm very new to Kotlin and Exposed and might be missing something. When doing a select query, I get the package name in the list of resultRows. Example:

Table definition
```
object ScoreTable: IntIdTable() {
    val average_score: Column<Float> =  float("average_score")
    val context_id: Column<String> = varchar("context_id", 255)
    val user_id: Column<String> = varchar("context_id", 255)
}
```

Statement
```
        val score = transaction {
            ScoreTable.select { ScoreTable.context_id eq "something" }.toList()
        }
println(score)

```
The printline here prints out the following:

```
[com.something.something.something.ScoreTable.id=1,
 com.something.something.something.ScoreTable.context_id="something",
 com.something.something.something.ScoreTable.average_score=0.6,
 com.something.something.something.ScoreTable.user_id="userid"]
```

I don't want the package name, I would expect to only receive something like this:
```
[id=1,context_id="something",average_score=0.6,user_id="userid"]
```

Can someone tell me what I'm missing?

I'm using the latest Exposed Core (version 0.37.3) with a Postgres DB (version 42.3.1) that's running in a Testcontainer (version 1.16.3)

**Comment by Tapac** [comment]
When you call `print` on `List` of `ResultRow` you print its internal representation. 
If you'd like to print it in a more pretty way you have to write something like:
```kotlin
fun main() {
    print(score.joinToString { it.prettyString() })
}

private fun ResultRow.prettyString() = fieldIndex.keys.joinToString {
    val name = if (it is Column<*>) it.name else it.toString()    
    "$name=${getOrNull(it)}" 
}
```

**Comment by johnkanon** [comment]
Thank you @Tapac , this is exactly what I was looking for!
