### ISSUE TITLE
DSL Batch Insert does not work with flag useBulkCopyForBatchInsert on SQL Server

### ISSUE THREAD

**Issue by david-terk** [JetBrains/Exposed#1447]
Batch insertion will not work if flag `useBulkCopyForBatchInsert=true` is set on SQL Server.

1. Create a table with a non auto incrementing primary key.
2. Ensure that the types meet the requirements of the Bulk Copy API see [here](https://docs.microsoft.com/en-us/sql/connect/jdbc/use-bulk-copy-api-batch-insert-operation?view=sql-server-ver15).  Ensure at least one type has a non nullable field.
3. Setup DSL and perform a batch insert.

Transaction will fail with message that column cannot be null.  Set `useBulkCopyForBatchInsert=false` and repeat.  There will be no issue.

**Comment by bog-walk** [comment]
@david-terk I was able to reproduce the exception and this seems to be a [known](https://github.com/spring-projects/spring-data-jpa/issues/2554) [problem](https://github.com/microsoft/mssql-jdbc/issues/1554) with the mssql-jdbc driver and column order (differs between create and insert statement).

This has been [fixed](https://github.com/microsoft/mssql-jdbc/pull/1992) now and running tests (with your above specs) using at least [version 12.3.0.jre8-preview](https://repo.maven.apache.org/maven2/com/microsoft/sqlserver/mssql-jdbc/12.3.0.jre8-preview/) resolved the exception on my end.

Please consider updating your SQL Server driver dependency and checking that it works for you too.
