### ISSUE TITLE
DSL functions should be inlined

### ISSUE THREAD

**Issue by Martmists-GH** [JetBrains/Exposed#1448]
### What's the issue?

Currently, only `select` is inlined, whereas `insert`, `deleteWhere` and `update` (among others, but these are the "essentials") are not.

### Why should this change?

The rationale behind this issue is not only to make these consistent, but also permit use of kotlinx.coroutines inside these selectors and/or bodies if desired and in a `suspendedTransactionAsync` block. 

### Alternatives

An alternative for this issue currently is to either precompute the variables you'll need, or alternatively create stubs copied from the standard provided functions and use them instead:
```kotlin
inline fun <T : Table> T.insert(body: T.(InsertStatement<Number>) -> Unit): InsertStatement<Number> = InsertStatement<Number>(this).apply {
    body(this)
    execute(TransactionManager.current())
}

inline fun Table.deleteWhere(limit: Int? = null, offset: Long? = null, op: SqlExpressionBuilder.() -> Op<Boolean>) =
    DeleteStatement.where(TransactionManager.current(), this@deleteWhere, SqlExpressionBuilder.op(), false, limit, offset)

// Here I had to make where not nullable to allow inlining sadly
inline fun <T : Table> T.update(where: SqlExpressionBuilder.() -> Op<Boolean>, limit: Int? = null, body: T.(UpdateStatement) -> Unit): Int {
    val query = UpdateStatement(this, limit, SqlExpressionBuilder.where())
    body(query)
    return query.execute(TransactionManager.current())!!
}

```

**Comment by christianitis** [comment]
This would be very useful in ktor

**Comment by fralligator** [comment]
i concur this would be very useful also exposed need better documentation
