### ISSUE TITLE
0.37.3 is missing from GitHub

### ISSUE THREAD

**Issue by felixdivo** [JetBrains/Exposed#1458]
[The version](https://github.com/JetBrains/Exposed/blob/master/docs/ChangeLog.md#0373) exists on maven [`org.jetbrains.exposed:exposed-core:0.37.3`](https://mvnrepository.com/artifact/org.jetbrains.exposed/exposed-core/0.37.3) but not [on GitHub](https://github.com/JetBrains/Exposed/releases).

**Comment by Tapac** [comment]
Published, thank you for a reminder

**Comment by felixdivo** [comment]
You're welcome 😄
