### ISSUE TITLE
Cannot access float from database

### ISSUE THREAD

**Issue by oxf** [JetBrains/Exposed#146]
Using your great library, in table like your example :
>object Users : Table() {
>val id = varchar("id", 10).primaryKey()
>val name = varchar("name", length = 50)
>val cityId = integer("city_id") references Cities.id).nullable()
>}

Is there possibility to use floating point column (only `integer()` is possible)?
Trying to use `varchar()` and `decimal()` functions cause :
> java.lang.Float cannot be cast to java.lang.String/BigDecimal

**Comment by Tapac** [comment]
As stated in Effective Java by Joshua Bloch ([https://books.google.ru/books?id=ka2VUBqHiWkC&lpg=PA219&ots=y_CiRgw1RX&dq=effective%20java%20bigdecimal&pg=PA218#v=onepage&q&f=false](chapter 48)) better not to use Float/Double for strict calculations, so Exposed supports only decimal column type which mapped to BigDecimal.

**Comment by oxf** [comment]
Guess I found the way : #118
