### ISSUE TITLE
enumeration: eq compares with ordinal value instead of given value for enums with numeric value

### ISSUE THREAD

**Issue by nusmanov** [JetBrains/Exposed#1465]
hi,

i am using the enumeration type for the column door.
In testFilter function i declare a condition with this column.
Debugging shows me, that exposed takes the ordinal value _1_ instead of taking the value _88_.

ps: if the column has a string datatype and enum value types are String, than exposed does a right comparison.

```
object CarTable : LongIdTable(name = "car", columnName = "id_car") {
val door = enumeration("test", TestEnum::class).nullable().default(TestEnum.AA)
}


fun testFilter(): Op<Boolean> = CarTable.door eq TestEnum.BB

enum class TestEnum(val value: Long) {
    AA(33),
    BB(88)
}


// JUnit Test
    @Test
    fun testFilterCondition() {
    Database.connect("jdbc:h2:mem:test", driver = "org.h2.Driver", user = "root", password = "")
        transaction {
            // given
            val con = testFilter()
            // when
            con.toString() shouldBe "CAR.DOOR = 88"
        }
    }
```

Expected :"CAR.DOOR = 88"
Actual   :"CAR.DOOR = 1"

**Comment by hfhbd** [comment]
This is expected. You could use `customEnumeration` instead.

**Comment by Tapac** [comment]
[Custom enumeration](https://github.com/JetBrains/Exposed/wiki/DataTypes#how-to-use-database-enum-types)
