### ISSUE TITLE
Large LocalDates make between() fail silently

### ISSUE THREAD

**Issue by Namnodorel** [JetBrains/Exposed#1470]
Using eg. `between(LocalDate.of(2000, 1, 1), LocalDate.MAX)` returns an empty result, with no error message (tested using an H2 in-memory DB). Using a more sensible date as the upper bound works fine.

I believe that this may be caused by Exposed just putting a big year value into the date literal, which the database can't interpret properly. Failing fast would be a better response, I believe.

This isn't a big issue once you're aware of what's going on, but it caused some tests to fail with no clear explanation. I wanted to report it just in case other people have the same problem.

**Comment by joc-a** [comment]
@Namnodorel What exactly do you mean by "Exposed just putting a big year value into the date literal"?
[LocalDate.MAX](https://docs.oracle.com/javase/8/docs/api/java/time/LocalDate.html#MAX)
