### ISSUE TITLE
Make Column<> more open

### ISSUE THREAD

**Issue by chmuche** [JetBrains/Exposed#148]
I want to use Exposed inside my framework but the definition of the column don't satisfy me.
I want to add more information about a column. 

A pattern info to satisfy before the insert/update for example:

```
object Users {
val login = varchar("login", pattern="my regex validator", otherInfo =...)
}
```

I can't do that 

so now I make a class that hold a table instance.

But I can't do the same trick with column 
because if I create for example a custom column

```
class MyStringColumn(val col: Column<String, val pattern=""){
 //some code here
}
```

when I use the sql query api I need to write something like

```
val userId = Users.insert {
            it[Users.login.col] = "My login"
        } get Users.id
```

but it's ugly.

So my question is 
Can you make `Column` and why not `Table` open
and any other answer are welcome.

Thanks

**Comment by Tapac** [comment]
You don't need to extend Column, ColumnType is a right way to do.
Try this:
```Kotlin
class RegexpString(private val pattern: String) : StringColumnType() {
    private val regexp = pattern.toRegex()
    override fun valueToDB(value: Any?): Any? {
        assert(value is String && regexp.matches(value)) { "$value doesn't match $pattern" }
        return super.valueToDB(value)
    }
}

fun Table.regexpString(name:String, pattern: String) = registerColumn<String>(name, RegexpString(pattern))

object Users : Table() {
   val regexpString = regexpString("login", "pattern")
}
```

**Comment by chmuche** [comment]
that so nice, thanks.
I close the issue
