### ISSUE TITLE
Any plans for a new release?

### ISSUE THREAD

**Issue by m-burst** [JetBrains/Exposed#1480]
Hi @Tapac,

Could you please tell me if there are any plans for a new release?
In particular, our team is waiting for the fix of #1415 (which is already done in #1417 and #1446), and this is blocking us from updating to a fresh version.

Thanks

**Comment by OBorce** [comment]
Is this library stable for production use?

**Comment by Tapac** [comment]
@m-burst , the release will be available next week. Sorry for a delay.

**Comment by Tapac** [comment]
@OBorce , yes, it's stable and used in production by many companies.

**Comment by Tapac** [comment]
0.38.1 versions was released

**Comment by cwrau** [comment]
I don't know if I should open a new issue, but are there plans for a new release?

Specifically, I'm waiting for #1743 😁
