### ISSUE TITLE
Add Dokka and publish the API docs

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/Exposed#1482]
Maybe on GitHub pages, including a getting started (and remove the wiki)

**Comment by christianitis** [comment]
This would be nice, Exposed is greatly lacking in documentation.

**Comment by bog-walk** [comment]
[Link to API documentation](https://jetbrains.github.io/Exposed/api/index.html) is available from the [documentation home page](https://jetbrains.github.io/Exposed/home.html).
