### ISSUE TITLE
ORA-00972: identifier is too long. Oracle 12.1.0.2.0

### ISSUE THREAD

**Issue by davidbasilashvili** [JetBrains/Exposed#1483]
Hi everyone,

I'm trying to create reference and facing to identifier limitation in Oracle 12.1.0.2.0.

Seems like expected behaviour: Exposed trim long id to supported length in current database version.
Actual behaviour: on Oracle 12.1.0.2.0 Exposed doesn't trim long ids to 30 digit ids

Regarding documentation long ids introduced in 12.2 Oracle release: [Long Identifiers in Oracle Database 12c Release 2 (12.2)](https://oracle-base.com/articles/12c/long-identifiers-12cr2)

The same issue was fixed in #654, but for Oracle 11. 

Regarding actual code we can go from reference creation: 
`val refColumn: Column<Long> = reference(name = "reference_name", refColumn = referenceColumn)` regarding actual code we have:
https://github.com/JetBrains/Exposed/blob/2092d3bcd2d5e5e7598b17d55c7a48826f889234/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt#L758-L768

And next `fkName` go to `ForeignKeyConstraint` as `name`:
https://github.com/JetBrains/Exposed/blob/2092d3bcd2d5e5e7598b17d55c7a48826f889234/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt#L703-L716

And next we can see how `fkName` should created:
https://github.com/JetBrains/Exposed/blob/2092d3bcd2d5e5e7598b17d55c7a48826f889234/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Constraints.kt#L107-L110

And cutting code here, you can see that it depends on `identifierLengthLimit`:
https://github.com/JetBrains/Exposed/blob/2092d3bcd2d5e5e7598b17d55c7a48826f889234/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/api/IdentifierManagerApi.kt#L93

And limit init found here:
https://github.com/JetBrains/Exposed/blob/2092d3bcd2d5e5e7598b17d55c7a48826f889234/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/api/IdentifierManagerApi.kt#L21-L29

Seems like there is no case for oracle version later 11g but before 12.2. 

Workaround: put fk name explicitly in reference method like `val refColumn: Column<Long> = reference(name = "reference_name", refColumn = referenceColumn, fkName = "fk_constraint_name")`
but for big codebase it can be overkill.

Could you please advise another workaround if possible or fix it somehow?

Many thanks!

**Comment by Tapac** [comment]
Will be fixed in 0.38.2
