### ISSUE TITLE
New custom ColumnType, why only StringColumnType is Open

### ISSUE THREAD

**Issue by chmuche** [JetBrains/Exposed#149]
Follow your advice inside the #148 

I don't understand why `StringColumnType` is Open but not `DateColumnType` or the other.

My goal is to add validity constraint before the insert/update.

Like the [Jsr303](http://beanvalidation.org/)

For the Date I want to add before: `LocalDate, after:LocalDate, defaultValue:LocalDate`

And I don't want to copy past all the code inside `DateColumnType`

I think to exentends `IColumnType` and add a `DateColumnType` inside MyCustomDateColumnType

**Comment by Tapac** [comment]
>I think to exentends IColumnType and add a DateColumnType inside MyCustomDateColumnType

That's a right way! Try to use kotlin delegation (https://kotlinlang.org/docs/reference/delegation.html) 
```Kotlin
class ValidatedDateTime(val before: LocalDate, val after: LocalDate, val defaultValue: LocalDate,
                        private val timeColType: DateColumnType = DateColumnType(true)) : IColumnType by timeColType {
    override fun valueToDB(value: Any?): Any? {
        assert(value != null) // Your validation here
        return timeColType.valueToDB(value)
    }
}
```

**Comment by chmuche** [comment]
Ok, it's exactly the code I write. But why StringColumnType is open ? 
It's just to know you made this choice.
Any way thanks for the quick answer.

**Comment by Tapac** [comment]
>  But why StringColumnType is open ?

StringColumnType has two inheritors in Exposed code, so it was easier to make it open instead of using delegates.
