### ISSUE TITLE
Incorrect leftJoin

### ISSUE THREAD

**Issue by JajaComp** [JetBrains/Exposed#1494]
Exposed version: 0.37.3
Example:
Two tables:
```
object PersonTestEntity : UUIDTable("persons_test") {
    val organizationId = reference("organization_id", OrganizationTestEntity)
}

object OrganizationTestEntity : UUIDTable("organization") {
    val creator = reference("creator", PersonTestEntity)
}
```
Try make join:
`(PersonTestEntity leftJoin OrganizationTestEntity).selectAll()`
Expected: 
select all persons with organizations
Result:
`SELECT persons_test.id, persons_test.organization_id, organization.id, organization.creator FROM persons_test LEFT JOIN organization ON persons_test.id = organization.creator`

**Comment by Tapac** [comment]
Why you create table that links to each other? What SQL do you expect here?

**Comment by JajaComp** [comment]
I use postgres. 
In real project all record have "_creator_id" field with reference to table "persons".
Also i have reference: Person -> Organization -> Chief -> Person

**Comment by Tapac** [comment]
My question was about `val organizationId = reference("organization_id", OrganizationTestEntity)` on Person table.
It will create a foreign key to organization while organization already have a reference to Person.

Also, if you'd like to fetch `select all persons with organizations` and have only Persons in the result you need to make:
```kotlin
(PersonTestEntity innerJoin OrganizationTestEntity).slice(PersonsTestEntity.columns).withDistinct().selectAll()
```

**Comment by JajaComp** [comment]
I expect what first table will be join to second (PersonTestEntity leftJoin OrganizationTestEntity) like this:
`SELECT persons_test.id, persons_test.organization_id, organization.id, organization.creator FROM persons_test LEFT JOIN organization ON **persons_test.organization_id = organization.id**`
But now i got:
`**persons_test.id = organization.creator**`

**Comment by Tapac** [comment]
You wrote: `In real project all record have "_creator_id" field with reference to table "persons".` 
That's exactly what the query represents. 
If you'd like to have `persons_test.organization_id = organization.id` you need to remove `val creator = reference("creator", PersonTestEntity)`

**Comment by JajaComp** [comment]
Are you sure what the reference search  in second table before first table is correct?

**Comment by JajaComp** [comment]
Thx. Now i use extention syntax for join.
I just wanted to clarify about the behavior.
That is, such a scheme will not work with a simple leftJoin:

Person field entity:
`organization_id -> Organization entity(id)`
Organization entity:
```
supervisor_id -> Person entity (id)
or
manager_id -> Person entity (id)
or
cleaner_id -> Person entity (id)
```

**Comment by bog-walk** [comment]
If you encounter any further issues with `leftJoin`, either in its infix or extended form, please consider reopening this issue on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763) with more details about your use case and the issue you're facing.
