### ISSUE TITLE
Deploy to Maven Central

### ISSUE THREAD

**Issue by sdeleuze** [JetBrains/Exposed#15]
It is currently difficult to use Exposed in real projects since there is no dependency available on Maven Central or other well known repository, leading to [this kind of anti-pattern](https://github.com/crazyproger/borsch/tree/master/lib).

Could you please deploy `exposed.jar` in Maven Central?

**Comment by shafirov** [comment]
Maven Central deploy seem to be a bit overly cumbersome at this point, the library is not quite settled down yet. We have done deploys to https://bintray.com/kotlin/exposed/exposed/view#files/org/jetbrains/exposed/exposed
Please click Set me up there for repository setup instructions.
Does that work for you?

**Comment by sdeleuze** [comment]
Yes, thanks a lot!

**Comment by sdeleuze** [comment]
Could it be possible to update README to make users aware that Exposed jar is available for Bintray?

**Comment by shafirov** [comment]
Makes sense, thanks. Done

**Comment by sdeleuze** [comment]
Thanks
