### ISSUE TITLE
Requests transpiled to duplicate SQL queries.

### ISSUE THREAD

**Issue by sergey-bulavskiy** [JetBrains/Exposed#1503]
Hello! 

Dependencies: 
```
exposedVersion=0.38.1
implementation("org.jetbrains.exposed:exposed-core:$exposedVersion")
implementation("org.jetbrains.exposed:exposed-dao:$exposedVersion")
implementation("org.jetbrains.exposed:exposed-jdbc:$exposedVersion")
implementation("org.jetbrains.exposed:exposed-java-time:$exposedVersion")
implementation("org.jetbrains.exposed:exposed-java-time:$exposedVersion")
```

I have a simple transaction: 

```
return transaction {
            val nowLocal = now.toLocalDateTime()
            var user = User.find { Users.telegramId eq telegramId }.single()

            user.firstName = firstName
            user.lastName = lastName
            user.nickName = nickName
            user.lastMessagedAt = nowLocal
        }
```

For some reason it transpiles to this SQL: 

```
18:44:42.233 [---] DEBUG Exposed - SELECT users.id, users.nick_name, users.first_name, users.last_name, users.telegram_id, users.rating, users.created_at, users.updated_at, users.last_message_at, users.last_updated_rating_at FROM users WHERE users.telegram_id = 133824122
18:44:42.233 [---] DEBUG Exposed - SELECT users.id, users.nick_name, users.first_name, users.last_name, users.telegram_id, users.rating, users.created_at, users.updated_at, users.last_message_at, users.last_updated_rating_at FROM users WHERE users.telegram_id = 133824122
18:44:42.544 [---] DEBUG Exposed - UPDATE users SET last_message_at='2022-05-02T11:44:42.1992965' WHERE id = 2
18:44:42.544 [---] DEBUG Exposed - UPDATE users SET last_message_at='2022-05-02T11:44:42.1992965' WHERE id = 2

```

I can imagine that i have two selects because of some kind of virtualization (first on `.find` and second on `.single()`, for example) but why does update happen two times for me is not clear. Maybe it is a logger bug ?

I init database like this: 
```
Database.connect(connect())
...

private fun connect(): HikariDataSource {
    val config = HikariConfig()
    config.jdbcUrl = dbConfiguration.dbUrl
    config.username = dbConfiguration.dbUsername
    config.password = dbConfiguration.dbPassword
    config.driverClassName = "org.postgresql.Driver"

    return HikariDataSource(config)
}
```

Please advise, maybe i'm doing something wrong?

**Comment by bog-walk** [comment]
Hi @sergey-bulavskiy I was not able to reproduce this issue using the following versions: Exposed 0.45.0, HikariCP 5.0.1, PostgreSQL driver 42.7.1. I created a `Users` table and `User` class at best approximation then ran the transaction block you provided and the only debug logs were a single SELECT and a single UPDATE.

If the problem still persists on your end with the latest Exposed version, please consider sharing a minimally reproducible example that includes a simplified version of your table mappings, how the transaction block is being called, and any other details. If you're using something like Logback, the configuration file could also be useful.

**Comment by bog-walk** [comment]
If the problem persists, please consider reopening this issue on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763) with the details requested above, so we can attempt to investigate further.
