### ISSUE TITLE
How can I dynamically create tables?

### ISSUE THREAD

**Issue by Trqhxrd** [JetBrains/Exposed#1508]
Hey guys!

I'm currently developing a Minecraft plugin and I'm trying to store data about the world.

A Minecraft world is made of blocks, which are grouped in so-called chunks which are 16x16x256 blocks large.
I want to create a SQLite database per world with a table per chunk.
Is that possible? I'm somewhat new to kotlin and can only really do Java-style code at the moment... The kotlin specific syntax in the tutorial I read is still pretty new to me.

I also read [this](https://github.com/JetBrains/Exposed/issues/672) issue but this isn't what I'm trying to do...
The person from the other issue is only trying to create one table if I recall correctly. I want to create one table per chunk (a world can have nearly unlimited chunks. That's why I need to create on when a player gets close to them)

Thank you for reading my question.

**Comment by bing-hsu** [comment]
Tutorial only shows modeling a table as an object. 
In fact you can subclass `Table` and instantiate multiple table objects.
Something like this:

```kotlin
class WorldTable(name: String) : Table(name) {
  // ...column definitions
}
```
To create a new table, first instantiate an object then use `SchemaUtils.create` to create the table in underlying database.
```kotlin
val worlds = listOf("fire", "water", "earth", "air")
worlds.forEach { w -> 
  val t = WorldTable(w)
  transaction { SchemaUtils.create(t) }
}
```

**Comment by Trqhxrd** [comment]
> Tutorial only shows modeling a table as an object. In fact you can subclass `Table` and instantiate multiple table objects. Something like this:
> 
> ```kotlin
> class WorldTable(name: String) : Table(name) {
>   // ...column definitions
> }
> ```
> 
> To create a new table, first instantiate an object then use `SchemaUtils.create` to create the table in underlying database.
> 
> ```kotlin
> val worlds = listOf("fire", "water", "earth", "air")
> worlds.forEach { w -> 
>   val t = WorldTable(w)
>   transaction { SchemaUtils.create(t) }
> }
> ```

Thank you very much.
One last thing. How can I list all tables in a database? Is that even possible? In the ´Database´ class there are only configuration fields and methods.

**Comment by bing-hsu** [comment]
It is database specific. Objects like table, columns, indices are usually listed in database's catalog or system tables. 
For SQLite, these information can be queried in a system table "SQLITE_SCHEMA", see [How do I list all tables/indices contained in an SQLite database](https://www.sqlite.org/faq.html#:~:text=If%20you%20are%20running%20the,including%20all%20tables%20and%20indices.)

**Comment by Trqhxrd** [comment]
thanks man
