### ISSUE TITLE
(Nullable) blobs in DAO not working

### ISSUE THREAD

**Issue by lehmanju** [JetBrains/Exposed#151]
Unfortunately, blobs don't work if you try to use them in a DAO representation.

Here is my simple test code:
```kotlin
@Test
fun testBlobs()
{
	val random = Util.getRandomLengthBytes(20) //generates some random bytes
	transaction {
		createMissingTablesAndColumns(
				TestTable
		)
		val write = TestDao.new {
			blob = SerialBlob(random)
		}.id
		val read = TestDao.findById(write)!!
		val readBlob = read.blob
		assertEquals(String(random), String(readBlob.binaryStream.readBytes()))
	}
}
```
and here the corresponding dao:
```kotlin
object TestTable : LongIdTable(name = "test_table")
{
	val testblob = blob("some_blob")
}

class TestDao(id : EntityID<Long>) : LongEntity(id)
{
	companion object : LongEntityClass<TestDao>(TestTable)
	
	var blob by TestTable.testblob
}
```

Executing this tests results in: ```java.lang.ClassCastException: java.io.ByteArrayInputStream cannot be cast to java.sql.Blob``` with no usable stack trace (error is somewhere at the assignment of readBlob).

Furthermore ```.nullable()``` is not supported, it results in a NullPointerException. Luckily, this can be fixed easily by adding a null check to _BlobColumnType.readObject_ and return null if the ResultSet returns null.

**Comment by lehmanju** [comment]
I tried this with SQLite3 and PostgreSQL, it failed both times the same wayj

**Comment by lehmanju** [comment]
Thank you very much, it now works as expected!

**Comment by lehmanju** [comment]
Unfortunately, there is still a ClassCastException at _BlobColumnType.notNullValueToDB_.

**Comment by Tapac** [comment]
@lehmanju , can you provide full Exception message and/or small sample to reproduce?

**Comment by lehmanju** [comment]
@Tapac It is basically the same as above, just change the following:
```kotlin
val write = TestDao.new {
  blob = null
}.id
val read = TestDao.findById(write)!!
read.blob = SerialBlob(random)
```
This means reassignment does not work.

**Comment by lehmanju** [comment]
I modified the _notNullValueToDB_ the way you modified _valueFromDB_ and it works.

**Comment by Tapac** [comment]
Fixed in master.
