### ISSUE TITLE
H2 Oracle mode seems to behave differently between memory and tcp

### ISSUE THREAD

**Issue by flyingcircle** [JetBrains/Exposed#1511]
I currently have a project that I am converting to using Exposed which uses H2 over tcp to run the webapp locally, but uses H2 over memory when running the unit tests.

When the app runs over locally, everything works just fine, but when I run the unit tests I get H2 SQL errors.

jdbc string over Memory: `"jdbc:h2:mem:db;MODE=Oracle;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;"`
jdbx string over Network: `"jdbc:h2:tcp://localhost/tmp/db;MODE=Oracle;AUTO_RECONNECT=TRUE;AUTO_SERVER=TRUE"`

```
05/13/22 11:10:19.213 WARN  [http-nio-65060-exec-7] Exposed - Transaction attempt #0 failed: org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "SELECT t.id, t.ip_address, t.description, t.hostnames FROM t WHERE t.ip_address = ? [*]LIMIT 1"; SQL statement:
SELECT t.id, t.ip_address, t.description, t.hostnames FROM t WHERE t.ip_address = ? LIMIT 1 [42000-212]. Statement(s): SELECT t.id, t.ip_address, t.description, t.hostnames FROM t WHERE t.ip_address = ?
org.jetbrains.exposed.exceptions.ExposedSQLException: org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "SELECT t.id, t.ip_address, t.description, t.hostnames FROM t WHERE t.ip_address = ? [*]LIMIT 1"; SQL statement:
SELECT t.id, t.ip_address, t.description, t.hostnames FROM t WHERE t.ip_address = ? LIMIT 1 [42000-212]
```

When I run the query locally against the H2 db, this query works. Absolutely no idea why I'm hitting this issue.

**Comment by dthuering** [comment]
@flyingcircle What did you do to solve this issue?

**Comment by dthuering** [comment]
I did set `spring.jpa.database-platform=org.hibernate.dialect.Oracle10gDialect` in properties. 
That seems to use `FETCH` instead of `LIMIT` when building SQL.
