### ISSUE TITLE
Can't import org.jetbrains.exposed

### ISSUE THREAD

**Issue by mrfrosk** [JetBrains/Exposed#1513]
Hi, I ran into a problem.I can't import Database exposed, because he writes me "Unresolved reference: Database", but I did everything according to the instructions in getting start:
Main
import org.jetbrains.exposed.sql
fun main(args: Array<String>) {
    val x = Database.connect("jdbc:postgresql://localhost:12346/test", driver = "org.postgresql.Driver",
        user = "root", password = "your_pwd")
}

import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    kotlin("jvm") version "1.6.21"
    application
}

group = "me.mrfrosk"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

Build.gradle.kts
val exposedVersion: String by project
dependencies {
    implementation("org.jetbrains.exposed:exposed-core:$exposedVersion")
    implementation("org.jetbrains.exposed:exposed-dao:$exposedVersion")
    implementation("org.jetbrains.exposed:exposed-jdbc:$exposedVersion")
    implementation("org.postgresql:postgresql:42.2.2")
}
tasks.test {
    useJUnitPlatform()
}

tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "1.8"
}

application {
    mainClass.set("MainKt")
}

gradle.properties
kotlin.code.style=official
exposedVersion=0.38.1

![image](https://user-images.githubusercontent.com/59608285/168460844-d5b0afd0-6d74-4b98-a494-a5e12c5340b4.png)
![image](https://user-images.githubusercontent.com/59608285/168460853-31f394aa-7f5b-4c30-952a-9660e614b2e9.png)
![image](https://user-images.githubusercontent.com/59608285/168460861-1709e4e3-6e09-4050-9fc9-103b532c3b5c.png)

**Comment by SchweinchenFuntik** [comment]
need to run gradle sync

**Comment by p4ulor** [comment]
@SchweinchenFuntik 
I clicked this button which I think also does a "gradle sync", but it's named different, so I'm not sure
![image](https://user-images.githubusercontent.com/32241574/190245287-96eb98e4-a7b2-49a9-ac51-4b943ab8d3f0.png)

But it worked me. Thanks
