### ISSUE TITLE
Cannot use eq() with year() ?

### ISSUE THREAD

**Issue by bayang** [JetBrains/Exposed#1516]
Hi I'm trying to select events where date.year() is 2022 for example, but I can't find how.

This works :
``` 
val yr = "2022"
query.andWhere { ReadingEventTable.modificationDate.year().between(yr, yr) }
```

This works : 
``` 
val yr = "2022"
query.andWhere { ReadingEventTable.modificationDate.year().lessEq(yr) }
```

But obviously it does not only fetch 2022

This does not work and I can't find a way to do it  : 
``` 
val yr = "2022"
query.andWhere { ReadingEventTable.modificationDate.year().eq(yr) }
```
IDE says : 
```
Type mismatch.Required:
Op<Boolean>
Found:
Unit
```

With ReadingEventTable like this : 

```
object ReadingEventTable : UUIDTable("reading_event") {
    val creationDate = timestamp("creation_date")
    val modificationDate = timestamp("modification_date")
}
```

**Comment by bog-walk** [comment]
@bayang `year()` represents a `Function<Int>`, so you have some options for comparison in a WHERE clause.

Option 1 - Provide `eq()` with an `Int` argument:
```
val yr = 2023
query.andWhere { ReadingEventTable.modificationDate.year().eq(yr) }
```

Option 2 - Use one of the [query parameter functions](https://github.com/JetBrains/Exposed/blob/master/exposed-kotlin-datetime/src/main/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinDateFunctions.kt#L236) (or the `java-time` equivalent):
```
// timestampParam() accepts an Instant
val yr = timestampParam(Clock.System.now()).year()
query.andWhere { ReadingEventTable.modificationDate.year().eq(yr) }
```

**Comment by bog-walk** [comment]
Please reopen this issue if the problem requires more answers.
