### ISSUE TITLE
MySQL table names case sensitivity

### ISSUE THREAD

**Issue by YakovSirotkin** [JetBrains/Exposed#152]
MySQL documentation https://dev.mysql.com/doc/refman/5.7/en/identifier-case-sensitivity.html says about system variable `lower_case_table_names`  value 2:

_Table and database names are stored on disk using the lettercase specified in the CREATE TABLE or CREATE DATABASE statement, but **MySQL converts them to lowercase on lookup**. Name comparisons are not case sensitive. This works only on file systems that are not case sensitive! InnoDB table names are stored in lowercase, as for lower_case_table_names=1._

And this is exactly what I see on my Mac when I run tests.  First of all, `org.jetbrains.exposed.sql.tests.shared.DDLTests#testCreateMissingTablesAndColumns01` creates table **Busy** and MySQL shows it with capital B (SQL query is `SELECT * FROM information_schema.tables where table_schema = 'testdb1';`). But immediately after that we create index `CREATE UNIQUE INDEX Busy_busy_unique ON Busy (busy)` and our table renamed to **busy** in lowercase. So far so good, but `org.jetbrains.exposed.sql.tests.shared.DDLTests#addAutoPrimaryKey` also has Busy-table logic and it checks if **Busy** table exists.  When we load all table names in `org.jetbrains.exposed.sql.vendors.VendorDialect#allTablesNames` we load table name as **busy**, no chance to convert to **Busy**. `org.jetbrains.exposed.sql.vendors.VendorDialect#getInProperCase` checks that both `TransactionManager.current().db.metadata.storesUpperCaseIdentifiers()` and `TransactionManager.current().db.metadata.storesLowerCaseIdentifiers()` are false and `org.jetbrains.exposed.sql.Table#nameInDatabaseCase` do not converts table name to lowercase.   After that `org.jetbrains.exposed.sql.vendors.VendorDialect#tableExists` can't find table **Busy** and `org.jetbrains.exposed.sql.SchemaUtils#createStatements` generates statements to create table **Busy**.

`CREATE TABLE IF NOT EXISTS Busy (busy BOOLEAN NOT NULL)` works fine and does nothing, but  index creation `CREATE UNIQUE INDEX Busy_busy_unique ON Busy (busy)` fails with weird `Duplicate key name 'Busy_busy_unique'`. And each isolated test works fine.

I suggest that `org.jetbrains.exposed.sql.vendors.VendorDialect#tableExists` should ignore 
`storesUpperCaseIdentifiers()/storesUpperCaseIdentifiers()` and compare lowercases against lowercases. It's possible to support system property that forces to compare table names without converting it to lowercase. Probably, `org.jetbrains.exposed.sql.vendors.VendorDialect#allTablesNames` shouldn't do any conversion.

Also I am not sure that we need to use `org.jetbrains.exposed.sql.SchemaUtils#withDataBaseLock` in `org.jetbrains.exposed.sql.SchemaUtils#createMissingTablesAndColumns`.

**Comment by Tapac** [comment]
I'll check that behavior on MacOs later, but AFAIK MySQL allows to create tables with names which difference only symbol cases: 
```sql
CREATE TABLE IF NOT EXISTS foobar (bar BOOLEAN NOT NULL);
CREATE TABLE IF NOT EXISTS Foobar (bar BOOLEAN NOT NULL);
CREATE TABLE IF NOT EXISTS FOObar (bar BOOLEAN NOT NULL);

SHOW TABLES like '%bar';
```

Main problem is how to decide which of this tables relates to `object FooBar : Table()` when Exposed used to map model over existing schema. Possibly we should fail with an exception when found tables with similar names and table name was not provided explicit. 

> Also I am not sure that we need to use org.jetbrains.exposed.sql.SchemaUtils#withDataBaseLock in org.jetbrains.exposed.sql.SchemaUtils#createMissingTablesAndColumns.

I guess it's fine to make it optional via additional function parameter.

**Comment by YakovSirotkin** [comment]
If we do case-sensitive check there are scenarios where we can try to create both **foobar** and **FOObar** tables. I suppose this is not best practice and can create a lot of pain for users. It will be better to throw "No such table" error later, at least user will have a chance to spot the difference in cases immediately. 

Also it is possible to force case-sensitive  names using quotes, at least in Oracle and PostgreSQL. I suppose we can get much more weird cases here.

**Comment by YakovSirotkin** [comment]
And similar problem with `org.jetbrains.exposed.sql.tests.shared.EntityHookTest` table **Users** converted to **users**, not dropped in `org.jetbrains.exposed.sql.SchemaUtils#drop` and we try to create it again.

One possible solution is to use `DROP TABLE IF EXISTS` and remove existence check.

**Comment by YakovSirotkin** [comment]
Problem in `org.jetbrains.exposed.sql.SchemaUtils#withDataBaseLock` can be solved by explicitly naming Busy table in lowercase: 

`val buzyTable = object : Table("busy") {`

**Comment by YakovSirotkin** [comment]
I create pull request to fix build issues on Mac https://github.com/JetBrains/Exposed/pull/155 but looks like it doesn't checked with TeamCity.

**Comment by Tapac** [comment]
>Problem in org.jetbrains.exposed.sql.SchemaUtils#withDataBaseLock can be solved by explicitly naming Busy table in lowercase:
>val buzyTable = object : Table("busy") {

That's ok.

>One possible solution is to use DROP TABLE IF EXISTS and remove existence check.

Sad, but Oracle doesn't support such syntax (https://docs.oracle.com/cd/B19306_01/server.102/b14200/statements_9003.htm). Please use `currentDialect.supportsIfNotExists` to check for this as it made in Table.createStatement().

**Comment by Tapac** [comment]
> I create pull request to fix build issues on Mac #155 but looks like it doesn't checked with TeamCity.

I configured TeamCity to build PR [here](https://teamcity.jetbrains.com/viewType.html?buildTypeId=Exposed_PullRequests), but it doesn't run Oracle tests atm (require additional setup to start Oracle in Docker).

**Comment by YakovSirotkin** [comment]
@Tapac thanks  a lot! The problem is that if "NOT EXISTS" is not supported we need to keep standard check for table existence. I will work on it.

**Comment by YakovSirotkin** [comment]
@Tapac I updated the pull request, but looks like TeamCity hadn't noticed the latest changes.

**Comment by YakovSirotkin** [comment]
TC build green.

**Comment by Tapac** [comment]
@YakovSirotkin , I will check whole change list later (today or tomorrow) and run tests against Oracle (it doesn't implemented on TC atm).

**Comment by YakovSirotkin** [comment]
@Tapac Sure, Oracle test is the special pain.

**Comment by YakovSirotkin** [comment]
@Tapac Sorry, there is clear bug in `org.jetbrains.exposed.sql.SchemaUtils#drop`, I will try to investigate.

**Comment by YakovSirotkin** [comment]
@Tapac Looks like I fixed error

**Comment by YakovSirotkin** [comment]
@Tapac Maybe it's possible to resolve this issue?

**Comment by Tapac** [comment]
@YakovSirotkin , sure, i just forgot to close it.
