### ISSUE TITLE
Got NotInitializedManager error using latest spring boot

### ISSUE THREAD

**Issue by windyboy** [JetBrains/Exposed#153]
Following the  [geospatial-messensger](https://github.com/sdeleuze/geospatial-messenger), I try to use exposed with latest(1.5.6) spring boot.

Although use 'Transactional' annotation,  the repository class throw not initialized error with transaction manager.

The error message  is 
>kotlin.NotImplementedError: An operation is not implemented.
>at org.jetbrains.exposed.sql.transactions.NotInitializedManager.currentOrNull(TransactionApi.kt:29)

But the the manager in geospatial-messensger seems works fines.

Is it works only in specific version like geospatial-messensger?

**Comment by Tapac** [comment]
You should use `@EnableTransactionManagement` and  `@Bean
fun transactionManager(dataSource: DataSource) = SpringTransactionManager(dataSource)` like shown  [here](https://github.com/sdeleuze/geospatial-messenger/blob/master/src/main/kotlin/io/spring/messenger/Application.kt) and then annotate your repository with `@Transactional` ([example](https://github.com/sdeleuze/geospatial-messenger/blob/master/src/main/kotlin/io/spring/messenger/repository/DefaultMessageRepository.kt))

**Comment by windyboy** [comment]
thanks!

I check the example code again.
add  
> @EnableTransactionManagement 

add two missing function:
> fun persistenceExceptionTranslationPostProcessor() =PersistenceExceptionTranslationPostProcessor()
> fun transactionManager(dataSource: DataSource) = SpringTransactionManager(dataSource)

with 
> @Bean annotation

It works.
