### ISSUE TITLE
UUID handling broken, different output between DAO & DSL

### ISSUE THREAD

**Issue by jonasborn** [JetBrains/Exposed#1535]
Looks like there is a failure in UUID handling between DAO and DSL, probably related to #1467

![image](https://user-images.githubusercontent.com/36806204/174343645-78a89a43-83f2-497b-9f31-c5e50fb5789a.png)
![image](https://user-images.githubusercontent.com/36806204/174345280-35433acb-1502-4199-a3fb-de852b2a6ff5.png)

Ubuntu Ubuntu 20.04.4 LTS x64
10.4.21-MariaDB - Source distribution
Protokoll-Version: 10
openjdk version "11.0.12" 2021-07-20 LTS
Kotlin version 1.6.21-release-334 (JRE 11.0.12+7-LTS)

using

exposed-core 0.38.2
exposed-jdbc 0.38.2
exposed-dao 0.38.2

Currently not sure, which UUID is the right one, will add a comment soon.

**Comment by jonasborn** [comment]
![image](https://user-images.githubusercontent.com/36806204/174345381-5b654ace-a1b5-453b-889e-baec84477a71.png)

Looks like c794e160-35ae-40b9-8c6b-8c1c7b71fd48 is the original I've added using DSL before. Goint to test, if there are differences when adding using DAO.

**Comment by AlexeySoshin** [comment]
Looks like your first select queries `Device` table, not `User` table as the second one.

Can you post your DAO Entity definition for `User` here, please?

**Comment by bog-walk** [comment]
Confirming that the printed UUID are equivalent after the proposed adjustment above. Please reopen this issue if the problem requires more answers.
