### ISSUE TITLE
Create table if not exists

### ISSUE THREAD

**Issue by ChA0S-f4me** [JetBrains/Exposed#1538]
How can I create table only if it not exists? `SchemaUtils.createMissingTablesAndColumns` throws `column "id" of relation "users" already exists`

**Comment by Tapac** [comment]
Can you share yours table mapping?
Also, you can check if table esists with `Table.exists()` function

**Comment by ChA0S-f4me** [comment]
I understood, probably "id" column was reserved by postgres beacause problem was solved after I changed `columnName` in model to another
