### ISSUE TITLE
Clarify how to bring in from maven

### ISSUE THREAD

**Issue by aryeh-looker** [JetBrains/Exposed#1539]
When using the example code in the README, there are compile errors for `PrimaryKey` if you use https://mvnrepository.com/artifact/org.jetbrains.exposed/exposed instead of https://mvnrepository.com/artifact/org.jetbrains.exposed/exposed-core which is kind of confusing.

Ideally docs might mention `-core`

![image](https://user-images.githubusercontent.com/12849602/174914186-01c6e924-5278-4968-9211-ef30ed96da06.png)

**Comment by aryeh-looker** [comment]
Resolved by using https://mvnrepository.com/artifact/org.jetbrains.exposed/exposed-core/0.38.2 instead of https://mvnrepository.com/artifact/org.jetbrains.exposed/exposed

**Comment by Tapac** [comment]
There is a link to "Getting started" with complete maven config to start from:
![изображение](https://user-images.githubusercontent.com/194469/179363391-0c331afb-a594-4c61-a067-15359e4053bd.png)
