### ISSUE TITLE
How to handle where clause subquery

### ISSUE THREAD

**Issue by miladamery** [JetBrains/Exposed#1542]
Hi
How below SQL can be achieved in kotlin exposed?
```
SELECT * FROM some_table_with_date_column
where "issueDate" = (select max("issueDate") from some_table_with_date_column)
```

**Comment by Tapac** [comment]
Please check [that part of wiki](https://github.com/JetBrains/Exposed/wiki/DAO#use-queries-as-expressions)

**Comment by csisy-bt4w** [comment]
Updated link: https://jetbrains.github.io/Exposed/deep-dive-into-dao.html#use-queries-as-expressions

**Comment by Tak** [comment]
Updated updated link: https://www.jetbrains.com/help/exposed/dao-crud-operations.html#use-queries-as-expressions
