### ISSUE TITLE
Is it possible to perform multiple joins with DAO property delegates?

### ISSUE THREAD

**Issue by vo1dmain** [JetBrains/Exposed#1543]
I need to load all the days for sessions linked with current timetable. Is that possible with any of existing delegates?

    object Timetables : IntIdTable() {
        val groupCode = reference("groupCode", Groups, CASCADE, CASCADE)
        val typeId = reference("typeId", TableTypes, CASCADE, CASCADE)
    }

    object Days : IntIdTable() {
        val title = varchar("title", 16)
    }

    object Sessions : IntIdTable() {
        // ...
        val dayId = reference("dayId", Days, CASCADE, CASCADE)
        // ...
    }

    object TimetableSessions : Table() {
        val timetableId = reference("timetableId", Timetables)
        val sessionId = reference("sessionId", Sessions)

        override val primaryKey = PrimaryKey(timetableId, sessionId)
    }

    class Timetable(id: EntityID<Int>) : IntEntity(id), HasModel<TimetableModel> {
        companion object : IntEntityClass<Timetable>(Timetables)

        // ...
        val sessions by Session via TimetableSessions
        val days by // SELECT DAYS.id, DAYS.title FROM DAYS 
                    // INNER JOIN SESSIONS 
                    // ON DAYS.id = SESSIONS.dayId
                    // INNER JOIN TIMETABLESESSIONS
                    // ON SESSIONS.id = TIMETABLESESSIONS.sessionId 
                    // WHERE TIMETABLESESSIONS.timetableId = this.id
                    // GROUP BY DAYS.id
    }

**Comment by vo1dmain** [comment]
So, I came up with this – https://gist.github.com/vo1dmain/efb299db640e1368f0c41dfaffef78a1

**Comment by Tapac** [comment]
Why not `val day get() = sessions.map { it.day }` ?
Or you can make session always to come with loaded day if you want to have single query there.

**Comment by vo1dmain** [comment]
> Why not `val day get() = sessions.map { it.day }` ? Or you can make session always to come with loaded day if you want to have single query there.

The problem with pre-loaded days was that multiple sessions in set could refer the same day, but I only needed distinct.
The problem with mapping was that sessions only had a day id, but not all the day data.

Evetually I've changed the model and completely removed the day entity, but I don't think it's not actuall at all.
