### ISSUE TITLE
id is not in record set

### ISSUE THREAD

**Issue by alogvinov-forter** [JetBrains/Exposed#1548]
Hi, I'm currently evaluating Exposed as an ORM for for a simple web application. Running the test below on Java 17, Exposed version 0.38.2 and H2 in-memory db.

Table and entity definitions:
```
object Requests : IdTable<String>() {
    val reqId: Column<String> = varchar("reqId", 256)
    override val primaryKey = PrimaryKey(reqId)
    override val id: Column<EntityID<String>> = reqId.entityId()
}
```
```
class RequestEntity(id: EntityID<String>) : Entity<String>(id) {
    companion object : EntityClass<String, RequestEntity>(Requests)
    var reqId by Requests.reqId
}
```
The following test fails with `Requests.reqId is not in record set`:
```
@Test
fun entityTest() {
    transaction(database) {
        addLogger(StdOutSqlLogger)

        SchemaUtils.create(Requests)

        RequestEntity.new {
            reqId = "123"
        }

        val requests = RequestEntity.all().count()
        println("Requests: $requests")
    }
}
```
Looking into debug, I can see that the column comparison fails because of the type mismatch - `EntityIDColumnType` vs `VarCharColumnType`.

If I change the entity mapping as such
```
    ...
    var reqId by Requests.id
```
and change the insert accordingly, the test passes.

Please advise if there's something I'm missing. (Also, it would be nice to include an example with non-int id in docs.)

**Comment by AlexeySoshin** [comment]
@alogvinov-forter , I'm curious, what is your use case for `String` as `EntityId`?
Is it due to historical reasons?

**Comment by alogvinov-forter** [comment]
@AlexeySoshin sorry, I've just noticed your comment. Not really, this is by design. Request id is an internal UUID, which is a formatted timestamp augmented with some random suffix and name of the sub system that generated it.

A way to workaround this issue would be to introduce an auto-increment id column which would be there just for the technical purposes, but I'd prefer not to do this as request id is unique, and it's a primary key.
