### ISSUE TITLE
[Postgres] java.lang.IllegalStateException: <Repo>.updated_at is already initialized

### ISSUE THREAD

**Issue by drammelt** [JetBrains/Exposed#1552]
We keep randomly getting this exception on one of our tables in our Postgres database which is updated frequently by external sources. I tried handling the exception but it falls through and kills the process.

```
    fun touch(sensor: SensorDAO) {
        val updatedSensor = transaction {
            val time = LocalDateTime.now()
            if (sensor.updatedAt != time) {
                try {
                    return@transaction sensor.apply {
                        updatedAt = time
                    }
                } catch (ex: IllegalStateException) {
                    ...
                }
            }
            return@transaction null
        }
}
```

 It appears to be caused by trying to update a column when it already contains the same value, hence I tried adding the updateAt != time check. However there is now a race condition between that check and the transaction which is resulting in the random exceptions we are getting.
However Postgres has no issue updating columns with duplicate values so I feel like this is a bug in exposed not our code.

The column sql definition is just

`	updated_at timestamp NOT NULL`

Sanitised exception stack...
```
 java[23433]: Exception in thread "pool-6-thread-8" java.lang.IllegalStateException: .database.repo.SensorRepo.updated_at is already initialized
 java[23433]: at org.jetbrains.exposed.dao.EntityBatchUpdate.set(EntityBatchUpdate.kt:22)
 java[23433]: at org.jetbrains.exposed.dao.Entity.flush(Entity.kt:276)
 java[23433]: at org.jetbrains.exposed.dao.EntityCache.updateEntities(EntityCache.kt:115)
 java[23433]: at org.jetbrains.exposed.dao.EntityCache.flush(EntityCache.kt:142)
 java[23433]: at org.jetbrains.exposed.dao.EntityCache.flush(EntityCache.kt:107)
 java[23433]: at org.jetbrains.exposed.dao.EntityCacheKt.flushCache(EntityCache.kt:243)
 java[23433]: at org.jetbrains.exposed.dao.EntityLifecycleInterceptor.beforeCommit(EntityLifecycleInterceptor.kt:73)
 java[23433]: at org.jetbrains.exposed.sql.Transaction.commit(Transaction.kt:67)
 java[23433]: at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:190)
 java[23433]: at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1)
 java[23433]: at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:215)
 java[23433]: at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:223)
 java[23433]: at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:214)
 java[23433]: at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:165)
 java[23433]: at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:223)
 java[23433]: at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:135)
 java[23433]: at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:132)
 java[23433]: at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:131)
 java[23433]: at .database.service.SensorService.touch(SensorService.kt:445)
 java[23433]: at .controllers.TriggerMonitor.processConnection(TriggerMonitor.kt:71)
 java[23433]: at .controllers.TriggerMonitor.access$processConnection(TriggerMonitor.kt:29)
 java[23433]: at .controllers.TriggerMonitor$monitor$1$1$1.invokeSuspend(TriggerMonitor.kt:115)
 java[23433]: at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 java[23433]: at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
 java[23433]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 java[23433]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 java[23433]: at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Tapac** [comment]
Can you please provide your table and entity mapping?

**Comment by drammelt** [comment]
```
object SensorRepo: BaseRepo("sensor") {
   ...
}
```

```
abstract class BaseRepo(name: String): LongIdTable(name = name) {
    val deleted = bool("deleted")
            .default(false)

    val createdAt = datetime("created_at")
            .clientDefault { LocalDateTime.now() }
    val updatedAt = datetime("updated_at")
            .clientDefault { LocalDateTime.now() }
}
```

```
class SensorDAO(id: EntityID<Long>): Entity<Long>(id) {
   ...

    var deleted by SensorRepo.deleted
    val createdAt by SensorRepo.createdAt
    var updatedAt by SensorRepo.updatedAt

    companion object: EntityClass<Long, SensorDAO>(SensorRepo)
}
```

**Comment by Tapac** [comment]
I wasn't able to reproduce the exception. It would be great if you'll share some working test sample to debug. 
Do you share the entity between transactions? That can be a problem I think.

**Comment by drammelt** [comment]
The entity is cached is certain high through put areas so yes it will be used by multiple threads. There are other caches in our code doing similar things without issue however none of them are high concurrency like this one, and so the likely hood of writing the same value is minimal.

I will put together a test application to try and reproduce it.

Could you give an example of this problem you are talking about? There are zero issues unless we write the exact same datetime stamp to a column.

**Comment by drammelt** [comment]
I have created a simple application which loosely models what is happening on our system. I have removed the updateAt != time for easier reproduction.

The database we are using is postgresql 14, I have included the table / data I used in this application to reproduce.

https://github.com/drammelt/test-exposed-datetime

**Comment by Tapac** [comment]
It looks like a bad idea to modify same entity from different threads without a synchronization as Entities are not thread save and concurrent modifications can lead to unpredictable results.

**Comment by drammelt** [comment]
It works fine for anything other than datetime, as stated we have other points in the code using the same methodology just with a lower throughput with no issues since they are not updating datetime columns. 

If you change the touch function to update deleted to the same value over and over it does not throw an exception, as far as I am aware any column type will work fine except for datetime.

I can understand that they are not thread safe and concurrent updates might lead to inconsistent data, but that is not the issue here. The issue is that it is throwing an exception when updating a duplicate datetime value.

**Comment by drammelt** [comment]
It seem you are correct, changing the method in the test application to extract a unique entity for each call results in zero exceptions updating the datetime columns. It looks like we will either need to use locks on the cached objects or extract unique entities for each call.

Thank you for your help with this.
