### ISSUE TITLE
query expression

### ISSUE THREAD

**Issue by mjjabarullah** [JetBrains/Exposed#1555]
SELECT a.message_id, a.sent_from, a.sent_to, a.message, a.seen,
users.username, users.user_image,
b.unread_messages
FROM messages a
INNER JOIN
(SELECT sent_from,
max(message_id) AS maxid,
COUNT(CASE WHEN seen = 'NO' THEN 1 ELSE NULL END) AS unread_messages
FROM messages
GROUP BY sent_from, sent_to) AS b ON a.message_id = b.maxid
INNER JOIN users ON users.user_id = a.sent_from
WHERE a.sent_to = 5

how to write this query using this framework

**Comment by Tapac** [comment]
Please check [those examples](https://github.com/JetBrains/Exposed/blob/53bcb6fc28f3624d200b50920531a0c0abcec628/exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/AliasesTests.kt#L53) in tests on how to join with subqueries

**Comment by mjjabarullah** [comment]
COUNT(CASE WHEN seen = 'NO' THEN 1 ELSE NULL END) AS unread_messages
is this exact one  for above sql ???  i cannot write   " ELSE NULL END"
Count(Case().When(Op.build { seen eq 'NO' }, intLiteral(1)).Else(intLiteral(0)))
this shows  " ELSE 0 END"

**Comment by Tapac** [comment]
Please use `Op.nullOp<Boolean>` instead.

**Comment by mjjabarullah** [comment]
this work well thanks @Tapac
