### ISSUE TITLE
Join with multiple references

### ISSUE THREAD

**Issue by jon49** [JetBrains/Exposed#156]
I'm not sure what the technical hurdle is for joining on multiple references is but for any nontrivial database this would be a must have:

Below are two `INFORMATION_SCHEMA` tables:

```kotlin
object TableConstraints : Table("TABLE_CONSTRAINTS") {
    val ConstraintCatalog = varchar("CONSTRAINT_CATALOG", 512)
    val TableConstraints = varchar("TABLE_CONSTRAINTS", 64)
    val ConstraintName = varchar("CONSTRAINT_NAME", 64)
    val TableSchema = varchar("TABLE_SCHEMA", 64)
    val TableName = varchar("TABLE_NAME", 64)
    val ConstraintType = varchar("CONSTRAINT_TYPE", 64)
}

object KeyColumnUsage : Table("KEY_COLUMN_USAGE") {
    val ConstraintCatalog = varchar("CONSTRAINT_CATALOG", 512)
    val ConstraintSchema = varchar("CONSTRAINT_SCHEMA", 64)
    val ConstraintName = varchar("CONSTRAINT_NAME", 64) references TableConstraints.ConstraintName
    val TableCatalog = varchar("TABLE_CATALOG", 512)
    val TableSchema = varchar("TABLE_SCHEMA", 64) references  TableConstraints.TableSchema
    val TableName = varchar("TABLE_NAME", 64) references  TableConstraints.TableName
    val ColumnName = varchar("COLUMN_NAME", 64)
    val OrdinalPosition = long("ORDINAL_POSITION")
    val PositionInUniqueConstraint = long("POSITION_IN_UNIQUE_CONSTRAINT").nullable()
    val ReferencedTableSchema = varchar("REFERENCED_TABLE_SCHEMA", 64).nullable()
    val ReferencedTableName = varchar("REFERENCED_TABLE_NAME", 64).nullable()
    val ReferencedColumnName = varchar("REFERENCED_COLUMN_NAME", 64).nullable()
}
```

In order to join the two it needs three references as seen in the code above. Joining the two like so, causes an error.

```kotlin
        (TableConstraints leftJoin KeyColumnUsage).slice(
            TableConstraints.ConstraintName,
            TableConstraints.ConstraintType,
            TableConstraints.TableName,
            KeyColumnUsage.ColumnName,
            KeyColumnUsage.ReferencedColumnName,
            KeyColumnUsage.ReferencedTableName,
            KeyColumnUsage.OrdinalPosition
        )
        .select{ TableConstraints.TableSchema.eq(schemaName) }
```

The error:

> Exception in thread "main" java.lang.IllegalStateException: Cannot join with MySQL.InformationSchema.KeyColumnUsage@11037d58 as there is multiple primary key <-> foreign key references.
> MySQL.InformationSchema.TableConstraints.CONSTRAINT_NAME -> MySQL.InformationSchema.KeyColumnUsage.CONSTRAINT_NAME & MySQL.InformationSchema.TableConstraints.TABLE_SCHEMA -> MySQL.InformationSchema.KeyColumnUsage.TABLE_SCHEMA & MySQL.InformationSchema.TableConstraints.TABLE_NAME -> MySQL.InformationSchema.KeyColumnUsage.TABLE_NAME

**Comment by FabioGimmillaro** [comment]
I also get this error in the new version 0.21.1

**Comment by Tapac** [comment]
@FabioGimmillaro , could you share a join clause that fails with your mapping?

**Comment by FabioGimmillaro** [comment]
(Users.leftJoin(UserRelations)) 

I just saw, that the join functions also provide arguments for onColumn and otherColumn.
When I explicity set these arguments everything works fine:
 (Users.leftJoin(UserRelations, { id }, { friendFK }))

**Comment by Tapac** [comment]
That's right, Exposed can't decide what relation to use and you have to declare it explicitly.

**Comment by trebor74hr** [comment]
I spent an hour to find solution to the same issue, so I would suggest to put this in DSL documentation in Join chapter (https://github.com/JetBrains/Exposed/wiki/DSL#join).

**Comment by hawklike** [comment]
As of April 2022, I couldn't find any function with a signature like `Users.leftJoin(UserRelations, { id }, { friendFK })`.

However, you can use `Users.join(UserRelations, JoinType.LEFT, Users.id, UserRelations.friendFK)` which does the same.
