### ISSUE TITLE
Unable to search results

### ISSUE THREAD

**Issue by keta1** [JetBrains/Exposed#1563]
my code is
``` kotlin
val words = LearnRecord.find {
                    LearnRecordDb.userId.eq(userId) and
                            LearnRecordDb.createTime.date().eq(Clock.System.now.date)
                }.limit(num, skip).mapNotNull {
                    Word.findById(it.wordId)
                }
```

The SQL code generated when viewed in the log is
``` SQL
2022-08-14 23:04:52.187 [eventLoopGroupProxy-4-1] DEBUG Exposed - SELECT learning_record.id, learning_record.user_id, learning_record.word_id, learning_record.EF, learning_record.NOI, learning_record.last_l, learning_record.next_l, learning_record.next_n, learning_record.completed, learning_record.repeatTimes, learning_record.master, learning_record.c_time FROM learning_record WHERE (learning_record.user_id = 1) AND (DATE(learning_record.c_time) = '2022-08-14') LIMIT 10

```

result size is 0

i try run SQL code in console

![image](https://user-images.githubusercontent.com/41381927/184543408-417f8447-e7c7-493c-b37a-bf837535014f.png)
The query returns a result

![image](https://user-images.githubusercontent.com/41381927/184543445-bf5bd4a5-f0fd-4572-a5dc-e37d4500408f.png)
![image](https://user-images.githubusercontent.com/41381927/184543464-e5afafc2-b41f-4f24-8452-2ab61f7579b3.png)

**Comment by keta1** [comment]
I found that the time was converted to a timestamp
date function returns the '2022-08-14'
so cause this error
![image](https://user-images.githubusercontent.com/41381927/184545767-1d557b97-0425-44c2-bde1-b9a65e9a7399.png)

**Comment by AlexeySoshin** [comment]
What library are you using for `Clock.System.now.date`? 
This isn't [kotlinx-datetime](https://github.com/Kotlin/kotlinx-datetime), I think, as it would be `Clock.System.now()`

**Comment by keta1** [comment]
> What library are you using for `Clock.System.now.date`? 
> This isn't [kotlinx-datetime](https://github.com/Kotlin/kotlinx-datetime), I think, as it would be `Clock.System.now()`
it is my custom extension funtion
He returns LocalDateTime

**Comment by AlexeySoshin** [comment]
Your function still returns `LocalDate`, so the timestamp conversion is correct here.
I guess this is MySQL.
You can either invoke `UNIX_TIMESTAMP` on the database, or `toString()` on the date.

Currently you are comparing String to Timestamp
