### ISSUE TITLE
Passing MDC context to newSuspendedTransaction

### ISSUE THREAD

**Issue by marioalvial** [JetBrains/Exposed#1565]
I`m trying to pass the MDC context to newSuspendedTransaction, but the function only accepts  a Dispatcher, not CoroutineContext. So when I execute the following code:

```kotlin
override suspend fun save(event: LedgerEvent, atomicFunction: () -> Unit) {
        MDC.get("correlation_id") // 8d3b7750-8626-4390-8750-7f2eef401570
        newSuspendedTransaction {
            LedgerEventsTable.insert {
                it[id] = event.eventId
                it[bankAccountId] = event.bankAccountId
                it[revision] = event.revision
                it[type] = event.type
                it[deserializer] = event.deserializer()
                it[createdAt] = event.createdAt.toLocalDateTime()
                it[data] = entryEventsDbMapper.toData(event)
            }

            MDC.get("correlation_id") // null

            atomicFunction()
        }
    }
```

I got null value as the return of `MDC.get("correlation_id")` when it is executed inside coroutine scope. 

How can I pass the current MDC Context to the new suspendedTransaction function?

**Comment by AlexeySoshin** [comment]
This is not directly related to Exposed, so not sure if it should be an issue.

But simply capturing the value before invoking `newSuspendedTransaction` should work:
```kotlin
val correlationId = MDC.get("correlation_id") 
newSuspendedTransaction {
    println(correlationId) // 8d3b7750-8626-4390-8750-7f2eef401570
}
```

**Comment by marioalvial** [comment]
Hi @AlexeySoshin is not directly related to Exposed, but I think it applying current context to the new context created should be something that exposed coroutine integration should do, does it?

Capturing the value before invoking the  `newSuspendedTransaction` is not scalable. If the function `atomicFunction()` needs to use values from mdc context I will need to pass one by one if I follow your suggestion.

Using coroutine we can pass the context like this:

```kotlin
MDC.put("kotlin", "rocks") // Put a value into the MDC context

launch(MDCContext()) {
    logger.info { "..." }   // The MDC context contains the mapping here
}
```

Shouldn't the function `newSuspendedTransaction()` also be able to pass context this way?

**Comment by AlexeySoshin** [comment]
There's a subtelty there, I think. 
`newSuspendedTransaction` does not launch a coroutine, unlike `launch`. 
So you don't have a coroutine context. It's a suspending block, but it's not a coroutine. 

You can see the details here:
https://github.com/JetBrains/Exposed/blob/e926b0cdc88edced464ab16e4a7088dfc55670fc/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/transactions/experimental/Suspended.kt#L91

Having said that, I may be missing something. 
If you would like to provide a test project to reproduce that issue (I'm particularly interested in your definition of `MDCContext`), I would be happy to take a look.

**Comment by marioalvial** [comment]
Hi @AlexeySoshin MDCContext is from `implementation("org.jetbrains.kotlinx:kotlinx-coroutines-slf4j:1.6.0")` lib. 

```kotlin
MdcContext() = MDC.getCopyOfContextMap()
```

**Comment by AlexeySoshin** [comment]
Thanks, that's helpful. 
`MDCContext()` creates a new empty coroutine scope.

If you want to pass the entire MDC context, you can do it like that:

```kotlin
MDC.put("kotlin", "rocks")

newSuspendedTransaction(context = MDCContext(MDC.getCopyOfContextMap())) {
    println("Hello ${MDC.get("kotlin")}") 
}
```

**Comment by marioalvial** [comment]
Hi @AlexeySoshin you dont even need to pass the context map as a parameter because the default value of this parameter already is the result of the function `MDC.getCopyOfContextMap()`.

But the problem is that the function `newSuspendedTransaction` does not accept the MDCContext instance (it highlights as a compile error) because the function accepts a CoroutineDispatcher and the MDCContext is a CoroutineContext. I think this PR fixed this issue: [#1592](https://github.com/JetBrains/Exposed/pull/1592)

**Comment by AlexeySoshin** [comment]
The solution from above did compile when I tested it, but I'm testing it on Exposed directly, so maybe this fix was there, but not released yet, though.

Do you consider the issue resolved, or is there still a problem?

**Comment by Tapac** [comment]
@marioalvial  after #1592 `newSuspendedTransaction` accepts `CoroutineContext` instead of dispatcher. 
Will this resolve the issue?

**Comment by bog-walk** [comment]
Closing as the 3 options, `newSuspendedTransaction`, `withSuspendTransaction`, and `suspendedTransactionAsync`, all accept `CoroutineContext` as the first argument.

Please consider reopening this issue on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763) if the problem persists beyond passing an `MDCContext` instance to the functions.
