### ISSUE TITLE
MySQL REPLACE doesn't update existing record (0.38.2)

### ISSUE THREAD

**Issue by rami51** [JetBrains/Exposed#1570]
I saw that @Tiscs could solve this issue in:

https://github.com/JetBrains/Exposed/pull/1514

This is solved on version 0.39.1. I cannot upgrade my kotlin version now (required by 0.39.1 version), so I need to fix the same problem in 0.38.2 or a new 0.38.3 version.
Is this possible?

Thanks!

**Comment by Tapac** [comment]
What kotlin version do you use?

**Comment by Tiscs** [comment]
@rami51 Build from a fork, I did it before the PR #1514 is merged.

BTW: As a suggestion, I upgrade gradle in [my project](https://github.com/Tiscs/spring-boot-practices) to 7.5.x, which is compatible with kotlin 1.7.x, everything is fine, nothing is incompatible.

**Comment by rami51** [comment]
> What kotlin version do you use?

Hi Tapac, I'm using Kotlin org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.10

**Comment by rami51** [comment]
> @rami51 Build from a fork, I did it before the PR #1514 is merged.
> 
> BTW: As a suggestion, I upgrade gradle in [my project](https://github.com/Tiscs/spring-boot-practices) to 7.5.x, which is compatible with kotlin 1.7.x, everything is fine, nothing is incompatible.

I tried this, but I have some dependencies failing... I've been trying 1 hour and I finished rollbacking the changes...

**Comment by Tapac** [comment]
Exposed 0.39.x should work with Kotlin 1.6. Can you please describe the problem you've faced in more details?

**Comment by bog-walk** [comment]
Please reopen this issue if the problem persists with current version 0.41.1.

If it does, could you also share more details so we could attempt to reproduce the problem?
