### ISSUE TITLE
Using DAO Entity without ID

### ISSUE THREAD

**Issue by ChA0S-f4me** [JetBrains/Exposed#1571]
I need to create table, that doesn't need ID column, but I can't. I using DAO API due to it convenience

**Comment by Tapac** [comment]
Exposed will not be able to fetch the proper Entity without unique ID, so it is not possible to use DAO without IdTable

**Comment by BierDav** [comment]
So when I have a nm table there is no way of creating a dao out of it, because an entity can only consist of one column?
