### ISSUE TITLE
Order by rand for dao?

### ISSUE THREAD

**Issue by recsater** [JetBrains/Exposed#1577]
![image](https://user-images.githubusercontent.com/16009827/186616340-0a0ca50c-fc12-4b48-8679-4ae4c4440ba3.png)

Users is dsl.
User is dao.

Is there no equivalent to code for dsl?

**Comment by Tapac** [comment]
`val users = User.wrapRows(Users.selectAll().orderBy(Random())).toList()`

**Comment by recsater** [comment]
> `val users = User.wrapRows(Users.selectAll().orderBy(Random())).toList()`

Thank you for your kind answer ;^;
