### ISSUE TITLE
SchemaUtils.addMissingColumnsStatements() fails to compare varchar and text column with empty default value. Postgres dialect used

### ISSUE THREAD

**Issue by notfinch** [JetBrains/Exposed#1587]
If in schema definition there are fields with empty default values like these
`val varchar = varchar(“varchar”, 255).default(“”)`
`val text = text(“text”).default(“”)`
then SchemaUtils.createMissingTablesAndColumns() triggers column alteration for columns of type varchar or text

The problem is that the value obtained from the schema is not equal to the default value:
https://github.com/JetBrains/Exposed/blob/c04cac255fd4c946f763f29df8062394b1787c4e/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SchemaUtils.kt#L210-L211

For varchar type `existingCol.defaultDbValue` returns "::character varying" and `col.dbDefaultValue?.let { dataTypeProvider.dbDefaultToString(it) }` returns "'::character varying"
There is an extra single quote

For text type `existingCol.defaultDbValue returns` "::text" and `col.dbDefaultValue?.let { dataTypeProvider.dbDefaultToString(it) }` returns "'::character varying"
Here the type is also not defined correctly, for all string types the corresponding varchar
https://github.com/JetBrains/Exposed/blob/b9b53f8bbdfbf8cbab56d5602f92543e2ccd473c/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SchemaUtils.kt#L154-L157

Reproduce on 0.38.2 and 0.39.2

**Comment by AlexeySoshin** [comment]
Thank you, I'll take a look into this
