### ISSUE TITLE
Why not use Kotlin operator overloading?

### ISSUE THREAD

**Issue by kamyar1979** [JetBrains/Exposed#159]
I think we can easily use Kotlin great operator overloading and replace User.id.eq(5) with User.id == 5 
This feature must be possible by adding operators to column types

**Comment by Tapac** [comment]
@kamyar1979 , interesting idea. I will discuss it with my colleagues.

**Comment by pie-flavor** [comment]
I don't think that will work because equals() has to return a boolean.

**Comment by Tapac** [comment]
@pie-flavor , you are absolutely right. That's sad, but I'll close this issue.
