### ISSUE TITLE
Did this project works on eclipse?

### ISSUE THREAD

**Issue by bazhe** [JetBrains/Exposed#16]
My project was developed with eclipse, and want to use kotlin and exposed to handle the work of DAL, but  after some try, I found this project is not working in my project,.following part got compiled issue, which the "forEach" and "it" is not found
`(Users join Cities).slice(Users.name, Cities.name).
			select {(Users.id.eq("andrey") or Users.name.eq("Sergey")) and
					Users.id.eq("sergey") and Users.cityId.eq(Cities.id)}.forEach {
				println("${it[Users.name]} lives in ${it[Cities.name]}")
			}`

**Comment by Tapac** [comment]
Can you provide version of JDK and kotlin-runtime and compilation error if it possible?

**Comment by shafirov** [comment]
No response, closing

**Comment by bazhe** [comment]
Sorry,  just back from the Spring Festival(chinese), I used jdk1.7.0_80, and the kotlin-runtime should be the one that built in with the eclipse plugin.
And for the compilation error is on the top.

**Comment by Tapac** [comment]
Can you confirm that with latest eclipse plugin, i guess it might be updated due to kotlin 1.0 release?
