### ISSUE TITLE
Documentation Sql relation

### ISSUE THREAD

**Issue by chmuche** [JetBrains/Exposed#160]
I want to use exposed as a backend framework for a simple Orm.

I know how to create **many 2 one** relation and **one 2 many** relation.

but the **one 2 one** and the **many 2 many** I don't know how to do it.

**one 2 one** is just a one 2 many with a UNIQUE constraint.

but the **many 2 many** I don't understand how to do it inside Dao entity.

I see a **InnerTableLink** with the **via** infix method but I think I don't use it correctly.

**Comment by Tapac** [comment]
You may look at [ViaTest.kt](https://github.com/JetBrains/Exposed/blob/master/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ViaTest.kt) for usage examples.

**Comment by chmuche** [comment]
Nice, thanks a lot.
