### ISSUE TITLE
About Schema Changes and table drop behaviour in runntime

### ISSUE THREAD

**Issue by gowelaine** [JetBrains/Exposed#1602]
Hi, I try to figure out this, but here is not very clear documentation.
What is the behaviour of schema change and table drop using exposed sql?

For instance, currently I'm using mysql with exposed sql. 

1. Initially,  I create tables with schema list, say:
 tables: [LoveTable, EatTable, PreyTable] using SchemaUtils.createMissingTablesAndColumns(*tables)

The tables will be created in our backend service in cloud.

2. After a while, we change the schema list that only contains [LoveTable, EatTable], those table schemas will also be updated using SchemaUtils.createMissingTablesAndColumns(*tables),
and this changes will be pushed to our running backend service,

will missing schema PreTable lead to delete the table and all its contents c?

Or the table will not be deleted even the schema is missing, we call only delete a table using SchemaUtils.dropSchema(PreTable).

**Comment by gowelaine** [comment]
Also, how to drop a table properly?
Should i remove the table schema?

**Comment by bog-walk** [comment]
Please consider reopening this issue on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763) if the problem requires more answers.
