### ISSUE TITLE
Not recognized .primaryKey() , val date = datetime("date")

### ISSUE THREAD

**Issue by lifestreamy** [JetBrains/Exposed#1605]
file Users.kt
```
import org.jetbrains.exposed.sql.Table

object Users : Table("users") {
    val id = integer("id").autoIncrement().primaryKey()
    val name = text("name")
    val birth_date = datetime("birthdate")
}
```
Not recognized even if put in a class or in a companion object

My build.gradle:
```
plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.7.10'
}
group = 'org.example'
version = '1.0-SNAPSHOT'


allprojects {
    repositories {
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}

dependencies {
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
    testImplementation 'org.slf4j:slf4j-api:2.0.2'
    implementation 'org.slf4j:slf4j-log4j12:1.7.29'
    implementation 'com.github.kotlin-telegram-bot.kotlin-telegram-bot:dispatcher:6.0.7'
    implementation 'org.jetbrains.exposed:exposed-core:0.38.2'
    implementation 'org.jetbrains.exposed:exposed-dao:0.38.2'
    implementation 'org.jetbrains.exposed:exposed-jdbc:0.38.2'
    implementation 'org.postgresql:postgresql:42.2.2'
    implementation 'com.github.lifestreamy:TreeBuilder:master-SNAPSHOT'
}

test {
    useJUnitPlatform()
}

compileKotlin {
    kotlinOptions.jvmTarget = '16'
}

compileTestKotlin {
    kotlinOptions.jvmTarget = '16'
}

```

**Comment by Tapac** [comment]
1. `Column.primaryKey` was removed use `override val primaryKey` on Table or just use `IntIdTable`
2. To use `datetime` you have add dependency to one of datetime modules, please check [wiki](https://github.com/JetBrains/Exposed/wiki/LibDocumentation#exposed-0181-and-higher)

**Comment by lifestreamy** [comment]
Yes, I figured about override but I am still not sure how to use it

**Comment by lifestreamy** [comment]
inner class PrimaryKey also has a comment //Unresolved attached to it

**Comment by Tapac** [comment]
Can you share you new code sample?

**Comment by lifestreamy** [comment]
![image](https://user-images.githubusercontent.com/44506462/194558382-bd8b0f28-73f4-43a1-9738-69210658f762.png)

**Comment by lifestreamy** [comment]
I have no idea how to do this in kotlin tbh

**Comment by lifestreamy** [comment]
Like this? 
![image](https://user-images.githubusercontent.com/44506462/194559117-8509d14a-360c-4705-a9c1-a2c32a0c8111.png)

**Comment by Tapac** [comment]
Please check that
```kotlin 
object Users : Table("users") {
   val id = integer("id").autoIncrement()
   // ... other columns
   override val primaryKey = PrimaryKey(id, name = "users_pkey")
}
```

**Comment by lifestreamy** [comment]
Thank you for your help, Tapac! No errors from the compiler so far.

**Comment by lifestreamy** [comment]
@Tapac also, could you please, help, what type in Exposed corresponds to "time with time zone" in PostgreSQL? I am using Exposed 38.2 now because error with Monotonic.markNow is not yet resolved, and time is commented out (see screenshot)
![image](https://user-images.githubusercontent.com/44506462/194603691-3f419b36-8945-4c01-a5e5-2f92e99e5bfc.png)
