### ISSUE TITLE
Exposed 38.2/39.2, fun Table.time(name: String): Column<LocalTime> is unavailable

### ISSUE THREAD

**Issue by lifestreamy** [JetBrains/Exposed#1606]
fun Table.time(name: String): Column<LocalTime> = registerColumn(name, JavaLocalTimeColumnType()) is commented out
Thus, can't use it (see screenshot)
![image](https://user-images.githubusercontent.com/44506462/194612782-90e53f6c-dd0c-490c-9a9f-7853be0cbaab.png)

**Comment by Tapac** [comment]
`LocalTime` wasn't supported in `kotlinx.datetime` previously, looks like it's available in 0.40 version. 
Will be available in the next Exposed release.
