### ISSUE TITLE
Why ColumnSet is abstract class?

### ISSUE THREAD

**Issue by InsanusMokrassar** [JetBrains/Exposed#1608]
I looked in sources of `ColumnSet` and didn't found any reason to make it `abstract class`. Could you please explain, why it was decided to make `ColumnSet` as `abstract class`?

**Comment by Tapac** [comment]
I don't think there were any reasons behind it. Most probably, it's a legacy thing. 
But I like you concern to make it an `interface`

**Comment by InsanusMokrassar** [comment]
Ok, thanks for you answer :)

**Comment by InsanusMokrassar** [comment]
I think, we may close this issue
