### ISSUE TITLE
deleteWhere regression in 0.40.1

### ISSUE THREAD

**Issue by lukas-krecan** [JetBrains/Exposed#1610]
After upgrading to 0.40.1 the following code does not compile

```
TableA.deleteWhere { TableA.id eq myId }
```
Getting `Unresolved reference: eq`

**Comment by Tapac** [comment]
I will take a look into it, for now you can simple remove `Table.` from a lambda

**Comment by GoryMoon** [comment]
You need to import this now for it to work
```kotlin
import org.jetbrains.exposed.sql.SqlExpressionBuilder.eq
```

**Comment by lukas-krecan** [comment]
The import helps, thanks. Can you please mention it in the release notes as a breaking change?

**Comment by AlexeySoshin** [comment]
@Tapac probably related to this:
https://github.com/JetBrains/Exposed/pull/1561

**Comment by jiaminglu** [comment]
> You need to import this now for it to work
> 
> ```kotlin
> import org.jetbrains.exposed.sql.SqlExpressionBuilder.eq
> ```

Is this the suggested way? Regardless of the `ISqlExpressionBuilder` at the `it` parameter?

In my understanding, either the `ISqlExpressionBuilder` parameter is useless, or direct imports should not be used.

My current workaround:
```kotlin
Table.deleteWhere { with(it) { id inList ids } }
```

It's kotlin's limitation of now allowing two receivers in lambda blocks. In case of two parameters competing the receiver position, libraries should make trade-offs. The `ISqlExpressionBuilder` as a receiver can be seen as a "context", although I don't know the implementation detail, but it can differ according to different senarios such as different SQL dialects etc. While the `Table` as a receiver acts only as a syntax sugar.

If the `ISqlExpressionBuilder` parameter could not be removed, I believe the old way is much more reasonable, since the `Table` is defined by users, users know how to use it.
```kotlin
Table.deleteWhere { with(Table) { id inList ids } }
Table.deleteWhere { Table.id inList ids }
```

**Comment by Tapac** [comment]
It should become better after [context receivers](https://github.com/Kotlin/KEEP/blob/master/proposals/context-receivers.md) go public

**Comment by AlexeySoshin** [comment]
@jiaminglu I disagree with that approach, as `Table` is redundant information there.

```kotlin
Table.deleteWhere { Table.id inList ids }
```

**Comment by jiaminglu** [comment]
> @jiaminglu I disagree with that approach, as `Table` is redundant information there.
> 
> ```kotlin
> Table.deleteWhere { Table.id inList ids }
> ```

@AlexeySoshin If you try to use the positional `ISqlExpressionBuilder` as a context,
```kotlin
Table.deleteWhere { with(it) { id inList ids } }
```

is definitely much more unreadable than 
```kotlin
Table.deleteWhere { Table.id inList ids }
```

**Comment by lukas-krecan** [comment]
If I am not mistaken, it currently behaves differently than `select`. I do not see why it should not be consistent.

**Comment by AlexeySoshin** [comment]
@lukas-krecan The reasoning behind this is that modifications are usually performed on the same table, while selects use joins.

This is consistent with how `insert` behaves:
https://github.com/JetBrains/Exposed/blob/990bff364176716e92cc1aac3a0217940da96513/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Queries.kt#L69

Having said that, I agree with @Tapac that once we have context receivers, we'll have best of both worlds.

**Comment by glasser** [comment]
An annoying thing about the change #1561 is that it broke code that used `it` inside the clause to reference an outer `it`, eg

```
  things.forEach {
    ThingTable.deleteWhere { ThingTable.thingID eq it.thingID }
  }
```

**Comment by AlexeySoshin** [comment]
@glasser It's certainly possible to revert that change, and I'm happy to create a PR for that.
Something I'd like to point out, though, is that the revert will most likely happen when the Context Receivers arrive, that would make the issue irrelevant.

**Comment by lukas-krecan** [comment]
As the original reporter, I assume that everybody already changed their code to work-around the breakage. So I would say no fix is needed apart documenting the change.

**Comment by timmc** [comment]
I spent a while trying to figure this out today, so I've made a PR to at least warn people in the changelog: https://github.com/JetBrains/Exposed/pull/1723

**Comment by inattentive-nerd** [comment]
The exact problem happened to me.

My code : `TaskTable.deleteWhere { TaskTable eq taskId }`
Error : `Unresolved reference 'eq'.`
