### ISSUE TITLE
Reproduce entities as data classes

### ISSUE THREAD

**Issue by ChA0S-f4me** [JetBrains/Exposed#1611]
Is there any way for reproducing entities as data classes? I need it for serializing data from DB

**Comment by aqeeliz** [comment]
I don't think there is currently any way to do this. You have to manually create data class for each entity.
Check this for some discussion and solutions on this topic: https://github.com/JetBrains/Exposed/issues/497

**Comment by ChA0S-f4me** [comment]
Well, I just created data classes for JSON objects and entities classes for DB
