### ISSUE TITLE
Can't set client default on nullable columns

### ISSUE THREAD

**Issue by terminalnode** [JetBrains/Exposed#1612]
This seems to work:
```kt
val myTableId: Column<EntityId<Long>?> = reference(name = "my_table_id", foreign = MyTable)
  .clientDefault(1)
  .nullable()
```
but this does not:
```kt
val myTableId: Column<EntityId<Long>?> = reference(name = "my_table_id", foreign = MyTable)
  .nullable()
  .clientDefault(null)
```
setting clientDefault to null before nullable also doesn't work because the type doesn't support it at that point in the chain. This seems to be because `clientDefault` extends `<T : Any> Column<T>` while default just extends `<T> Column<T>`.

Is there a reason not to support nullable columns here?

**Comment by AlexeySoshin** [comment]
The reason you can't write 
```kotlin
.nullable()
  .clientDefault(null)
  ```
  
is because `nullable` returns `Column<T?>` while `clientDefault` expects `Column<T>`

One option is to change the type definition of `clientDefault` from `<T : Any>` to `<T : Any?>`

But I'm not sure if that won't cause some nuanced issues down the line.

**Comment by terminalnode** [comment]
Wouldn't it be better to change `<T : Any>` to just `<T>`? Isn't the purpose of extending `Any` just the NP safety? If changed to `<T : Any?>` I think `T` will have to *always* be nullable rather than just being nullable when a nullable `T` is provided.

**Comment by AlexeySoshin** [comment]
`<T>` is the same as `<T : Any?>`

Again, I'm not sure if this won't cause some other issues. 
But if you're interested, you're welcome to create PR and see if all the tests pass :)

**Comment by terminalnode** [comment]
I'll give it a shot :-)
