### ISSUE TITLE
can i use null alias in SELECT query?

### ISSUE THREAD

**Issue by yoonjoynow** [JetBrains/Exposed#1614]
using union query, i wanna write null alias like
```
SELECT
    m.id as 'user_id',
    m.name as 'user_name',
    null as 'user_age'
FROM
    member m
```

how can exposed use null alias?

**Comment by AlexeySoshin** [comment]
You can try and define your own expression for that:

```kotlin
val nullAlias = object : Expression<Int>() {
            override fun toQueryBuilder(queryBuilder: QueryBuilder) = queryBuilder {
                append("null")
            }
        }.alias("age")

        val q2 = (MembersTable).slice(nullAlias).selectAll().forEach {
            println(it)
        }
        ```
        
        
   This results in the following SQL:
   ```sql
SELECT null age FROM members
```

Hope that helps!

**Comment by Tapac** [comment]
There is also `Op.nullOp()` that also can help

**Comment by joc-a** [comment]
Closing this since solutions have been provided. If there are any further questions, feel free to re-open the issue. Thanks!
