### ISSUE TITLE
H2 create Oracle Database

### ISSUE THREAD

**Issue by Jens1977** [JetBrains/Exposed#1615]
I have created a springboot app that uses exposed to connect to an oracle database. I use H2 in my unit-tests.
When I use Mode=Oracle in the connection string, tables cannot be created because of the following error:

[42001-214] on BIGINT AUTO_INCREMENT PRIMARY KEY

I noticed an OracleDialect class. Can I use this so that tables are created using Oracle syntax? If yes, how can I implement it?

**Comment by Tapac** [comment]
Support of all H2 compatibility modes will come in the next release
