### ISSUE TITLE
Support default expression value of another field in a table

### ISSUE THREAD

**Issue by Nek-12** [JetBrains/Exposed#1618]
I want to match exposed schema declaration to the following sql:
```sql
alter table entry
add column entry_id uuid not null default (id); 
-- entry has a field named id
```
(this won't work with raw sql but is this possible with exposed?)

But how can I do this using exposed syntax, except for defining my own custom expression?
I couldn't find ways to convert column to Expression, couldn't do it using CustomFunction, haven't found any other ways

**Comment by AlexeySoshin** [comment]
You should be able to do that using `defaultExpression()` syntax.

You didn't post your table definition, but I would expect that something like

`kotlin
object EntryTable : UUIDTable() {
    val entryId = uuid("entry_id").defaultExpression(EntryTable.id)
}
```
would work.

**Comment by Nek-12** [comment]
@AlexeySoshin 

I'm using an UUIDTable:
```
Type mismatch.
Required:
UUID
Found:
EntityID<UUID>

Type mismatch.
Required:
EntityID<UUID>
Found:
UUID
```

**Comment by AlexeySoshin** [comment]
You're right, it won't work for PKs, since `EntityID<UUID> != UUID`

Probably having a custom expression is the way to go:
```kotlin
object EntryTable : UUIDTable() {
    val entryId = uuid("entry_id").defaultExpression(object : Expression<UUID>() {
        override fun toQueryBuilder(queryBuilder: QueryBuilder) = queryBuilder {
            append("ID")
        }
    })
}
```
This generates the following SQL:
```sql
CREATE TABLE IF NOT EXISTS entry (id uuid PRIMARY KEY, entry_id uuid DEFAULT (ID) NOT NULL)
```

By the way, I'm curious, which database are you using? 
At least PostgreSQL doesn't support this syntax:
`cannot use column reference in DEFAULT expression`

**Comment by Nek-12** [comment]
Yeah I said that this won't work with sql, but I wanted to do this in runtime then. Wouldn't it be possible?

**Comment by AlexeySoshin** [comment]
There's `clientDefault` in Exposed that could work theoretically, but I don't think would work practically. 

To reference ID of a newly created row, you need to somehow obtain it first. Currently the default values are set independently from one another:
https://github.com/JetBrains/Exposed/blob/9c0d2955424e3521abe025dcbdb932544aa8f3f1/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/InsertStatement.kt#L95

And I don't see any guarantees that your EntityID default value will be initialized first.

**Comment by Nek-12** [comment]
Okay, I just settled on treating this functionality as impossible to implement using neither sql or orms of any kind. We can close this if we mention that this is not supported somewhere in the docs
