### ISSUE TITLE
Many inserts with one call

### ISSUE THREAD

**Issue by Dashito14** [JetBrains/Exposed#1635]
I have two questions:

Which type of file i need to create for create the database in Android Studio? Are there some example of a project with Exposed?

How can i insert many values in a table? I saw the examples `Users.insert(...) Users.insert(...)`
Are there a possibility to do something like `Users.insert([name='...'][name='...'])`?

**Comment by AJRego** [comment]
Hei @Dashito14.

First, since you are talking about file and android studio i will assume you are using sqlite, so the file extension doesn't really matter, you could even have a file with just your database name.

Second, I think [this](https://github.com/JetBrains/Exposed/wiki/DSL#batch-insert) might interest you.

**Comment by Dashito14** [comment]
Hi, thank you for your answer.

Yes, i'm using sqlite, thx!

I saw that batch insert but i didn't understand how to use with tables that have more than one field. With a list is easy but if i want to _insert in Users the fields name, city, address and parent name,_ for example. How can i do a batch insert of this?

**Comment by Dashito14** [comment]
My question is, how can i simplify this? In this example i have 4 inserts but i wanna do hundreds... didn't see good way to achieve this


![image](https://user-images.githubusercontent.com/48255774/203807717-467371cd-09b3-4742-a603-d9bd7983975c.png)

**Comment by AlexeySoshin** [comment]
@Dashito14 `batchInsert` work on any interable:

```kotlin
data class Example(val name: String, val example: String, ...)

val sampleData = listOf(Example("a_name", "a_example"), Example("b_name", "b_example"), ...)

temporalTable.batchInsert(sampleData) { e ->
    it[name] = e.name
    it[example] = e.example
        ...
}
```

**Comment by bog-walk** [comment]
Here's a [link](https://github.com/JetBrains/Exposed/wiki/DSL#batch-insert) to the updated 'Batch Insert' section.

An update about documentation:

We are actively working towards improving KDocs throughout the codebase, as well as enhancing and publishing all Wiki documentation and samples to an Exposed website.

If you're interested, here is a [link](https://blog.jetbrains.com/kotlin/2023/08/exposed-moving-forward/) to the most recent official blog post regarding our plans moving forward.
