### ISSUE TITLE
exposed-spring-boot-starter does not work with spring-boot v3.0.0

### ISSUE THREAD

**Issue by smelfungus** [JetBrains/Exposed#1636]
May it be related to **jakarta** replacing **javax**?
https://spring.io/blog/2022/05/24/preparing-for-spring-boot-3-0
>**Check if Third-party Projects Have Jakarta EE 9 Compatible Releases**
Jakarta EE 9 a new top-level jakarta package, replacing EE 8’s javax top-level package. For example, the Servlet specification in Jakarta EE 8 uses a javax.servlet package but this has changed to jakarta.servlet in EE 9.
>
>Generally speaking, it’s not possible to mix Java EE and Jakarta EE APIs in the same project. You need to ensure that your own code, as well as all third-party libraries are using jakarta.* package imports.
>
>The good news is that most well-maintained libraries are producing Jakarta EE 9 compatible variants. For example Hibernate, Thymeleaf, Tomcat, Jetty and Undertow have all done so already.
>
>We recommend that you take some time to check that any third-party libraries that you use that integrate with Jakarta EE and check that they have EE 9 compatible variants. The most common problems we’ve found are with projects that import Servlet APIs.

**Comment by neetkee** [comment]
I guess we should also get rid of `spring.factories` and replace it with different file: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#auto-configuration-files

**Comment by dummyco** [comment]
@neetkee, indeed, that's the main reason

**Comment by Tiscs** [comment]
I added a configuration class in my project, and it works.
``` kt
import org.jetbrains.exposed.spring.autoconfigure.ExposedAutoConfiguration
import org.springframework.boot.autoconfigure.EnableAutoConfiguration
import org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
import org.springframework.context.annotation.Configuration
import org.springframework.context.annotation.Import

@Import(value = [ExposedAutoConfiguration::class])
@EnableAutoConfiguration(exclude = [DataSourceTransactionManagerAutoConfiguration::class])
@Configuration
class ExposedConfig
```

**Comment by rbraeunlich** [comment]
Hi everyone,
I sketched the migration from spring.factories to the new AutoConfiguration file. There is only one thing I couldn't figure out:
the replacement for the `EnableAutoConfiguration.exclude`
Maybe anyone here knows what's the replacement.
Cheers,
Ronny

**Comment by penguisnt** [comment]
Any update on this? We should at least add this to the documentation.

I just spend a couple hours trying to figure out why this wasn't being autoconfigured, and thought it was some dependency issue or something.

I only found this by searching for ExposedAutoConfiguration on github code and someone linked to this bug in a code comment..
