### ISSUE TITLE
Outer Transaction will create entities from failed inner transaction

### ISSUE THREAD

**Issue by simboel** [JetBrains/Exposed#1637]
**Problem**

When an inner (as in nested) transaction will throw an exception and the outer transaction code will catch this exception, all entities from the inner transaction will be created.

This is especially problematic in tests where the test method will open a transaction (by default via Interceptor) and then call a Service which internally creates a transaction, too.

**Context**

Spring Boot (2.7.5) application with Exposed Starter (0.41.1).

**Example**

```kotlin
object StarWarsFilms : IntIdTable() {
    val sequelId = integer("sequel_id").uniqueIndex()
    val name = varchar("name", 50)
}

class StarWarsFilm(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<StarWarsFilm>(StarWarsFilms)

    var sequelId by StarWarsFilms.sequelId
    var name by StarWarsFilms.name
    var director by StarWarsFilms.director
}

/** Basic assertThrows function implementation, so we don't need other dependencies for this example. */
inline fun <reified T : Exception> assertThrows(block: () -> Unit) {
    var exceptionThrown = false
    try { block() } catch (ex: Exception) {
        exceptionThrown = true
        if (ex !is IllegalStateException)
            throw RuntimeException("Expected ${T::class.simpleName} to be thrown, but ${ex::class.simpleName} was thrown instead.")
    }
    if (!exceptionThrown) throw RuntimeException("Expected ${T::class.simpleName} to be thrown, but nothing was thrown")
}

fun test() {

    // This will work without any problem and as expected.
    // The entity will **not** be created because there was an exception in the transaction.
    // Creating the entity would've resulted in an BatchDataInconsistentException as we didn't set the director.
    println("Test case 1")
    assertThrows<IllegalStateException> {
        transaction {
            addLogger(StdOutSqlLogger)
            StarWarsFilm.new {
                name = "Film 1"
                sequelId = 1
            }
            // some validation function
            throw IllegalStateException("Some problem...")
        }
    }


    // This will not work!
    // Even though the inner transaction exited with an exception,
    // the outer transaction will now try to create the entity from
    // the inner transaction.
    println("Test case 2")
    transaction {
        // Test case 2 outer transaction
        addLogger(StdOutSqlLogger)
        assertThrows<IllegalStateException> {
            transaction {
                // Test case 2 inner transaction
                StarWarsFilm.new {
                    name = "Film 2"
                    sequelId = 2
                }
                // some validation function will now throw an exception
                throw IllegalStateException("Some problem...")
            }
        }
    }

    // This will work as expected
    // The inner transaction will throw an exception.
    // This will be given to the outer transaction, too.
    // This way, no entity will be created in the database.
    println("Test case 3")
    assertThrows<IllegalStateException> {
        transaction {
            // Test case 3 outer transaction
            addLogger(StdOutSqlLogger)
            transaction {
                // Test case 3 inner transaction
                StarWarsFilm.new {
                    name = "Film 3"
                    sequelId = 3
                }
                // some validation function will now throw an exception
                throw IllegalStateException("Some problem...")
            }
        }
    }
}
```

The result of the execution is

```
[...]
Test case 1
Test case 2
SQL: INSERT INTO STARWARSFILMS ("NAME", SEQUEL_ID) VALUES ('Film 2', 2)
Test case 3
[...]
```

The `SQL: INSERT INTO STARWARSFILMS ("NAME", SEQUEL_ID) VALUES ('Film 2', 2)` shouldn't be there as you can clearly see that the `Test case 2 inner transaction` has been terminated with an `IllegalStateException` 

When looking into the database (H2 in my case) you can see that `Film 2` was created:
![grafik](https://user-images.githubusercontent.com/5895949/210178928-9612c0bb-0d6f-458e-88ed-e6c6f0812c9a.png)

**Expected behavior**

The outer transaction of `Test case 2` should **not** create the entity `Film 2` as the inner transaction (where the entity was created) encountered an exception. In general: An outer transaction should never create entities from an inner transaction if this transaction exited with an exception.

`useNestedTransactions = true` didn't help, either.

**Comment by AlexeySoshin** [comment]
Thank you for providing the details to reproduce that. Will take a look.

**Comment by AlexeySoshin** [comment]
I didn't manage to reproduce this behaviour, but maybe that's because I'm running my tests on H2 database.

**Comment by simboel** [comment]
I was using H2, too. I'll create a sample project and upload that later today.

**Comment by simboel** [comment]
Sorry, there were a few errors in the example from above (missing StdOutLogger, director column, ...). I've fixed the example code above.

Here is the project file using Spring Boot 2.7.5 and Exposed 0.41.1
[demo.zip](https://github.com/JetBrains/Exposed/files/10325868/demo.zip)

Just execute `./gradlew bootRun`
This will result in 
```
[...]
Test case 1
Test case 2
SQL: INSERT INTO STARWARSFILMS ("NAME", SEQUEL_ID) VALUES ('Film 2', 2)
Test case 3
[...]
```

Inside the archive you'll find the h2 db file from a single run including the db state after executing the application. This contains "Film 2" as mentioned from the logs (which is not correct behavior).

**Expected behavior**

An outer transaction should never create entities from an inner transaction, when that inner transaction didn't return without an exception.

**Comment by bog-walk** [comment]
Hi @simboel There's been a lot of pushback against the fix for this issue and I would prefer not to revert it because we do agree this is a bug. But I'm hoping to confirm some aspects of your original issue before we settle on a compromise. Namely:

1. Are you still setting `useNestedTransactions = true`?
2. The exception that is being caught by the inner transaction in your use case. Is it an exception thrown by the database (some `SQLException`), or any app/library/client `Exception`?

The argument being, from other users, that they understand the need to rollback commits from inner to outer when a database operation fails and throws.
But they are pushing for the original behavior regarding client-side `Exception`s to be maintained:

- That if these non-db exceptions are thrown and caught by the inner transaction, then they should not trigger a rollback of the outer transaction (and if a rollback is still needed, this should be manually called using `rollback()`).

I'm trying to find something that works best for both sides and still fits the expected rules of a transaction.

**Comment by simboel** [comment]
Hi @bog-walk , I'll answer you in a few days.

**Comment by simboel** [comment]
Hi @bog-walk , sorry for the late answer.

### To your questions

#### Question 1
> 1. Are you still setting useNestedTransactions = true?

No I'm not doing this. My intention is to start with a top-level transaction as an atomic transaction. I want to have `useNestedTransactions = false`

_Example to show Reasoning_: Client calls an API, which will be received by `XYZController` and given to my `XYZService`. The service will do some sanity checks and then opens a transaction. After that it calls other functions (or helper methods). The call to the `XYZService` is basically the atomic transaction from my business logic perspective.
Now for some reasons (mostly being lazy and I don't want to write stuff multiple times) other methods being called from within the `XYZService` also open up a transaction.
Therefor I have nested transactions but I still want to handle them as a "single" (atomic) transaction started in the `XYZService`.

Now when I look at the documentation:
http://jetbrains.github.io/Exposed/transactions.html#using-nested-transactions
> Since Exposed 0.16.1 it is possible to use nested transactions as separate transactions by setting useNestedTransactions = true on the desired Database instance.
>
> After that any exception or rollback operation that happens within a transaction block will not roll back the whole transaction but only the code inside the current transaction. 

I can see that `useNestedTransactions = true` would have the opposite effect of what I want to achieve.


#### Question 2

> 2. The exception that is being caught by the inner transaction in your use case. Is it an exception thrown by the database (some SQLException), or any app/library/client Exception?

**Short**: From my perspective it doesn't matter which kind of exception happened. Looking at my bugs, it is 90% application code and 10% `SQLException` (mostly constraint violations).

**Long**:
From my perspective the exception type doesn't really matter. I explicitly use transactions as part of my business logic. When there was a problem with any database operation as part of a single client request, the whole operation failed and I would like everything made from the user request to be rolled back to not have any unknown state.
The type of exception doesn't matter. It could be that the database had a "problem" (eg. schema mismatch, deleting row with existing references). Another possibility is an exception in my application code (logically my database problems are application code problems, too).

I could - of course - implement something like this in application code - but then I'd think of dropping Frameworks like Exposed because their value would be very limited.


### Regarding feedback from other users

> [...] they understand the need to rollback commits from inner to outer when a database operation fails and throws. [...] if these non-db exceptions are thrown and caught by the inner transaction, then they should not trigger a rollback of the outer transaction (and if a rollback is still needed, this should be manually called using rollback()).

Ah, I see. I think that both requesting parties are "correct". In some scenarios you don't want to rollback when you handle the exception (maybe because the result is still `okay-ish`.
But then I still stand by my point that the standard behavior would be that inner exceptions are rolled back when they throw an exception.

If it helps: I think there could be a setting like `useNestedTransactions` for this scenario. I'll just call it `rollbackOnApplicationExceptions` (defaultt `true`) for now.

When `rollbackOnApplicationExceptions = true` then inner transactions will be rolled back when they exit by throwing an exception.
If `rollbackOnApplicationExceptions = false` then transactions will be persisted even if they where exited by throwing an exception.
