### ISSUE TITLE
incorrect behaviour of SchemaUtils.create in a certain scenario involving composite foreign keys

### ISSUE THREAD

**Issue by minisaw** [JetBrains/Exposed#1643]
in case there are two tables (parent and child), with the child table referring the parent by the means of a composite foreign key **only**, the reference is not taken into account by the call `SchemaUtils.create` and, subsequently, by `SchemaUtils.sortTablesByReferences`

this causes the SchemaUtils to try to create the child table first, resulting in an SQL error:
`CREATE TABLE IF NOT EXISTS child ..., CONSTRAINT fk_name FOREIGN KEY (col1, col2) REFERENCES parent(col1 col2) ...`
`[42102-199]. Statement(s): ...`
`Table parent not found`
(using H2 in this instance)

the problem is actual as of 0.41.1

**Comment by minisaw** [comment]
related issue: [https://github.com/JetBrains/Exposed/issues/511](url)

**Comment by naftalmm** [comment]
I suggest to extract first problem into a separate issue since it's completely unrelated to the second one (and composite foreign key feature)

**Comment by minisaw** [comment]
sure, i have extracted the first problem into a ticket of its own:
https://github.com/JetBrains/Exposed/issues/1650
