### ISSUE TITLE
error accured: com.impossibl.postgres.jdbc.PGSQLSimpleException: 'could not serialize access due to concurrent update'

### ISSUE THREAD

**Issue by SeifAouay1** [JetBrains/Exposed#1647]
Problem analysis:

This exception is thrown if multiple web service calls that act on the same data structures are executed at the same time.
When consulting the web service log, we see several service requests submitted simultaneously without waiting for the return of the previous call
Database communication and transactions are handled by the jetbrains Exposed library.
Exposed offers us a "defaultRepetitionAttempts" configuration parameter used to repeat the transaction blocked by another transaction.

how can we solve this problem?

**Comment by Tapac** [comment]
Please share a test case to reproduce as it's not clear what is blicked and how.

**Comment by bog-walk** [comment]
If the problem persists with current version 0.44.0, please consider reopening this issue on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763) with the details requested above.

Any form of a minimally-reproducible example, or details of how `defaultRepetitionAttemps` is being used would be helpful, so we can attempt to investigate further.
