### ISSUE TITLE
Group By a column with comparison operator is incorrectly serialised into query

### ISSUE THREAD

**Issue by vvvlasov** [JetBrains/Exposed#1656]
Versions of Exposed and drivers
```
implementation "org.jetbrains.exposed:exposed-spring-boot-starter:0.41.1"
implementation "org.jetbrains.exposed:exposed-java-time:0.41.1"
implementation "com.h2database:h2:2.1.214"
implementation "org.postgresql:postgresql:42.5.1"
```

The code I'm executing
```
fun main() {
    Database.connect("jdbc:h2:mem:testdb", "org.h2.Driver")
    transaction {
        addLogger(StdOutSqlLogger)

        SchemaUtils.create(People)

        Person.new {
            name = "Carol"
            age = 4
        }
        Person.new {
            name = "Charlie"
            age = 2
        }
        Person.new {
            name = "Bob"
            age = 36
        }
        Person.new {
            name = "Alice"
            age = 36
        }
        val adult = People.age greaterEq 18
        val count = Count(stringLiteral("*"))
        People.slice(count, adult).selectAll().groupBy(adult).forEach {
            println(it[count] to it[adult])
        }
    }
}

object People : IntIdTable() {
    val name = varchar("name", 255)
    val age = integer("age")
}

class Person(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<Person>(People)

    var name by People.name
    var age by People.age
}
```

The error I'm seeing both on h2 and postgresql (with slightly different wording)
```
org.jetbrains.exposed.exceptions.ExposedSQLException: org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "USERS.AGE" must be in the GROUP BY list; SQL statement:
SELECT COUNT('*'), USERS.AGE >= ? FROM USERS GROUP BY USERS.AGE >= ? [90016-214]
```

The reason is that the query is serialised into a prepared statement which actually looks like this
```
SELECT COUNT('*'), USERS.AGE >= $1 FROM USERS GROUP BY USERS.AGE >= $2
```

Since $1 and $2 are technically different parameters both h2 and postgres interpret `USERS.AGE >= $1` and `USERS.AGE >= $2` as different columns producing this error despite the value going into $1 and $2 is the same. (On a side note the message itself is misleading as well, but it's produced by the DB itself). For the sake of comparison this prepared statement executes with no issues and returns the desired result
```
SELECT COUNT('*'), USERS.AGE >= $1 FROM USERS GROUP BY USERS.AGE >= $1
```
I'm happy to raise a fix but I struggled to debug where exactly the serialisation is happening.

**Comment by AlexeySoshin** [comment]
Hi @vvvlasov 
Thank you for providing the library versions and detailed steps to reproduce.

After looking at the code, though, I think that there's no bug in Exposed.

It seems that what you want to write is the following:
```kotlin
val adult = People.age greaterEq 18

        People.slice(People.age, People.age.count())
            .select(adult)
            .groupBy(People.age)
            .forEach {
                println(it[People.age.count()] to it[adult])
            }
            ```
            
            
This works and produces the following query:
```sql
SELECT people.age, COUNT(people.age), people.age >= 18 FROM people WHERE people.age >= 18 GROUP BY people.age
```

Hope that helps!

**Comment by vvvlasov** [comment]
I'm afraid you completely misunderstood what query I'm trying to run.
The query is supposed to be 

```
SELECT COUNT('*'), USERS.AGE >= 18 FROM USERS GROUP BY USERS.AGE >= 18
```

and print 

```
(false, 2)
(true, 2)
```

i.e. _aggregate_ by `>=` column, whereas your query will simply output the number of adults (with an age for no reason)

```
(2, 36)
```

which is not what I want. As per my original post, I'm not trying to solve a problem of constructing a query to return the result I need, I already replaced it with direct `exec()` call. I'm raising an issue of the library incorrectly serialising a valid query.

**Comment by bog-walk** [comment]
@vvvlasov The integer value that is not meant to be serialized as part of the prepared statement just needs to be wrapped as a literal. The generated SQL will remain unchanged but Exposed will now know how to handle the expression correctly.

Performing the following change produces the expected output that you detailed in your comment above, in both databases:
```kt
// ...
val adult = People.age greaterEq intLiteral(18)
// ...
```

**Comment by bog-walk** [comment]
Please consider reopening this issue on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763) if the answer above requires more details.
