### ISSUE TITLE
Inconsistent column names for different databases (ie. H2 & PostgreSQL)

### ISSUE THREAD

**Issue by simboel** [JetBrains/Exposed#1658]
When defining a column that requires quotation the user will run into problems when changing databases (i.e. PostgreSQL for production and H2 for local tests).

**Context**:
- Using H2 for local tests and PostgreSQL for production
- Flyway as db migration tool (both used for local tests as well as in production)
- There are columns that will be quoted (ie. identical to keywords)

## Problem

When running the application, the quoted column names will be different depending on the target database. In H2 the column name will be changed to quoted UPPERCASE and when using PostgreSQL the column name will be changed to lowercase.

This means that the Flyway migration script will create a database that can only be read by H2 or PostgreSQL, but never both (when there is at least one column requiring quotation).

My current workaround is to iterate over all tables and columns and make sure, that no column will be quoted by Exposed. If it does, there will be an error and I manually change the column names.

## Example

```kotlin
import org.jetbrains.exposed.dao.id.IntIdTable
import org.jetbrains.exposed.exceptions.ExposedSQLException
import org.jetbrains.exposed.sql.*
import org.jetbrains.exposed.sql.transactions.transaction
import org.springframework.boot.context.event.ApplicationReadyEvent
import org.springframework.context.event.EventListener
import org.springframework.stereotype.Component

object StarWarsFilms : IntIdTable() {
    val name = varchar("name", 50) // name is a keyword in SQL and must be quoted to be used as a column
}

@Component
class BigEntityTest() {
    @Suppress("unused")
    @EventListener(ApplicationReadyEvent::class)
    fun test() {
        transaction {
            addLogger(StdOutSqlLogger)
            // now just select all (only to get the sql SELECT statement in the logs)
            try { StarWarsFilms.selectAll().forEach {  } } catch (ex: ExposedSQLException) { }

        }
    }
}
```

### Result on H2

```sql
SELECT STARWARSFILMS.ID, STARWARSFILMS."NAME" FROM STARWARSFILMS
```

### Result on PostgreSQL

```sql
SELECT starwarsfilms.id, starwarsfilms."name" FROM starwarsfilms
```

### Result

When using a flyway migration script, we will define the column name to `id` and `name`. This will result in SQL exception when using H2 as there the column `"NAME"` will be used instead.
This problem will arise with all columns that match any of the roughly 500 keywords.

### Expected result

Exposed should never change column names from the explicit value used in the table definition (at least when quotation is required). So the SQL should look like this:
```sql
SELECT STARWARSFILMS.id, STARWARSFILMS."name" FROM STARWARSFILMS
```

**Note** that id and name are both identical to the definition in the Table.

If consistency between column names and generated sql is not undesired, Exposed should make sure, that the name will be identical to the column definition when quoting is required (ie. identical to a keyword).

**Comment by dzikoysk** [comment]
I'm facing several similar issues trying to connect Exposed DSL against existing database scheme, unfortunately current implementation is so inconsistent in this area that I guess it won't work. I wouldn't even mind that much to quote it on my own, but:

* https://github.com/JetBrains/Exposed/issues/683

**Comment by simboel** [comment]
@dzikoysk I don't think inconsistent is the right term.

It will try to use UPPERCASE or lowercase only depending on the used database. This shouldn't make any difference as `MYOLUMN` and `mycolumn` are the same for a database implementing the SQL standard.

When you have upper and lowercase mixed in your column name (like `myColumn`) it will quote it automatically for you so you will have `"myColumn"`.

But, when you have a column name identical to a keyword, it will be changed to UPPERCASE or lowercase depending on database AND it will be quoted. And this is the problem described in this ticket.

So I see two possible solutions I could think of:

1. Drop the feature to automatically change the case of column names. So `mycolumn` should never be converted to `MYCOLUMN`.
2. Do not change the column name case when quotation is required.

I would side with solution 1 but this would result in a higher impact on existing applications and might not be desired. Solution 2 may be a good trade-off.

**Comment by simboel** [comment]
I've further looked into this and I think that this is indeed deeply linked to #683 

@Tapac Do you have any opinion about the way Exposed should behave?
You can see two possible solution drafts above. As I've said, I would drop the `IdentifierManagerApi.inProperCase(identity: String)` and always use the identity as-is or quote if necessary. But I'm unsure about the reasoning behind this method.

I'm eager to work on a Pull Request for this problem if you want. But as we're talking about breaking changes I want to be extra careful.

So even if you decide for any of the solutions from above (or something else), I would like to think a bit about how to incorporate the breaking changes. I have a few ideas:

1. Just break applications and change the behavior.
2. Just break applications but provide an optional configuration (somewhere) that can be used to recover the previous behavior.
3. Do not break the application and provide a configuration option on the Table object instance as proposed in #683:  `open class Table(name: String = "", useExplicitName: Boolean = false)`
4. Do not break the application and provide an optional configuration (somewhere) that can be used to enable the new behavior.

I'd advise against option 1 (obviously not very elegant or user friendly) and option 3 (specify this on all tables manually is cumbersome and error-prone).
Depending on the current stability of Exposed I'd go with option 2 or 4, favoring option 4. With option 4 we could provide an easy "fix" for this problem so users just need to enable the configuration option. And we could also notify users that this configuration option will switch to true by default in n versions down the line. Of course, this is only required if we want to change the default behavior (which I think we should).

**Comment by dzikoysk** [comment]
For sure it cannot be solved by any kind of breaking change, so I'd personally go for opt-in option (4) to enforce explicit names for each identifier used in Exposed for tables/coulmns/indices names, even sth like `IdentifierManagerApi.enforceExplicitNames = true` at this point.

**Comment by AlexeySoshin** [comment]
@simboel 
The potential change should be pretty small:
https://github.com/JetBrains/Exposed/blob/990bff364176716e92cc1aac3a0217940da96513/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/api/IdentifierManagerApi.kt#L65
There's a `keywords` map available, so you could say that if the identified is in keywords, you return `identity`

I would say, let's give it a try and see where it breaks. The test suite should be quite comprehensive.

**Comment by bog-walk** [comment]
Hi @simboel . Please note that this issue will be closed by the PR over the next few days.

In the interest of continuing the discussion regarding a new feature flag that enables user-defined case sensitivity, please address any thoughts/design wishes in the related issue mentioned above (#683).  Or in the dedicated [YouTrack issue](https://youtrack.jetbrains.com/issue/EXPOSED-157/Support-table-identifier-case-sensitivity-by-enabling-auto-quote).

Replying here might mean that I miss your response and I'd rather avoid that if possible.
Thanks in advance!
