### ISSUE TITLE
Simple Table with schema fails when using SchemaUtils.createMissingTablesAndColumns

### ISSUE THREAD

**Issue by BlackHornet** [JetBrains/Exposed#1661]
Whenever I try to use a schema it fails with a schema table, when I am going to initialize with SchemaUtils.createMissingTablesAndColumns

```
object Tests: LongIdTable("auth.test")

SchemaUtils.createSchema(Schema("auth"))

SchemaUtils.createMissingTablesAndColumns(
    listOf(Tests),
    inBatch = true,
    withLogs = true
)
```

DEBUG Exposed - CREATE TABLE IF NOT EXISTS auth.test (id BIGSERIAL PRIMARY KEY)
DEBUG Exposed - ALTER TABLE auth.test ADD id BIGSERIAL PRIMARY KEY
WARN  Exposed - Transaction attempt #0 failed: java.sql.BatchUpdateException: Batch entry 0 ALTER TABLE auth.test ADD id BIGSERIAL PRIMARY KEY was aborted: **ERROR: column "id" of relation "test" already exists**  Call getNextException to see other errors in the batch.. Statement(s): ALTER TABLE auth.test ADD id BIGSERIAL PRIMARY KEY

With that I am not able to use any database schema

**Comment by AlexeySoshin** [comment]
Hi @BlackHornet,
Could you please specify which Exposed version and what database are you using?

**Comment by AlexeySoshin** [comment]
I think I managed to reproduce that with 0.41.1
```kotlin
    @Test
    fun `createMissingTablesAndColumns should work on schema prefixed tables`() {
        val schemaName = "my_schema"
        val testTable = object : LongIdTable("$schemaName.test_table") {
        }

        withTables(excludeSettings = listOf(TestDB.H2_MYSQL)) {
            SchemaUtils.createSchema(Schema(schemaName))
            SchemaUtils.create(testTable)
            SchemaUtils.createMissingTablesAndColumns(testTable)
            assertTrue(testTable.exists())
            SchemaUtils.drop(testTable)
        }
    }
```

Will see if I'm able to fix that.

**Comment by albert361** [comment]
Any estimated time that fix could be released :D ?

**Comment by BlackHornet** [comment]
@AlexeySoshin 
Oh sorry, it was 0.40.1 with a remote postgres (cockroachDB) database
