### ISSUE TITLE
Allow "For Update" to select which table it references

### ISSUE THREAD

**Issue by chrisjenx** [JetBrains/Exposed#1663]
For update selects the second table in joins, this is not what you want when building a lock. We ideally should be able to define the table it is targeting.

Example join:

```
Equine
    .leftJoin(EquineStatuses)
    .slice(Equine.columns.plus(EquineStatuses.columns))
    .select { Equine.id eq id }
    .orderBy(Equine.barnName to SortOrder.ASC, EquineStatuses.added to SortOrder.DESC)
    .let { if (forUpdate) it.forUpdate() else it }
```

Will throw:
`org.postgresql.util.PSQLException: ERROR: FOR UPDATE cannot be applied to the nullable side of an outer join`

We need something like:

`forUpdate(tableA)`

**Comment by chrisjenx** [comment]
FYI reversing the tables and using right join is the same issue

**Comment by bog-walk** [comment]
Hi @chrisjenx I believe the syntax you're looking for is `FOR UPDATE OF ...`, which is supported by `ForUpdateOption`. There are a few [PostgreSQL-specific options](https://github.com/JetBrains/Exposed/blob/main/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/ForUpdateOption.kt#L36) available and they all allow target tables to be passed as arguments.

For your use case, making this change generates the clause mentioned above and should resolve the issue:
```kt
// ...
.let { if (forUpdate) it.forUpdate(ForUpdateOption.PostgreSQL.ForUpdate(ofTables = arrayOf(Equine))) else it }
```

**Comment by bog-walk** [comment]
If there are any further issues with using `forUpdate()`, please consider reporting them on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763).
