### ISSUE TITLE
how can write query?!

### ISSUE THREAD

**Issue by hpn33** [JetBrains/Exposed#1676]
have this lib any feature to write query without dsl?!

**Comment by AlexeySoshin** [comment]
Hi @hpn33,
One of the main goals of Exposed is to provide a DSL to write SQL queries.
But if you really need to run an arbitrary SQL statement, you have an `exec()` method available within a transaction.

**Comment by hpn33** [comment]
yep, this kina solve my problem

and 
have any where of tut that talk about?!

**Comment by hpn33** [comment]
tell this ability on documentation plz
