### ISSUE TITLE
pg_dump  in exposed

### ISSUE THREAD

**Issue by mahramane** [JetBrains/Exposed#1677]
hi
can i use pg_dump in exposed to export sql code from database?

**Comment by mahramane** [comment]
@AlexeySoshin
Thank you for your explanation.
Is there a way that I can get the SQL output from the database with Exposed?

**Comment by AlexeySoshin** [comment]
@mahramane 
Could you describe what an "SQL output" is, please?
Is it the schema or the data? 
If it's the data, in which format do you expect to get that?
While theoretically, if you have all the tables mapped with Exposed, you could do that, I would say that this is still not the best way to do that.

**Comment by mahramane** [comment]
@AlexeySoshin 
I want to output the rows of a table as  `INSERT` SQL code in exposed

**Comment by AlexeySoshin** [comment]
As far as I can tell from looking at the code, there's no such feature.

**Comment by bog-walk** [comment]
Confirming that Exposed does not offer any database backup utilities equivalent to those provided by, for example, pg_dump or mysqldump.

The closest features available are certain `SchemaUtils` functions that generate +/- execute SQL statements required to ensure database object definitions match Exposed table object definitions (namely `createMissingTablesAndColumns` and `statementsRequiredToActualizeScheme`).
Please note that these functions do not output the existing table data in the way pg_dump does.

If the objective is just to get the data from modified rows while they are being manipulated, then the `RETURNING` clause would be the answer (at least for PostgreSQL). This is not yet supported, but most likely will be as soon as we can address its implementation.
