### ISSUE TITLE
can't find `via` keyboard

### ISSUE THREAD

**Issue by mbunderline76** [JetBrains/Exposed#1679]
hi, I want to create many to many relation with two tables,
and as documentation i should relate them like this : 
`var ads by AdTable via UserAdTable`
but `via` keyword is not available
here is my build.gradle
    `implementation("org.jetbrains.exposed:exposed-core:0.41.1")
    implementation("org.jetbrains.exposed:exposed-dao:0.41.1")
    implementation("org.jetbrains.exposed:exposed-jdbc:0.41.1")`

how can i solve this

**Comment by AlexeySoshin** [comment]
Hi,
`via` function is defined on an Entity.
Judging by your code, you're trying to invoke it on a table.

If you have an `Ads` entity, this should work:

```kotlin
var ads by Ads via UserAdTable
```
