### ISSUE TITLE
nullable reference DAO

### ISSUE THREAD

**Issue by mbunderline76** [JetBrains/Exposed#1684]
Hi, I have a table like this:
`object TransactionTable : LongIdTable() {

    val user = reference("user_id", UserTable)
    val ad = reference("ad_id", AdTable).nullable()
    val status = enumeration("status", TransactionStatus::class)
    val amount = long("award")
    val createdAt = datetime("created_at")
        .defaultExpression(CurrentDateTime)
    val updatedAt = datetime("updated_at")
        .nullable()
    
}`
and an entity like this:
`class TransactionEntity(id: EntityID<Long>) : LongEntity(id) {
    companion object : LongEntityClass<TransactionEntity>(TransactionTable)

    var user by UserEntity referencedOn TransactionTable.user
    var ad by AdEntity referencedOn TransactionTable.ad
    var status by TransactionTable.status
    var amount by TransactionTable.amount
    var createdAt by TransactionTable.createdAt
    var updatedAt by TransactionTable.updatedAt
}`
![Screenshot from 2023-02-05 10-03-33](https://user-images.githubusercontent.com/95180357/216805273-374c6910-2079-4932-85d8-caa2eb63909f.png)

as you can see in the picture when I add `.nullable` on `ad` i get error in my entity.

**Comment by Burtan** [comment]
For those who stumble over this:
[Optional references](https://jetbrains.github.io/Exposed/dao-relationships.html#optional-reference)
