### ISSUE TITLE
Duplicate column name "XXX" in table "dual" when using ktor in development mode

### ISSUE THREAD

**Issue by solution-al** [JetBrains/Exposed#1686]
We are using ktor in development mode with IDEA Ultimate. This seems to be causing a problem when `nullable` fields are defined and changes are detected in the background by ktor.

We are getting the following Exception:
```
Caused by: org.jetbrains.exposed.exceptions.DuplicateColumnException: Duplicate column name "XXX" in table "dual"
	at org.jetbrains.exposed.sql.Table.addColumn(Table.kt:410)
	at org.jetbrains.exposed.sql.Table.replaceColumn(Table.kt:404)
	at org.jetbrains.exposed.sql.Table.nullable(Table.kt:920)
```

`XXX` is a column in our table and it is set as `nullable` and it seems that problem only exists for specific fields which are related to our defined types.

For example this causes problems:
```kotlin
class Todo(id: EntityID<Long>) : LongEntity(id) {
    companion object : LongEntityClass<Todo>(Todos)

    var todoType by Todos.todoType.nullable()
}

object Todos : LongIdTable("todos") {
    val todoType = enumerationByName<TodoType>("todo_type", 20)
}
```

We have tracked it down that the problem is in `Table.replaceColumn` where `oldColumn` is tried to be replaced with an old column:
```kotlin
fun <TColumn : Column<*>> replaceColumn(oldColumn: Column<*>, newColumn: TColumn): TColumn {
  _columns.remove(oldColumn)
  _columns.addColumn(newColumn)
  return newColumn
}
```

However `_columns.remove(oldColumn)` code does not remove that column, thus `addColumn` will throw the Exception described above. Problem is that `oldColumn` does not equal with anything in the `_columns` list even though we see it there with debugger. Debugging even more ends us seeing that in `EnumerationNameColumnType#equals` compared `KClass`-es are not equal for that specific type/column:
```kotlin
   override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false
        if (!super.equals(other)) return false

        other as EnumerationNameColumnType<*>

        if (klass != other.klass) return false // <======= this returns out with `false`

        return true
    }
```

We suspect that it is related with ktor automatic code-reloading, but not sure. What are we doing wrong?

**Comment by solution-al** [comment]
Just found out - we stumbled on this problem originally due to ktor development mode, but just found out that this is easily reproducible also with IntelliJ IDEA Ultimate when performing _Recompile_ after any changes by pressing `ctrl+shift+f9`.

**Comment by AlexeySoshin** [comment]
The issue is in this line:

```kotlin
var todoType by Todos.todoType.nullable()
```
What happens here is that you define your Entity column to be nullable, but your DB column is still non-nullable.

The correct way to do that is to define nullability on the Table:

```kotlin
val todoType = enumerationByName<TodoType>("todo_type", 20).nullable()
```

And to remove `nullable` from your entity.

Hope that helps!

**Comment by solution-al** [comment]
Thank you! It does seem to work for now.

Maybe change API design so that it's not possible to put nullable calls into wrong place?

Closing this issue.
