### ISSUE TITLE
PostgreSQL batch insert

### ISSUE THREAD

**Issue by Hell-Innocence** [JetBrains/Exposed#1688]
How build insert sql
`insert into tableA(columnA)values
('2'),
('3'),
('4'),
('5'),
('6'),
('7')`

**Comment by lucas-avila-aside** [comment]
@Hell-Innocence Here you have [one](https://github.com/JetBrains/Exposed/blob/9ca11124cf1fe8feb7b1f5777e5a6c34f836f658/exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/sqlserver/SQLServerDefaultsTest.kt#L47) example. More in the code by searching for `batchInsert`

**Comment by Hell-Innocence** [comment]
@lucas-avila-aside my db is PostgreSQL, not SQLServer.

**Comment by chrisjenx** [comment]
Some examples, there are some in the docs and tests.
```
UserDisciplines.batchInsert(list, true) { id ->
            this[UserDisciplines.userId] = userId
            this[UserDisciplines.disciplineId] = id
        }
```

```
EquineStatuses.batchInsert(statuses, ignore = true) {
            this[EquineStatuses.equineId] = uuid
            this[EquineStatuses.userId] = it.userId
            this[EquineStatuses.status] = it.status
            this[EquineStatuses.date] = it.date
            this[EquineStatuses.added] = it.added
        }
```

**Comment by frosenek** [comment]
For the PostgreSQL driver specifically I had to do the following to get it working:

1. Set "reWriteBatchedInserts" to true for your jdbc (https://jdbc.postgresql.org/documentation/use/) connection
2. batchInsert(models, shouldReturnGeneratedValues = false) { ... }

**Comment by bog-walk** [comment]
Here's a link to the [Wiki](https://github.com/JetBrains/Exposed/wiki/DSL#batch-insert) with updated examples, info about the driver options above, and how to confirm if batch insert is working correctly in PostgreSQL.

Also an update about documentation:

We are actively working towards improving documentation throughout the codebase, as well as enhancing and publishing all Wiki pages and samples to an Exposed website.

If you're interested, here is a [link](https://blog.jetbrains.com/kotlin/2023/08/exposed-moving-forward/) to the most recent official blog post regarding our plans moving forward.

**Comment by tuananh** [comment]
@frosenek did you get it to work. i tried both of the suggesion you wrote but check postgres logs, it seems like it doesnt work

this is what i have

```
val db = R2dbcDatabase.connect(
        databaseConfig = R2dbcDatabaseConfig {
            connectionFactoryOptions {
                option(ConnectionFactoryOptions.USER, dbUser)
                option(ConnectionFactoryOptions.PASSWORD, dbPassword)
                option(ConnectionFactoryOptions.HOST, dbHost)
                option(ConnectionFactoryOptions.PORT, dbPort)
                option(ConnectionFactoryOptions.DATABASE, dbName)
                option(ConnectionFactoryOptions.DRIVER, "postgresql")
                // PostgreSQL-specific option for batch insert optimization
                option(Option.valueOf("reWriteBatchedInserts"), "true")
            }
        }
    )
```
and 

```kotlin
JobTable.batchInsert(jobs, shouldReturnGeneratedValues = false) { (payload, templateId, scheduledAt) ->
            this[JobTable.payload] = payload
            //
        }
```

**Comment by chrisjenx** [comment]
Have you tried on JDBC not R2DBC?

**Comment by bog-walk** [comment]
Hi @tuananh In your ticket, [EXPOSED-924](https://youtrack.jetbrains.com/issue/EXPOSED-924/batch-insert-doesnt-work-with-r2dbc-postgres), I've responded regarding the use of `reWriteBatchedInserts` with `r2dbc-postgresql`.
