### ISSUE TITLE
Printing out constructed queries for debugging

### ISSUE THREAD

**Issue by alexandre-g** [JetBrains/Exposed#169]
I am trying to write the following MySQL query using Exposed:
`    SELECT * FROM db.followers WHERE user_id = 262673099 AND follower_id NOT IN (SELECT db.notified.notified_user_id FROM db.notified WHERE db.notified.by_user_id = 136134408)
`

So got this:
`    val selected = Followers.select { Followers.userId eq 262673099 and (Followers.followerId notInList (Notified.notifiedUserId.table.select { Notified.byUserId eq 136134408 })) }
`

Running the code I get a crash:
`
[Thread-5] INFO Exposed - Transaction attempt #0: Invalid argument value: java.io.NotSerializableException. Statement: null
java.sql.SQLException: Invalid argument value: java.io.NotSerializableException
`

Is there a way to check what SQL query is getting constructed with the Kotlin query builders to debug the issue?

**Comment by Tapac** [comment]
To print plain sql query you may use `printLn(seleted.prepareSQL(QueryBuilder(false))`, but query which you want to write is unsupported in Exposed - you can't call inList/notInList with subquery. 
I guess you may rewrite it with join:
```Kotlin
Followers.join(Notified, JoinType.INNER, Followers.followerId, Notified.notifiedUserId)
.slice(Followers.columns)
.select { Followers.userId eq 262673099 and (Notified.byUserId neq 136134408) }
```

**Comment by alexandre-g** [comment]
Thanks for the info! The INNER join doesn't seem to work. I've had better luck with this:

`
Followers.join(Notified, JoinType.LEFT, Followers.followerId, Notified.notifiedUserId)
                .select { Notified.notifiedUserId.isNull() and (Followers.userId eq 262673099) }
`

But can't figure out how to filter by the Notified.byUserId eq 136134408.

I guess this is out of the scope of this repository and we have the answer to the issue of debugging, so closing this. Thanks for the help.
