### ISSUE TITLE
Readme includes slack links which do not appear to work

### ISSUE THREAD

**Issue by AlexChesser** [JetBrains/Exposed#1693]
Specifically both the sections 

https://github.com/JetBrains/Exposed#links
https://github.com/JetBrains/Exposed#community

Appear to suggest joining the slack group and channel.  

Attempting to join the channel without an `@jetbrains.com` email address appears to fail.  

I'm not sure if the team wants to remove the links to the slack channel or improve the instructions around how to get an invitation to the group, but the current readme does not provide enough information on how to access the slack community.

**Comment by PoisonedYouth** [comment]
What do you expect? A link to the Slack invite page of JetBrains?

**Comment by AlexChesser** [comment]
I think that is one possible solution.   

If the project is going to put a link on the readme with the claims:

> for more information visit the link
or
> Do you have questions? Feel free to ask and join our project conversation at our [#exposed](https://kotlinlang.slack.com/archives/C0CG7E0A1) channel on [kotlinlang.slack.com](https://kotlinlang.slack.com/).

Should EITHER provide links to meaningful information or be removed entirely. 

- If providing  an invite link to their slack is possible for Jetbrains then they should provide a working invite link.
- If potential spam is a problem, they should link to an way to get an invite after vetting that the person is a real human (eg: send an email to xyz@jetbrains.com asking for an invite)
- If the cost of inviting a potentially large number of community members is prohibitive, then they should abandon the idea that people can join the slack community and remove the instructions to go there from the readme
  - IF they can't do slack, then maybe consider starting a forum or SOMETHING to ensure the claims of a community are meaningfully true.

The precise solution that exposed chooses isn't as important as the fact that the instructions in the readme are correct.

**Comment by bog-walk** [comment]
@AlexChesser  Thanks for bringing this to our attention and for your interest in joining the community. The Readme is being adjusted accordingly. Here's a link to the [invitation request page](https://surveys.jetbrains.com/s3/kotlin-slack-sign-up) in the meantime.
