### ISSUE TITLE
Explain `keepLoadedReferencesOutOfTransaction` on the "DAO API" wiki page

### ISSUE THREAD

**Issue by yttrian** [JetBrains/Exposed#1694]
Right now [Eager Loading](https://github.com/JetBrains/Exposed/wiki/DAO#eager-loading) notes that references are not available outside of a transaction. This is true unless the user enables `keepLoadedReferencesOutOfTransaction = true` which is not mentioned as an option on this page.

Personally, I didn't even realize this was possible until searching through issues and seeing someone mention it because I don't normally need to use `DatabaseConfig`.

**Comment by joc-a** [comment]
Fixed [here](https://github.com/JetBrains/Exposed/wiki/DAO/_compare/41a960adc1cc5cc636262e28a5a2ff5794e925ba...473b95f8f839d1d05fa70babdbca4ca0120ea7f9?diff=split).
