### ISSUE TITLE
Make it spring-boot 3 compatible

### ISSUE THREAD

**Issue by bushwakko** [JetBrains/Exposed#1700]
Spring boot 3 made changes to how auto-configurations are registered:

https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#auto-configuration-files

**Comment by PoisonedYouth** [comment]
It is not only the way of registering autoconfiguration file that changed, also the java baseline is 17 now.

**Comment by PoisonedYouth** [comment]
> Yah - please make this change. You could probably just get away with leaving it as Spring Boot 2.x and adding a text file `META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports` and then placing the name of the autoconfiguration class on the first line. It would still be nice if you took it a bit further and provided an integration for GraalVM native images, as per this issue [from 2021](https://github.com/JetBrains/Exposed/issues/1274). Thanks again for your amazing project!

Josh is everywhere 😂

**Comment by CyrilDreamJobs** [comment]
My temporary fix:

`@Configuration
class ExposedAutoConfiguration2() {

    @Bean
    fun exposedAutoConfiguration(applicationContext: ApplicationContext) =
        ExposedAutoConfiguration(applicationContext)

    @Bean
    fun springTransactionManager(exposedAutoConfiguration: ExposedAutoConfiguration, datasource: DataSource, databaseConfig: DatabaseConfig) =
        exposedAutoConfiguration.springTransactionManager(datasource, databaseConfig)

    @Bean
    fun databaseConfig(exposedAutoConfiguration: ExposedAutoConfiguration, ) =
        exposedAutoConfiguration.databaseConfig()
}
`

**Comment by PoisonedYouth** [comment]
I could fix it with  adding _org.springframework.boot.autoconfigure.AutoConfiguration.imports_ file to the resources with following content: 
```org.jetbrains.exposed.spring.autoconfigure.ExposedAutoConfiguration```

 and also creating a custom configuration which excludes the necessary AutoConfigurations:
```
@Configuration
@EnableAutoConfiguration(
    exclude = [
        DataSourceTransactionManagerAutoConfiguration::class,
        JdbcRepositoriesAutoConfiguration::class,
    ],
)
class ExposedConfiguration
```

**Comment by Mohamadhassan98** [comment]
> Temporary fix:
> 
> ```
> @Configuration
> class DatabaseConfiguration() {
> 
>     @Bean
>     fun exposedAutoConfiguration(applicationContext: ApplicationContext) =
>         ExposedAutoConfiguration(applicationContext)
> 
>     @Bean
>     fun springTransactionManager(exposedAutoConfiguration: ExposedAutoConfiguration, datasource: DataSource, databaseConfig: DatabaseConfig) =
>         exposedAutoConfiguration.springTransactionManager(datasource, databaseConfig)
> 
>     @Bean
>     fun databaseConfig(exposedAutoConfiguration: ExposedAutoConfiguration, ) =
>         exposedAutoConfiguration.databaseConfig()
> }
> ```

Anyone facing this error for the suggested workaround?
`Cannot access class 'org.jetbrains.exposed.spring.SpringTransactionManager'. Check your module classpath for missing or conflicting dependencies`
I'm new to spring and can't make it working inside RestController, getting `No transaction in context` exception.

Trying to fix with suggested workaround raises this error.

Any suggestions?
