### ISSUE TITLE
Support quotes when using schema in the tablename

### ISSUE THREAD

**Issue by gel-hidden** [JetBrains/Exposed#1710]
The function `String.isAlreadyQuoted() ` in `IdentifierManagerApi` uses the following logic:

```
private fun String.isAlreadyQuoted() = startsWith(quoteString) && endsWith(quoteString)
```

Which does not work for `schema."MyTable"`.

**Comment by gel-hidden** [comment]
It is possible to just change the name to `"schema"."MyTable"` to fulfill the condition.

**Comment by bog-walk** [comment]
@gel-hidden Changes were made recently to `Table` and how it handles schema and table names ([PR #1678](https://github.com/JetBrains/Exposed/pull/1678)).
So I'm not getting any issue when using a table name like in your example:
```kt
object TestTable : Table("tester.\"MyTable\"") { //... }

object TestTable : Table("\"Tester\".\"MyTable\"") { //... }

// both ways work (create, insert, select, drop)
```

Please confirm whether this issue persists for you with current version 0.44.0.
If it does, please consider sharing an example of a table object, the database being used, and any exceptions that you're seeing.

**Comment by bog-walk** [comment]
If the issue persists, please consider reopening this issue on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763) with the details requested above, so we can attempt to investigate further.

**Comment by gel-hidden** [comment]
This issue does not persist for 0.44.0.
