### ISSUE TITLE
Is it maintained?

### ISSUE THREAD

**Issue by dzikoysk** [JetBrains/Exposed#1713]
Exposed is quite popular choice for newcomers & smaller projects, but atm it looks like a big tech debt for a project that will eventually use it as there's a high chance to fall into series of bugs/missing features that won't be handled. In the end, you need to rewrite everything to a new library or try to workaround it in a pretty nasty way. 

The number of issues related to Exposed grows each week, but there's no feedback from current maintainers, mostly @Tapac at this point. He has been seen about 4 months ago on GitHub, while his last contribution to the repo occurred 5 months ago + the main branch were updated ~3 months ago.

Understandably, you may not have the time or desire to develop this project as it was in the past, but maybe it's a time to make a decision on what's the current goal & future of this project? Before someone will say it's open-source and everyone can contribute... well, that's not the case here, most of the recent PRs didn't receive any feedback from maintainers, so we can't even talk about having a discussion atm.

**Comment by hhariri** [comment]
We've hired two people specifically to work on Exposed full time and we're ramping up efforts in many areas. Rest assured it will be getting the deserved attention.
