### ISSUE TITLE
Combination of Spring-based transactions and newSuspendedTransaction does not work properly

### ISSUE THREAD

**Issue by peter-plochan** [JetBrains/Exposed#1722]
**Exposed version:** `0.38.2`

We have an application which uses the Spring for transaction management which means that it uses the [SpringTransactionManager](https://github.com/JetBrains/Exposed/blob/c8fa037f07dcb3273786383caacc5eeedd25010c/spring-transaction/src/main/kotlin/org/jetbrains/exposed/spring/SpringTransactionManager.kt#L22) as the primary manager for the database. Because we are using coroutines as well, we started to use [newSuspendedTransaction](https://github.com/JetBrains/Exposed/blob/c8fa037f07dcb3273786383caacc5eeedd25010c/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/transactions/experimental/Suspended.kt#L52) for ensuring that the transaction (provided by the Spring) will be properly passed through the coroutine run. The problem is that this `newSuspendedTransaction` updates and restores only the `TransactionManager` and the `Transaction` itself within thread-local variables (actually, it is done by [TransactionCoroutineElement](https://github.com/JetBrains/Exposed/blob/c8fa037f07dcb3273786383caacc5eeedd25010c/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/transactions/experimental/Suspended.kt#L30)). This is not enough for Spring and `SpringTransactionManager` itself, because there are additional resources saved into the thread local variables which are not properly set and cleared when the coroutine leaves or resumes a thread. For more info, see the whole [TransactionSynchronizationManager](https://github.com/spring-projects/spring-framework/blob/695601aa0681047c0922096bb880b8ec48c1e32a/spring-tx/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java) (e.g. saves the "DB connection holder" into thread-local). As a consequence of not clearing all resources from the thread, Spring considers that the thread contains an "active" transaction when a transaction manager tries to get a transaction during any DB call, so it does not start a new one (saves a new transaction to the thread). This state ends up with errors like e.g. "No transaction in context" when calling any SQL statement.

### Reproducer
Uses Spring Data + Coroutines which is similar to our environment.

<details>
  <summary>build.gradle.kts</summary>

```kotlin
plugins {
    kotlin("jvm") version "1.7.21"
    kotlin("plugin.spring") version "1.7.21"
    id("io.spring.dependency-management") version "1.0.11.RELEASE"
    id("org.springframework.boot") version "2.6.9"
}

repositories {
    mavenCentral()
}

dependencies {
    api("org.jetbrains.exposed:exposed-spring-boot-starter:0.38.2")

    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.data:spring-data-commons")
    implementation("org.springframework:spring-tx")
    implementation("io.github.microutils:kotlin-logging:2.1.23")

    testImplementation("org.junit.jupiter:junit-jupiter:5.9.2")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testRuntimeOnly("com.h2database:h2:2.1.212")
}

tasks {
    withType<Test> {
        useJUnitPlatform()
    }
}
```
</details>

<details>
  <summary>App.kt</summary>

```kotlin
package com.example.stub.project

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withContext
import mu.KotlinLogging
import org.jetbrains.exposed.sql.Table
import org.jetbrains.exposed.sql.insert
import org.jetbrains.exposed.sql.select
import org.jetbrains.exposed.sql.transactions.experimental.newSuspendedTransaction
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication
import org.springframework.stereotype.Repository
import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.EnableTransactionManagement
import org.springframework.transaction.annotation.Transactional


@SpringBootApplication
@EnableTransactionManagement
class MyApp

data class MyEntity(val id: Int)
object TMyEntity : Table("my_entity") {
    val id = integer("id")
}

@Service
class DatabaseTest(private val myEntityRepository: MyEntityRepository) {
    private val logger = KotlinLogging.logger {}
    private val testingEntity = MyEntity(1)

    fun runTest() {
        // setup DB entry
        myEntityRepository.create(testingEntity)
        // testing coroutine
        runBlocking(Dispatchers.IO) {
            launch {
                newSuspendedTransaction {
                    logger.info { "Preparing select in a new coroutine..." }
                    val coroutineSelectResult = withContext(Dispatchers.IO) {
                        myEntityRepository.selectSingle(testingEntity.id)
                    }
                    logger.info { "Delaying the new coroutine..." }
                    delay(5000)
                    logger.info { "The new coroutine select result: $coroutineSelectResult" }
                }
            }
            logger.info { "Waiting some time for the new coroutine to start..." }
            delay(1000)
            logger.info { "Starting current coroutine select" }
            val selectResult = myEntityRepository.selectSingle(testingEntity.id)
            logger.info { "Current coroutine select result: $selectResult" }
        }
    }
}

@Repository
@Transactional
class MyEntityRepository : org.springframework.data.repository.Repository<MyEntity, Int> {
    fun create(entity: MyEntity) {
        TMyEntity.insert { it[id] = entity.id }
    }

    fun selectSingle(identifier: Int) =
        TMyEntity.select { TMyEntity.id eq identifier }
            .map { resultRow -> MyEntity(resultRow[TMyEntity.id]) }
            .firstOrNull()
}

fun main() {
    runApplication<MyApp>()
}
```
</details>

<details>
  <summary>AppTest.kt</summary>

```kotlin
package com.example.stub.project

import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest

@SpringBootTest(
    properties = [
        "spring.exposed.generate-ddl=true",
        "logging.level.Exposed=DEBUG",
        "spring.datasource.url=jdbc:h2:mem:testdb",
    ]
)
class AppTest {

    @Autowired
    lateinit var dbTest: DatabaseTest

    @Test
    fun test() {
        dbTest.runTest()
    }
}
```
</details>

### Possible solutions
Some possible solutions which come into my mind:
* Allow passing custom coroutine element to `newSuspendedTransaction`, e.g. in the form of lambda `(Lazy<Transaction>, TransactionManager) -> CoroutineContext`. Even this is a very simple change, it won't fix the problem, just proposes a way to workaround that. 
* Support proper cleaning and setting-up of `TransactionSynchronizationManager` in a special Spring-based `ThreadContextElement`.

**Comment by bog-walk** [comment]
@peter-plochan Thanks very much for providing a sample. I was able to reproduce the issue you're seeing using older versions.

Upgrading to the current Exposed version 0.44.0 resolved the issue and the test passed. Please consider trying your app with this version and confirming if it works for you too.

**Note** The only changes I had to make to your sample were in the build file:
-> upgrade Exposed (0.44.0), Spring Boot (3.1.2), & JDK (17).

**A note about SpringTransactionManager:**

`SpringTransactionManager`  got an overhaul in the [latest release](https://github.com/JetBrains/Exposed/blob/main/docs/BREAKING_CHANGES.md#0440), which in its best interests removes any interference from Exposed's transaction management, in favor of Spring's own transaction lifecycle. This should improve its usability, significantly reducing the backlog of issues faced by our Spring users (e.g. with nested transactions, propagation, & isolation).

If you're interested in the rationale behind these changes, here are some links: [EXPOSED-109](https://youtrack.jetbrains.com/issue/EXPOSED-109/Suggestion-Improve-SpringTransactionManager), [PR 1840](https://github.com/JetBrains/Exposed/pull/1840).

**Comment by bog-walk** [comment]
If the issue persists, or if you encounter any further problems with Spring and `newSuspendedTransaction`, please consider reporting them on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763), so that we can investigate further.
