### ISSUE TITLE
Unnecessary query after calling with() and iteration.

### ISSUE THREAD

**Issue by neetkee** [JetBrains/Exposed#1726]
Hello. After calling with() for preload, there will be an additional query when iterating results.

Example test. Tables for it can be found in [EntityTests.kt class](https://github.com/JetBrains/Exposed/blob/master/exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityTests.kt).
```kotlin
    @Test
    fun testUnnecessaryQuery() {
        withTables(Regions, Schools) {
            School.new {
                name = "Eton"
                region = Region.new { name = "United Kingdom" }
            }
            commit()

            inTopLevelTransaction(Connection.TRANSACTION_SERIALIZABLE, 1) {
                addLogger(StdOutSqlLogger)
                School
                    .all()
                    .with(School::region)
                    .forEach {
                        // additional query will be executed here
                    }
            }
        }
    }
```

Test query output:
```
SQL: SELECT school.id, school."name", school.region_id, school.secondary_region_id FROM school
SQL: SELECT region.id, region."name" FROM region WHERE region.id = 1
SQL: SELECT school.id, school."name", school.region_id, school.secondary_region_id FROM school
```

I think this behaviour is related to the [#1585](https://github.com/JetBrains/Exposed/pull/1585) change, as with() now returns a SizedIterable.

Test query output without [#1585](https://github.com/JetBrains/Exposed/pull/1585) change:
```
SQL: SELECT school.id, school."name", school.region_id, school.secondary_region_id FROM school
SQL: SELECT region.id, region."name" FROM region WHERE region.id = 1
```

**Comment by organize** [comment]
Running into the same issue.

**Comment by mhaynesjr** [comment]
Also seeing this issue. I have been banging my head all day trying to figure out why Im getting all these repeated SQL statements. Only when I remove the with() will the calls be what Im expecting.

**Comment by zivkovic** [comment]
I just stumbled on the same thing, but using `.with(...).toList()`. I think we could simply cache the `toList()` call result inside of `.with` function, and then simply return the cached list when we call `.toList()`. If any other actions were executed on the iterable the cache could be invalidated. Did I miss any issues with this solution?
