### ISSUE TITLE
What is the correct way to return results of a query?

### ISSUE THREAD

**Issue by ndchorley** [JetBrains/Exposed#173]
Hi,

I'd like to abstract away the database access into a function, for example:

```kotlin
object Users: Table() {
    val id = integer("id").primaryKey()
    val name = varchar("name", 50)
}

data class User(val id: Int, val name: String)

fun getUsers(): List<User> {
    Database.connect("jdbc:sqlite:users.db", "org.sqlite.JDBC")
    return Users.selectAll().map { User(it[Users.id], it[Users.name]) }
}
```
This doesn't work - it throws `java.lang.IllegalStateException: No transaction in context`. It seems that you have to wrap everything inside `transaction`:

```kotlin
fun getUsers(): List<User> {
    Database.connect("jdbc:sqlite:users.db", "org.sqlite.JDBC")
    TransactionManager.manager.defaultIsolationLevel = Connection.TRANSACTION_SERIALIZABLE

    transaction {
        return Users.selectAll().map { User(it[Users.id], it[Users.name]) }
    }
}
```
In this case, the code won't compile, complaining that "return not allowed here". Since the only operation here is a read, I'm not sure why one needs to use a transaction anyway.

So, then, how do I return the list of my value objects after processing the rows from the query?

Thanks!

**Comment by Darych** [comment]
I'm doing the same thing.
As the simplest solution, I can suggest you, to store your results in temporary List and return this instance of List. Hope this will help!

`fun getUsers(): List<User> {
    Database.connect("jdbc:sqlite:users.db", "org.sqlite.JDBC")
    TransactionManager.manager.defaultIsolationLevel = Connection.TRANSACTION_SERIALIZABLE

    res = mutableListOf<User>()
    transaction {
        res = Users.selectAll().map { User(it[Users.id], it[Users.name]) }
    }
    return res
}`

**Comment by ndchorley** [comment]
Yeah, I'd considered that, but it's a bit weird to have to create a list you're not going to use (granted, it won't use much memory, but still...).

**Comment by Tapac** [comment]
If it's not the only place where you want to use such approach (note that you may call `connect` once per application run), then I advice to introduce helper function:
```Kotlin
fun connectAndExec(statement: Transaction.() -> T) : T {
   Database.connect("jdbc:sqlite:users.db", "org.sqlite.JDBC")
   return transaction(Connection.TRANSACTION_SERIALIZABLE, 3, statement)
}
```
then your code will look like
```Kotlin
fun getUsers(): List<User> = connectAndExec {
    Users.selectAll().map { User(it[Users.id], it[Users.name]) }
}
```

**Comment by ndchorley** [comment]
Thanks, @Tapac.

**Comment by lamba92** [comment]
I'm having a similar error but I don't get where i am wrong:
```
val cameras = serializableTransaction(Settings.localDatabase) {
    Camera.find { CameraTable.configured eq false }
}
call.respond(cameras.map { it.toMap() })
```
```
fun <T> serializableTransaction(db: Database? = null, function: Transaction.() -> T)
        = transaction(Connection.TRANSACTION_SERIALIZABLE, 3, db,function)
```

**Comment by Tapac** [comment]
If you have any text or blob fields in your table most of jdbc drivers them wont load them into memory until you ask for it.  So you need to make `toMap` within a transaction block.

```kotlin
val cameras = serializableTransaction(Settings.localDatabase) {
    Camera.find { CameraTable.configured eq false }.map { it.toMap() }
}
call.respond(cameras)
```

**Comment by lamba92** [comment]
That was it, thanks!! 😄
