### ISSUE TITLE
Replace using H2 in MySQL mode doesn't work when using pool (Hikari) 

### ISSUE THREAD

**Issue by fgaule** [JetBrains/Exposed#178]
Trying to use REPLACE statement in a H2 database in MySQL mode ("jdbc:h2:mem:test;MODE=MySQL") results in an UnsupportedOperationException with message "REPLACE is only supported in MySQL compatibility more for H2" when you are using a connection pool like [Hikari](https://github.com/brettwooldridge/HikariCP) due to failure in getting H2 mode in `org.jetbrains.exposed.sql.vendors.H2Dialect`

Connection is tried to be cast to `org.h2.jdbc.JdbcConnection` but if you are using a connection pool. connection instance is an instance of a proxy.

**Comment by vetrovosk** [comment]
We are abserving the same broken behaviour again when using HikariCP with h2 database, apparently it was recently broken by commit e4a3f9c2ee4afcd767568fbf89c00d7cbce69efd [here](https://github.com/JetBrains/Exposed/commit/e4a3f9c2ee4afcd767568fbf89c00d7cbce69efd#diff-b4f5210618ac4d3cf58b162f146c0163R16)

**Comment by Tapac** [comment]
@vetrovosk , thank you for a report. Fixed in master branch. Will be released in 0.19.2
