### ISSUE TITLE
Mapping two columns in many to many Table with DAO

### ISSUE THREAD

**Issue by Artraxon** [JetBrains/Exposed#180]
Hello,
i have the following structure:
```Kotlin
object Songs : IntIdTable() {
    val name = varchar("name", 64)
}
object Artists : IntIdTable() {
    val name = varchar("name", 20)
}
object ArtistSongs : IntIdTable() {
    val songID = reference("songID", Songs)
    val artist_ID = reference("artistID", Artists)
    val role = integer("role")
}
class Song(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<Song>(Songs)

    var artists by Artist via ArtistSongs
    var name by Songs.name
}
class Artist(id: EntityID<Int>) : IntEntity(id){
    companion object : IntEntityClass<Artist>(Artists)

    var name by Artists.name
    var songs by Song via ArtistSongs
}
```

Is there a way how i could easily map the role Of an Artist to the artists in Song, or to the Songs in Artist?
Like
```Kotlin
class Artist(id: EntityID<Int>) : IntEntity(id){
…
var songs by (Song via ArtistSongs) mapTo ArtistSongs.role
}
```
At the moment, i can't set Song.artists or vice versa because this would leave role empty.
Any suggestions?

**Comment by Tapac** [comment]
I guess the easiest way is to use additional entity. Something
```Kotlin
class Artist(id: EntityID<Int>) : IntEntity(id){
    companion object : IntEntityClass<Artist>(Artists)

    var name by Artists.name
    val songsAndRoles by ArtistSong.referrersOn(ArtistSongs.artist_ID)

    val allRoles get() = songsAndRoles.map { it.role }.distinct()
}

class ArtistSong(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<ArtistSong>(ArtistSongs) {
        override val dependsOnTables: ColumnSet = Artists.innerJoin(ArtistSongs).innerJoin(Songs)
        override fun createInstance(entityId: EntityID<Int>, row: ResultRow?): ArtistSong {
            val tr = TransactionManager.current()
            row?.tryGet(Artists.id)?.let {
                Artist.wrap(it, row, tr)
            }
            row?.tryGet(Songs.id)?.let {
                Song.wrap(it, row, tr)
            }

            return super.createInstance(entityId, row)
        }
    }

    var role by ArtistSongs.role
    var artist by Artist referencedOn ArtistSongs.artist_ID
    var song by Song referencedOn ArtistSongs.songID
}
fun main(args: Array<String>) {
    Artist.all().filter { 
       it.songsAndRoles.any { it.role == 5 }
    }
}
```
Code within EntityClass should help to prevent additional queries to load linked entities. 
I don't run that code, but I hope it works as expected:D

**Comment by Artraxon** [comment]
Thanks for the answer!
What i dont understand is why i have to to all of this
```Kotlin
override fun createInstance(entityId: EntityID<Int>, row: ResultRow?): ArtistSong {
            val tr = TransactionManager.current()
            row?.tryGet(Artists.id)?.let {
                Artist.wrap(it, row, tr)
            }
            row?.tryGet(Songs.id)?.let {
                Song.wrap(it, row, tr)
            }

            return super.createInstance(entityId, row)
        }
```
because i honestly don't understand what it does.
It would be great if someone has the time to explain that to me.

**Comment by Tapac** [comment]
@Artraxon , every time you call entity by id (with Entity.forIds(), or by references, or any Entity.find{}) Exposed check EntityCache for an already loaded entity with that id and returns it without making a call to DB.
Entity is placed into the cache on loading from DB (with Entity.wrap() function), so if you make single select which loads multiple related entities (like artists-songs), you may manually put them to cache and prevent additional queries when you'll trying to read those entities.

**Comment by Artraxon** [comment]
Ah, thank you. So it basically just stores information in the cache?
And i have a second question (i don't wannt to open a new issue) which is similiar to Entity.new
but checks whether the table already has a row with the specified values?

**Comment by Tapac** [comment]
> Ah, thank you. So it basically just stores information in the cache?
Yep.

>And i have a second question (i don't wannt to open a new issue) which is similiar to Entity.new
but checks whether the table already has a row with the specified values?
What do you mean by "specified values"?

**Comment by Artraxon** [comment]
Nevermind, sorry.
