### ISSUE TITLE
configuring the primary key column of an IdTable by using clientDefault breaks insertAndGetId

### ISSUE THREAD

**Issue by lnhrdt** [JetBrains/Exposed#183]
IntIdTable defines the primary key like this:

```kotlin
integer(columnName).autoIncrement().primaryKey().entityId()
```

and `MyIntIdTable.insertAndGetId { ... }` works great.

I'm trying to create my own IdTable (very similar to the UUIDTable in #108). I've defined the primary key like this:

```kotlin
varchar(columnName, 36)
            .primaryKey()
            .clientDefault { UUID.randomUUID().toString() }
            .entityId()
```

but calling `MyUUIDTable.insertAndGetId { ... }` fails. Digging around in the source code I think it has something to do with the way `InsertStatement.generatedKey` is set. Maybe `clientDefault { ... }` doesn't setup the data the same way `autoIncrement()` does.

**Comment by caskolkm** [comment]
@lnhrdt do you have any workaround available? insertAndGetId doesn't work at all for varchar id's

**Comment by caskolkm** [comment]
@lnhrdt i really have a workaround by set an id without clientDefault.

**Comment by Tapac** [comment]
We going to fix that issue till next release, because it's really annoing.
Workaround is just not implicit id set to field as you mentioned above.


22 нояб. 2017 г. 12:05 AM пользователь "caskolkm" <notifications@github.com>
написал:

**Comment by caskolkm** [comment]
@Tapac any ETA for a fix?

**Comment by Tapac** [comment]
@caskolkm , will be available with next release. Already fixed in a branch.

**Comment by caskolkm** [comment]
@Tapac nice, good work!
