### ISSUE TITLE
Indeterminate behaviour creating tables

### ISSUE THREAD

**Issue by PaulMuriithi** [JetBrains/Exposed#189]
Sometimes some tables do not get created, for some weird reason I don't seem to understand.
Is there anyone else who has experienced this?
I am using the latest version and using MySQL

**Comment by Tapac** [comment]
Which version of Exposed do you use?
Can you check that you have tabled with name Busy? Does it contain any values?

**Comment by PaulMuriithi** [comment]
I am using version `0.8.7`

Check this example I have just created to simulate what I am experiencing.

https://github.com/PaulMuriithi/TestJetbrainsExposed/tree/master

**Comment by PaulMuriithi** [comment]
My initial debugging suggests it has something to do with the latest mysql connector https://mvnrepository.com/artifact/mysql/mysql-connector-java/6.0.6 because when I try with an older version of the same like https://mvnrepository.com/artifact/mysql/mysql-connector-java/5.1.44, it works as expected.

**Comment by PaulMuriithi** [comment]
Maybe it has something to do with the new driver class `com.mysql.cj.jdbc.Driver` from version `6.0.2`

**Comment by Tapac** [comment]
I guess that MySQL jdbc driver 6.x version works only with MySQL 5.7 or newer. We don't test Exposed on that versions yet, but going to do that at #171

**Comment by PaulMuriithi** [comment]
Great! I will be following the progress over there.
