### ISSUE TITLE
Feature Request: Make enum values accept strings

### ISSUE THREAD

**Issue by msrd0** [JetBrains/Exposed#191]
I have a field in my db that acts like an enumeration, however it's current type is text. All columns in the db are either `"TEXT"` or `"NUMBER"`. I wanted to change the type from `text("type")` to `enumeration("type", Type::class.java)` with

```kotlin
enum class Type
{
    TEXT,
    NUMBER
}
```

However, I receive an exception:

```
Caused by: java.lang.IllegalStateException: TEXT is not valid for enum com.example.Type
	at org.jetbrains.exposed.sql.EnumerationColumnType.valueFromDB(ColumnType.kt:166)
	at org.jetbrains.exposed.sql.ResultRow.get(Query.kt:23)
	at org.jetbrains.exposed.dao.Entity.lookup(Entity.kt:218)
	at org.jetbrains.exposed.dao.Entity.getValue(Entity.kt:204)
```

I'd expect exposed to use `Type.valueOf("TEXT")` instead of throwing an exception.

**Comment by Tapac** [comment]
You may try to use a mapping like this :
```Kotlin
object Foo : Table() {
   val type = enumerationByName("type", 10, Type::class.java)
}
```

**Comment by msrd0** [comment]
Looks like this is exactly what I'm looking for. However, it would be more convenient to have an overloaded function if you don't want to specify the text length (i.e. use `TEXT` instead of `VARCHAR`). Looking at the source code this should be possible by specifying a length bigger than 0xFF.

**Comment by Tapac** [comment]
@msrd0, a text type is not always a good choice for such fields because it's impossible to include text fields to the index in most databases, but frequently you want to fast search something by "enum" field. 
Maybe is large enough varchar field (128 chars?) will be ok by default to cover most cases?

**Comment by msrd0** [comment]
Actually, some databases [have](https://www.postgresql.org/docs/9.6/static/datatype-enum.html) [enum](https://dev.mysql.com/doc/refman/5.7/en/enum.html) [types](http://www.h2database.com/html/datatypes.html#enum_type) which is probably what you want to use in the first place. However, it sounds reasonable to use varchar instead of text as a backup.

**Comment by Tapac** [comment]
Yep, it's nice to have, but not so easy to implement: on schema adjustment you should check what that enum field covers all values from enum in code, what might be not so obvious while using jdbc.

**Comment by Tapac** [comment]
You can use `customEnumeration` function (see [example](https://github.com/JetBrains/Exposed/blob/8d1f31f9ed1f247466d5050913bf28827bd89590/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt#L582)). 
This functionality will be available on the closest release (this week I hope).
