### ISSUE TITLE
Custom wrapper columns with autoincrement - AutoIncColumnType should be open?

### ISSUE THREAD

**Issue by pivovarit** [JetBrains/Exposed#194]
In our application, we're representing our ids as data class wrappers for standard `long` ids:

    data class UserId(val value: Long) {

        companion object {
            fun newOrNull(value: Long?): UserId? {
                return value?.let(::UserId)
            }
        }
    }

In order to make our life easier, we created a custom wrapper column type that bypasses the type layer and operates straight on the raw long inside a data class:

    class WrapperColumnType<Raw : Any, out Wrapper : Any>(
            private val rawColumnType: ColumnType,
            internal val rawClazz: KClass<Raw>,
            private val wrapperClazz: KClass<Wrapper>,
            private val instanceCreator: (Raw) -> Wrapper,
            private val valueExtractor: (Wrapper) -> Raw
    ) : ColumnType() {

        override fun sqlType(): String = rawColumnType.sqlType()

        override fun valueFromDB(value: Any) = when {
            rawClazz.isInstance(value) -> instanceCreator(rawColumnType.valueFromDB(value) as Raw)
            else -> error("Database value ${value.javaClass} is not valid $rawClazz")
        }

        override fun notNullValueToDB(value: Any) = when {
            wrapperClazz.isInstance(value) -> rawColumnType.notNullValueToDB(valueExtractor(value as Wrapper))
            else -> error("Wrapper value ${value.javaClass} is not valid $wrapperClazz")
        }

        override fun nonNullValueToString(value: Any) = rawColumnType.valueToString(value)

        override fun toString() = "WrapperColumnType(rawColumnType=$rawColumnType, rawClazz=$rawClazz, wrapperClazz=$wrapperClazz)"
    }

So far, it was enough to set the `autoinc` property:

    fun <N : Any, C : Column<N>> C.autoIncrement(): C {
        // ...
        columnType.autoinc = true
        return this
    }

but, since 0.8.x we need to deal with immutable columns and leverage the provided `AutoIncColumnType`. Everything works cool until we realize that the following code exists and is unoverrideable:

    val IColumnType.isAutoInc: Boolean get() = this is AutoIncColumnType || (this is.    EntityIDColumnType<*> && idColumn.columnType.isAutoInc)
    val Column<*>.autoIncSeqName : String? get() {
            return (columnType as? AutoIncColumnType)?.autoincSeq
                ?: (columnType as? EntityIDColumnType<*>)?.idColumn?.autoIncSeqName
    }

We can't override those methods nor we can extend the `AutoIncColumnType`. Do you have any tips how to achieve this without using any forms of black magic? Maybe it'd make sense to open the `AutoIncColumnType`?

**Comment by Tapac** [comment]
AutoIncColumnType is just wrapper for ColumnType, so you just write : 
```Kotlin
object Foo : Table() {
   val col = registerColumn("wrapped", WrapperColumnType(...)).autoIncrement() 
}
```
Or I miss something?

**Comment by pivovarit** [comment]
@Tapac `autoIncrement` is defined only for `EntityID` and `Number` columns:
    fun <N:Number> Column<N>.autoIncrement
    fun <N:Number> Column<EntityID<N>>.autoinc

**Comment by Tapac** [comment]
It's still possible to:
```Kotlin
object Foo : Table("") {
    val bar = registerColumn<Long>("bar", LongWrapper).autoIncrement()
    val baz = registerColumn<Long>("baz", AutoIncColumnType(LongWrapper, "")) // Will not compile with last release because registerColumn expexts ColumnType instead of IColumnType. Fixed in master
}
```

**Comment by pivovarit** [comment]
It will not really work because we need the generic `Column<T>` and not `Column<Long>` - unless I'm missing something

I tried simply wrapping the `AutoIncColumnType` but it does not work because of `val IColumnType.isAutoInc: Boolean get()` extension method. It simply does not recognize it as the AutoInc-able type

**Comment by Tapac** [comment]
Do you want to have a column of wrapped type? If so try this:
```Kotlin
class WrapperColumnType<Raw : Any, out Wrapper : Any>(
        private val rawColumnType: IColumnType, <-- IColumnType instead of ColumnType
        internal val rawClazz: KClass<Raw>,
        private val wrapperClazz: KClass<Wrapper>,
        private val instanceCreator: (Raw) -> Wrapper,
        private val valueExtractor: (Wrapper) -> Raw
) {... }


class FooClass (val id: Long)

val FooWrapper = WrapperColumnType(
        AutoIncColumnType(DecimalColumnType(5, 5), ""), Long::class, FooClass::class,
        { FooClass(it) }, { it.id })

object Foo : Table("") {
    val foo = registerColumn<FooClass>("foo", FooWrapper)
}
```

**Comment by pivovarit** [comment]
This is one of the first things I tried but it does not work because the WrapperColumn is not recognized as autoincrementable.

    java.lang.IllegalStateException: No key generated
            at org.jetbrains.exposed.sql.statements.InsertStatement.get(InsertStatement.kt:14)

https://github.com/JetBrains/Exposed/blob/6d5533a3d9814087ebf1301314b47fafe878e311/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt#L76

**Comment by Tapac** [comment]
Do you want to have a column of wrapped type? If so try this (I add helper function for creating wrapper columns, but you can don't use it):
```Kotlin
class WrapperColumnType<Raw : Any, out Wrapper : Any>(
        private val rawColumnType: IColumnType, <-- IColumnType instead of ColumnType
        internal val rawClazz: KClass<Raw>,
        private val wrapperClazz: KClass<Wrapper>,
        private val instanceCreator: (Raw) -> Wrapper,
        private val valueExtractor: (Wrapper) -> Raw
) {... }

inline fun <reified Raw: Any, reified Wrapper: Any>
    Table.registerWrapperColumn(name: String, columnType: IColumnType, autoInc: Boolean,
                               noinline to: (Raw) -> Wrapper, noinline from: (Wrapper) -> Raw): Column<Wrapper> {
    val originalColType = WrapperColumnType(columnType, Raw::class, Wrapper::class, to, from)
    val final = if (autoInc) AutoIncColumnType(originalColType, "") else originalColType
    return registerColumn(name, final)
}

class FooClass (val id: Long)

object Foo : Table("") {
    val bar = registerWrapperColumn<Long, FooClass>("bar", DecimalColumnType(5, 5), false, { FooClass(it)}, { it.id })
    val baz = registerWrapperColumn<Long, FooClass>("baz", DecimalColumnType(5, 5), true, { FooClass(it) }, { it.id })
}
```

**Comment by pivovarit** [comment]
Yes, the goal is to have a column of a wrapped type which contains an autoincremented value. Let me try this

**Comment by pivovarit** [comment]
Looks like this should work, when can we expect the `0.8.9` to be released?

**Comment by pivovarit** [comment]
@Tapac `Error:Could not GET 'https://dl.bintray.com/kotlin/exposed/org/jetbrains/exposed/exposed/0.8.9/exposed-0.8.9.pom'. Received status code 401 from server: Unauthorized` :)

**Comment by Tapac** [comment]
@pivovarit , please try now. I forgot to publish artifacts on bintray

**Comment by pivovarit** [comment]
@Tapac works like a charm now :)
