### ISSUE TITLE
IllegalStateException: Column and factory point to different tables

### ISSUE THREAD

**Issue by msrd0** [JetBrains/Exposed#195]
I tried applying your solution from #158 to a little more complex scenario:

I have a user table, like this:

```kotlin
object Users : LongIdTable()
{
    val name = text("name")
}
```

One user can have multiple addresses:

```kotlin
object Addresses : LongIdTable()
{
    val user = reference("user", Users)
    val street = text("street")
    val city = reference("city", Cities)
}

object Cities : LongIdTable()
{
    val cityName = text("city_name")
}
```

Now, I want to print all addressess, including their city, for a huge list of users. I tried writing it like this, but it makes tons of requests and is very slow:

```kotlin
User.all().forEach { user ->
    println("USER ${user.name}")
    User.addresses.forEach { address ->
        println("  ADDR ${address.street} ${address.city.cityName}")
    }
}
```

Because this is far to slow, I tried warming up the reference:

```kotlin
User.all.toList().apply {
    Address.warmUpReference(map{it.id}, Addresses.user)
} // ...
```

This will make only one query to the addresses table, however still tons of queries to the cities table. So I tried adding this line in the `apply` block:

```kotlin
Cities.warmUpReference(flatMap{it.addresses.map{a->a.id}}, Cities.address)
```

However, this gives me, additional to the one big query to the address table, tons of queries to the addresses table with only one id, plus the following exception:

```
java.lang.IllegalStateException: Column and factory point to different tables
	at org.jetbrains.exposed.dao.EntityKt.checkReference(Entity.kt:41)
	at org.jetbrains.exposed.dao.EntityKt.access$checkReference(Entity.kt:1)
	at org.jetbrains.exposed.dao.EntityClass.warmUpReferences(Entity.kt:624)
```

How should I wrap this complicated request in three or less queries?

**Comment by Tapac** [comment]
The problem that City is not referenced to Address, to "warm up" that relation you just have to load all cities by id from Addresses.city field. 
There is no such function in Exposed atm, but you may workaround it like this:
```Kotlin
class Address() : Entity() {
  val cityId by Addresses.city
  var city by City referencedOn Address.city
}

// warmup
City.forEntityIds(flatMap{it.addresses.map{a->a.cityId}}).toList()
```
I think that warmUp* functions are lacked kdoc and examples. And possibly there should be one more function to warm up `referenced` entities (all other are warming `references`)

**Comment by msrd0** [comment]
After several attempts to get it running with exposed I ended up doing a query to `Addresses.innerJoin(Cities)`, putting everything in a map of userId to a list of addresses (including the city), and using that one. Two queries (fast), but not very readable code.

> I think that warmUp* functions are lacked kdoc and examples.

This applies to almoust all parts of your great library. I hope you'll find some time someday to address that problem.

**Comment by MrThreepwood** [comment]
Could I see an example of what you ended up doing? There's almost no documentation on any of this stuff. I have no idea how to get an object with a list of related objects on it, near it or whatever without making a query per top level object. It's one of the most common use cases for a database, but I can't find even one example anywhere on the internet of how to do this... I'd like to use this library, but since there's no documentation, I don't see how I can.

**Comment by msrd0** [comment]
@MrThreepwood I don't have the exact code I used in my response above anymore. However, I wrote an extension function that will load two tables with a reference between them in two database calls. It will return a `List<Pair<FirstTable, SecondTable>>`. I hope this helps.

Note that there were some changes in exposed 0.10 that broke some of my extension functions. I don't know if the one below is working for exposed 0.10, but it does work up to 0.9.

```kotlin
fun <T : Entity<*>, ID : Comparable<ID>, R : Entity<ID>> Iterable<T>.loadReference(getRefId : (T) -> ID, referenceClass : KClass<R>) : List<Pair<T, R>>
{
	val reference = referenceClass.companionObjectInstance as EntityClass<ID, R>
	val ids = map { t -> getRefId(t) }
	if (ids.isEmpty())
		return emptyList()
	val op = object : Op<Boolean>() {
		override fun toSQL(queryBuilder : QueryBuilder) : String
			= ids.joinToString(" OR ") { "(id = $it)" }
	}
	val references : Map<ID, R> = reference.find(op).groupBy { it.id.value }.mapValues { (_, v) -> v.first() }
	val list = ArrayList<Pair<T, R>>()
	forEach { t ->
		list.add(t to (references[getRefId(t)]!!))
	}
	return list
}
```

You can use the above method like this:

```
Address.all().loadReference(Addresses::cityId, City::class).forEach { (address, city) ->
}
```
