### ISSUE TITLE
Query.get throws NPE although hasValue is true

### ISSUE THREAD

**Issue by kaasasolut** [JetBrains/Exposed#196]
I'm using PostgreSQL and try to do:

    val query = (LeftTable leftJoin RightTable).select { LeftTable.id eq id }
    query.forEach({
        if (it.hasValue(RightTable.id)) {
            // Do some stuff
            // Do something with it[RightTable.id]
            // Do other stuff
        }
    })

I get a NullPointerException at the line where I use `it[RightTable.id]` although I checked it with `hasValue`. So I logged `hasValue` and `tryGet`. The results are strange:

    hasValue: true
    tryGet: null

Is that a bug or intended behavior? If it's not a bug, what is the use of `hasValue`?

**Comment by Tapac** [comment]
NULL is a valid value in SQL, so that means that your query returns null for `RightTable.id`.
`hasValue` returns true when column/expression value is initialized and exists in ResultRow.
What you want to achieve is better make with `let{}` : 
```Kotlin
query.forEach({
    it.tryGet(RightTable.id)?.let { rightId ->
        // Do some stuff
        // Do something with rightId
        // Do other stuff
    }
})

**Comment by kaasasolut** [comment]
I see, but it's still a bit strange.
The tables look like this:

    object LeftTable : Table() {
        val id = integer("id").autoIncrement().primaryKey()
    }
    
    object RightTable : Table() {
        val id = integer("id").autoIncrement().primaryKey()
        val left = integer("left_id").references(LeftTable.id)
    }

As you can see, `RightTable.id` is not nullable. So I didn't expect null. Why does it return null?

**Comment by Tapac** [comment]
Left join means that you want to retrieve all rows from the first table and related rows from the second one if they exist. In your case, I guess you have rows in Left without reference from Right, 

Possibly you want to make innerJoin or rightJoin instead.

https://www.w3schools.com/sql/sql_join.asp

**Comment by kaasasolut** [comment]
Left join is the right one. I expected that `hasValue` would be `false` if there are no values from the Right table after the join.

**Comment by kostrse** [comment]
I also found this behavior confusing.
Everyone would expect that `getOrNull` returns null, `get` throws exception and `hasValue` returns false.

**Comment by Tapac** [comment]
@kostrse Why `get` on nullable column should throw?
`NULL` is a valid value for a column.

**Comment by kostrse** [comment]
> @kostrse Why `get` on nullable column should throw?
Probably It should not be nullable in this case?

It feels like the framework isn't assisting you in solving your domain problem, but other way around, forces you to think about the framework instead.
