### ISSUE TITLE
Feature request: MySQL all 4 BLOB and TEXT types

### ISSUE THREAD

**Issue by Petitt88** [JetBrains/Exposed#201]
MySQL has 4 blob types: TINYBLOB, BLOB, MEDIUMBLOB, and LONGBLOB

All it needs is to be able to override the ```java BlobColumnType's sqlType ``` function and set it to the corresponding type.

The same goes for the TEXT type: TINYTEXT, TEXT, MEDIUMTEXT, and LONGTEXT.

**Comment by Tapac** [comment]
Exposed uses most common types for every supported DBMS, so we try to not add a lot of specific functions/types. 

BTW you can just delegate everything to BlobColumnType and override only sqlType function: 
```Kotlin
class TinyBlobColumnType : IColumnType by BlobColumnType() {
    override fun sqlType(): String = "TINYBLOB"
}

object Foo : Table() {
    val tiny = registerColumn("tiny", TinyBlobColumnType())
}
```

**Comment by Petitt88** [comment]
Thank you, this solution is elegant and more importantly: works.

**Comment by devgor88** [comment]
I had same issue. Now you should add type parameter to `IColumnType` like this:
```
class TinyBlobColumnType : IColumnType<ExposedBlob> by BlobColumnType() {
    override fun sqlType(): String = "TINYBLOB"
}

object Foo : Table() {
    val tiny = registerColumn("tiny", TinyBlobColumnType())
}
```
