### ISSUE TITLE
Change in behavior of `inList` ("inListIds" variant)

### ISSUE THREAD

**Issue by jeremyluinstra-RL** [JetBrains/Exposed#2069]
A recent change was made to the signature of [this inList function](https://github.com/JetBrains/Exposed/blob/42ac41b14c632e745c58d234641e9a2862d3204a/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt#L836) from 
```kotlin
infix fun <T : Comparable<T>, ID : EntityID<T>?> Column<ID>.inList(list: Iterable<T>)
```
to 
```kotlin
infix fun <T : Comparable<T>> Column<EntityID<T>?>.inList(list: Iterable<T>)
```
This is breaking and I'm not sure I see the point of it. Now to select from an `IdTable` you have to convert your list of ids to EntityID, whereas before this was not necessary. This change will break _a lot_ of code.

Example of code that is no longer valid
```kotlin
val table = UUIDTable("test_table")
val uuidList = listOf<UUID>()
table.selectAll().where { table.id inList uuidList }
```

**Comment by bog-walk** [comment]
@jeremyluinstra-RL An update in case you missed it:

Version 0.50.1 is available with the fix for this issue included.
