### ISSUE TITLE
IdTable should allow other types of ID's

### ISSUE THREAD

**Issue by apatrida** [JetBrains/Exposed#21]
We use GUID Id's generated by the application, but cannot use DAO because of this, without making it another value.  Some databases also support auto generated GUID's on the server-side.  Neither can work with IdTable as it is now.  Therefore cannot use DAO's

**Comment by Tapac** [comment]
Thank you for information. We will look how we can refactor idTable/EntityId to support any type of primary key instead of integer.

**Comment by Tapac** [comment]
We reworked IdTable to use typed ids. You may check IntEntity.kt for usage example.
