### ISSUE TITLE
Partition support

### ISSUE THREAD

**Issue by brezinajn** [JetBrains/Exposed#216]
Hi,
is it currently possible to create partitioned table via Exposed?
Thanks

**Comment by Tapac** [comment]
Not yet. You are the first who ask for that functionality. 
Usually, such operations (with very specific syntax) making manually with traditional plain sql queries.

**Comment by brezinajn** [comment]
I can see why. Although it would minimise number of cases "Here we have definition of our tables except for those three…". Anyway thanks. Closing the issue.

**Comment by Tapac** [comment]
As workaround you can inherit from Table and make your own implementation like (in very simple case):
```Kotlin
open class PartitionTable(name: String, val partitionBy: List<Column<*>>) : Table(name) {
    override fun createStatement(): List<String> {
        return super.createStatement() +
                " PARTITION BY LIST ${partitionBy.joinToString(prefix = "COLUMNS(", postfix = ")") { it.name }}" 
    }
}
```

**Comment by brezinajn** [comment]
Thanks. This will definetly help.
