### ISSUE TITLE
Provide VendorDialect for mocking database

### ISSUE THREAD

**Issue by KolesnichenkoDS** [JetBrains/Exposed#217]
Providing a new vendor dialect that will just save data locally (e.g. in a hashmap) will simplify mocking database for testing.

**Comment by KolesnichenkoDS** [comment]
Or maybe you can open (remove `internal` keyword) some classes/interfaces (like `VendorDialect`) - thus one will be able to write his own provider (for new database type or for mocking database as I said before)

**Comment by Tapac** [comment]
There is `DatabaseDialect` interface, you can mock it and register with `Database.registerDialect()`

**Comment by KolesnichenkoDS** [comment]
Thanks for the queck response. That's what I need, so I'm closing the issue.

**Comment by oshai** [comment]
I think it can be nice to have such an implementation in order to easily understand what is the sql that will be executed (for testing and tutorials)

**Comment by Tapac** [comment]
@oshai , about which implementation do you talk?

**Comment by oshai** [comment]
like a mock DB (in memory) so when for example you add
 ` transaction {  
    // print sql to std-out  
    logger.addLogger(StdOutSqlLogger)  
  } `
you will see the sql that is going to run later in production.

**Comment by Tapac** [comment]
@oshai, I'm not sure that it will help without real data when you select something and then use result in next query. h2 database already works in memory (with proper url), so it's worth to use it + logger if you want to view SQL. 
One problem is that you will see SQL from h2 dialect which will surely differ in DDL (and some DML)

**Comment by oshai** [comment]
@Tapac ok I get what you mean. I will think about it a little more. generally what might help is a tool to translate dsl into sql so I guess that what I means. I will think of a way to achieve that.

**Comment by Tapac** [comment]
You always can use something like this:
```Kotlin
val query = FooTable.selectAll()
val sql = query.prepareSQL(QueryBuilder(false)) // true if you want to see ? placeholders instead of real values
```

**Comment by oshai** [comment]
@Tapac what I am trying to avoid here is the need for connection to database (and the need to configure one)

**Comment by Tapac** [comment]
Query requires database metadata to know about keywords to escape, which case (upper/lower/mix) to use for identifiers (tables/columns). Possibly it also can be mocked.
