### ISSUE TITLE
varchar limit seems too short.

### ISSUE THREAD

**Issue by divinespear** [JetBrains/Exposed#218]
(first, excuse my bad english...)

in `StringColumnType`, max length of `varchar` is limited up to 255, but it seems to short.
most RDBMS support more then 255 bytes/chars, Oracle is smallest support but it's 4000.

IMHO, limit of varchar is different by DBMS, so can define it to (or handle it at) `VendorDialect`...

(I found [interesting article](http://www.vertabelo.com/blog/technical-articles/comparing-char-and-varchar-data-types-in-different-database-engines) while I writing this.)

**Comment by Tapac** [comment]
Already fixed #205, will be available with next release.
