### ISSUE TITLE
Creating tables with the same name in different schemas not possible

### ISSUE THREAD

**Issue by siksniraps** [JetBrains/Exposed#219]
When creating tables the current connection schema is not taken in account when the existance of tables is checked.

```
    transaction {
        connection.schema = "schema1"
        create(UsersTable)
        connection.schema = "schema2"
        create(usersTable)
    }
````
The seccond table in schema2 will not be created.

The issue could be fixed by passing the current schema when checking if table exists.

Default.kt
```
    override fun allTablesNames(): List<String> {
        val result = ArrayList<String>()
        val tr = TransactionManager.current()
        val resultSet = tr.db.metadata.getTables(null, tr.connection.schema, "%", arrayOf("TABLE"))

        while (resultSet.next()) {
            result.add(resultSet.getString("TABLE_NAME").inProperCase)
        }
        return result
    }
```

**Comment by Kabbura** [comment]
I think this is the same as https://github.com/JetBrains/Exposed/issues/171
Try MySQL Connector/J version 5.X. Let us know if you it still occurs.
