### ISSUE TITLE
Select with a list of where clauses

### ISSUE THREAD

**Issue by ChFlick** [JetBrains/Exposed#222]
Hello,

is there a way to have an "optional" where clause that are only executed if the clause is not empty, or maybe a way to select by a list of where clauses?

There could even be a language-feature for that but I haven't found something appropriate.

My problem is the following: I've got a function with optional parameters that should only be used if they are present.
Currently I've got something like this, but it's going to explode if I introduce more parameters.
```kotlin
fun getSomethingBySomeParameters(name: String?, place: String?){
    val nameClause = SomeTable.name eq name
    val placeClause = SomeTable.place eq place
    val where = if (!name.isNullOrEmpty() && !place.isNullOrEmpty())
        nameClause and placeClause
    else if (!name.isNullOrEmpty())
        nameClause
    else
        placeClause

    SomeTable.select(where)....
}
```

I appreciate all help given.

Thanks and greetings

**Comment by oshai** [comment]
how about using it mixed with an always true predicate:
`var where = someTruePredicate
 if (!name.isNullOrEmpty()) where = where and nameClause 
if (!place.isNullOrEmpty())) where = where and placeClause 
`

**Comment by ChFlick** [comment]
thanks for the response, that's going to work for me.
In the meantime I found out that the approach
```kotlin
val nameClause = SomeTable.name eq name or booleanParam(name.isNullOrEmpty())
```
also works, but your solution is even nicer

**Comment by Tapac** [comment]
@ChFlick 
, there is `Query.adjustWhere` function, which allows modifying existing condition. 
I think that in your case you may use:
```Kotlin 
SomeTable.select {
   if (!name.isNullOrEmpty()) {
      SomeTable.name eq name
   }
   if (!place.isNullOrEmpty()) {
      adjustWhere {
          this?.and(SomeTable.place eq place) ?: SomeTable.place eq place 
      }
   }
}
```

I think we will short form for add and or functions, something like:
```Kotlin
fun Query.addAnd(op: Op<Boolean>) : Query = adjustWhere { this?.and(op) ?: op }

SomeTable.select {
   if (!name.isNullOrEmpty()) {
      SomeTable.name eq name
   }
   if (!place.isNullOrEmpty()) {
      addAnd(SomeTable.place eq place)
   }
}
```
