### ISSUE TITLE
Support TIME data type

### ISSUE THREAD

**Issue by lnhrdt** [JetBrains/Exposed#224]
Exposed supports `date` and `datetime` types in table definitions (both using a DATETIME SQL type) but does not yet support a `time` type (no date component). Support for a `time` type could also use the DATETIME SQL type or could leverage the TIME SQL type.

https://dev.mysql.com/doc/refman/5.7/en/time.html
https://www.postgresql.org/docs/8.2/static/datatype-datetime.html#AEN4733

**Comment by Decoydoll** [comment]
Let me work on this

**Comment by abishai** [comment]
I need time datatype as well. What is the best workaround at the moment? Use LocalDateTime and discard date part ? Or maybe number of seconds since day start?
