### ISSUE TITLE
MariaDB Connector/J 2.2.1 does no longer work

### ISSUE THREAD

**Issue by AndreasVolkmann** [JetBrains/Exposed#225]
Exposed no longer works with MariaDB Connector 2.2.1.

I compared with 2.2.0, where everything works as expected. 

Even though my url is `jdbc:mysql://localhost/`, the url in the `transaction` block reads `jdbc:mariadb://address...`. 

The connect call succeeds:
`Database.connect(url = url, driver = driver, user = username, password = password)`
or `Database.connect(ds)`

But the first transaction fails:
```
transaction {
    println(db.url)
    SchemaUtils.create(table)
}
```

**Comment by divinespear** [comment]
Here is dirty workaround:
```
Database.registerDialect("mariadb") {
  @Suppress("UNCHECKED_CAST")
  val type = (Class.forName("org.jetbrains.exposed.sql.vendors.MysqlDialect") as Class<DatabaseDialect>).kotlin
  type.createInstance()
}
```

It's safe to use cause MariaDB has (mostly) same dialect as MySQL.

**Comment by goreRatzete** [comment]
Thanks, that works 👍
