### ISSUE TITLE
Support complex order by statements

### ISSUE THREAD

**Issue by maxim5** [JetBrains/Exposed#227]
For instance, I'd like to query `order by case when`:

```sql
SELECT ...
ORDER BY CASE
         WHEN till IS NOT NULL THEN till
         ELSE since
         END
```

... which is supported by MySQL, PSQL, MS SQL. And currently I can do it only with "exec raw sql" workaround.

Example use case: https://stackoverflow.com/q/29600737/712995

**Comment by maxim5** [comment]
@Tapac thanks! How can I write the whole `ordery by case when ... end` query in Exposed?

**Comment by Tapac** [comment]
These changes are not released yet, but there was `Query.orderBy(expression, boolean)` function which allowed to provide expression to order by part.
You may try:
```Kotlin
 val case = Expression.build { case().When(Table.till.isNotNull(), Table.till).Else (Table.since)
Table.selectAll().orderBy(case, true).toList()
```
Or 
```Kotlin
Table.selectAll().orderBy(Coalesce(Table.till, Table,since), true).toList()
```
