### ISSUE TITLE
Paging on Oracle 12 still generates invalid query

### ISSUE THREAD

**Issue by Petitt88** [JetBrains/Exposed#229]
I've just tested the paging on Oracle in the current (0.9.2) snapshot release but it is still not good.

If the ```limit``` function has both the offset and n values set the query is still invalid.

Currenty it looks like this: 
```sql
SELECT ...
FROM table
OFFSET 20 FETCH FIRST 20 ROWS ONLY
```

However, it should be like this:
```sql
SELECT ...
FROM table
OFFSET 20 ROWS FETCH FIRST 20 ROWS ONLY;
```
So the ```ROWS``` keyword is missing before ```FETCH```.

**Comment by Tapac** [comment]
Thank you for the report, I think that `{ROW | ROWS}` part of `OFFSET.. FETCH` syntax is optional

Caused by: #210

**Comment by lukaseder** [comment]
For the record:

![image](https://user-images.githubusercontent.com/734593/34832339-f0662c08-f6e9-11e7-8678-ef9bb732bc3b.png)

https://docs.oracle.com/database/121/SQLRF/statements_10002.htm#SQLRF01702

Back to lurking :-)
