### ISSUE TITLE
Table 'Project' can't be created

### ISSUE THREAD

**Issue by Suntrie** [JetBrains/Exposed#238]
After execution of this piece of code table wasn't created (and execution wasn't logged):

`object Project : Table() {
    var id = integer("id").primaryKey()
}

fun main(args: Array<String>) {

    val jdbc = "jdbc:mysql://127.0.0.1:3306/awesome_database?serverTimezone=UTC"
    val driver = "com.mysql.cj.jdbc.Driver"

    val connection = Database.connect(jdbc, user = "root", password = "***", driver = driver)

    transaction {
        logger.addLogger(StdOutSqlLogger)
            SchemaUtils.create(Project)}

}`

**Comment by Tapac** [comment]
As I can see you use Connector/J v.8. Currently Exposed was tested only with v.5 version. Also, MySQL 8 was never tested with Exposed.

Could you test same code but with https://dev.mysql.com/downloads/connector/j/ v.5.1 ?

**Comment by Kabbura** [comment]
I had the exact same problem. Exposed did not create the table when another table exist in a different db with the same name. I tried with 
'mysql:mysql-connector-java:6.0.6' and  'mysql:mysql-connector-java:8.0.11'
I can confirm that it worked when I switched to
'mysql:mysql-connector-java:5.1.46'

**Comment by Tapac** [comment]
@Kabbura , @Suntrie , could you please check this issue with the latest Exposed version as it might be fixed in #339 ?
