### ISSUE TITLE
Composite unique constraint

### ISSUE THREAD

**Issue by quangIO** [JetBrains/Exposed#239]
Can we do something like this with Exposed?
```
CREATE TABLE someTable (
    id serial primary key,
    col1 int NOT NULL,
    col2 int NOT NULL,
    unique (col1, col2)
)
```
or 
```
CREATE TABLE someTable (
    col1 int NOT NULL,
    col2 int NOT NULL,
    primary key (col1, col2)
)
```

**Comment by Tapac** [comment]
``` 
object SomeTable : Table() {
    val col1 = integer("col1").primaryKey(0) // case 2 - composite PK
    val col2 = integer("col2").primaryKey(1) // case 2 - composite PK
    init {
        index(true, col1, col2) // case 1 - Unique index
    }
}
```

}

**Comment by terancet** [comment]
@Tapac I didn't understand what does the following `.primaryKey(0) ` mean? Does index `0` stand for the column `col1`?

**Comment by Tapac** [comment]
@terancet , that means what `col1` will be the first column in a primary key.

**Comment by tentypwtk** [comment]
Given this is still advised solution for the problem, any suggestion how to handle DAO on such table (where two fields used are used as combined ID)?

**Comment by AdityaAnand1** [comment]
Highly recommend adding this to Wiki 😄
