### ISSUE TITLE
DAO lifecycle hooks

### ISSUE THREAD

**Issue by cha55son** [JetBrains/Exposed#240]
Similar to ActiveRecord's callbacks it would be great if there were official hooks into the lifecycle of the DAOs. http://guides.rubyonrails.org/active_record_callbacks.html#available-callbacks

Exposed could start with the following to meet ~80% of use-cases would be my guess:

* beforeSave
* afterSave
* beforeUpdate
* afterUpdate
* beforeDelete
* afterDelete

My specific use-case: I would like to add `created_at` and `updated_at` columns to my objects and have it managed at the DAO layer vs. having my controllers/services doing it.

**Comment by Tapac** [comment]
There is EntityHooks for that, but only on "after" persist to DB events:
```
EntityHook.subscribe {
   if (it.changeType == EntityChangeType.Created) {
      (it.toEntity() as? YourEntity)?.createdAt = DateTime.now()
   }
}
```

But for "created_at" I prefer to use default value on a column with the current timestamp.

**Comment by cha55son** [comment]
@Tapac thanks that helps. I found your other post with `ExtendedIntIdTable` and that was exactly what I was looking for. 

I wish there was a way to "add" the property before the entity is saved so an extra query isn't made. i.e. `EntityChangeType.BeforeUpdated` 

off-topic: I'm currently stuck on an issue that looks like a bug between exposed and sqlite regarding datetimes. Using the code above `(it.toEntity() as? YourEntity)?.createdAt = DateTime.now()` it's inserting `1518143928700` and throws an error whenever it tries to read the row. When I execute an INSERT directly in sqlite it generates `2018-02-05 02:41:52`. Am I doing something wrong or is this worth creating another ticket for?

**Comment by Tapac** [comment]
@cha55son , please file an issue with STR and exact exception. I'm working on refactoring date and time support in Exposed (#100) and I think that it nice to cover it with the tests which include timezone checks. 
Maybe it's your case - wrong datetime conversion before insert in SQLite.

**Comment by AlecBenzer** [comment]
Any update on this? Is there an open ticket?
