### ISSUE TITLE
Order by rand

### ISSUE THREAD

**Issue by brezinajn** [JetBrains/Exposed#241]
Is it currently possible to do `ORDER BY RAND()`?

**Comment by Tapac** [comment]
Already fixed in master #227 , will be released this or next week.
```
Table.selectAll().orderBy(Random())
```

**Comment by alexsteinerde** [comment]
Unfortunately this does not work with Kotlin >= 1.3. Could you please name a new solution for this issue?

**Comment by brezinajn** [comment]
Can you please specify what does not work for you? Cannot confirm right now, but I'm fairly sure it works. That or I have a HUGE bug in production :D

**Comment by alexsteinerde** [comment]
Oh, it was my fault. My IDE imported the wrong "Random()" class. 
When I import the "Exposed" Random class it works great.
Thank you for your reply.
