### ISSUE TITLE
MySql / MariaDb keyword not quoted

### ISSUE THREAD

**Issue by goreRatzete** [JetBrains/Exposed#242]
One of my tables looks like this: 
```
object TemplateFields : Table("template_fields") {
    val templateId = integer("template_id") references Templates.id
    val index = integer("index")
    val title = varchar("title", 255)
    val type = varchar("type", 255)
}
```

However the keyword `index` is not quoted and therefore throws an exception when I try to run the create script. 
`index` is a reserved keyword in both
* MariaDb (https://mariadb.com/kb/en/library/reserved-words/)
* MySql (https://dev.mysql.com/doc/refman/5.7/en/keywords.html)

When I run `Database.keywords`, `index` is not in the set. 

I tried adding the quotes manually, but then they are escaped by exposed.

**Comment by Tapac** [comment]
Which jdbc driver do you use (please provide link/config url to maven repo)?

**Comment by goreRatzete** [comment]
Here is a repo: https://github.com/goreRatzete/exposed-keywords

As can be seen in the build.gradle, I use `mariadb.jdbc @ 2.2.0`. 
The newer version doesn't work with exposed anymore, re my other issue: #225

**Comment by Tapac** [comment]
You should report to driver developers that they don't provide the full list of keywords in DatabaseMatadata:
https://github.com/MariaDB/mariadb-connector-j/blob/386819936ffad08d0ac213413c7a15c7b9a18dad/src/main/java/org/mariadb/jdbc/MariaDbDatabaseMetaData.java#L1064
As you can see the INDEX keyword is missing from that list.

**Comment by goreRatzete** [comment]
I thought so. Thanks, I will do that!
