### ISSUE TITLE
SQLite text column for datetime

### ISSUE THREAD

**Issue by cha55son** [JetBrains/Exposed#243]
I'm using SQLite and Liquibase to manage DB migrations. I've got a migration like the following:

```
<column name="updated_at" type="datetime">
    <constraints nullable="false"/>
</column>
```

which creates the following schema:

```
updated_at TEXT NOT NULL
```

I'm using a DAO following this pattern: https://github.com/JetBrains/Exposed/issues/89#issuecomment-276119664

and when it tries to read a timestamp from the TEXT column I get the following error:

[exposed-datetime-error.log](https://github.com/JetBrains/Exposed/files/1714804/exposed-datetime-error.log)

Interestingly I didn't see this issue in the unit tests of Exposed when I copied my code over locally. When I saved the sqlite DB to a file and looked at the schema I noticed Exposed was creating a `NUMERIC` column. When I update liquibase to `number` everything works as expected.

Per the [SQLite docs](https://www.sqlite.org/datatype3.html#date_and_time_datatype) datetime TEXT columns are valid. So it seems Exposed may need to be tweaked to support SQLite TEXT column datetimes. Let me know if I can provide any more info.

**Comment by Tapac** [comment]
I guess that problem is that you update a column with existing data in it.
So, as it was numeric column and you made it TEXT while all numbers just become strings, not a date representation of it. which is required: 
> TEXT as ISO8601 strings ("YYYY-MM-DD HH:MM:SS.SSS").
