### ISSUE TITLE
Sql Server createMissingTablesAndColumns: collation conflict

### ISSUE THREAD

**Issue by AndreasVolkmann** [JetBrains/Exposed#245]
Calling `SchemaUtils.createMissingTablesAndColumns` on a table results in
`SQLServerException: Cannot resolve the collation conflict between "Danish_Norwegian_CI_AS" and "Finnish_Swedish_CI_AS" in the equal to operation.`

Code:
```
fun main(args: Array<String>) {
    Database.connect(   ...    )

    transaction {
        SchemaUtils.createMissingTablesAndColumns(SomeTable) // throws
        SchemaUtils.create(SomeTable) // works
    }
    
}

object SomeTable : Table() {
    val column = varchar("inde_x", 10)
}
```

I guess the first collation is my local one. Is there any way to change this ?

**Comment by Tapac** [comment]
Could you provide the whole exception stacktrace?
Also, you can setup collation as the third parameter of varchar() function.
