### ISSUE TITLE
Nested queries

### ISSUE THREAD

**Issue by PaulMuriithi** [JetBrains/Exposed#248]
What is the best way to represent some nested query such as
```
SELECT t1.id, t1.name, t2.itemsCount
FROM Table1 t1
LEFT JOIN (
     SELECT
       Table2.foreignKey,
       COUNT(*) AS counted
     FROM Table2
     GROUP BY Table2.foreignKey
   ) t2 ON t1.id = t2.foreignKey
WHERE t1.userId = 2
```

**Comment by PaulMuriithi** [comment]
At the moment I have something like this but I am looking for a cleaner/more efficient way
```
val result = transaction {
        (Table1 leftJoin Table2)
                .slice(Table1.id, Table1.name)
                .select { Table1.user eq userId }
                .map {
                    ResponseObject(it[Table1.id].value, it[Table1.name],
                            Table2.select { Table2.foreignKey eq it[Table2.id] }.count())
                }
```

**Comment by Tapac** [comment]
You can use [alias](https://github.com/JetBrains/Exposed/wiki/DSL#alias) for an inner query. 
There is [the test](https://github.com/JetBrains/Exposed/blob/4360ae18c708072dfda261742e65b8b56a696adc/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DMLTests.kt#L1284) for the same case.

**Comment by oshai** [comment]
I added a link to here from FAQ: https://github.com/JetBrains/Exposed/wiki/FAQ#q-how-can-i-implement-nested-queries
