### ISSUE TITLE
Allow to perform queries outside a db.transaction{ } block

### ISSUE THREAD

**Issue by sdeleuze** [JetBrains/Exposed#25]
In [geospatial-messenger](https://github.com/sdeleuze/geospatial-messenger/), I am currently forced to `use db.transaction { }` (see [MessageRepository](https://github.com/sdeleuze/geospatial-messenger/blob/master/src/main/kotlin/io/spring/messenger/repository/MessageRepository.kt)).

It would be nice if Exposed could make it possible to support existing transaction management system like the one provided by Spring ([see this documentation](http://docs.spring.io/autorepo/docs/spring/4.2.x/spring-framework-reference/html/transaction.html) and [DataSourceTransactionManager Javadoc](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/jdbc/datasource/DataSourceTransactionManager.html)).

Exposed could maybe allow to set the default db to use at `Table` level, delegate the transaction management to any kind of other mechanism and allow to perform queries with `Table.foo()` functions without a wrapping them into a `db.transaction{ }` block.

My goal is to be able, potentially with some extensions, to be able to annotate service functions with `@Transactional` and just rely on our regular JDBC based transaction management ([more details here](http://docs.spring.io/autorepo/docs/spring/4.2.x/spring-framework-reference/html/transaction.html#transaction-declarative-annotations)).

**Comment by AlexCzar** [comment]
+1

**Comment by Tapac** [comment]
Implemented [SpringTransactionManager](https://github.com/JetBrains/Exposed/blob/master/spring-transaction/src/main/kotlin/org/jetbrains/exposed/spring/SpringTransactionManager.kt) class (subclass of spring DataSourceTransactionManager).
Please look at [ExposedTransactionManagerTest.kt](https://github.com/JetBrains/Exposed/blob/master/spring-transaction/src/test/kotlin/org.jetbrains.exposed.spring/ExposedTransactionManagerTest.kt) for example and feel free to report any problems.

**Comment by sdeleuze** [comment]
Thanks for adding such support.

I tried to update Geospatial Messenger project but I got a blocking error: `IllegalStateException: Already value [org.jetbrains.exposed.sql.Transaction@3672276] for key [org.jetbrains.exposed.spring.SpringTransactionManager@255e5e2] bound to thread [main]`. Maybe there is something to fix in [SpringTransactionManager](https://github.com/JetBrains/Exposed/blob/master/spring-transaction/src/main/kotlin/org/jetbrains/exposed/spring/SpringTransactionManager.kt). See https://github.com/sdeleuze/geospatial-messenger/commit/transactional

Please also make sure that `spring-transaction` will be deployed with the right `groupId` and `version` since I had to tweak Exposed `build.gradle` to be able to use `org.jetbrains.exposed:spring-transaction:0.5.0-SNAPSHOT` dependency.

**Comment by dragossusi** [comment]
What about multiplatform?

**Comment by Tapac** [comment]
@dragossusi , how is it related to that issue?

**Comment by dragossusi** [comment]
> My goal is to be able, potentially with some extensions, to be able to annotate service functions with @Transactional and just rely on our regular JDBC based transaction management (more details here).

I thought he wants to use @Transactional with exposed methods

**Comment by Tapac** [comment]
Yes, it's possible with `spring-transaction` or `exposed-spring-boot` modules.
