### ISSUE TITLE
Name of constraints, indices, etc should be quoted (schema workaround)

### ISSUE THREAD

**Issue by NekoiNemo** [JetBrains/Exposed#254]
Since there is currently no proper schema support, a workaround is to just append schema name to table name:

```
object FileStorageTable : Table("$SYSTEM_SCHEMA_NAME.FileStorage"){

    val id = long("id").primaryKey().autoIncrement()
    val type = varchar("type", 32)
    val path = varchar("path", 256)
}
```

Which works fine and does create/query tables in proper schemas, but the issues occur with the creation of constraint, indices, etc. For example above code gets converted into following (postgres) sql:

```
CREATE TABLE IF NOT EXISTS "system".filestorage (
  id   BIGSERIAL   NOT NULL,
  type VARCHAR(32) NOT NULL,
  path TEXT        NOT NULL,
  CONSTRAINT pk_system.FileStorage PRIMARY KEY (id)
)
```

Which throws error about incorrect symbol '.' in the constraint name. However that does not happen if constraint name is quoted:

```
CREATE TABLE IF NOT EXISTS "system".filestorage (
  id   BIGSERIAL   NOT NULL,
  type VARCHAR(32) NOT NULL,
  path TEXT        NOT NULL,
  CONSTRAINT "pk_system.FileStorage" PRIMARY KEY (id)
)
```

Above is a perfectly valid scrip that creates table and, granted, awkwardly named, constraint.

I suggest using this method as a workaround until proper schema support is implemented.

**Comment by NekoiNemo** [comment]
For my own use i hacked together a dirty fix for this: https://github.com/NekoiNemo/Exposed/commit/653545b875d8c21cca283629d9ce17b0dbc97dda
But i'm not sure what potential side effects it might have.

**Comment by Tapac** [comment]
@NekoiNemo , thank you for reporting. I guess that we will support schemas in proper way someday, but anyway, I guess that schema shouldn't be included in index/constraint name. 

Will look into it issue soon.

**Comment by LoneEngineer** [comment]
Just want to add, one more example:

`object PhoneRequests : LongIdTable("\"auth\".\"phoneRequests\"") {
    val sessionId = text("sid").uniqueIndex()
....
`
well, I know, schema is not supported very well and case sensitive table names are bad, but I need to support legacy database. So if I use SchemaUtils.create(PhoneRequests,...) in tests  then I get following error:
`2020-03-25 22:53:34.564 DEBUG [main][][] Exposed - CREATE TABLE IF NOT EXISTS "auth"."phoneRequests" (id BIGSERIAL PRIMARY KEY, phone TEXT NOT NULL, sid TEXT NOT NULL, "confirmCode" TEXT NOT NULL, "appName" VARCHAR(64) NOT NULL, "osName" TEXT NOT NULL, "createTimestamp" TIMESTAMP NOT NULL, "validTill" TIMESTAMP NOT NULL)
2020-03-25 22:53:34.573 DEBUG [main][][] Exposed - CREATE INDEX phoneRequests_phone_idx ON "auth"."phoneRequests" (phone)
2020-03-25 22:53:34.574 INFO  [tc-okhttp-stream-2128859746][][] containers - STDERR: 2020-03-25 20:53:34.574 UTC [71] ERROR:  syntax error at or near "." at character 57
2020-03-25 22:53:34.575 INFO  [tc-okhttp-stream-2128859746][][] containers - STDERR: 2020-03-25 20:53:34.574 UTC [71] STATEMENT:  ALTER TABLE "auth"."phoneRequests" ADD CONSTRAINT "auth".""phoneRequests"_sid_unique" UNIQUE (sid)
2020-03-25 22:53:34.615 DEBUG [main][][] Exposed - ALTER TABLE "auth"."phoneRequests" ADD CONSTRAINT "auth".""phoneRequests"_sid_unique" UNIQUE (sid)`

Same for PostgreSQL and H2.

**Comment by Tapac** [comment]
Scheme support will be available in the next release.

**Comment by LoneEngineer** [comment]
Thanks @Tapac for great news.
