### ISSUE TITLE
Order by String case insensitive

### ISSUE THREAD

**Issue by glureau** [JetBrains/Exposed#26]
Is there a way to order by on a text field in case insensitive?
In SQL I know 2 ways:
SELECT * FROM xxxxxx ORDER BY LOWER(yyyy)
SELECT * FROM xxxxxx ORDER BY yyyy COLLATE NOCASE
I would avoid to write plain SQL but I didn't find a dedicated method in this library, so if you have any workaround with the current version, I'm interested.

If it's not present in the library, maybe this ticket can be a good feature to add?

**Comment by shafirov** [comment]
Added .ucase() and .lcase() functions for Expression<String>
