### ISSUE TITLE
How to compare two columns of the database

### ISSUE THREAD

**Issue by msrd0** [JetBrains/Exposed#263]
Consider I have a DAO with two properties, both of type Integer. Now, how can I write a query like the following:

```kotlin
Table.find { Tables.foo neq Tables.bar }
```

The above throws an exception as exposed tries to convert `Tables.bar` to an integer which obviously does not work.

**Comment by Tapac** [comment]
There is missed `infix` modifier on `neq` condition. You can use it as
`Table.find { Tables.foo.neq(Tables.bar) }` prior we release a fix.

**Comment by Tapac** [comment]
Fixed in master.

**Comment by Tapac** [comment]
Released in #0.10.2
