### ISSUE TITLE
Insufficient escaping for MySQL in default settings

### ISSUE THREAD

**Issue by spand** [JetBrains/Exposed#264]
MySQL will by default allow backslashes for escaping. See: https://dev.mysql.com/doc/refman/5.7/en/string-literals.html#character-escape-sequences

This means that currently whenever Exposed is not configured to use prepared statements it will generate SQL strings that with the possibility of unescaped input. This can be disabled with https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_no_backslash_escapes but it sucks be vulnerable by default.

Perhaps the MySQL dialect should probe the server/connection for the settings and adjust escaping accordingly ?

**Comment by Tapac** [comment]
Nice point. 
Main problem is that different DBMS has different escape syntax/requirements. There is [OWASP](https://www.owasp.org/index.php/SQL_Injection_Prevention_Cheat_Sheet) implementation for Oracle and Mysql, but I don't really want to add that dependency to Exposed.

I think that the best way is to use some function from the drivers, but not sure that all of them provide public `escape` function (e.g. there are StringUtils and EscapeProcessor classes in mysql jdbc).

But for that, we at first need to split Exposed into per-dialect modules with driver dependency.

**Comment by oshai** [comment]
Is it possible to use prepared statements?

בתאריך 6 במרץ 2018 12:33,‏ "Andrey.Tarashevskiy" <notifications@github.com>
כתב:

**Comment by Tapac** [comment]
Exposed uses PreparedStatement, but also escapes a string values before sets it to a statement. Besides, there are some places (like stringLiteral) where string will be placed at SQL in-line what can cause SQL-injection if not escaped properly.

**Comment by julKali** [comment]
I believe this issue does not get the attention it deserves. I just realized that my application had a huge SQL injection attack surface because my SQL library from 2020 does not properly escape parameters. This is a 2000s security issue. If my current project wouldn't be a pet project, I would immediately switch off Exposed and go for Spring Data or similar.
I think you guys did a really good job, in general. However, you also bear the responsability of providing a solid framework for all the developers that put their trust in you. By neglecting such a huge issue, you undermine this trust. I would hope to see this issue fixed as soon as possible to make this library fit for production.

**Comment by spand** [comment]
> I believe this issue does not get the attention it deserves. I just realized that my application had a huge SQL injection attack surface because my SQL library from 2020 does not properly escape parameters.

Could you be a bit more explicit here? Does your project not use PreparedStatements ?

**Comment by julKali** [comment]
No, I noticed the missing escaping when I tried something like
`Example.column like "previews\\"`
where building the query would result in
```Example.`column` LIKE 'previews\'```
which escapes the trailing `'`, essentially destroying the whole statement.

**Comment by spand** [comment]
> No, I noticed the missing escaping when I tried something like
> `Example.column like "previews\\"`
> where building the query would result in
> `` Example.`column` LIKE 'previews\' ``
> which escapes the trailing `'`, essentially destroying the whole statement.

@julKali Could you share some code using Exposed that generates that ?

**Comment by julKali** [comment]
Here you go. I tried to keep it as simple as possible while staying as close as possible to my actual project.
Please note that while this example uses Java 8 I use Java 11 in my project. However, it makes no difference in this case.

Main.kt
```
import org.jetbrains.exposed.dao.id.IntIdTable
import org.jetbrains.exposed.sql.*
import org.jetbrains.exposed.sql.transactions.transaction

fun connectToDatabase() {
    val url = "jdbc:mysql://localhost:3306/test?serverTimezone=Europe/Berlin"
    val driver = "com.mysql.cj.jdbc.Driver"
    val user = "root"
    val password = ""

    Database.connect(url, driver, user, password)
}

object Examples : IntIdTable() {
    val test: Column<String> = varchar("test", 256)
}

fun main(args: Array<String>) {
    connectToDatabase()
    val sampleValue = "previews\\example.png"
    val result = transaction {
        SchemaUtils.create(Examples)
        Examples.deleteAll()
        Examples.insert {
            it[test] = sampleValue
        }
        Examples.selectAll().andWhere {
            Examples.test like "previews\\"
        }.toList()
    }
    assert(result.size == 1)
    assert(result.single()[Examples.test] == sampleValue)
}
```

build.gradle
```
plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '1.3.72'
}

group 'org.example'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenLocal()
    jcenter()
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile "org.jetbrains.exposed:exposed-core:$exposed_version"
    compile "org.jetbrains.exposed:exposed-dao:$exposed_version"
    compile "org.jetbrains.exposed:exposed-jdbc:$exposed_version"
    implementation "mysql:mysql-connector-java:8.0.19"
    compile group: 'org.slf4j', name: 'slf4j-simple', version: '1.7.30'
}

compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
compileTestKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
```

build.properties
```
kotlin.code.style=official
exposed_version=0.24.1
```

This is the debug log from running this application:
```
[main] DEBUG Exposed - DELETE FROM examples
[main] DEBUG Exposed - INSERT INTO examples (test) VALUES ('previews\example.png')
[main] DEBUG Exposed - SELECT examples.id, examples.test FROM examples WHERE examples.test LIKE 'previews\'
Exception in thread "main" java.lang.AssertionError: Assertion failed
	at MainKt.main(Main.kt:31)
```

**Comment by spand** [comment]
It is correct that the DEBUG log is incorrect but its not what is being sent to the server afaik.

I think your assertion error is because you have forgotten the wildcard % ie.: `Examples.test like "previews\\%"`

**Comment by julKali** [comment]
You are right, I forgot the `%`, so it makes sense to not find anything.
This code works:
```kt
// ...
val sampleValue = "parent\\previews\\"
val result = transaction {
    SchemaUtils.create(Examples)
    Examples.deleteAll()
    Examples.insert {
        it[test] = sampleValue
    }
    Examples.selectAll().andWhere {
        Examples.test like "%previews\\"
    }.toList()
}
// ...
```

So the real issue is incorrect DEBUG log? Why is that?

**Comment by spand** [comment]
I am a bit burned out for today but I think you could say its because the sql dialect used in the log doesnt have \ as an escape character.

That is also what this is issue is about. The escaping in exposed in incorrect but its not a "big issue" currently because it will always use PreparedStatement which sidesteps this issue by not relying on escaping. Obviously this is a bit of a landmine since its just waiting for someone to mess up.

**Comment by julKali** [comment]
I just tried the following, which is the original example with a `%` added to the LIKE pattern.
```kt
connectToDatabase()
    val sampleValue = "previews\\example.png"
    val result = transaction {
        SchemaUtils.create(Examples)
        Examples.deleteAll()
        Examples.insert {
            it[test] = sampleValue
        }
        Examples.selectAll().andWhere {
            Examples.test like "previews\\%"
        }.toList()
    }
    assert(result.size == 1)
    assert(result.single()[Examples.test] == sampleValue)
```
It still fails:
```
[main] DEBUG Exposed - DELETE FROM examples
[main] DEBUG Exposed - INSERT INTO examples (test) VALUES ('previews\example.png')
[main] DEBUG Exposed - SELECT examples.id, examples.test FROM examples WHERE examples.test LIKE 'previews\%'
Exception in thread "main" java.lang.AssertionError: Assertion failed
	at MainKt.main(Main.kt:31)
```

This is consistent with my project where I see the same behavior. I see your point now that it is not a security issue as it just looks like one through the logger. But it essentially looks for a string starting with "previews%" and thus ends up with the wrong query. I guess this is what this issue is about ...
I will use this workaround for now:

```kt
// see https://dev.mysql.com/doc/refman/5.7/en/string-literals.html
// and https://github.com/JetBrains/Exposed/issues/264
private fun String.escapeRemainingSqlCharacters(): String = replace("\\", "\\\\")
    .replace("%", "\\%")
    .replace("_", "\\_")
```

Now please get some time off :)

**Comment by Tapac** [comment]
@spand, thank you for a help here:)

@julKali, as @spand mentioned what you see in debug log is not the exactly what will be executed. 
In _DEBUG_ log you just see a statement with inlined placeholders. It made to help you _debug_ your code, otherwise it should look like:
`SELECT examples.id, examples.test FROM examples WHERE examples.test LIKE ?`
