### ISSUE TITLE
Mark fields as mandatory in query

### ISSUE THREAD

**Issue by maxim5** [JetBrains/Exposed#265]
There are fields that one always has to pay attention to in *all queries*. One particular example is `deleted`. Typical story: after an entity is marked with `deleted=true`, it should not be visible anywhere, except specially chosen places. Any query that *does not* set `deleted` explicitly in `where` (either `true` or `false`) is highly likely a bug. In some cases, when there is a chance of private data exposure, the cost of this bug is huge, higher than 503 response.

Since Exposed controls all fields, it could assist in controlling this field. It could work like this:
- a field and a table get annotated;
- all queries to this table that do not specify this field issue a warning or even an error in runtime;
- it's not a big deal if the warning is false positive in complex queries, if it could be suppressed per-query.

**Comment by Tapac** [comment]
I'm not sure that this is a very common case and that it's worth special syntax/mechanic. 
There is StatementInterceptor already and I think that you can cover your case with it. Something like this:
```kotlin
object SafeInterceptor : StatementInterceptor {
    override fun beforeExecution(transaction: Transaction, context: StatementContext) {
        (context.statement as? Query)?.let { q ->
            if (q.targets.contains(FooTable) )
                q.adjustWhere { this?.and (FooTable.deleted eq false) ?: FooTable.deleted eq false }
        }
    }

    override fun afterExecution(transaction: Transaction, contexts: List<StatementContext>, executedStatement: PreparedStatement) {
        
    }

}

fun safeTransaction(body: Transaction.() -> Unit ) {
    transaction { 
        monitor.register(SafeInterceptor)
        body()
    }
}
```

**Comment by raderio** [comment]
@Tapac does it work also on `JOIN`? `JOIN` should only work if deteled="false"

**Comment by Tapac** [comment]
@raderio , all tables used in `join` will be available in `targets`.

**Comment by bog-walk** [comment]
Please consider reopening this issue on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763) if the problem requires more answers or if the suggested use of `StatementInterceptor` requires more explanation.
