### ISSUE TITLE
DAO access foreign key?

### ISSUE THREAD

**Issue by Togrias** [JetBrains/Exposed#267]
Is there any way to access the foreign key of some relation on the DAO, for example Book.authorId without making a database call?

My main motivation is batching. Let's say, Author wrote many Books, and Reader reads many Books. If I want to query Reader -> Get all authors of the books I read, I want to send at most 2 database queries:

reader.books -> Return a list of all books I've read
books.forEach{ it.AuthorId.let {store in some List} } <--- it.AuthorId is the feature I'm looking for.
Authors.find { Author.id.value inList List }

**Comment by Tapac** [comment]
You just need to map id field instead of relation and use it:
```
class Book : IntEntity() {
   val authorId by BookTable.authorId
}

val authors = Authors.forEntityIds(reader.books.map { it.authorId } )
```
