### ISSUE TITLE
set default value to null

### ISSUE THREAD

**Issue by coolemza** [JetBrains/Exposed#274]
Is it possible to set dafault value for table column to null? in case it nullable() ana didnt set in batchInsert it throws: 
java.sql.BatchUpdateException: Field 'cross_id' doesn't have a default value

**Comment by Tapac** [comment]
Which database do you use?

**Comment by coolemza** [comment]
Mysql

**Comment by Tapac** [comment]
Sounds strange, are you sure that column in database has NULL in definition? 
If that's so, please provide short sample how to reproduce it.

**Comment by coolemza** [comment]
It was my mistake, it worked fine, a bit strange that BatchInsert() returns list of BigInteger as insert id list, even when primary key is Int, like:
val id = integer("id").autoIncrement().primaryKey()
