### ISSUE TITLE
java.lang.ClassNotFoundException: org.h2.Driver

### ISSUE THREAD

**Issue by DinuNcl** [JetBrains/Exposed#278]
Hello, 

I get this error. What can I do about it?
java.lang.ClassNotFoundException: org.h2.Driver
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.h2.Driver" on path: DexPathList[[zip...
Thank you.

**Comment by Tapac** [comment]
Add `compile 'com.h2database:h2:1.4.196'` to your build.gradle dependencies

**Comment by DinuNcl** [comment]
It worked. Thank you. But how can I make a local permanent db. This way jdbc:h2:mem:test the db is just in the memory.

**Comment by DinuNcl** [comment]
Is this the correct way?
 "jdbc:h2:file:~$path/test"
path = context.filesDir.absolutePath

**Comment by Tapac** [comment]
@DinuNcl , please look at examples on h2 official reference : http://h2database.com/html/cheatSheet.html
