### ISSUE TITLE
MySql BatchInsert returns BigInteger

### ISSUE THREAD

**Issue by coolemza** [JetBrains/Exposed#280]
BatchInsert on MySql db returns list of BigInteger as list of insert id's, even when primary key id is integer, h2:mem:test, returns list of integer in this case

**Comment by xJoeWoo** [comment]
I met this issue today as well.  Here was my trace to this issue:

1. In `batchInsert()` method, `result` uses `generatedKey` from `BatchInsertStatement`
https://github.com/JetBrains/Exposed/blob/7569ad81ce41eddf203569f8e1e9b16dfbc3cebd/src/main/kotlin/org/jetbrains/exposed/sql/Queries.kt#L91

2. `generatedKey` references to `resultedValues` from `InsertStatement`
https://github.com/JetBrains/Exposed/blob/75bd4740c9c8daa5b00e21d2b10d93f27234d6f3/src/main/kotlin/org/jetbrains/exposed/sql/statements/BatchInsertStatement.kt#L17-L18

3. `resultedValues` is assigned by `processResults()`
https://github.com/JetBrains/Exposed/blob/864e4fb7ecd06e8707492305c24d895dd9bea1f7/src/main/kotlin/org/jetbrains/exposed/sql/statements/InsertStatement.kt#L104

4. `processResults()` is reading results from `java.sql.ResultSet` by `getObject()`, which will return a `BigInteger` object ignoring `INT` or `LONG` type of column, then return `BigInteger` object to `batchInsert()` directly 
https://github.com/JetBrains/Exposed/blob/864e4fb7ecd06e8707492305c24d895dd9bea1f7/src/main/kotlin/org/jetbrains/exposed/sql/statements/InsertStatement.kt#L34
-----
Not like `insertAndGetId()` or `insertIgnoreAndGetId()` method, the generated result of `batchInsert()` from `ResultSet` is not processed by a column's `valueFromDB()`
https://github.com/JetBrains/Exposed/blob/85f2da27a0b7628ea57b956834c831b0b3fc8394/src/main/kotlin/org/jetbrains/exposed/sql/Queries.kt#L101-L105
https://github.com/JetBrains/Exposed/blob/85f2da27a0b7628ea57b956834c831b0b3fc8394/src/main/kotlin/org/jetbrains/exposed/sql/statements/InsertStatement.kt#L19-L20
-----
My opinion is adding column type handling to `batchInsert()` before return the result so the result's type is in consistent with `XXXAndGetId()` methods.

**Comment by Tapac** [comment]
Should be fixed in master since 0.12.1 (related issue #424)
