### ISSUE TITLE
Support entity references by non-ID column 

### ISSUE THREAD

**Issue by Tapac** [JetBrains/Exposed#282]
From slack channel:
Let’s say I have the following DAO (for MySQL):
```kotlin
object OrgMemberships : IntIdTable() {
    val userId = reference("user", Users.uid)
    val orgId = reference("org", Orgs.uid)
    val roleId = reference("role", Roles)
}

class OrgMembership(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<OrgMembership>(OrgMemberships)

    val userId by OrgMemberships.userId
    val orgId by OrgMemberships.orgId
    val roleId by OrgMemberships.roleId
    val user by User referencedOn OrgMemberships.userId
    val org by Org referencedOn OrgMemberships.orgId
    val role by Role referencedOn OrgMemberships.roleId
}
```

It’s a join on three underlying tables, Users, Orgs, and Roles. Here’s the DAO for Orgs:
```kotlin
object Orgs : IntIdTable() {
    val uid = varchar("uid", 36).uniqueIndex().entityId()
    val name = varchar("name", 256, collate = "utf8mb4_general_ci")
}

class Org(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<Org>(Orgs)

    var uid by Orgs.uid
    var name by Orgs.name
}
```
Rather than using the implicit Orgs id, I want to reference on the Orgs (and Users) uid, which is a unique string. What’s the proper syntax for defining OrgMembership in that case? IntelliJ complains that `val org by Org referencedOn OrgMemberships.orgId` has a type mismatch, where it expects a `Column<EntityId<Int>>` but gets a `Column<EntityId<String>>`. How do I tell OrgMembership to use that string?

**Comment by lnhrdt** [comment]
I'm also interested in this. My "memberships" tables don't even have an explicit ID:

```kotlin
object UsersCompaniesTable : Table("users_companies") {
    val user = reference("user", UserTable).primaryKey()
    val company = reference("company", CompanyTable).primaryKey()
    val role = enumerationByName("role", 255, CompanyRole::class.java)
}
```

and I've been trying to find a way to access that `role` column using DAOs.
