### ISSUE TITLE
UUID's are not shown in logs

### ISSUE THREAD

**Issue by chrisjenx** [JetBrains/Exposed#289]
Maybe it's my config, but UUID's show a memory reference instead of their string representation.
See this example:
```
16:48:11.589 [main] DEBUG Exposed - INSERT INTO EVENTOCCURRENCES (EVENT_ID, ID, "START") VALUES ([B@495b0487, [B@55dfcc6, 1524092400)
```

**Comment by Tapac** [comment]
Thank you for a report. Fixed in master
