### ISSUE TITLE
How to judge whether MySQL has a connection

### ISSUE THREAD

**Issue by AlphaFase** [JetBrains/Exposed#292]
How to judge whether MySQL has a connection

How to judge the connection of closing the SQLite

**Comment by Tapac** [comment]
What do you mean by that? 
You always can check : 
```
transaction {
  connection.isClosed
}
```

**Comment by AlphaFase** [comment]
How to turn off sqlite

**Comment by Tapac** [comment]
How you turn it in?

**Comment by AlphaFase** [comment]
db.isClose Why I can't find, I don't write the server, so I don't need a persistent connection. I just want to close the database when I'm done, because I have to handle multiple databases


My English is very bad, these words are translated by Google, I hope you can understand

**Comment by Tapac** [comment]
If you share your code, then maybe I can help you.

**Comment by Tapac** [comment]
First of all, you should check that .db file exists, then you can try something like:
``` 
val connected = try {
   db.metadata.databaseMajorVersion != null
} catch (e: Exception) {
  false
}
```

You shouldn't close `Database`, because it's just holder for a function to instantiate connection to DB.

**Comment by vbudilov** [comment]
That didn't work since it'll always be true. But it led me to try this, which should work, right? :)

                val connected =
                        transaction {
                            try {
                                !connection.isClosed
                            } catch (e: Exception) {
                                false
                            }
                        }

**Comment by Tapac** [comment]
@vbudilov , there is also `connection.isValid()` function.
