### ISSUE TITLE
README.md seems to be out of date

### ISSUE THREAD

**Issue by randombyte-developer** [JetBrains/Exposed#30]
The README.md suggests
``` kotlin
Database.connect(...)
transaction {
    create(table)
}
```

But `create()` is not available in `Transaction`.

Please update the README.md.

**Comment by gcscaglia** [comment]
`import org.jetbrains.exposed.sql.SchemaUtils.create`

But yeah, the DAO sample does not have that import, only the SQL DSL one.

**Comment by randombyte-developer** [comment]
Ah, thanks. I will use `SchemaUtils.create(...)`, that's more clear.
