### ISSUE TITLE
Varchar doesn't validate length

### ISSUE THREAD

**Issue by aria42** [JetBrains/Exposed#300]
The `VarCharColumnType` doesn't validate the length of the value to write to DB, since it doesn't override `StringColumnType::nonNullValueToString` and `error` if the string is too long for the length. I'm not sure what the general policy is on trying to throw errors here (especially since some vendors like sqlite3) don't enforce any of this. 

Is this something you'd like to check (and potentially disable for sqlite3 connections)? Would you welcome a PR.

**Comment by Tapac** [comment]
PRs are always very welcomed, but what kind of an expection are you going to throw? 
And also, should that exception be raised only on write to that column? 
What if a real column has more length than one which mapped in Exposed?

**Comment by aria42** [comment]
Yeah it should be when you try to make a DB valid value from `nonNullValueToString` since you can't make a valid value. I'm assuming the validation should be about the data supplied to the column data class, rather than whatever the "real" column length is. You can't do any validation if you assume the column could be arbitrarily different since the valid might be correct.
