### ISSUE TITLE
Can I chose FractionDateTime value?

### ISSUE THREAD

**Issue by letusfly85** [JetBrains/Exposed#301]
I'm using MySQL 5.7.
And I want to use `datetime` column and add default value to the column `current_timestamp`, however MySQL 5.7 doesn't support  following expression.

`column_name datetime(6) default current_timestamp(6)`

So, I want to choose `FractionDateTime` by some properties.
Is there any milestone for it?

https://github.com/JetBrains/Exposed/blob/master/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Mysql.kt#L9:L11

refs:
---

- https://dev.mysql.com/doc/refman/5.7/en/timestamp-initialization.html

**Comment by bog-walk** [comment]
@letusfly85 I can't seem to reproduce this using current version 0.41.1. I'm able to generate the expression you mentioned using:

```kt
val tester = object : Table("tester") {
    val stamp = datetime("stamp").defaultExpression(CurrentDateTime)
    // OR timestamp("stamp").defaultExpression(CurrentTimestamp())
}
// CREATE TABLE IF NOT EXISTS tester (stamp DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL)
```
and insert & select statements are working.

Exposed's [MySQL dialect](https://github.com/JetBrains/Exposed/blob/master/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Mysql.kt#L15) does now check `FractionDateTime` support for MySQL versions.

If I'm misunderstanding and the problem still persists, please consider reporting it on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763) with your current MySQL version and the specific date-time module dependency.
