### ISSUE TITLE
Can I use java.sql.Connection?

### ISSUE THREAD

**Issue by KenjiOhtsuka** [JetBrains/Exposed#303]
Can I use java.sql.Connection to connect the database?

like as follows

```
val connection = (java.sql.Connection instance)
Database.connect(connection)
```

**Comment by Tapac** [comment]
`Database.connect({ connection })`

**Comment by KenjiOhtsuka** [comment]
@Tapac Thank you

**Comment by andreas-mausch** [comment]
I've tried this, but the connection is closed by a transaction.

Debugging led me here: https://github.com/JetBrains/Exposed/blob/a0e5eb21754b1476c92fbfc1e76f858ab0d6713e/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/transactions/ThreadLocalTransactionManager.kt#L85

The connection should stay open, the TransactionManager shouldn't close a connection it hasn't established.

**Comment by Tapac** [comment]
@andreas-mausch it's not expected that you manage connections manually. 
What the use-case?

**Comment by andreas-mausch** [comment]
I experimented with some database migration tools and flyway provides a `java.sql.Connection` in their context object (see an example here: https://flywaydb.org/getstarted/java). And they expect the migration to not close the connection, which is reasonable.

This is related to #165.

If it's not possible to use the connection they provide, I think I cannot use flyway and will have a look at harmonica.
