### ISSUE TITLE
Better way to add different dialect functions

### ISSUE THREAD

**Issue by chrisjenx** [JetBrains/Exposed#304]
Not sure the best way of doing this, but as all the methods are internal when adding custom expressions and operators I have to resort to getting the vendor and use that:

```
class DayDiff<T : DateTime?, T2 : DateTime?>(private val start: Expression<T>, private val end: Expression<T2>) : Function<Int>(IntegerColumnType()) {
    override fun toSQL(queryBuilder: QueryBuilder): String {
        return when (TransactionManager.current().db.vendor.toLowerCase()) {
            "postgres" -> "DATE_PART(day, ${start.toSQL(queryBuilder)}, ${end.toSQL(queryBuilder)})"
            else -> "DATEDIFF(d, ${start.toSQL(queryBuilder)}, ${end.toSQL(queryBuilder)})"
        }
    }
}
```

Would be nice if there is a way to add custom dialects... (or we keep adding these to the base types)?
I can do a PR if you are happy to expand out the built in functions/expressions?

**Comment by Tapac** [comment]
After next release (0.10.4) all dialects will be open classes, so you can extend them if you need that.
Also, your example can be replaced as 
```kotlin
    when (TransactionManager.current().db.dialect) {
         is PostgreSQLDialect -> ...
    }
```

**Comment by chrisjenx** [comment]
Awesome, thanks for the update.
