### ISSUE TITLE
Obligatory reload of DAO with BLOB

### ISSUE THREAD

**Issue by Cydhra** [JetBrains/Exposed#310]
When loading a DAO from database (H2 in my case) in one transaction and accessing a BLOB in it in another transaction, the access fails because the BLOB is freed (org.h2.jdbc.JdbcSQLException: Object already closed). That is unless you explicitly reload the DAO:

```
val exampleDao = ExampleTable.reload(previousDao)!! 
exampleDao.someBlob.getBytes(1, 4)
```

Is that intended, because it seems very counter intuitive to the DAO concept which should abstract away the database from my data objects, shouldn't it?

**Comment by Tapac** [comment]
It can be too risky to make all blob fields eager even when you don't need to use their content.
But you can define your own "eagerBlob" and use it where you think it worth:
```kotlin
fun eagerBlob(name: String) : Column<Blob> = registerColumn(name, EagerBlobColumnType())
    
class EagerBlobColumnType(private val delegate : IColumnType = BlobColumnType()) : IColumnType by (delegate) {
    override fun valueFromDB(value: Any): Any {
        val result = delegate.valueFromDB(value) as Blob
        return result as? SerialBlob ?: SerialBlob(result)
    }
}
```
