### ISSUE TITLE
[Question] Creating auto incremented string

### ISSUE THREAD

**Issue by AllanWang** [JetBrains/Exposed#311]
I want to create a field that defaults to "Ticket $id", where id is essentially an auto incremented integer/long starting at 1. How to I go about adding that?

**Comment by Tapac** [comment]
You want to keep that "Ticket $id" in a database, or just entity field?
If first, then it's possible only with triggers or it will require 2 steps: insert an entity and then update nullable field.

**Comment by AllanWang** [comment]
I wasn't really acquainted with entities until yesterday, so I think a possible solution is to just same some integer that is auto incremented and use entities (or any retrieval) to prepend "Ticket". The point was to be able to create the value based on an incrementing integer supplied by the db
