### ISSUE TITLE
RxJava Support

### ISSUE THREAD

**Issue by MRezaNasirloo** [JetBrains/Exposed#326]
It would be nice to have RxJava support, maybe a wrapper at least.

**Comment by Tapac** [comment]
We don't plan to support RxJava. We want to support kotlin coroutines instead.

**Comment by MRezaNasirloo** [comment]
I'm talking about reactive streams, I don't see how coroutines would replace RxJava!

Why not have both?

**Comment by Tapac** [comment]
Could you provide any examples of what kind of support do you expect?

**Comment by fabriziofortino** [comment]
@Tapac @MRezaNasirloo 
I'd love to have something like that in Exposed.
In the past, I have worked with Slick (a Scala FRM) that supports async reactive operations http://slick.lightbend.com/doc/3.2.0/introduction.html#reactive-applications

This is pretty handy for data-intensive applications. Supporting back-pressure on read/write operations is not trivial from a developer point of view. If the library would support that it could open a number of new scenarios where Exposed could be used.

**Comment by GrishinSergey** [comment]
I know, that this thread is pretty old, but I have some use cases for rx java & Exposed orm:
- will be cool to subscribe to data, and, when something changed in table, receive update via rx observable,
- Flowable's back-pressure is cool, as for me also will be cool, to manage threads for database, like in rxJava (subscribeOn , observeOn) (ok, it's also possible via coroutines)

**Comment by BrianEstrada** [comment]
Supporting some way of subscribing to table changes would be fantastic whether it's RxJava or not

**Comment by MRezaNasirloo** [comment]
@BrianEstrada Yep at the time RxJava was still hot on the subject (pun intended), with the introduction of `kotlin.flow` I think it's easier more than ever to have something like that, nonetheless I'm closing this since it's not relevant anymore.
