### ISSUE TITLE
MySQL DateTime with org.joda.time

### ISSUE THREAD

**Issue by julianzelayeta** [JetBrains/Exposed#330]
I have a column in MySql of `datetime` type. When I'm getting local time in kotlin using `LocalDateTime.now()`, this datetime is not correctly persisted.
In example, `LocalDateTime.now()` returns something like this `2018-01-01T15:20:10`, that is wrongly persisted into MySql (the error is that time has an offset of hours), I'm pretty sure is the `T` character between date and time.

I've also managed to fix this declaring that column table (in exposed) as `String`, and in MySql that column still in `datetime` type. Writing into MySql now its working, but when I'm trying to read that date I'm getting (of course) an exception, that could not cast datetime to string.

**Comment by Tapac** [comment]
Could be fixed with changes to Java 8 Time Api and another fixes in 0.18.1
https://github.com/JetBrains/Exposed/wiki/LibDocumentation#exposed-0181-and-higher
