### ISSUE TITLE
sqlState is not working anymore for PostgreSQL

### ISSUE THREAD

**Issue by mobiletoly** [JetBrains/Exposed#331]
This code used to report sqlState correctly in version 0.10.2 for PostgreSQL database. Now it is broken in 0.10.3

       try {
            Listings.insert {
                it[Listings.id] = listing.id
                it[Listings.providerUserId] = listing.providerUserId
                ...
            }
        } catch (ex: ExposedSQLException) {
            throw when (ex.sqlState) {
                "23505" -> RequestedListingAlreadyExistsException(listingId = listing.id)
                else -> ex
            }
        }

in case when Listings.id violates a constraint (duplicate). Now ex.sqlState is always null (as well as ex.errorCode is 0).

**Comment by Tapac** [comment]
Now ExposedSQLException will delegate its sqlState and errorCode to an original exception if it was an instance of SQLException.
