### ISSUE TITLE
WIKI page seams out of date

### ISSUE THREAD

**Issue by C06A** [JetBrains/Exposed#333]
Examples on the page https://github.com/JetBrains/Exposed/wiki/Getting-Started shows `logger` which is deprecated in the latest version and `create(...)` method which was moved from `Transaction` to `SchemaUtils` class.

I don't know what else is out of date, but it is frustrating when samples of the code in the documentation are not working in the real project.

**Comment by Tapac** [comment]
Thank you for reporting. Wiki was updated and also short-cut `addLogger` function was introduced.
