### ISSUE TITLE
Inconsistent IColumnType.valueFromDB() implementations

### ISSUE THREAD

**Issue by plannigan** [JetBrains/Exposed#335]
None of the `IColumnType` methods are documented, so there is no guidance to how they should be implemented. As a result, there are a variety of strategies of how to convert the value to the expected type and what to do a value with an unexpected type.

The default implementation returns the value unchanged.

`CharacterColumnType`, `IntegerColumnType`, `LongColumnType`, `EnumerationColumnType`, `EnumerationNameColumnType`, `BlobColumnType`, `UUIDColumnType`:

- Throw an error if the value is an unexpected type.

`FloatColumnType`, `DecimalColumnType`:

- Calls the super implementation (which doesn't do anything), then if it can't convert to the correct type, it returns the value unchanged.

`DateColumnType`:

- Convert for a number of expected types. If the value is a String, convert if the dialect is SQLite, otherwise return value unchanged (Used to be parsed, but [this commit](https://github.com/JetBrains/Exposed/commit/9f4d77b14821716dbe780743b0e84c0e98c1c7b8#diff-3ef338089063e2c51d88c3b6ab3c177cL191) changed the behavior and it's not clear why.). Any other type, attempt to parse `value.toString()`.

`VarCharColumnType`, `TextColumnType`, `BinaryColumnType`:

- Convert if value is a single specific type, otherwise return value unchanged.

`BooleanColumnType`:

- For an unexpected type, try to convert`value.toString()`.

The interface methods should be documented so the expected behavior is explicitly stated. There should be a standard strategy to convert the value so they implementations can be consistent.

**Comment by joc-a** [comment]
Closing this as all `IColumnType` methods are now documented.
