### ISSUE TITLE
column "id" specified more than once

### ISSUE THREAD

**Issue by RDCynthia** [JetBrains/Exposed#336]
I have two tables A and B,and want to references B to A:

Table A:
```
object As: LongIdTable(){
    val b = long("b_id") references B.long("id")
}
class A(id: EntityID<Long>) : LongEntity(id){
    companion object : LongEntityClass<A>(As)
    var b by As.b
}
```

Table B:
```
object Bs: LongIdTable(){}
class B(id: EntityID<Long>) : LongEntity(id){
    companion object : LongEntityClass<B>(Bs)
}
```
When i run `create(A,B)`  or `createMissingTablesAndColumns(A,B)`,it will throw exception like:

```
column "id" specified more than once

``` 
Here is console SQL statement:
```
CREATE TABLE IF NOT EXISTS B (id BIGSERIAL PRIMARY KEY , id BIGINT NOT NULL)
```
Why there's two id column to create? Did i do something wrong or it doesn't support reference like this?Thanks for some help~

**Comment by Tapac** [comment]
Why you use such strange syntax: `references B.long("id")` ? It should be just `references B.id`.
`long("id")` function creates new long column with name "id".

**Comment by RDCynthia** [comment]
@Tapac I really really tried syntax `references Bs.id`, but IDE will give a compile period error:
(btw : there's no such parameter 'id' in class B, so can't B.id)

```
Type inference failed: Cannot infer type parameter T in 

fun <T, S : T, C : Column<S>> C.references
(
ref: Column<T>
)
: C
None of the following substitutions

receiver: Column<Long>
arguments:
(
Column<EntityID<Long>>
)

receiver: Column<Long>
arguments:
(
Column<Long>
)
can be applied to

receiver: Column<Long>
arguments:
(
Column<EntityID<Long>>
)
```
Seems like `references` need `Column<Long>` not `Column<EntityID<Long>>`.that's why i use `long(id)`
And when i use `long(id)` in middle table to use ManyToMany ,it works well:
```
object UserAuthorities : LongIdTable() {
    val user = long("user_id") references Users.long("id")
    val authority = long("authority_id") references Authorities.long("id")
}
```
That's strange...

**Comment by Tapac** [comment]
Sorry, I was not very attentive, you should use `references Bs.id`, because you create reference between tables, not entities.
