### ISSUE TITLE
Generating listOf of a given model based on ResultSet

### ISSUE THREAD

**Issue by bnlambert** [JetBrains/Exposed#338]
Hi,
Given the DSL query
`Cities.selectAll()` for example,

How can I generate a list of `City()` model based on the ResultRow list or ResultSet?
Just as `query.toList()`, is there a work around to accomplish `query.toModel`  ?

Thanks

**Comment by Tapac** [comment]
`Cities.selectAll().map { City.fromResultSet(it) }`

**Comment by bnlambert** [comment]
Than you very much for the prompt response. I currently get this error `Error:(xxx) Kotlin: Unresolved reference: fromResultSet`
Please how do i import it?
Thanks

**Comment by Tapac** [comment]
That was just an example, Exposed knows nothing about your model when you use DSL, so you should call a constuctor or another function which will create `City` object from ResultSet fields.
```
class City(name: String, region: String) 
Cities.selectAll().map { rs -> City(rs[Cities.name], rs[Cities.region]) }
```

**Comment by bnlambert** [comment]
Tapac! Thank you very much. You are life saver.
