### ISSUE TITLE
[PostgreSQL] Table with customEnumeration column doesn't work with Entity/DAO API 

### ISSUE THREAD

**Issue by panjiesw** [JetBrains/Exposed#340]
I have a table which uses PostgreSQL enum type. I followed the example in wiki in how to declare it in an Exposed table. I also created an entity class for the table. Something like this:

```kotlin
class PGEnum<T:Enum<T>>(enumTypeName: String, enumValue: T?) : PGobject() {
    init {
        value = enumValue?.name
        type = enumTypeName
    }
}

enum class Foo { Bar, Baz }

object EnumTable : LongIdTable("EnumTable") {
    val enumColumn = customEnumeration(
        "enumColumn", 
        "FooEnum", 
        { Foo.valueOf(it as String) }, 
        { PGEnum("FooEnum", it) }
    )
}

class EnumTableEntity(id: EntityID<Long>) : LongEntity(id) {
    companion object : LongEntityClass<EnumTableEntity>(EnumTable)

    val enumColumn by EnumTable.enumColumn
}
```

Using the entity, there is no problem in inserting new row:

```kotlin
EnumTableEntity.new { enumColumn = Foo.Bar }
```

But when I tried to query it, there is a cast exception something like `can't cast PGEnum to String` in `valueFromDB` function of `ColumnType`. 

```kotlin
EnumTableEntity.findById(1L) // cast exception
```

If I do an insert using DSL API and then querying it, it works as expected.
Any idea?

**Comment by bvjebin** [comment]
I am having same trouble with update using DAO.

```
val status: Column<Status> = customEnumeration(
            "status",
            "user_status",
            {value ->
                Status.valueOf(value.toString())},
            {it ->
                PGEnum("user_status", it)
            }).default(Status.ACCEPTED)
```

When I do `user.status = Status.valueOf(value as String)`, I am getting the following exception.

`java.lang.ClassCastException: com.me.commons.entities.PGEnum cannot be cast to java.lang.Enum`

Any help would be appreciated.

**Comment by Tapac** [comment]
@bvjebin, Which version of Exposed do you use?

**Comment by lavalamp-** [comment]
Getting this one too, version `0.17.7`
