### ISSUE TITLE
EntityHook subscription alerts firing bug

### ISSUE THREAD

**Issue by PaulMuriithi** [JetBrains/Exposed#341]
I have been using this model of setting and updating the dates records are created/updated using `EntityHook.subscribe ` for quite a while. I also answered this [issue](https://github.com/JetBrains/Exposed/issues/334) the same way but I have come to note that it has quite some issues.

I have made a [repo](https://github.com/PaulMuriithi/ExposedDatesAutoFill) for the tests I have run on the same. Kindly check particularly the last 2 tests - `testThatMultipleInsertsDoNotAffectPreviousRecordsDates` and `testThatInsertingOrUpdatingUsersDoesNotAffectRoles`

I am not sure whether it is a bug on the `EntityHook.subscribe` but will keep checking.

https://github.com/PaulMuriithi/ExposedDatesAutoFill

**Comment by rajansoft1** [comment]
@PaulMuriithi I  am new to Kotlin and Exposed, wanted to check if its possible to create a new Type say IdAutoDateTable , if we use that class to create our model it will take care of createdAt and updatedAt.

**Comment by PaulMuriithi** [comment]
I agree, that was one way to go about it but am looking into why it is not working ok.

**Comment by PaulMuriithi** [comment]
Resolved the issue.
