### ISSUE TITLE
referrersOn DAO performance?

### ISSUE THREAD

**Issue by Miclebrick** [JetBrains/Exposed#344]
In ORMs like ebean and hibernate, it's slow with many many's when loading the one if you have a onetomany because it creates an object for each one whenever you access it. Is this the case in Exposed when using DAO?

**Comment by Tapac** [comment]
All references loaded on demand. 
In your case, UserRatings instances will be created only when you call `film.ratings.forEach { ... }`
Real db request and instance creation happen when you start to iterate over a result.

**Comment by Miclebrick** [comment]
Ok, thanks
