### ISSUE TITLE
Calling Database.connect() replaces the global TransactionManager so running threads lose their thread-local transaction reference

### ISSUE THREAD

**Issue by DrFriendless** [JetBrains/Exposed#35]
Maybe I'm doing an odd thing, but this was a very confusing bug that Exposed seems to be vulnerable to. I'm writing a web server. On each request I call connect on org.jetbrains.exposed.sql.Database. That creates a new ThreadLocalTransactionManager and assigns it to TransactionManager.manager. This means that if I have 2 calls come in at the same time, the first gets a ThreadLocalTransactionManager with a ThreadLocal pointing to its Transaction. The second comes in and gets a second ThreadLocalTransactionManager with a ThreadLocal pointing at its Transaction. However when the first thread goes to find its Transaction it looks at TransactionManager.manager (which is the second ThreadLocalTransactionManager) and asks for the ThreadLocal value for its Transaction. However that's the wrong ThreadLocal, it really needs the one from the first ThreadLocalTransactionManager. So it gets null and Exposed thinks that thread has no transaction in progress which is wrong.

Although I can call Database.connect less often, I would expect your code would be better if the ThreadLocal inside ThreadLocalTransactionManager were inside a companion object. I've tried that and it solves my problem.

**Comment by Tapac** [comment]
Good point, and it's really looks like a bug, but you can (and it's way to go if you don't change a connection settings between invocations of Database.connect) call Database.connect just once and store it's result as lazy field. That prevents you from initializing TransactionManager on every request.

But we will look further how to handle reconnections properly.
