### ISSUE TITLE
UPDATE..RETURNING support

### ISSUE THREAD

**Issue by jonnyzzz** [JetBrains/Exposed#351]
It is possible to have updated rows back from a database. Let's support the syntax in Exposed too. Right now `UpdateStatement` return `Int` and thus isolates a possible `ResultSet`

Example reference from PostgreSQL
https://www.postgresql.org/docs/9.5/static/sql-update.html

**Comment by Tapac** [comment]
Are there other databases (besides PostgreSQL) which support returning affected rows with `UPDATE`?

**Comment by pedro-carneiro** [comment]
Oracle should [support it too](https://docs.oracle.com/cd/E11882_01/java.112/e16548/oraint.htm#JJDBC28176).

**Comment by swistaczek** [comment]
Hey, this is a very important feature for my project. Is there any chance of upstream support?

**Comment by CommanderTvis** [comment]
> Hey, this is a very important feature for my project. Is there any chance of upstream support?

Same

**Comment by pablo-silverback** [comment]
+1

**Comment by pablo-silverback** [comment]
+1

**Comment by pablo-silverback** [comment]
+1 (6 months later)

**Comment by emise** [comment]
+1!

**Comment by cpoyatos1** [comment]
+1

**Comment by vkopichenko** [comment]
There are some UPDATE RETURNING code snippets in this duplicate: https://github.com/JetBrains/Exposed/issues/1271.

**Comment by chskela** [comment]
+1

**Comment by cantaylancapraz** [comment]
+1
