### ISSUE TITLE
Composite key model setup

### ISSUE THREAD

**Issue by vbudilov** [JetBrains/Exposed#353]
I'm following the docs but can't figure out how to setup my models if my primary key is a composite. I'm not sure what my Companion class should be. 

Here's what I have: 

```
class Order(id: EntityID<String>) : Entity<String>(id) {
    companion object : EntityClass<Order>(Orders)

    var orderId by Orders.orderId
    var orderItemId by Orders.orderItemId
    var sku by Orders.sku
}
```

```
object Orders : Table("orders") {
    val orderId = varchar("order-id", 300).primaryKey()
    val orderItemId = varchar("order-item-id", 300).primaryKey()
    val sku = text("sku")
}
```

Any help is appreciated!

P.S. Using Orders without the entity instance Order works perfectly well.

**Comment by Tapac** [comment]
Entity classes can work only with IdTables which at the moment supports only one-column ids (https://github.com/JetBrains/Exposed/issues/43), you still can create IdTable with autoIncrement id and composite primaryKey

**Comment by vbudilov** [comment]
Thanks!
