### ISSUE TITLE
sqlState still not working anymore for PostgreSQL

### ISSUE THREAD

**Issue by mobiletoly** [JetBrains/Exposed#355]
This is related to a ticket that I opened previously and it was closed with a fix, but I just tried for 0.10.4
https://github.com/JetBrains/Exposed/issues/331

Same code I posted before, but sqlState still produces null

    val ktor0_1_14_State = ex.sqlState // null
    val sqlState = (ex.cause as? SQLException)?.sqlState // this returns valid state

**Comment by Tapac** [comment]
Ouch, the fix was committed to non-master branch and wasn't released in 0.10.4.
Sorry about that and thank you for your attention. I cherry-pick that commit and will release a new version soon.
