### ISSUE TITLE
Arithmetic functions -- are they implemented? 

### ISSUE THREAD

**Issue by vbudilov** [JetBrains/Exposed#357]
I'm trying to replicate my sql query but can't seem to find the right methods. Is this query possible? 

```
select sku, sum(amount) as amt_sum,  `order-item-code`, sum(`quantity-purchased`) as quantity_sum 
from settlements 
group by sku 
order by `quantity_sum` DESC
```
I can't find any docs on the arithmetic functions of Exposed, so maybe the docs are simply missing, instead of the functionality. 

Thanks in advance!

**Comment by Tapac** [comment]
https://github.com/JetBrains/Exposed/wiki/DSL#group-by
