### ISSUE TITLE
Any plan for stable version release?

### ISSUE THREAD

**Issue by mirromutth** [JetBrains/Exposed#359]
This DSL ORM is awesome, just like jOOQ or QueryDSL, and looks like better than them on Kotlin! Should I use this for my business projects? But I should wait for stable version release... emm, any plan for stable version release?

> Any plan for Async JDBC support after [ADBA](https://github.com/oracle/oracle-db-examples/tree/master/java/AoJ) released?

**Comment by Tapac** [comment]
@mirromutth , we have some roadmap before making a 1.0 release:
1. Rework date/time support to work with different providers (JodaTime/Java8 Time API/ThreeTen)
2. Rework to support coroutines 
3. Improve documentation
After that, we'll be ready to make an initial release.

If you afraid of Exposed stability than I can tell you that we in Jetbrains use it in production for more then 3 years.

We will look for ADBA when all main databases will support it.
