### ISSUE TITLE
Can we write a simple where condition `1 = 1`

### ISSUE THREAD

**Issue by letusfly85** [JetBrains/Exposed#361]
Hi, I want to execute such a query sometimes.

```sql
select
  * 
from
  employees
where
  1 = 1
and ( department_id = '11' or tel_number like '%000%' )
```

How can I build a condition for `1 = 1` with expose DSL or some methods? 👀

**Comment by Tapac** [comment]
` select { intLiteral(1) eq intLiteral(1) } `

**Comment by letusfly85** [comment]
@Tapac 

Thank you!
