### ISSUE TITLE
Join aliases for self referencing tables

### ISSUE THREAD

**Issue by lephyrius** [JetBrains/Exposed#363]
I'm trying to join a table and this is the SQL query I get:
`SELECT * FROM testdummies LEFT JOIN testdummies ON testdummies.id = testdummies.test_dummy WHERE testdummies.name = 'Thief' LIMIT 10`

I really want to be able to reference it like this:
`SELECT * FROM testdummies LEFT JOIN testdummies t0 ON t0.id = testdummies.test_dummy WHERE t0.name = 'Thief' LIMIT 10`

Is it possible to do that with the current API?

```kotlin
            val joinTable = joinColumn.table
            val tableAlias = Alias(joinTable, "t0")
            tableAlias.columns.forEachIndexed { index, column ->
                column.referee = joinTable.columns.get(index).referee
            }
            joinedTable = joinedTable.join(tableAlias, JoinType.LEFT, joinColumn)

```
I tried with this code.

it gave me this:
`SELECT * FROM testdummies LEFT JOIN testdummies t0 ON testdummies.id = t0.test_dummy WHERE testdummies.name = 'Thief' LIMIT 10
`
As you can see the `testdummies.id = t0.test_dummy ` This is the wrong way.

**Comment by Tapac** [comment]
```
val t0 = TestDummiesTable.alias("t0")
val resultRow = TestDummiesTable.join(t0, JoinType.LEFT, t0[TestDummiesTable.id], TestDummiesTable.test_dummy)
                .select { t0[TestDummiesTable.name] eq "Thief" }.limit(10).toList()
```

**Comment by Tapac** [comment]
https://github.com/JetBrains/Exposed/wiki/DSL#alias
