### ISSUE TITLE
How to serialization entity & get resultRaw metadata

### ISSUE THREAD

**Issue by RDCynthia** [JetBrains/Exposed#372]
Q1:How to serialization entity
I'm writing a rest API use springMVC and i need return a entity object to frontpoint.But it can't serialization to json by spring:
```
val room = transaction(DbSettings.db) {
        Room.find { Rooms.roomId eq 123 }.firstOrNull()
    }
```
When i return this via `mapof('room' to room)`, it said : `can't parse JSON.` and show a lot of mess Raw result.How can i serialization this 'room'?

Q2:How to get resultRaw metadata
When i use DSL like:
```
val room = transaction(DbSettings.db) {
        Rooms.slice(Rooms.roomId,Rooms.roomName).select {
            Rooms.roomId eq 135
        }.limit(1).firstOrNull()
```
Run it and got resutRaw,that's find.But method `room.data` just return a array about values,where is column metadata?
Coz i need `<key,value>` like `mapof('column name' to 'column value ')` to frontPoint.

Could someone help me to resolve this two problem? Thanks~

**Comment by Tapac** [comment]
Q1: ResultRow is just a holder of jdbc ResultSet values and it wasn't designed to be published somewhere. You can create your own extension function and use it like this:
```
fun Entity<*>.serialize() = this.klass.dependsOnColumns.associate { it.name to this.readValues[it] }
...
mapOf("room", room.serialize())
```
Q2: 
```
fun Query.firstOrNullSerialized() = firstOrNull()?.let { row -> set.source.columns.associate { c -> c.name to row[c]} }
```

**Comment by RDCynthia** [comment]
@Tapac Thanks for help ~ it's very helpful.
 There's a little doubt for me is sometimes i just need to fetch a few columns ,but `columns.associate` or `dependsOnColumns.associate` will detect all columns ,and throw a exception when it doesn't contain this column.
so i just fix like this:
```
......
set.source.columns.associate { c ->
        if (row.hasValue(c)) c.name to row[c] else Pair("", "")
    }
......
```
The question is it has excess pair in the result like:
```
{room={id=11,  =  ,type=TEAM}}
```
How can i write in right way? Thanks for help again ^_^

**Comment by Tapac** [comment]
You can provide columns list as a function parameters : 
```Kotlin
fun Entity<*>.serialize(colums : List<Column<*>> = this.klass.dependsOnColumns) 
    = columns.associate { it.name to this.readValues[it] }
...
mapOf("room", room.serialize(listOf(Room.id, Room.num)))
```

**Comment by RDCynthia** [comment]
thanks~i solve the problem ^ ^

**Comment by LookBad** [comment]
It doesn't work with column id - Infinite recursion (StackOverflowError) 
`(through reference chain: org.jetbrains.exposed.sql.Column["table"]->com.easythings.com.easythings.booky.repository.BookRepo["columns"]->java.util.ArrayList[0]->org.jetbrains.exposed.sql.Column["table"]->com.easythings.com.easythings.booky.repository.BookRepo["columns"]->java.util.ArrayList[0]->org.jetbrains.exposed.sql.Column["table"]->`
