### ISSUE TITLE
How to manage multiple database handles

### ISSUE THREAD

**Issue by tr8dr** [JetBrains/Exposed#378]
I was looking at another post here concerning running native SQL (for situations where using the typed kotlin is insufficient).   Saw code like this:

```
TransactionManager.current().exec("select name, description from sometable") { rs -> ... }
```
Looking at the code for ```TransactionManager```, I could not determine how one would use this in the context of multiple ```Database``` connections.   i.e. how does one get a ```TransactionManager``` for a specific database?   Alternatively, is there another way to execute a query given the Database handle?

**Comment by Tapac** [comment]
https://github.com/JetBrains/Exposed/wiki/Transactions#working-with-a-multiple-databases

**Comment by rbbl-dev** [comment]
current location of the docs https://jetbrains.github.io/Exposed/transactions.html#working-with-multiple-databases
