### ISSUE TITLE
Postgresql .pgpass support?

### ISSUE THREAD

**Issue by wputnam** [JetBrains/Exposed#387]
I've used Postgresql's `.pgpass` file to read in database credentials for features using the C++ `libpq` libraries. It's a great alternative to hardcoding such information, especially passwords, from a security standpoint. From the documentation for [DataSource](https://github.com/JetBrains/Exposed/wiki/DataBase-and-DataSource), it's possible to move the credentials into a `DataSource` object supplied with information from the `.yml` or `.properties` file for your Kotlin project.

Thing is, this method still requires hardcoding those credentials into that `.yml`/`.properties` file. That wouldn't be a problem if you configured your `.gitignore` to ignore it, but if you had other important settings in your file, then anyone else working on the code would have to make their own `.yml`/`.properties` file in order to get the program to work. It would be nice if instead of having the information saved in _any_ of the project files, the programmer could pass some sort of reference to the `.pgpass` file so that Exposed could read in the file information and parse it that way.

I wasn't able to find any documentation supporting `.pgpass`, so I was wondering if it was already a feature but not documented, and/or if there were any plans to include this feature. Thanks.

**Comment by Tapac** [comment]
We don't plan to implement such functionality, but you can wait while PRs https://github.com/pgjdbc/pgjdbc/pull/1205 or https://github.com/pgjdbc/pgjdbc/pull/1222 will be merged and released. 
Or you can rewrite that [code sample](https://stackoverflow.com/a/49679074/813981) on Kotlin and use connection params in Database.connect()
