### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by rerzer** [JetBrains/Exposed#39]
Outside of the samples there seems to be little to no documentation on the library.

What I haven't been able to figure out for example:
Using the DAO method, can I have the object extend Table() and set the primary key myself (say I have some kind of unordered UUIDs or something), if so how would that change the sample code.

There also isn't any kind of javadoc, which makes working with the library quite difficult.

**Comment by Tapac** [comment]
Thank you for your feedback, we aware about lack of documentation but have no time and resources to make it at the moment.

> Using the DAO method, can I have the object extend Table() and set the primary key myself (say I have some kind of unordered UUIDs or something), if so how would that change the sample code.

Please look at UUIDTable in ViaTest.kt

**Comment by Tapac** [comment]
Please see [wiki](https://github.com/JetBrains/Exposed/wiki).
