### ISSUE TITLE
Autoinc column does not necessarily need to be the first column in the table

### ISSUE THREAD

**Issue by jedrz** [JetBrains/Exposed#398]
I noticed an error when getting generated key that is not the first column in the table. I think the `rs.getObject(1)` in the following line https://github.com/JetBrains/Exposed/blob/master/src/main/kotlin/org/jetbrains/exposed/sql/statements/InsertStatement.kt#L27 should be replaced with `rs.getObject(firstAutoIncColumn.name)`.

I think I can provide a corresponding MR with the fix in couple of days. What do you think? The fix seems to be trivial so please let me know if I should do so.

**Comment by Tapac** [comment]
Not all database returns ResultSet with named columns, e.g. MySQL throws `Column 'id' not found.` because name of the column is `GENERATED_KEY. But i'll will try to keep both behaviors.

**Comment by jedrz** [comment]
Thank you fixing this issue!
