### ISSUE TITLE
Syntax seems degraded since the fork

### ISSUE THREAD

**Issue by apatrida** [JetBrains/Exposed#4]
The syntax with all the it[xxx] calls seems a uglier than before the fork (and the current readme which shows different syntax)

The other choice is to have an object representing schema, but a class to represent state so that you can have an instance of that class available during insert, update, etc.   I think the kotlin-nosql went that route.

Without state classes, this is similar to JDBC where you are always having to copy things OUT of something to put into state and pass around.  It is more similar to ResulSet now than it was when it started...

**Comment by raderio** [comment]
But how was the syntax before fork?
