### ISSUE TITLE
Consider switching from Joda Time to ThreeTen

### ISSUE THREAD

**Issue by fwgreen** [JetBrains/Exposed#40]
The creator of Joda Time also maintains a backport of JSR-310 called [ThreeTen](https://github.com/ThreeTen/threeten.github.io).

**Comment by guredd** [comment]
Thank you. We will rather switch to Java 8 java.time API. However in nearest future we will not depend on Java 8.

**Comment by hannesstruss** [comment]
Maybe support for third party libraries like JodaTime or ThreeTenBP could be offered as separate artifacts and removed from the main library? Thanks to extension methods this would be mostly seamless.
