### ISSUE TITLE
Is it possible to get an entity from a `ResultRow` that contains aliased table?

### ISSUE THREAD

**Issue by ezhaka** [JetBrains/Exposed#404]
Hi!

Consider a simple example:

```kotlin
val subQueryAlias = Table2.select { /* tricky subquery goes here */ }

val query = Join(Table1).join(subQueryAlias) { Table1.id eq subQueryAlias[Table2.id] }

query.map { resultRow -> 
    // bang! it's impossible to do because Table2 is under the alias in the resultRow
    Table2Entity.wrapRow(resultRow) 
}
```

Is there a way to get my entity from `ResultRow`?

**Comment by albertPu** [comment]
@Tapac 
.Net LinqToDB  framework for querying data is very convenient, if you can achieve that effect kotlin's query is too convenient

**Comment by yanghengyh** [comment]
@Tapac  How can I define the serialization program myself?

**Comment by rabolfazl** [comment]
Please add this feature :)

**Comment by gabrielgatu** [comment]
For those still searching: [**this has been implemented**](https://github.com/JetBrains/Exposed/commit/2950267edd15dc378a4239e71dfc889449f91043) so now it's possible to deserialize ResultRow into a model. In my case, this is what I've had to write:

```kotlin
RevenueTable.innerJoin(ProductTable)
        .slice(RevenueTable.columns)
        .select {
            ...
        }.let { RevenueModel.wrapRows(it) }.toList()
```

Hope this can help other people in my same situation.

**Comment by gunslingor** [comment]
I'm not following the solution.... what needs to happen? I don't see the wrapRows function anywhere, nor Table2Entityh. Somehow there has to be an efficient way to get entities back instead of resultRows without manually doing this for every table right?

```
object Outlets : Table() {
    val outlet = varchar("outlet", 255)
    val url = varchar("url", 2083)

    fun getAll(){
        dbConnect()
        val result = mutableMapOf<String, Outlet>()
        transaction { selectAll() }.forEach {
            result.put(it[outlet],
                Outlet(
                    it[outlet],
                    it[url]
                )
            )
        }
        return result
    }
}

class Outlet(
    val outlet: String,
    val url: String? = null
)
```

**Comment by joaoeudes7** [comment]
Any solution to get value from alias in ResultRow?

**Comment by Tapac** [comment]
@joaoeudes7 , please check [that test](https://github.com/JetBrains/Exposed/blob/2950267edd15dc378a4239e71dfc889449f91043/exposed/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/AliasesTests.kt#L75), it contains an example.
