### ISSUE TITLE
druid Connection pool error

### ISSUE THREAD

**Issue by albertPu** [JetBrains/Exposed#406]
![screenshot_3](https://user-images.githubusercontent.com/42194697/47007595-2ce96800-d16b-11e8-9bc3-5bbeeaadf965.png)
![screenshot_4](https://user-images.githubusercontent.com/42194697/47007604-2fe45880-d16b-11e8-9e77-30d973dbf55c.png)

**Comment by Tapac** [comment]
@albertPu , please provide more data (tables mapping, code which throws exception, etc)

**Comment by albertPu** [comment]
@Tapac 
Both the c3p0 and the druid connection pool will report an error, and the Exposed connection to the database will not

**Comment by Tapac** [comment]
Looks like a druid problem, not an Exposed : https://github.com/alibaba/druid/issues/1126

**Comment by albertPu** [comment]
@Tapac 
thank you very much
