### ISSUE TITLE
Find or fail functionality 

### ISSUE THREAD

**Issue by CharlieTap** [JetBrains/Exposed#411]
I find myself writing the following extension function with each new project 

```kotlin
class EntityNotFoundException : Exception()

fun <ID: Comparable<ID>, T: Entity<ID>> EntityClass<ID, T>.findOrFail(id : ID): T {
    return findById(id) ?: throw EntityNotFoundException()
}
```

This idea is actually borrowed from other DB frameworks, where I've found it quite useful for situations where the object has to be retrieved in order to proceed. It would be great for it to be part of the framework and not an extension function, if its of interest I can submit a pull request with it in?

**Comment by Tapac** [comment]
@CharlieTap , there is 
```
operator fun get(id: EntityID<ID>): T = findById(id) ?: throw EntityNotFoundException(id, this)
```

**Comment by CharlieTap** [comment]
> @CharlieTap , there is
> 
> ```
> operator fun get(id: EntityID<ID>): T = findById(id) ?: throw EntityNotFoundException(id, this)
> ```
> already on EntityClass. And `get(id: ID)` too.

Thats certainly more concise, although a little confusing as using the get operator suggests that your accesing an index of something

> @CharlieTap , there is
> 
> ```
> operator fun get(id: EntityID<ID>): T = findById(id) ?: throw EntityNotFoundException(id, this)
> ```
> already on EntityClass. And `get(id: ID)` too.

Oh that's exactly what I needed thank you, although a little confusing as that operator isn't usually used in that way. I would of guessed that it was used for setting properties of an object , I suppose the constructor is already off limits...

**Comment by Tapac** [comment]
It was made for the cases when you declare EntityClass as companion object, then your code looks like
`val foo = Foo[fooId]` as if you *get* an entity from database by id.
