### ISSUE TITLE
DAO Limit Query

### ISSUE THREAD

**Issue by CharlieTap** [JetBrains/Exposed#413]
When trying to limit the result set from a DAO search, I have two approaches: either

```kotlin

User.all().limit(100)

```

or 

```kotlin

User.searchQuery(limitedQuery)

```

Does the former pull the entire result on all? and then chop in memory? 
If so does a method exist that would return an Iterable of ```DAO<T>``` for a limited query?

**Comment by Tapac** [comment]
No, `.limit()` on `.all` (or in other words on SizedIterable) will set a limit on the underlying query, so you'll not consume whole memory.

**Comment by CharlieTap** [comment]
So SizedIterable represents a lazy computation? When do actual queries execute?

**Comment by Tapac** [comment]
Yes, indeed. Query will be executed when you will get iterator (in forEach/map/etc).

**Comment by CharlieTap** [comment]
Okay cool that makes sense, maybe that's something for the docs? Unless of course that's subject to change before 1.0..
