### ISSUE TITLE
Custom Enumeration Default

### ISSUE THREAD

**Issue by CharlieTap** [JetBrains/Exposed#416]
Rather than repeating the same bits of boilerplate, we could provide a function like below

```kotlin

inline fun <reified T: Enum<T>> Table.customEnumeration(name: String) =
    registerColumn<T>(name, object : ColumnType() {

        override fun sqlType(): String              = enumValues<T>().joinToString(",", prefix = "ENUM(", postfix = ")") { "'" + it.name + "'" }
        override fun valueFromDB(value: Any)        = enumValueOf<T>(value as String)
        override fun notNullValueToDB(value: Any)   = (value as T).name
    })

```

Allowing us to do:

```kotlin

customEnumeration<Enum>("field_name")

```

**Comment by Tapac** [comment]
As you can see [here](https://github.com/JetBrains/Exposed/wiki/DataTypes#how-to-use-database-enum-types) different databases have different implementation of Enums, so it can't be generalized like this, but you can use it in your code if your only target is MySQL.

Maybe it will be possible to put such function for each database if/when we split Exposed to per-db modules (https://github.com/JetBrains/Exposed/issues/184)

**Comment by CharlieTap** [comment]
That would be very interesting to see, out of interest do you have a Roadmap for this project?
