### ISSUE TITLE
[Postgresql 9.1] createMissingTablesAndColumns() now broken on case-sensitive foreign keys.

### ISSUE THREAD

**Issue by Togrias** [JetBrains/Exposed#417]
Hi,

I don't think #394 has been resolved in 0.11.1

The SQL statements generated are still:
```
ALTER TABLE roles DROP CONSTRAINT books_authorId_fkey
```

where the correct form should be:
```
ALTER TABLE roles DROP CONSTRAINT "books_authorId_fkey"
```

A fuller description of the problem:

Foreign keys in Postgresql are optionally case-sensitive. If a foreign key column is defined in Exposed as not all lower-case, then the foreign key generated is case-sensitive e.g. "books_authorId_fkey".

Case-sensitive foreign keys must be referenced with quotation marks. Otherwise the database would throw an Exception e.g. "ERROR: constraint "books_authorId_fkey" of relation "books" does not exist"

**Comment by Tapac** [comment]
@Togrias, could you please check is this issue reproduces on the latest (0.14.1) Exposed?

**Comment by Togrias** [comment]
Hello,

I can't reproduce it anymore on the latest version.

**Test Schema:**
```
object TestTableA: IntIdTable("test_a") {
	val bRef = reference("bRef", TestTableB).uniqueIndex()
}

object TestTableB: IntIdTable("test_b")
```

**Generates the following SQL:**
```
CREATE TABLE IF NOT EXISTS test_b (id SERIAL PRIMARY KEY)
CREATE TABLE IF NOT EXISTS test_a (id SERIAL PRIMARY KEY, "bRef" INT NOT NULL, CONSTRAINT fk_test_a_bref_id FOREIGN KEY ("bRef") REFERENCES test_b(id) ON DELETE RESTRICT ON UPDATE RESTRICT)
ALTER TABLE test_a ADD CONSTRAINT test_a_bref_unique UNIQUE ("bRef")
```

Observations:
column name supports case-sensitivity: "bRef"
constraint name is now to lower case.
