### ISSUE TITLE
Encrypted fields

### ISSUE THREAD

**Issue by lostcodingsomewhere** [JetBrains/Exposed#419]
There seems to be no simple way to have encrypted fields functionality without implementing it outside of the library?

**Comment by lostcodingsomewhere** [comment]
essentially similar functionality to: https://github.com/attr-encrypted/attr_encrypted

allowing to tag a field as being 'encrypted' and thus auto encrypting/decrypting when getting/setting the data and adding the needed fields on the back end (ex: salt, iv)

**Comment by Tapac** [comment]
Yes, there is no support (and you are the first who asked) for encrypted fields. You can implement it on your side for DSL or DAO.

**Comment by lostcodingsomewhere** [comment]
Oh awesome, is there any documentation on this, haven't been able to find any yet. thanks!

**Comment by lostcodingsomewhere** [comment]
interesting that nobody has brought it up ever. I'll look into implementing it on my end or creating a PR for exposed.

**Comment by jlandrum** [comment]
If you are using dao and wish to keep it in the model:
```
  private var _password by Users.password
  var password : String
    get() = _password
    set(value) { _password = value.reversed() }
```

**Comment by raderio** [comment]
@lostcodingsomewhere have you implemented it?

**Comment by lostcodingsomewhere** [comment]
@raderio haven't had time to prioritize it -- just went with the suggestion from @jlandrum to make a function in the DAO model's getter/setter

**Comment by hoonga** [comment]
I was looking for a similar functionality, but with salting and hashing (for passwords). Could this be part of the scope of the issue?

**Comment by Lafie-rage** [comment]
I don't get how we use those columns in where clauses. May be we shouldn't.
My idea was to create an encrypted or hashed field in order to store passwords.
When I want to retrieve a user by its pseudo and password it doesn't work.
The where clause needs the encrypted value to be compare using like.

Here is the code I used, in case it helps:

```kotlin
object Users : Table() {
    private val encryptor  = Algorithms.AES_256_PBE_CBC(
        ENCRYPTING_CONFIGURATION.password,
        ENCRYPTING_CONFIGURATION.salt
    )

    val id = integer("id").autoIncrement()
    val pseudo = varchar("pseudo", 110)
    val password = encryptedVarchar(
        "password",
        100,
        encryptor,
    )

    val firstName = varchar("first_name", 50)
    val lastName = varchar("last_name", 50)
    val email = varchar("email", 150)

    override val primaryKey = PrimaryKey(id)
}

// The get by pseudo & password function from my DAO
override suspend fun get(pseudo: String, password: String): User? =
    dbQuery {
        Users
            .select { (Users.pseudo eq pseudo) and (Users.password like password) }
            .map(::resultRowToUser)
            .singleOrNull()
    }

// Configuring routing
route("/users") {

    post("authenticate") {
        println(userDao.getAll()[0])
        val formParameters = call.receiveParameters()
        try {
            val pseudo = formParameters.getOrFail("pseudo")
            val password = formParameters.getOrFail("password")
            userDao.get(
                pseudo,
                password,
            )?.let {
                call.respondText(
                    "You're authenticated !",
                    status = HttpStatusCode.OK,
                )
            } ?: call.respondText(
                "Unable to authenticate you...",
                status = HttpStatusCode.NotFound
            )
        } catch (e: MissingRequestParameterException) {
            call.respondText(
                "Missing parameter : ${e.parameterName}",
                status = HttpStatusCode.BadRequest,
            )
        }

    }

}
```

The entire project can be found [here](https://github.com/Lafie-rage/ktor_openclassroom_api).

I've tried to encrypt the password value send via args but it doesn't give the same value due to the encrypting algrorithm.

**Comment by mbunderline76** [comment]
it would be nice to have BCrypt password encoder builtin support

**Comment by EdricChan03** [comment]
Found this issue when searching for the option for a built-in hashing-based database column... I've submitted a [YouTrack issue under the EXPOSED project](https://youtrack.jetbrains.com/issue/EXPOSED-1049/Support-hashing-algorithms-table-column-for-Crypt-module), let me know if there's a duplicate

cc @hoonga @mbunderline76
