### ISSUE TITLE
TRIGER AFTER UPDATE OR DELETE

### ISSUE THREAD

**Issue by 1shkelzeni** [JetBrains/Exposed#422]
I HAVE CREATE THIS TRIGER, AND IT Compiled ,BUT AFTER I TRY MAKE SOME TEST TO SEE IF IT WORK , IT GIVES ME THE ERROR.
One error saving changes to table "CCTEST"."TICKETS":
Row 1: ORA-00001: unique constraint (CCTEST.TICKET_NOTIFICE_PK) violated
ORA-06512: at "CCTEST.TICKET_NOTIFICE_T", line 9
ORA-04088: error during execution of trigger 'CCTEST.TICKET_NOTIFICE_T'

` create or replace TRIGGER ticket_notifice_t
  AFTER UPDATE OR DELETE ON tickets
  FOR EACH ROW
  DECLARE
  v_transaction VARCHAR2(10);
BEGIN
-- determine the transaction typ
   v_transaction := CASE  
         WHEN UPDATING THEN 'UPDATE'
         WHEN DELETING THEN 'DELETE'
   END;
INSERT INTO ticket_notifice
    (id,
     useridrichiedente,
     stato,
     nosologico,
     OPERAZIONE)
  VALUES
    (:new.id,
     :new.useridrichiedente,
     :new.stato,
     :new.nosologico,
     :new.OPERAZIONE);
    
END ticket_notifice_t;

 `

**Comment by Tapac** [comment]
How is this related to Exposed?
