### ISSUE TITLE
Is it possible create an entity class from a table with a composite primary key?

### ISSUE THREAD

**Issue by jorginius** [JetBrains/Exposed#43]
It seems the API forces the IdTable derived objects have got only one key column.  Is there any equivalent to the JPA's EmbeddedId and IdClass annotations?

**Comment by Tapac** [comment]
Hi, @jorginius . 
It's not possible at the moment, but I hope we can fix it in a while. 
Do you have any experience with EmbeddedId or IdClass approach? Or maybe you can share your vision how it might be implemented to be mostly useful?

**Comment by jorginius** [comment]
Hi, @Tapac .

I commented about the EmbeededId (and Embeddable) annotation because I think it could be the less disruptive approach (one object key, one parameter), but I'm not sure if mimicking JPA is the right way on this point:

```java
@Embeddable
public class UserToRoleKey {
   @Column(nullable = false)
   private String code;
   @Column(nullable = false)
   private String username;
   // ...
}

@Entity
public class UserToRole {
    @EmbeddedId
    private UserToRoleKey key;
    // ...
}

// ...
UserToRoleKey key = new UserToRoleKey();
key.setCode("USER");
key.setUsername("test);
entityManager.find(UserToRole.class, key);
```
"Raw" Table objects can hold a composite key easily:
```kotlin
internal object UsersToRoles : Table("users_roles") {
    val code = reference("code", Roles.code).primaryKey()
    val login = reference("username", Users.username).primaryKey()
}
```
Perhaps the ideal API :-) has a EntityClass which works with Table objects (creating EntityId from primaryId fields automatically) or IdTable is deprecated/superseded by simple Table, i don't know.

**Comment by kamyar1979** [comment]
It is my only problem in current project! Please lead me with a workaround at least!

**Comment by Tapac** [comment]
@kamyar1979 , sad, but there is not workaround atm, because entityId is a hardly coupled with a single column instance. We have uncompleted refactoring with this feature support, but it requires a lot of testing before release, so we can't give any ETA :(

**Comment by kamyar1979** [comment]
Sorry! I have to return to old Hibernate for now!

**Comment by OleksandrSamsonov** [comment]
Need this feature as well :(

**Comment by MigiKun** [comment]
Any news?

**Comment by rnett** [comment]
A very ugly and <8 bit int-specific work around I've been using:

`object dgmtypeeffects: IntIdTable(columnName = "typeID\" << 8 | \"effectID") {
    val typeID = integer("typeID").primaryKey()
    val effectID = integer("effectID").primaryKey()
    val isDefault = bool("isDefault")
    val effect = reference("effectID", dgmeffects)
    val type = reference("typeID", invtypes)

    fun idFromPKs(typeID: Int, effectID: Int): Int {
        return typeID shl 8 or effectID
    }

    fun findFromPKs(typeID: Int, effectID: Int): dgmtypeeffect? {
        return dgmtypeeffect.findById(idFromPKs(typeID, effectID))
    }

}

class dgmtypeeffect(id: EntityID<Int>): IntEntity(id) {
    companion object: IntEntityClass<dgmtypeeffect>(dgmtypeeffects)

    var typeID by dgmtypeeffects.typeID
    var effectID by dgmtypeeffects.effectID
    var isDefault by dgmtypeeffects.isDefault
    val effect by dgmeffect referencedOn dgmtypeeffects.effect
    val type by invtype referencedOn dgmtypeeffects.type

}`

findByPKs returns the correct object, and accessing these by references in other tables works, I can't say more than that.

The shift could be adjusted, and more values could be added.

**Comment by jcflorezr** [comment]
seems there is a solution here: https://github.com/JetBrains/Exposed/issues/239

**Comment by Hc747** [comment]
Have there been any updates on this?

**Comment by Tapac** [comment]
@Hc747, not yet.

**Comment by DRSchlaubi** [comment]
This issue was created 4 years ago, how is this not fixed yet?

**Comment by kimble** [comment]
> This issue was created 4 years ago, how is this not fixed yet?

You should ask for your money back

**Comment by BrunoMend** [comment]
I believe that I found a solution:
https://stackoverflow.com/questions/57633755/kotlin-exposed-entity-for-table-with-no-identity-column

**Comment by PedroD** [comment]
@Tapac is there any README about this on-going feature that the community can read and try to contribute?

**Comment by downloadpizza** [comment]
Bumping because this is ridicolous, I just made an IntIdTable now without using the Id ever.

**Comment by Displee** [comment]
Bump :)

**Comment by akamuza** [comment]
4 years later we still need it. Really )

**Comment by simonnepomuk** [comment]
Bump :)

**Comment by azariiva** [comment]
bump

**Comment by PGliw** [comment]
bump! ⏳

**Comment by Dezzley** [comment]
Bump 🆙

**Comment by downloadpizza** [comment]
![grafik](https://user-images.githubusercontent.com/33293877/167101753-ee35cba8-67e7-45e4-906a-c486d606bf1e.png)

bump

**Comment by romsper** [comment]
Bump

**Comment by trebsoj** [comment]
bump

**Comment by MoktanP** [comment]
bump

**Comment by well-balanced** [comment]
happy new year

**Comment by WayayueGyee** [comment]
bump

**Comment by Nek-12** [comment]
Merry christmas guys

**Comment by ilyasKerbal** [comment]
@Nek-12 Merry Christmas, any updates?

**Comment by Nek-12** [comment]
> @Nek-12 Merry Christmas, any updates?

Yeah, lots of updates: I finished school, got into university, finished university, started my masters, found a job and left that job.
