### ISSUE TITLE
What is the proper way to accomplish "WHERE NOT EXISTS"?

### ISSUE THREAD

**Issue by brjcarbone** [JetBrains/Exposed#445]
I'm attempting to convert the single query viewable here: https://gist.github.com/brjcarbone/ade2c372b8e964ee51e5c50140278466 to Exposed using DSL. Currently, I have two queries replacing this single query, but I would like to have an equivalent conversion.

insertIgnore wouldn't work since I don't have the primary keys stored in memory.

**Comment by Tapac** [comment]
Try something like this.
```Kotlin
val query = DualTable.select { 
   notExists(RopeDataTable.select {
        RopeDataTable.world eq world.id and ...
   })
}
RopeDataTable.insert(query)
```

**Comment by brjcarbone** [comment]
@Tapac Does Exposed contain a reference to the dummy table, "DUAL"?
