### ISSUE TITLE
Public Roadmap ?

### ISSUE THREAD

**Issue by carlospaulino** [JetBrains/Exposed#446]
I am trying to figure out ways to contribute to this project, but from what I see there is no public roadmap. Do you have one available that you can add to the wiki? If not, could we start a conversation around potential features? For example:

-	Support for coroutines.
-	Paranoid mode. (mark row as deleted instead of deleting)
-	Auto createdAt/updatedAt.
-	Improved documentation.
-	Schema migrations.
-	Etc.

**Comment by raderio** [comment]
>Paranoid mode. (mark row as deleted instead of deleting)

What do you mean by this?

**Comment by carlospaulino** [comment]
@raderio it means that we don't delete database entries but set a date field(deletedAt) to the current date.

**Comment by raderio** [comment]
@carlospaulino can you please be more detailed what are use cases?

**Comment by hendraanggrian** [comment]
@Tapac in #2 scenario, would it be then possible to add support for NoSQL?

**Comment by Tapac** [comment]
@hendraanggrian , I'm not sure that Exposed DSL suites well NoSQL approach, but you can try https://github.com/cheptsov/kotlin-nosql
