### ISSUE TITLE
Remove deprecated logger instance in transaction block

### ISSUE THREAD

**Issue by doxavore** [JetBrains/Exposed#447]
I name my loggers `logger`, often using the [KotlinLogging ](https://github.com/MicroUtils/kotlin-logging) library which seems to be reasonably popular. However, any time I'm inside a `transaction` block, it's finding the deprecated [`Transaction.logger`](https://github.com/JetBrains/Exposed/blob/e54fa34c02c575969e6a81c4a92f3002a0dba3b9/src/main/kotlin/org/jetbrains/exposed/sql/Transaction.kt#L40) instead (as one would expect).

It seems this was originally deprecated in v0.10.3. How long should we keep this around before removing it?

**Comment by Tapac** [comment]
Thank you for a reminder. WIll be removed on the next release.
