### ISSUE TITLE
inTopLevelTransaction with specific database

### ISSUE THREAD

**Issue by doxavore** [JetBrains/Exposed#448]
When requiring a new transaction (and the caller may already be in a transaction) with a single database seems to work with:
```kotlin
inTopLevelTransaction(
    isolationLevel,
    repetitionAttempts,
    null,
    statement
)
```

However, it isn't clear how this should work for a transaction when you're using (and possibly interleaving) multiple databases. `TransactionManager.managerFor` is marked as `internal`, so this doesn't work:
```kotlin
inTopLevelTransaction(
    isolationLevel,
    repetitionAttempts,
    TransactionManager.managerFor(database),
    statement
)
```

Is there a better way to handle this? Should we provide an overload of `inTopLevelTransaction` that accepts a `Database` instead of a `TransactionManager`? Or do we need to create a new `TransactionManager` for each `inTopLevelTransaction`?

**Comment by Tapac** [comment]
Agree. I had replaced `TransactionManager` with `Database` as 3rd parameter of inTopLevelTransaction.
