### ISSUE TITLE
Service/DAO flow

### ISSUE THREAD

**Issue by raderio** [JetBrains/Exposed#453]
In our flow we have services for business logic & DAO to access database.
So in our service we can make a select, do some logic, make an insert, do some logic, make an update, do some logic.

How this will be implemented, all code will be done in services, the logic and the queries?
And how to reuse the queries? We need to call same query in multiple services

**Comment by Tapac** [comment]
Exposed's `Query` will be executed only when you'll try to iterate over it.
For all other cases you can build statements and execute them when needed, like:
```kotlin
val insertCitizens = InsertStatement(Citizens).also {
   it[Citizens.id] = "eugen"
} 

insertCitizens.execute(TransactionManager.current())
```

**Comment by raderio** [comment]
```Type inference failed: Not enough information to infer parameter Key in 

constructor InsertStatement<Key : Any>
(
table: Table,
isIgnore: Boolean = ...
)

Please specify it explicitly.
```

**Comment by Tapac** [comment]
Sorry, I wrote code right into github. Try `InsertStatement<Int>(Citizens)`
