### ISSUE TITLE
Modeling hierarchical structure

### ISSUE THREAD

**Issue by mukoki** [JetBrains/Exposed#458]
I have a db model representing a directed graph and containing two tables,
one for the nodes (FeatureTypes), and one to implement a many-to-many 
relation (Inherits)

object FeatureTypes:IntIdTable
+name

object Inherits
+parent reference ("parent", FeatureTypes)
+child reference ("child", FeatureTypes)

I try to create the DAO model following the many-to-many example in the documentation, something like

class FeatureType(id: EntityID<Int>): IntEntity(id) {
    companion object : IntEntityClass<FeatureType>(FeatureTypes)
    ...
    var parents by FeatureType via Inherits
    var children by FeatureType via Inherits
    ...
}

but I can't figure out a way to desambiguate the roles of Inherits columns

**Comment by mukoki** [comment]
I could get what I wanted with the following painful and heavyweight solution : 
3 similar singletons describing the same "feature_type" data table : FeatureTypes, Parents, Children
2 singletons describing the relation table : 
- Ascendants (using FeatureTypes and Parents),
- Descendants (using FeatureTypes and children)

And the 3 following classes 

open class FeatureType(id: EntityID<Int>): IntEntity(id) {
    companion object : IntEntityClass<FeatureType>(FeatureTypes)
    var parents by Parent via Ancestors
    var children by Child via Descendants
    var name by FeatureTypes.name
}
class Parent(id: EntityID<Int>): FeatureType(id) {
    companion object : IntEntityClass<FeatureType>(Parents)
}
class Child(id: EntityID<Int>): FeatureType(id) {
    companion object : IntEntityClass<FeatureType>(Children)
}

Hopefully, there is a more elegant way to achieve the same goal

**Comment by bradcypert** [comment]
I think you should be able to do something like this: https://github.com/JetBrains/Exposed/wiki/DAO#many-to-many-reference

```
class FeatureType(id: EntityID): IntEntity(id) {
companion object : IntEntityClass(FeatureTypes)
...
var parents by FeatureType via Inherits.parent
var children by FeatureType via Inherits.child
...
```

I haven't used the DAO as much as the DSL, but I believe that should work?

**Comment by mukoki** [comment]
Thanks for your answer.
I could use the example for a "normal" many-to-many relation where the relation table contains links made of two ids pointing respectively to the source table and to the target table.
In my case, links point to a single table which play both roles of source and target. It creates a kind of ambiguity I could not resolve properly until now.

**Comment by Tapac** [comment]
@mukoki , did you check this part of wiki? 
https://github.com/JetBrains/Exposed/wiki/DAO#parent-child-reference

**Comment by mukoki** [comment]
Hi Tapac,

Yes, I think this part of the doc has been added a few weeks ago and along with the last version of Exposed, it perfectly matches my original question. 
Thank you for the great library.

**Comment by Tapac** [comment]
Thank you too.
