### ISSUE TITLE
[Question] Transaction inside transaction

### ISSUE THREAD

**Issue by Will3333** [JetBrains/Exposed#465]
Hello,

For example, I have a transaction in function b and I call b in a transaction of function a.

```
    fun a()
    {
        transaction { 
            val rows = GroupsTable.select { blablabla }
            b()
        }
    }
    
    fun b()
    {
        transaction {
            val rows = UsersTable.select { blablabla }
        }
    }
```
Will Exposed generate two sql requests in one transaction or two transactions with their own sql request ?

**Comment by Tapac** [comment]
Nested transaction blocks will be executed in the same transaction (started in the outermost transaction).
