### ISSUE TITLE
[Question] Logger for all transactions

### ISSUE THREAD

**Issue by Will3333** [JetBrains/Exposed#466]
Hello,

I use "addLogger(StdOutSqlLogger)" to show sql requests but I have to add it for each transaction.

How to show generated SQL requests for all transactions ?

**Comment by Tapac** [comment]
You could create your own function and use it instead of built-in transaction:
```kotlin
fun <T> loggedTransaction(statement: Transaction.() -> T): T ) = transaction {
   addLogger(StdOutSqlLogger)
   statement()
}
```

**Comment by hiranyey** [comment]
There was an extra round end bracket after T.

fun <T> loggedTransaction(statement: Transaction.() -> T): T  = transaction {
   addLogger(StdOutSqlLogger)
   statement()
}
