### ISSUE TITLE
Compound operations

### ISSUE THREAD

**Issue by Edvinas01** [JetBrains/Exposed#469]
I have a list of operations (they get generated dynamically based on user input and table columns) which need to be joined into a single operation using `OR` operator:
```kotlin
val ops : List<Op<Boolean>> = ...
```

In order to do so, I've created a helper utility:
```kotlin
abstract class CompoundOp<T>(
    private val exp: List<Expression<T>>,
    private val op: String
) : Op<T>() {

    override fun toSQL(queryBuilder: QueryBuilder) = exp
        .joinToString(separator = op) { exp ->
            "(${exp.toSQL(queryBuilder)})"
        }
}

class CompoundOrOp<T>(exp: List<Expression<T>>) : CompoundOp<T>(exp, " OR ")
```

then I can use it in the following way:
```kotlin
val ops : List<Op<Boolean>> = ...

val op: Op<Boolean> = CompoundOrOp(ops)
```

which results in:
```sql
(COLUMN_A = TRUE) OR (COLUMN_B = FALSE) OR (COLUMN_C = 'foo')
```

However I think I'm missing something. Is there a way to achieve this with current functions and classes present in the library? If not, could this be added as a new feature?

**Comment by Edvinas01** [comment]
My use case is that I have quite a lot of "data tables" which depend on flat data structures (that is my entities do not contain joins). 

In order to reduce the need of manually having to type out all specific filtering queries, I've created an utility class which takes `dependsOnColumns` and creates the filter query dynamically. The result of this is `List<Op<Boolean>>` which I need to pass to `searchQuery` method.

Previously I was using Spring Data, it had something similar where you can pass an array of `Predicate` to `QueryBuilder.or`. That is why I'm looking for similar functionality in Exposed.

**Comment by Edvinas01** [comment]
Also the reduce operation which you've shown doesn't quite cut it, it will create such result:
```
(exp OR (exp OR))
```

while I'm looking for:
```
exp OR exp OR exp
```

**Comment by Tapac** [comment]
Fixed in master: added `compondAnd`/`compoundOr` functions and optimized `or` operator to generate `(exp) or (exp) or (exp) `
