### ISSUE TITLE
UUID value not read correctly

### ISSUE THREAD

**Issue by kristiansvensson** [JetBrains/Exposed#473]
Exposed 0.12.1
Microsoft SQL Server

To reproduce

Create the table in SQL Server:
```
CREATE TABLE [dbo].[StarWarsFilms2](
	[id] [uniqueidentifier] NOT NULL,
	[sequel_id] [int] NULL,
	[name] [varchar](50) NULL,
	[director] [varchar](50) NULL
) ON [PRIMARY]
```

Run the following tests:
```
@Test
    fun mayTheForce2() {
        sqlTransaction {
            StarWarsFilms2.insert {
                it[id] = UUID.fromString("521826a4-0de9-4dec-a685-629017503bc5")
                it[name] = "The Last Jedi"
                it[sequelId] = 8
                it[director] = "Rian Johnson"
            }
        }
    }
    @Test
    fun readTheForce2() {
        sqlTransaction {
            StarWarsFilms2.select { StarWarsFilms2.sequelId eq 8 }.forEach {
                println(it[StarWarsFilms2.id])
            }
        }
    }
```

Expected: 521826a4-0de9-4dec-a685-629017503bc5 is printed
Actual: 41343236-3138-3532-2d45-3930442d4543 is printed

**Comment by kristiansvensson** [comment]
Forgot to supply the table definition:

```
object StarWarsFilms2 : Table() {
    val id: Column<UUID> = uuid("id")
    val sequelId: Column<Int> = integer("sequel_id").uniqueIndex()
    val name: Column<String> = varchar("name", 50)
    val director: Column<String> = varchar("director", 50)
}
```

Also, `sqlTransaction` in above code is a wrapper around `transaction` that also opens a database connection.

**Comment by Tapac** [comment]
The problem here is what Exposed uses `BINARY(16)` for UUID representation in SQLServer, while you use `uniqueidentifier` type. 
Do you have any links to SQLServer docs where `uniqueidentifier` described?

**Comment by kristiansvensson** [comment]
I hope that this helps: https://docs.microsoft.com/en-us/sql/t-sql/data-types/uniqueidentifier-transact-sql?view=sql-server-2017

**Comment by Tapac** [comment]
Fixed in master
