### ISSUE TITLE
Impossible to set default value with nullable column?

### ISSUE THREAD

**Issue by silospen** [JetBrains/Exposed#474]
For a column which is both nullable and has a default value, it should be possible to set 3 different values: 
 - A value
 - NULL
 - The default value

In the insert SQL, that would equate to:
 - SQL containing a value
 - SQL containing an explicit NULL
 - SQL with the field missing

As far as I can tell in exposed there's no way to express the third variant and so it's impossible to get a default value. Am I missing a setting somewhere or are you using NULL to indicate both the absence of data and null data?

Thanks!

```
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.SchemaUtils
import org.jetbrains.exposed.sql.Table
import org.jetbrains.exposed.sql.insert
import org.jetbrains.exposed.sql.selectAll
import org.jetbrains.exposed.sql.transactions.transaction

object ExampleTable : Table() {
    val text = varchar("text", 50).default("default-text-value").nullable()
}

fun main(args: Array<String>) {
    Database.connect("jdbc:h2:mem:", "org.h2.Driver")

    transaction {
        SchemaUtils.create(ExampleTable)
        ExampleTable.insert { it[text] = "first-text-value" }
        ExampleTable.insert { it[text] = null }
        ExampleTable.insert {  }
        ExampleTable.selectAll().forEach(::println)
    }

    /**
     * EXPECTED:
     *  - "first-text-value"
     *  - NULL
     *  - "default-text-value"
     */

    /**
     * ACTUAL:
     *  - "first-text-value"
     *  - NULL
     *  - NULL
     */

}
```

**Comment by Tapac** [comment]
Definitely `empty` insert should work, but it doesn't. Will be fixed on the next release
