### ISSUE TITLE
Using neq with binary on PostgreSQL returns wrong results

### ISSUE THREAD

**Issue by peterwilli** [JetBrains/Exposed#477]
I encountered this issue on the latest version of Exposed (0.12.1). It seems to only return rows that are set to null, but not any other value that is on the right side of the neq-statement.

I made a sample to prove the problem:

My Gradle script is this:

```gradle
plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '1.3.20'
}

group 'TestBugByteArrayNeq'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    jcenter()
    mavenCentral()
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    compile 'org.jetbrains.exposed:exposed:0.12.1'
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile "org.postgresql:postgresql:42.2.2"
}

compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
compileTestKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
```

The Demo code (kotlin) is this:

```kotlin
import org.jetbrains.exposed.sql.*
import org.jetbrains.exposed.sql.transactions.transaction
import java.security.SecureRandom

object TestBug : Table() {
    val hash = binary("orderId", 32).nullable().index()
}

fun main(args: Array<String>) {
    val db = Database.connect("jdbc:postgresql://localhost:5432/hsm_test", driver = "org.postgresql.Driver",
        user = "admin", password = "legaal")
    transaction {
        SchemaUtils.drop(TestBug)
        SchemaUtils.create(TestBug)
    }

    // Insert 10 nulls
    for (i in 0..10) {
        transaction {
            TestBug.insert {
                it[TestBug.hash] = null
            }
        }
    }

    val b = ByteArray(32)
    val rand = SecureRandom()
    transaction {
        for (i in 0..10) {
            rand.nextBytes(b)
            TestBug.insert {
                it[TestBug.hash] = b
            }
        }
    }

    transaction {
        // Search for everything except one, should return 19 tables...
        val q = TestBug.select {
            TestBug.hash neq b
        }

        println("result: ${q.count()}")
    }
}
```

As you can see, I make 20 tables: 10 with null, and 10 with a random byte array. I remember the latest byte array and use it in a neq-query. The result should be 19 but it's getting at 10. It seems to ignore all the other binary rows that have any value besides null set.

Update: It also seems to fail with neq in strings!

**Comment by Tapac** [comment]
Sorry, but after some deeper investigation, I can conclude that everything works fine.
1. You insert 22 records instead of 20 in your test
2. The result is correct and equals 10 records with non-null hash values except the last inserted (you have 11 records with hashes)
3. It's a bit complicated how NULL values are treated when compared to other values. You can experiment by your self:
```sql
select 1= null from dual; // returns null
select 1 != null from dual; // returns null
```
A null value in "where" condition is treated nor as true, nor false.
