### ISSUE TITLE
One to many join using DSL

### ISSUE THREAD

**Issue by jorgerabello3** [JetBrains/Exposed#482]
Hi I'm trying to make a selectAll making a join of two tables, in this case I have a OneToMany relationship.

Here is my definitions of tables (Student and Phone) where a sutdent has many phones numbers:

`
object Student : LongIdTable() {
    val name = varchar("name", 150)
    val email = varchar("email", 255).uniqueIndex()
}
`

`
object Phone : LongIdTable() {
    val prefix = varchar("prefix", 2)
    val number = varchar("number", 9)
    val student_id = long("student_id")
}
`

And I'm trying to make a query that selects all students, make a join with phones and returns a list of students and theis respective phones, based on this example https://github.com/JetBrains/Exposed/wiki/DSL#where-expression

`
Players.join(StarWarsFilms, JoinType.INNER, additionalConstraint = {StarWarsFilms.sequelId eq Players.sequelId})
  .slice(Players.name.count(), StarWarsFilms.name)
  .groupBy(StarWarsFilms.name)
`

But when I try to make the code, I can't call the groupBy function... And I don't understand why... 

`
 override fun findAll(): List<Student> {
        val students = mutableListOf<Student>()

        PhoneTable.join(StudentTable, JoinType.INNER, additionalConstraint = {StudentTable.id eq PhoneTable.student_id})
            .slice(PhoneTable.number.count(), StudentTable.name)
            .groupBy()
`

Thanks

**Comment by Tapac** [comment]
Documentation about table referencing is missing from DSL part of wiki, but you can look at [DAO](https://github.com/JetBrains/Exposed/wiki/DAO#referencing) and just skip all that relate to entities.
In your example, you have to replace `val student_id = long("student_id")` with `val student_id = reference("student_id", Student)` 
and your query will look like:
```
StudentTable.leftJoin(PhoneTable).
    slice(PhoneTable.name.count(), StudentTable.name).
    groupBy(StudentTable.id)
```

**Comment by jorgerabello3** [comment]
Hi Tapac, thanks to your answer, but I'm still having problems...

First: I tried to do it that way you said, heres my code:

StudentTable

```
internal object Student : LongIdTable() {
     val name: Column<String> = varchar("name", 150)
     val email: Column<String> = varchar("email", 255).uniqueIndex() }
```

PhoneTable

```
internal object Phone : LongIdTable() {
    val prefix = varchar("prefix", 2)
    val number = varchar("number", 9)
    val student = reference("student_id", StudentTable)
}
```

And then I tried do make the join like this:

```
StudentTable.leftJoin(PhoneTable).
            slice(PhoneTable.number.count(), StudentTable.name).
            groupBy(StudentTable.id)
``` 

But when I call the the grouBy() function I have a 'Unresolved reference' message. : / 

I need a response more or less as this:

For example when I make a request to list all students: 

```
{
    "students": [
        {
            "id": 1,
            "name": "Jorge111",
            "email": "jorge1123@concrete.com",
            "phones": [
                               {
                                  "id": 1,
                                 "prefix": "11",
                                "number": "951482377"
                             },
                               {
                                  "id": 2,
                                 "prefix": "21",
                                "number": "111482377"
                             },
                         ]
        },
        {
            "id": 25,
            "name": "1234",
            "email": "xpto@concrete.com",
            "phones": []
        },
    ]
}
```

Thank you soo much !!!

**Comment by Tapac** [comment]
There is missing `selectAll()`  call before `groupBy`. The proper code is:
```kotlin
StudentTable.leftJoin(PhoneTable). 
    slice(PhoneTable.number.count(), StudentTable.name). 
    selectAll().
    groupBy(StudentTable.id)
```
