### ISSUE TITLE
Release notes / changelog?

### ISSUE THREAD

**Issue by glasser** [JetBrains/Exposed#484]
Does Exposed have a changelog anywhere? We're on 0.10 and have no idea if there are any compatibility issues to worry about from a 0.12 upgrade.

**Comment by Tapac** [comment]
https://github.com/JetBrains/Exposed/blob/master/ChangeLog.md

**Comment by glasser** [comment]
I honestly can't explain how I missed that. Sorry!

**Comment by icguy** [comment]
file moved to: https://github.com/JetBrains/Exposed/blob/master/docs/ChangeLog.md
