### ISSUE TITLE
Is there a way to disable entity cache?

### ISSUE THREAD

**Issue by lephyrius** [JetBrains/Exposed#488]
The problem is that we want to query the same entity with different slices of columns.  My issue is that we only get the first entity with a different slice of columns than the second one.  I think that Exposed caches the first entity without checking the slices in the cache.  

Is there a way to disable the entity cache so I can debug this or am I doing something else wrong?

**Comment by Tapac** [comment]
Nice point to check is an entity was fully or partially loaded and check slices for a partial case.
At the moment you only can remove entities from cache manually by calling `EntityClass.removeFromCache()`.

**Comment by lephyrius** [comment]
Ok, then how can I check if entities are fully or partially loaded?

**Comment by Tapac** [comment]
Maybe something like:
```kotlin
if (entity.klass.dependsOnColumns.all { entity._readValues?.hasValue(it) == true }) {
   entity.klass.reload(entity)
}
```

**Comment by lephyrius** [comment]
It works!
So what could be the reason to why _readValues is null in the model ?

**Comment by Tapac** [comment]
There is `readValues` field which will return cached `_readValues` or load fields from a database. 
It's safe to check `_readValues` in your case because if your entity was created like `FooEntity(id)` there is nothing was loaded from db yet and you will not make additional query.

**Comment by IgnatBeresnev** [comment]
For anyone finding this when Googling, _it seems_ you can disable it via database config:
```kotlin
DatabaseConfig.invoke {
            maxEntitiesToStoreInCachePerEntity = 0
        }
```

**Comment by Kykara4uk** [comment]
Unfortunately, looks like 
DatabaseConfig.invoke {
    maxEntitiesToStoreInCachePerEntity = 0
} 

breaks changing data via DAO API
