### ISSUE TITLE
Is it possible to have the table name as a variable?

### ISSUE THREAD

**Issue by loxs** [JetBrains/Exposed#489]
I have to work with a database which has 1500 tables of several "types". Is there a way to configure the table name(s) to be variable, which I can specify on querying?

**Comment by Tapac** [comment]
It's possible to instantiate Table instance as local variable and provide a required name:
```kotlin
abstract GenericTable(name: String) : Table(name) {
   // your columns here
}

fun queryToATable(tableName: String) {
   val table = object : GenericTable(tableName) {} 
   table.select { table.field1 eq "foo }
}
```
