### ISSUE TITLE
`AssertionError: Entity must be inserted` with self-references - cache problem

### ISSUE THREAD

**Issue by gcscaglia** [JetBrains/Exposed#49]
When executing multiple inserts for the same table and setting up references between those new entities, the entity cache will fail to flush with `java.lang.AssertionError: Entity must be inserted` (full stack trace in annexed files).

This can be avoided by flushing the cache explicitly in-between inserts, and doesn't happens with a debbugger atached (inspecting probably triggers cache flushing). My guess is that `BatchInsertStatement` is trying to build a statement of the form `INSERT INTO table (v) VALUES (v1), (v2), ...`, which won't work in this case because the ID of the parent entity is still unknown.

Bellow are an complete test case for reproduction and the test reports from my executions:
[insert-flush-example.zip](https://github.com/JetBrains/Exposed/files/453387/insert-flush-example.zip)
[reports.zip](https://github.com/JetBrains/Exposed/files/453388/reports.zip)

**Comment by Tapac** [comment]
Thank you for report. Issue is fixed and your tests moved to EntityTests.kt.
