### ISSUE TITLE
Allow to extract results from nested, aliased queries

### ISSUE THREAD

**Issue by Edvinas01** [JetBrains/Exposed#493]
I have the following query:
```sql
SELECT i.name
FROM (
  SELECT name
  FROM test_table
) AS i;
```

Though I can't seem to find a way on how to re-create it in Exposed:
```kotlin
val innerQuery = TestTable
    .slice(TestTable.name)
    .selectAll()
    .alias("i")

val query = innerQuery
    .slice(???)
    .selectAll()
    .forEach { row ->
        print(row[???])
    }
```

Looking at `Query` implementation it seems to append `set.fields` which are of type `FieldSet`. Though none of current `FieldSet` implementations allow me to specify aliased table columns (e.g. `i.name`) which I could pass to `slice(...)` and `row[...]` methods or use them in expressions of the parent query.

**Comment by Tapac** [comment]
Did you read https://github.com/JetBrains/Exposed/wiki/DSL#alias ?

**Comment by Edvinas01** [comment]
Yes, however all of those examples contain joins. 

I also took a look at:
https://github.com/JetBrains/Exposed/issues/248

**Comment by Edvinas01** [comment]
Played around a bit more and ran into this result:
```kotlin
val inner = TestTable
    .slice(TestTable.name)
    .selectAll()
    .alias("i")

val name = inner[TestTable.name]
inner
    .slice(name)
    .selectAll()
    .forEach { row ->
        println(row[name])
    }
```

It produces the following query which is just what I'm looking for (also managed to build the more complex query using this method as well, though it does get a little messy):
```sql
SELECT i.name
FROM (
  SELECT test_table.name
  FROM test_table
) i;
``` 

@Tapac there doesn't seem to be an example of how to refer to inner query columns in the docs though (that is that I have to do `row[inner[TestTable.name]]`). Should I add this example somewhere in the Wiki or should I just close this issue?

**Comment by Tapac** [comment]
Any improvements to documentation are very welcome especially when it covers real-life use-cases.

**Comment by Edvinas01** [comment]
Expanded the "Alias" section with sub-query example on:
https://github.com/JetBrains/Exposed/wiki/DSL#alias
