### ISSUE TITLE
ColumnMetadata object does not have length property

### ISSUE THREAD

**Issue by pokhodenko** [JetBrains/Exposed#495]
I'm building a database migration tool using Exposed and need to be able to compare existing columns with mapping. For example if I change varchar column length there is no way to determine if mapping is not in sync. 
There is more columns required to make reverse migrations so it would be good to grab all documented columns.
I can try to provide PR but first want to check if it is needed improvement.

**Comment by Tapac** [comment]
@pokhodenko Sure, you can PR this improvement, but do you mind to extend it also with `collate` property?
