### ISSUE TITLE
Custom ColumnType that applies a function on inserting

### ISSUE THREAD

**Issue by giylmi** [JetBrains/Exposed#496]
I want to apply a stored function on a column value when inserting new row.

Let's use `lower` function as an example.

I am trying to add a new column type that will apply a `lower` function on the value when preparing statement.

I got logging of the sql work good, but obviously that `nonNullValueToString` call does not get inserted to sql statement.

Any ideas, how can I achieve this?

My example code is below

 ```kotlin
class LowerVarcharColumnType(colLength: Int, collate: String?) : VarCharColumnType(colLength, collate) {
    override fun nonNullValueToString(value: Any): String {
        val valueToString = super.nonNullValueToString(value)
        return "LOWER($valueToString)"
    }
}

fun Table.lowerVarchar(name: String, colLength: Int, collate: String? = null): Column<String> = registerColumn(name, LowerVarcharColumnType(colLength, collate))

class Example(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<Example>(ExampleTable, Example::class.java)

    var name by ExampleTable.name
}

object ExampleTable : IntIdTable("example") {
    val name = lowerVarchar("name", 100)
}

class ExampleSpek : StringSpec({
    "test create" {
         Database.connect("jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE", driver = "org.h2.Driver")
        val example = transaction {
            SchemaUtils.create(ExampleTable)
            Example.new {
                 name = "UPPER LETTERS NAME"
            }
        }

        transaction {
            SchemaUtils.drop(ExampleTable)
        }

        example.name shouldBe "upper letters name"        
    }
})
```

I was also thinking of custom `Expression<*>` class but couldn't find a way to integrate it to `ColumnType`

**Comment by Tapac** [comment]
Why not make it on DAO level, not DSL? Right now if you read name value from new Example you'll get upper-cased text, do you expect that?

**Comment by giylmi** [comment]
No I expect lower-cased text... I think I got your point - I will anyway need to refetch the entity to get value assigned by database. So it's worth to use `insert` not `new`.

Anyway I'm still having problem with inserting the entity.

```kotlin
class Example(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<Example>(ExampleTable, Example::class.java)

    var name by ExampleTable.name
}

object ExampleTable : IntIdTable("example") {
    val name = varchar("name", 100)
}

class ExampleSpek : StringSpec({
    "test create" {
        Database.connect("jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE", driver = "org.h2.Driver")
//        Database.connect("jdbc:mysql://localhost:3306/test", driver = "com.mysql.jdbc.Driver", user = "user", password = "pswd")
        val id = transaction {
            SchemaUtils.create(ExampleTable)
            ExampleTable.insertAndGetId {
                it.update(name, LowerCase(stringLiteral("UPPER LETTER NAME")))
            }
        }

        Example[id].name shouldBe "upper letters name"
    }
})
```

With `h2` I'm getting `org.h2.jdbc.JdbcSQLException: Serialization failed, cause: "java.io.NotSerializableException: org.jetbrains.exposed.sql.LowerCase" [90026-197]`

With `mysql` I'm getting `java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).`

**Comment by Tapac** [comment]
It's not what I advised, something like:
```kotlin
class Example(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<Example>(ExampleTable, Example::class.java)

    private var _name by ExampleTable.name
    var name: String
          get() = _name
          set(value: String) {
              _name = value.toLowerCase()
          }
}
```

**Comment by giylmi** [comment]
The problem is that in real life, I will use stored function when inserting the row.
So in resulted sql, I will want something like `insert into Example(name) values (my_stored_function('some_name'))`

**Comment by Tapac** [comment]
Could you write such query with plain jdbc PrepareStatement?
