### ISSUE TITLE
how do you reference in a DAO many-to-one

### ISSUE THREAD

**Issue by lamba92** [JetBrains/Exposed#499]
Say you have 2 tables, `CameraTable` and `SnapshotUriTable`. Now for each `camera` you have many `snapshotUri`s. You could follow the [example ](https://github.com/JetBrains/Exposed/wiki/DAO#many-to-many-reference) and create an intermediary table, but what if you want to store the reference inside `SnapshotUriTable` with a column containing the `id` of the `camera`?

**Comment by lamba92** [comment]
I guess it was easier then I thought! 
```
class Camera(id: EntityID<Int>) : IntEntity(id) {
    var snapshotUris = CameraSnapshotUri.find { CamerasSnapshotUriTable.cameraId eq id }
}
```

**Comment by Tapac** [comment]
Did you try?
```kotlin 
class Camera(id: EntityID<Int>) : IntEntity(id) {
    var snapshotUris = CameraSnapshotUri.referrersOn(CamerasSnapshotUriTable.cameraId)
```
This case described [here](https://github.com/JetBrains/Exposed/wiki/DAO#many-to-one-reference) closer to the end (look for `Now if you wanted to get all the ratings for a film`)

**Comment by lamba92** [comment]
`val snapshotUris by CameraSnapshotUrl referrersOn CamerasSnapshotUrlTable.cameraId` did just fine! Thank you!
I'd recomment to write it more explicitly int the wiki with a section titled `many-to-one`

**Comment by Tapac** [comment]
@lamba92 , wiki is open for a contibution. Feel free to update that section.
