### ISSUE TITLE
support for SQL ORDER BY clauses

### ISSUE THREAD

**Issue by heenenee** [JetBrains/Exposed#50]
Please add support for ORDER BY clauses.  If there already is support and I'm not seeing it, please add an example of how to add an ORDER BY clause to a Entity.find query.  Thanks.

**Comment by Tapac** [comment]
There is two ways to "order by" entities:

1. Make your find and order it in memory afterward :
```Entity.find { condition }.sortedBy { it.name }```

2. Make ordered query and wrap rows: 
```
Entity.wrapRows(
     Entity.dependsOnTables.select { condition }.orderBy(EntityTable.name, false)
)
```
