### ISSUE TITLE
Want access to executedStatements

### ISSUE THREAD

**Issue by yoshutch** [JetBrains/Exposed#504]
https://github.com/JetBrains/Exposed/blob/1c799ede465bede585fb2c6656f92c1147635eb0/src/main/kotlin/org/jetbrains/exposed/sql/Transaction.kt#L51

Is there a reason that I cannot see as to why the `executedStatements` variable is internal and not public like the other fields inside a `Transaction`?

We have a use case where we'd like to ultimately write out all the executed statements from running the `SchemaUtils.createMissingTablesAndColumns()` function to a file in order to automate the creation of ddl migration scripts (for migration tools like Flyway). We can't run the `SchemaUtils.createMissingTablesAndColumns()` function in production because our prod database doesn't allow the code to make ddl migrations, so we'll run this in a local test database to find out automate what migrations scripts we need to run in production. And this `executedStatements` field looks like it would have everything I need to determine what migrations scripts to run.

I don't think the `statements`  variable will work because it's truncated and padded for readability, nor will the `statementStats` variable work because it's a HashMap and therefore we lose the order of the executed statements.

Can we make `executedStatements` public or is there another way to get the statements that are required to migrate a database?

**Comment by Tapac** [comment]
We are do not want (and trying so) to expose any `PreparedStatement` related stuff as it will block us from moving to any other non-jdbc implementations (like ADBA).
I guess you may use `StatementInterceptor.afterExecution` instead of `executedStatements` and log SQL like (as you can see even `executedStatement` is available):
```kotlin
override fun afterExecution(transaction: Transaction, contexts: List<StatementContext>, executedStatement: PreparedStatement) {
        val sqls = contexts.joinToString("\n") { it.expandArgs(transaction) }
....
}
```

**Comment by yoshutch** [comment]
Awesome! That's exactly what I needed! Thanks.
