### ISSUE TITLE
Ability to modify statementContext in StatementInterceptor?

### ISSUE THREAD

**Issue by boonshift** [JetBrains/Exposed#505]
Hi, I am looking into using StatementInterceptor to dynamically inspect and modify statements to add a mandatory AndOp for some sort of multi tenancy query. The downside now is that the statementContext.args is a val. Also, there is no way to replace the incoming statementContext and returning a different one at beforeExecution().

```
interface StatementInterceptor {
    fun beforeExecution(transaction: Transaction, context: StatementContext) {}
```

Would this be possible?

```
interface StatementInterceptor {
    fun beforeExecution(transaction: Transaction, context: StatementContext): StatementContext {}
```

Obviously, it also means prepareArgs might need to be called later in executeIn()...

**Comment by boonshift** [comment]
Let me know if you are okay with this and I can work on a PR for it.

**Comment by Tapac** [comment]
It wasn't planned to modify statements at this point but I understood your point and it sounds promising.
The main issue is that adding return value will break compatibility with the previous version.

**Comment by bog-walk** [comment]
@boonshift [PR #1622](https://github.com/JetBrains/Exposed/pull/1622) added a function `afterStatementPrepared()` to the `StatementInterceptor` interface, which may potentially be beneficial for your need to modify prepared statements before executing.

Could you please confirm if this issue persists with current version 0.42.1? If it does, please consider sharing more details regarding what's lacking with current support, so we can investigate further.

**Comment by bog-walk** [comment]
Please consider reopening this issue on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763) if the new function `afterStatementPrepared()` does not provide the expected enhancement.

If you choose to do so, please also share more details about your use case and how `StatementInterceptor` is lacking in the current version (0.44.0 at time of writing), so we can attempt to assist you further.
