### ISSUE TITLE
Is it possible to have multiple ContentNegotiation per route definition or per module?

### ISSUE THREAD

**Issue by magillus** [JetBrains/Exposed#512]
When trying to install ContentNegotiation inside additional (not main) module:
```
install(ContentNegotiation) {
        register(ContentType.Application.Xml, MyContentConverter()) {

        }
    }
```
I have this error:
```
Caused by: io.ktor.application.DuplicateApplicationFeatureException: Conflicting application feature is already installed with the same key as `ContentNegotiation`
```
however I would like that part of the routes could by default use different content negotiation.
some API require to have XML.

Is there way to have that configured per module, and also per per routing sub path?

**Comment by magillus** [comment]
I think I found content type per routing:
```
routing {
        contentType(ContentType.Application.Xml){
            get("/myxml/api"){
                
            }
            
        }
```

**Comment by Tapac** [comment]
@magillus , why you post it in Exposed repo, not into https://github.com/ktorio/ktor ?

**Comment by magillus** [comment]
I really sorry wrong tab ...
