### ISSUE TITLE
Unique or null index?

### ISSUE THREAD

**Issue by Togrias** [JetBrains/Exposed#515]
I would like to create a column that has the following constraint:

It can be null. If it is not null, it must be a unique value.

SQL supports WHERE clauses on indices. So we can do "WHERE value IS NOT NULL"

**Comment by Tapac** [comment]
```kotlin
object FooTable : TableI() {
     val nullableUniqueCol = varchar("col", 123).nullable().uniqueIndex()
}
```

**Comment by Togrias** [comment]
But I want multiple rows set to null to be allowed.

Using the DAO syntax:

```
foo1 = Foo.new { col = null }
foo2 = Foo.new { col = null } //i want to allow this; currently error 
foo3 = Foo.new { col = "a" }
foo4 = Foo.new { col = "b" }
foo5 = Foo.new { col = "a" } //error
```

**Comment by Tapac** [comment]
What database do you use? AFAIK most databases allow multiple nulls for unique columns (see https://sqlite.org/faq.html#q26).

What kind of an error do you get on second `foo2 = Foo.new { col = null }` ?
