### ISSUE TITLE
Is it possible to create ordered relationships with the DAO?

### ISSUE THREAD

**Issue by jacquerie** [JetBrains/Exposed#516]
In SQLAlchemy it's possible to declare an ordering for the related records of a relationship, see for example: https://docs.sqlalchemy.org/en/latest/orm/extensions/declarative/relationships.html.

Is a similar thing possible with the DAO from Exposed? I know how to do it when dropping down to the DSL, but it's unclear to me if it is even possible with just the DAO.

**Comment by Tapac** [comment]
No, it's not supported yet.
