### ISSUE TITLE
[Doc] all() and orderBy() docs are wrong

### ISSUE THREAD

**Issue by cbeust** [JetBrains/Exposed#519]
1. `all()` is called `selectAll()`.

2. There's only `orderBy()`, no more `orderByDescending()` and the order of the sort is paired with each column, e.g.

```
Table.selectAll().orderBy(Pair(Table.col1, ASC), Pair(Table.col2, DESC)))
```

**Comment by Tapac** [comment]
@cbeust, Do you mean that kdocs are absent on those functions or it related to a wiki?

**Comment by cbeust** [comment]
I meant the wiki. I should have included the link, sorry, and now... I can't find the wrong doc any more. Weird.
