### ISSUE TITLE
How can I use UNIX_TIMESTAMP

### ISSUE THREAD

**Issue by tomocrafter** [JetBrains/Exposed#520]
Question is in title. How can I use UNIX_TIMESTAMP in where?

**Comment by Tapac** [comment]
What `UNIX_TIMESTAMP` do you mean? Mysql function?

**Comment by tomocrafter** [comment]
yes, it is MySQL function.
I guess we can do with DateTime().

**Comment by Tapac** [comment]
You could define your own function: 
```kotlin
class UnixTimestamp<T:DateTime?>(val expr: Expression<T>?) : Function<Long>(LongColumnType()) {
    override fun toSQL(queryBuilder: QueryBuilder): String = buildString {
        append("UNIX_TIMESTAMP(")
        expr?.let {
            append("'${it.toSQL(queryBuilder)}'")
        }
        append(")")
    }
}
```

**Comment by tomocrafter** [comment]
I'm sorry. I do not know well,
`SELECT * FROM log WHERE executed_at > UNIX_TIMESTAMP(?)`
What if I want to execute the SQL statement?
? Is a String.

**Comment by tomocrafter** [comment]
Okay, I found a solution, Change the line 1 to
`class UnixTimestamp<T:String?>(val expr: Expression<T>?) : Function<Long>(LongColumnType()) {`
And `Log.executed_at.greater(UnixTimestamp(stringParam("something")))` it is works well.
