### ISSUE TITLE
Join on two tables with more than one foreign key constraint fails even with additionalConstraint

### ISSUE THREAD

**Issue by rabolfazl** [JetBrains/Exposed#522]
Consider the following:

```
class User(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<User>(Users)
}

object Users : IntIdTable() {
}

class Subscription(id: EntityID<Long>) : LongEntity(id) {
    companion object : LongEntityClass<Subscription>(Subscriptions) {
    var user by User referencedOn Subscriptions.user
    var adminBy by User optionalReferencedOn Subscriptions.adminBy
}

object Subscriptions : LongIdTable() {
    val user = reference("user", Users)
    val adminBy = reference("adminBy", Users).nullable()
}

```
The following join query fails:

`Subscriptions.join(Users, JoinType.INNER, additionalConstraint = {Subscriptions.user eq Users.id})
`

The problem is in file org.jetbrains.exposed.sql.Table.kt on line 92 (0.13.3):

`else -> return join(otherTable, joinType, fkKeys.map { it.first to it.second.single() }, additionalConstraint)
`

`it.second.single()` fails while according to previous lines, when additional constraints are specified, `it.second()` may have more than one element so `.single()` fails.

**Comment by Tapac** [comment]
In your case it's better to use:
`Subscriptions.innerJoin(Users, { user }, { id })` but it's unrelated to a bug you mentioned.
