### ISSUE TITLE
How can I disconnect a connected database?

### ISSUE THREAD

**Issue by Maxr1998** [JetBrains/Exposed#523]
For testing purposes, I want to connect and afterwards disconnect multiple databases sequentially - I currently have the following code to disconnect the currently active one:
```Kotlin
fun disconnectDatabase() {
    if (db == null)
        return

    TransactionManager.currentOrNull()?.connection?.close()
    TransactionManager.resetCurrent(null)
    db = null
}
```

However, it seems that my database/transaction manager is not in fact removed from the registered ones in `TransactionApi.kt`, only the raw connection is closed - how can I completely reset all transaction managers that none is initialized anymore?

**Comment by Tapac** [comment]
I guess that it's possible only via reflection as `registeredDatabases` is private in `TransactionManager`

**Comment by Maxr1998** [comment]
@Tapac I see.. would it make sense to add this to the library? I could do a PR if you want.

**Comment by Tapac** [comment]
Sure, PRs are always welcome.

**Comment by Maxr1998** [comment]
Where would you put that method? In Database.kt maybe?

**Comment by Tapac** [comment]
There or near/inside `TransactionManager`.
