### ISSUE TITLE
How to perform WHERE ... NOT IN {subquery}

### ISSUE THREAD

**Issue by Wnzebkhan** [JetBrains/Exposed#528]
How can I perform the following SQL-statement? 
Preferably, I would like the DAO-style, but DSL is fine aswell. 

The SQL Query I want to perform:
```
SELECT *
FROM User
WHERE User.id NOT IN ( SELECT UserId 
                       FROM Project_Member_List
                       WHERE Project_Member_List.ProjectId = 7)

```

**Comment by Tapac** [comment]
There is no `inList` for subqueries but your case is very similar to the second part of https://github.com/JetBrains/Exposed/issues/202#issuecomment-347542306

**Comment by Wnzebkhan** [comment]
When you say 'The second part of..', do you mean this snippet? 
```
Companies.select {
   exists(Measures.select { Companies.id eq Measures.number })
}
```
I am sorry, just a bit confused right now...

**Comment by Tapac** [comment]
Yes, your code could be written like:
```kotlin
User.select {
   notExists(ProjectMemerList.select{ 
        ProjectMemerberList.projectId eq 7 and (ProjectMemerberList.userId eq User.id )
   })
}

**Comment by Wnzebkhan** [comment]
Alright!

I've run the snippet you provided:
```
var users : List<User> = listOf()
        transaction {
            val query = Users.select {
                notExists(ProjectMemberLists.select{
                    (ProjectMemberLists.project eq projectId) and (ProjectMemberLists.member eq Users.id )
                })
            }
            users = User.wrapRows(query).toList()
            //end of the transaction
        }
```
As of now, this code is returning the rows I was expecting it to return, so it looks like this works.

Thanks for your support!
