### ISSUE TITLE
Add MS SQL Server Dialect

### ISSUE THREAD

**Issue by heenenee** [JetBrains/Exposed#53]
I'm trying to perform a `limit` query against a Microsoft SQL Server database, but I'm getting a "No dialect registered for sqlserver" error.  Exposed could use a SQLServerDialect class.

**Comment by YakovSirotkin** [comment]
I added support for MSSQL in https://github.com/YakovSirotkin/Exposed/tree/sqlserver-dialect, but I want to wait with pull request until clarification with https://github.com/JetBrains/Exposed/pull/155

Testing with Docker is not trivial and maybe it will be possible to re-use approach for Oracle tests to SQL server.

**Comment by YakovSirotkin** [comment]
I created pull request https://github.com/JetBrains/Exposed/pull/164 with SQL Server support, but I am not sure about Docker tests. Maybe it makes sense to create one tests with 2 Docker instance with Oracle and SQL Server.

**Comment by Tapac** [comment]
Ok, I will check PR next week and will try to setup single TC configuration to run both DBMS.

**Comment by mkporwit** [comment]
Would be great to get MS SQL support in Exposed. We're about to start integrating our services with our Azure backend. Happy to help with testing/validation if that's of benefit.

**Comment by YakovSirotkin** [comment]
@Tapac Do you have a plan how to add SQL Server support? Maybe we can create branch in main repo from https://github.com/JetBrains/Exposed/pull/164#discussion_r139973220? At least it will be easier to keep branch up-to-date.

**Comment by Tapac** [comment]
@YakovSirotkin, finally I'm ready to merge your branch with SQLDialect into master and create a release. 
First of all, thank you for that PR, and let me know you have an account at kotlinlang.slack.com, because I want to mention you in release announce in the Exposed channel.

Also, I found out that DATETIME2 type doesn't have that problem with losing millis.

**Comment by YakovSirotkin** [comment]
@Tapac thanks a lot for all your work!  I think that I don't have  account at kotlinlang.slack.com because I don't have email at jetbrains.com:)

**Comment by Tapac** [comment]
@YakovSirotkin , I'm not sure that it's required to, but sent you invitation to @telamon.ru anyway .

**Comment by YakovSirotkin** [comment]
@Tapac, thanks a lot, I just registered.
