### ISSUE TITLE
Last insert id support ?

### ISSUE THREAD

**Issue by douglarek** [JetBrains/Exposed#54]
There does not seem to be a way of getting the record id of the last inserted record(s).

**Comment by Tapac** [comment]
Do you try Table.insert{...}.generatedKey or Table.insert{...}[Table.id] ?

**Comment by douglarek** [comment]
@Tapac yeah, but *generatedKey* or [Table.id] only support `Int` not `Long`

**Comment by Tapac** [comment]
Guess it's related to #31 . Hope we fix it soon.
