### ISSUE TITLE
How can I connect to a database that is in my project's asset folder?

### ISSUE THREAD

**Issue by DinuNcl** [JetBrains/Exposed#540]
Hello, 

How can I connect to a database that is in my project's asset folder?

**Comment by Tapac** [comment]
What kind of a database? I think you should read documentation for it. Exposed uses same jdbc connection url as any other java orm/sql frameworks.

**Comment by DinuNcl** [comment]
I mean a database that is in your project folder like this:
![PDj2t](https://user-images.githubusercontent.com/37775427/55715991-8e91dd00-59fe-11e9-8a5d-e02775738aec.png)
 
How can I get the path in order to conect:
`Database.connect("jdbc:h2:file:~$path/testDB", driver = "org.h2.Driver")
`

**Comment by Tapac** [comment]
http://www.h2database.com/html/faq.html#database_files
