### ISSUE TITLE
[Feature] Could support "android framework sqlite” by implement a  “AndroidExposedDataSource”?

### ISSUE THREAD

**Issue by Guang1234567** [JetBrains/Exposed#546]
Hello dev:

As we know, Exposed does not support  `android framework sqlite`, so could you support it by implementing a `AndroidExposedDataSource` ?   thanks.

**Comment by Tapac** [comment]
Re-implementing Android SQLite API is out of Exposed scope, you could try to look for `https://github.com/SQLDroid/SQLDroid/` and leave a feedback if it works with an Exposed.

**Comment by Guang1234567** [comment]
@Tapac 

Thanks your reply. so i close this issue now.
