### ISSUE TITLE
jcenter version need updated

### ISSUE THREAD

**Issue by douglarek** [JetBrains/Exposed#55]
Exposed's latest tag is *0.6.6* in GitHub, but *0.6.5* in [jcenter](https://bintray.com/kotlin/exposed/exposed/view#);

And I can not use jcenter download Exposed directly, I have to do this:

```
repositories {
    mavenCentral()
    maven { url "https://dl.bintray.com/kotlin/exposed" } // for kotlin exposed only not jcenter() here.
}
```

Gradle 2.14.1

**Comment by Tapac** [comment]
0.6.7 published to bintray

**Comment by douglarek** [comment]
@Tapac 

```
$ http -F GET "https://jcenter.bintray.com/org/jetbrains/exposed/spring-transaction/0.6.7/spring-transaction-0.6.7.pom"

HTTP/1.1 404 Not Found
Connection: keep-alive
Content-Length: 88
Content-Type: application/json;charset=ISO-8859-1
Date: Mon, 26 Sep 2016 09:59:56 GMT
Server: nginx
X-Artifactory-Id: repo.jfrog.org
X-Node: nginx-dedicated4e.prod-use1

{
    "errors": [
        {
            "message": "Could not find resource",
            "status": 404
        }
    ]
}```

**Comment by Tapac** [comment]
https://bintray.com/kotlin/exposed/exposed#files/org/jetbrains/exposed/spring-transaction/0.6.7

**Comment by douglarek** [comment]
@Tapac thanks, I just want to use it by Gradle like other projects not jars;

**Comment by douglarek** [comment]
```
http -F GET "https://jcenter.bintray.com/org/jetbrains/exposed/exposed/0.6.7/exposed-0.6.7.pom"
HTTP/1.1 404 Not Found
Connection: keep-alive
Content-Type: application/json;charset=ISO-8859-1
Date: Mon, 26 Sep 2016 10:41:16 GMT
Server: nginx
X-Artifactory-Id: repo.jfrog.org
X-Node: nginx-dedicated1e.prod-use1
transfer-encoding: chunked

{
    "errors": [
        {
            "message": "Could not find resource",
            "status": 404
        }
    ]
}
```

**Comment by Tapac** [comment]
We are not ready to publish it to jcentral yet (have some critical design issues) so you should be able to get it from bintray repo. 
If you couldn't please provide your gradle build config.

**Comment by Tapac** [comment]
@brabo-hi , any errors from gradle logs?

**Comment by brabo-hi** [comment]
**Here is the error**
root project '1': Unable to build Kotlin project configuration</b>
Details: java.lang.reflect.InvocationTargetException: null
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':compileClasspath'.
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find org.jetbrains.kotlinx:kotlinx-html-jvm:0.6.9.
Searched in the following locations:
    https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-html-jvm/0.6.9/kotlinx-html-jvm-0.6.9.pom
    https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-html-jvm/0.6.9/kotlinx-html-jvm-0.6.9.jar
    https://dl.bintray.com/kotlin/kotlinx/org/jetbrains/kotlinx/kotlinx-html-jvm/0.6.9/kotlinx-html-jvm-0.6.9.pom
    https://dl.bintray.com/kotlin/kotlinx/org/jetbrains/kotlinx/kotlinx-html-jvm/0.6.9/kotlinx-html-jvm-0.6.9.jar
    https://dl.bintray.com/kotlin/exposed/org/jetbrains/kotlinx/kotlinx-html-jvm/0.6.9/kotlinx-html-jvm-0.6.9.pom
    https://dl.bintray.com/kotlin/exposed/org/jetbrains/kotlinx/kotlinx-html-jvm/0.6.9/kotlinx-html-jvm-0.6.9.jar
    https://dl.bintray.com/kotlin/ktor/org/jetbrains/kotlinx/kotlinx-html-jvm/0.6.9/kotlinx-html-jvm-0.6.9.pom
    https://dl.bintray.com/kotlin/ktor/org/jetbrains/kotlinx/kotlinx-html-jvm/0.6.9/kotlinx-html-jvm-0.6.9.jar
Required by:
    project : > io.ktor:ktor-html-builder:0.9.2</i>
