### ISSUE TITLE
Offset without Limit

### ISSUE THREAD

**Issue by mrAppleXZ** [JetBrains/Exposed#550]
Hello!
Is there a built-in way to do something like `query.offset(Int)`? It seems that currently offset can be applied only using a `limit` function: https://github.com/JetBrains/Exposed/wiki/DSL#limit

**Comment by Tapac** [comment]
@mrAppleXZ , there is no generic SQL syntax for OFFSET, so Exposed doesn't provide such one also. 
You can define your own extension like `fun SizedIterable<*>.offset(o: Int) = limit(Int.MAX_VALUE, o)`
