### ISSUE TITLE
How to use blob

### ISSUE THREAD

**Issue by Wnzebkhan** [JetBrains/Exposed#555]
I have the following model:

```
import java.sql.Blob //Unsure about the import

object Entries : IntIdTable("Entry") {
    val content : Column<Blob> = Entries.blob("Content")  // Not sure whether this is correct
}

//Enable Data Access Object (DAO) for more convenient data-transactions
class Entry(id: EntityID<Int>) : Entity<Int>(id) {
    companion object : EntityClass<Int, Entry>(Entries)

    var content by Entries.content
}
```

How do I insert a new instance of Entry class in the database? Right now I have this:

```
val newEntry = transaction { Entry.new {
                    content = //??? What am I supposed to put here? The blob will contain a JSON
                } 
            }
```

**Comment by Tapac** [comment]
```kotlin
val jsonAsByteArray = "json".toByteArray()
Entry.new {
   content = SerialBlob(jsonAsByteArray)
} 
```

**Comment by Wnzebkhan** [comment]
Thanks for the reply! I have one more question:

How can I now retrieve whatever is in the Blob, but then in a String? 

```
val jsonAsByteArray = "json".toByteArray()
val createdEntry = transaction {
                        Entry.new {
                                content = SerialBlob(jsonAsByteArray)
                        }
                  }
val myBlobbedContent = createdEntry.content
val myStringContent = //What to do here with the myBlobbedContent?


```

**Comment by Tapac** [comment]
`val myStringContent = myBlobbedContent.toString(Charsets.UTF_8`
Please note that you should access `blob` fields within transaction block or it might throw an exception as blob values load lazily.

Also, why you want to use `blob` for json values instead of `text`?

**Comment by Wnzebkhan** [comment]
Thanks for replying! 
> Your sample

The sample code you provided does not work since the IDE gives an error and says the fun `toString()` does not accept any argument. 

> Why `blob` instead of `text`.

According to some peers, it is better to store the json-strings in a column with `blob`-type. I have not looked into the advantages that `text` has over `blob`. 
The json-string I am storing may get very big, so `blob` seemed like a good fit. 
Could you perhaps enlighten me if I am doing something wrong now?

**Comment by Tapac** [comment]
@Wnzebkhan , you've mixed up `varchar` and `text`. `text` could be as big as blob field but allows to read and select (with `like` operator) values right from a database. 

> The sample code you provided does not work since the IDE gives an error and says the fun toString() does not accept any argument
That's strange as kotlin-stdlib has `ByteArray.toString(Charset)` function.
