### ISSUE TITLE
How to optionally  disable logging in using DSL API

### ISSUE THREAD

**Issue by blackmo18** [JetBrains/Exposed#556]
Hi,

I am using KTOR as my web framework and using default SLF4J for logging,
how can I disable exposed logging whenever I perform a query to DB using DSL API?

**Comment by Tapac** [comment]
@blackmo18, what kind of logging do you want to suppress? Could you provide an example message?

**Comment by blackmo18** [comment]
@Tapac sorry for the late reply

here is my setup of Gradle dependencies and I'm using your SQL DSL API

//-- ktor
 implementation "io.ktor:ktor-server-core:$ktor_version"
 implementation "io.ktor:ktor-server-netty:$ktor_version"

//-- logging
implementation "ch.qos.logback:logback-classic:1.2.3"

//-- exposed "
implementation org.jetbrains.exposed:exposed:0.13.6"

for example, I call an API succesfully:
localhost:port/home/player/find-one-by-id?id=1

on the logs it displays
DEBUG Exposed - SELECT player.id, player.external_id...FROM player WHERE player.id = 1

when I supposed I only wanted to display on the logs is that this API is called successfully or whatever the result. this happens whenever any query is performed via SQL

**Comment by gertvdijk** [comment]
@blackmo18 It seems that you just need to configure your logger framework. I am using logback too, and this below worked for me. HTH.

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <!-- ... appender config, up to you ... -->
    </appender>

    <!-- Set Exposed logger on INFO level  -->
    <logger name="Exposed" level="info" additivity="false">
        <appender-ref ref="STDOUT"/>
    </logger>

    <!-- Set root logger on another level  -->
    <root level="debug">
        <appender-ref ref="STDOUT"/>
    </root>

</configuration>
```

**Comment by STIV3NS** [comment]
> @blackmo18 It seems that you just need to configure your logger framework. I am using logback too, and this `logback.xml` resource below worked for me. HTH.
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <configuration>
> 
>     <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
>         
>     </appender>
> 
>     
>     <logger name="Exposed" level="info" additivity="false">
>         <appender-ref ref="STDOUT"/>
>     </logger>
> 
>     
>     <root level="debug">
>         <appender-ref ref="STDOUT"/>
>     </root>
> 
> </configuration>
> ```

It doesn't help in my case. I'm unable to disable DEBUG messages ;/

**Comment by foxwoosh** [comment]
I have the same issue. It's strange that there's no tool from the code to setup logging level.

**Comment by Tapac** [comment]
@gandrewstone , @foxwoosh , what kind of logs do you talk about?
