### ISSUE TITLE
Function for retrieving DAO column value

### ISSUE THREAD

**Issue by CharlieTap** [JetBrains/Exposed#557]
When using the DAO syntax I often find I want to reference a foreign key without querying the actual foreign reference.

For example, rather than:

```kotlin
user.profile.id
```
I do:

```kotlin
user.readValues[Users.profile].value
```
To ensure I don't make an extra query. As I do this often I created an extension function:

```kotlin

fun <SRCID : Comparable<SRCID>, REFID: Comparable<REFID>> Entity<SRCID>.referenceId(column: Column<EntityID<REFID>>) : REFID {
    
    if(this.klass.table != column.table ) {
        throw IllegalArgumentException("Column provided does not exist on source table.")
    }
    
    return readValues[column].value
}
```

It would be nice to get something like this into the library as its probably best if readValues is abstracted away. This is potentially the moment @Tapac when you tell me it already exists 😅

**Comment by Tapac** [comment]
You always can just reference to raw value by:
```kotlin
class User : IntEntity() {
   val profileId by Users.profile
}
```
Or you often need to check different columns in result set?

**Comment by CharlieTap** [comment]
@Tapac Thats a much more sensible solution, I'll just map all the FK's onto the entity class itself. Thank you
