### ISSUE TITLE
Join on multiple custom columns 

### ISSUE THREAD

**Issue by SackCastellon** [JetBrains/Exposed#560]
### Preface
This issue is directly related to the problem stated on issue #511 

### Problem
In that issue I needed to create a table that references another one using a composite foreign key, to accomplish that I had to create the foreign key manually, meaning that the foreign key was not registered by Exposed.

The problem is that now I need to join the two tables but, because the foreign key was not registered by Exposed I cannot call:
```kotlin
TableA.innerJoin(TableB)
```
Also, I cannot manually specify more that one `ON` clause in the [`innerJoin(otherTable, onColumn, otherColumn)`](https://github.com/JetBrains/Exposed/blob/master/exposed/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt#L42).

### Possible solution
Making the method [`join(otherTable, joinType, cond, additionalConstraint)`](https://github.com/JetBrains/Exposed/blob/master/exposed/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt#L101) **`public`** could solve the problem a I would be able to specify multiple `ON` clauses for the `JOIN` clause.

**Comment by Tapac** [comment]
Why not to use [join(otherTable, joinType, onColumn, otherColumn, additionalConstraint)](https://github.com/JetBrains/Exposed/blob/5f673996937c77066ff00a47d89b0914c596213d/exposed/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt#L96):


```kotlin
val onCondition = listOf(TableA.col1 to TableB.col2, TableA.col2 to Table
TablaA.join(TableB, JoinType.INNER, null, null) {
    (TableA.col1 eq TableB.col1) and (TableA.col2 to TableB.col2)
}
```

**Comment by SackCastellon** [comment]
Sorry for not replying earlier, this seem to work fine so far, thanks.
