### ISSUE TITLE
Cannot work in servlet application.  java.lang.ClassNotFoundException: kotlin.reflect.KDeclarationContainer

### ISSUE THREAD

**Issue by riddle12** [JetBrains/Exposed#562]
When I use transaction(Database){} , it crashed.

```
java.lang.ClassNotFoundException: kotlin.reflect.KDeclarationContainer
    ...
    at top.riddle12.servlet.TestServlet.doPost(TestServlet.kt:17)
    ...
```

I had added org.jetbrains.kotlin:kotlin-reflect:1.3.31 in Project Structure.

```kotlin
package top.riddle12.servlet

import ...

@WebServlet("/test")
class TestServlet : HttpServlet() {

    override fun doPost(req: HttpServletRequest?, resp: HttpServletResponse?) {
        val writer = resp!!.writer

        transaction(MyDatabase.db) { //error occurs this line
            writer.write("\n transaction")
        }

        writer.flush()
        writer.close()
    }
}
```

**Comment by Tapac** [comment]
Which version of kotlin do you use in your project? Try to set it to `1.3.21`.

**Comment by riddle12** [comment]
> Which version of kotlin do you use in your project? Try to set it to `1.3.21`.

I'm using `1.3.31`,but that is fine . The cause is that I made some stupid mistakes, i didn't add libs to my tomcat folder. It works perfectly now .
Thanks for your helping!
