### ISSUE TITLE
Support read-slaves on read-only transactions

### ISSUE THREAD

**Issue by jacek99** [JetBrains/Exposed#564]
A common requirement in any production deployment is to support writing to a single master DB and reading from multiple read slaves/replicas, fronted by a load balancer.

Exposed doesn't seem to allow this in any way. The Database singleton allows for just one connection, whereas in this setup you usually need two: one for read/write to master and one for read from a load balanced set of read replicas.

Would be great if Database allowed specifying 2 separate connections
and instead of a single transaction {} block, it would be great to support a

readOnlyTransaction {
   ...read only SQL from replica...
}

block that would automatically use the other DB connection to a read replica.

Right now, without any support for DB read slaves/replicas, Exposed is not really usable in any sort of proper enterprise deployment.

**Comment by Tapac** [comment]
You could make any amount of Database instances and use them as a `transaction` function parameter.
