### ISSUE TITLE
Local Date Time

### ISSUE THREAD

**Issue by fmgonsalves** [JetBrains/Exposed#565]
Hey guys,

I've been using Exposed to create a database for some timeseries data.  I've noticed the following code in ColumnType.kt:

```
class DateColumnType(val time: Boolean): ColumnType() {
    override fun sqlType(): String  = if (time) currentDialect.dataTypeProvider.dateTimeType() else "DATE"

    override fun nonNullValueToString(value: Any): String {
        if (value is String) return value

        val dateTime = when (value) {
            is DateTime -> value
            is java.sql.Date -> DateTime(value.time)
            is java.sql.Timestamp -> DateTime(value.time)
            else -> error("Unexpected value: $value of ${value::class.qualifiedName}")
        }

        return if (time)
            "'${DEFAULT_DATE_TIME_STRING_FORMATTER.print(dateTime.toDateTime(DateTimeZone.getDefault()))}'"
        else
            "'${DEFAULT_DATE_STRING_FORMATTER.print(dateTime)}'"
    }
```

This uses `DateTimeZone.getDefault()` to get the string for the DateTime value. However, I do not want to use the System Locale Timezone to save values on the DB. Could we make a change to specify the timezone to use?  Another (maybe easier) solution would be to include functionality for Joda's LocalDateTime instead.

Let me know what you guys think.

Fred

**Comment by fmgonsalves** [comment]
Now that I think about it, is there any reason why we are forcing the use of the default DateTimeZone when storing/querying the DB?  Why not just write the date in the time zone defined by the user?

**Comment by Tapac** [comment]
Java Time Api LocalDateTime available.

**Comment by Rubyj** [comment]
@Tapac That is not a solution to this issue. I argue this should be re-opened. Java LocalDateTime does not use a time zone. IF we use a LocalDateTime with exposed, it will assume system default time zone on insert.

**Comment by Smitty010** [comment]
I was going to tryout exposed.  However, the lack of ZonedDateTime means I will use Hibernate/JPA.  I don't really have a choice.  My company decided a few years ago was that everything would be GMT going forward, but we can't change all of the servers to GMT because of older existing software.  Exposed looks promising, but it needs it needs full support for the java 8 date/time api.

**Comment by ViktorPetrovski** [comment]
I did something like this to convert all the date time in UTC before entering into the DB
`val createdAt = datetime("created_at").clientDefault { ZonedDateTime.now(ZoneId.of("UTC")).toLocalDateTime() }`

**Comment by akifb** [comment]
We are keeping `updatedAt` field in database with UTC timezone, and our servers are deployed in cloud in different location, and all of our Instant values are converted to system default. This is a real use case for systems that run in cloud. Now we are evaluating Exposed this can be a blocker issue for us.

**Comment by holdbetter** [comment]
Guys, it's not okay at all

I'm storing Instant and it also changes the timezone on Insert/Replace operations. If you'll check any guideline about storing datetime it says "store in UTC" and do whatever you need after. I don't understand why Exposed takes my data and changes it, it's like sending you "name", but you save it in reversed order without any reasons

Also this "feature" isn't reflected in docs so you should face it, find why it's keep going and do some fix to be worked with.

Let's figure out something
