### ISSUE TITLE
Is it the function of transaction a atomic operation

### ISSUE THREAD

**Issue by luckyxiaomo** [JetBrains/Exposed#568]
![image](https://user-images.githubusercontent.com/42728605/58245398-4567d380-7d87-11e9-8dad-2b7b74e48e88.png)

First, I am sorry for my poor English.
I'm not sure it works well or not with multiple threads.
Can any one tell me.

I like Exposed and Kotlin.

**Comment by Tapac** [comment]
It's `atomic` in scope of database data consistency: it either changes a whole data within `transaction` block, either it won't change anything. 
You can read more at [Database Transaction](https://en.wikipedia.org/wiki/Database_transaction) page on wikipedia
