### ISSUE TITLE
LazySizedCollection.limit() produce StackOverflowError exception

### ISSUE THREAD

**Issue by HanikLZ** [JetBrains/Exposed#569]
function limit in LazySizedCollection class 
`
override fun limit(n: Int, offset: Int): SizedIterable<T> = copy().limit(n, offset)
`
function copy in LazySizedCollection class
`
override fun copy(): SizedIterable<T> = LazySizedCollection(delegate.copy())
`
is this a bug?

**Comment by Tapac** [comment]
@HanikLZ , definitely. Thank you for the report.
