### ISSUE TITLE
Field Comment, table comment set by mapping support feature request

### ISSUE THREAD

**Issue by sergeybannikov** [JetBrains/Exposed#58]
varchar("id", 10).primaryKey().**comment**("Identifier")
Our team very like your project, and we think that this ORM is the most laconic and simple for java (kotlin).
We use it with CodeFirst approach and would be nice to have opportunity to add db comments via mappings.
Thank you for your GREAT work!

**Comment by Tapac** [comment]
@Aileron1410 , there is no standard sql syntax to add comments to table/column, so it may to take time to research the way it's required for each DBMS.

Also there is no generic way to retrieve comment information with jdbc metadata, so it might be hard to track comment mapping changes with what exists in database.

Is it really useful to keep comments in database with "code first" approach? Maybe just comment it in code or create comprehensible field names?

**Comment by Aileron1410** [comment]
Andrey, thank you for your reply, you're right, we can develop without it,
and if it is hard to realise, it is not necessary

20 Окт 2016 г. 23:46 пользователь "Andrey.Tarashevskiy" <
notifications@github.com> написал:

**Comment by guai** [comment]
"Is it really useful to keep comments in database with "code first" approach? Maybe just comment it in code or create comprehensible field names?"
One could use them in many other places. Generate docs for example. Wrap your DB with some rest and show comments there, etc.
"there is no standard sql syntax to add comments to table/column"
DBeaver does it somehow. I believe it uses jdbc drivers, so it should be possible

**Comment by bog-walk** [comment]
Starting with version 0.52.0, column comments in MySQL, MariaDB, H2, and SQLite will be available using:
```kt
object TestTable: IdTable("test") {
    val name = varchar("name", 20).withDefinition("COMMENT", stringLiteral("Name"))
}
```

Table comments (or column comments via `COMMENT ON COLUMN`) are still not supported. Please see [EXPOSED-418](https://youtrack.jetbrains.com/issue/EXPOSED-418/Support-comments-on-tables) to bump/track this feature request.

**Comment by hizhengfu** [comment]
> ```kotlin
> withDefinition
> ```
Can we add an extension function。
```
fun <T> Column<T>.comment(description: String): Column<T> = apply {
    withDefinition("COMMENT", stringLiteral(description))
}
```
