### ISSUE TITLE
Database-provided default values

### ISSUE THREAD

**Issue by bendiksolheim** [JetBrains/Exposed#588]
Hello,

I am using Exposed with PostgreSQL, trying to create tables with UUID primary keys. This works well, but I am unsure how (or if) I can make PostgreSQL create the UUID on insert. The `pgcrypto` extension exposes the function `gen_random_uuid()`, so `CREATE TABLE tbl(my_column UUID DEFAULT gen_random_uuid())` would work as I want. Is there any way to  achieve this with Exposed? As far as I can see, all of the `default`-modifiers on columns expect me to provide a default value from Kotlin.

**Comment by Tapac** [comment]
You can try to mix [custom functions](https://github.com/JetBrains/Exposed/wiki/Functions#custom-functions) with default values. Something like:
```kotlin
object Foo : Table() {
    val uuid = uuid("my_column").defaultExpression(CustomFunction("gen_random_uuid()", UUIDColumnType()))
}
```

**Comment by bendiksolheim** [comment]
Thanks a lot @Tapac , that does indeed work wonders. I never though of placing the `gen_random_uuid()` in the insert statement.. :) 

For reference, this is what worked:
```Kotlin
.defaultExpression(CustomFunction("gen_random_uuid", UUIDColumnType()))
```
It seems `CustomFunction` appends `()` after the function call itself.

Thanks for the help!
