### ISSUE TITLE
MySQL DDL Not Working 

### ISSUE THREAD

**Issue by ChasDouglass** [JetBrains/Exposed#589]
I just upgraded exposed to 0.15.1 from 0.8.5 (I know, been awhile).

Anyway, all of the DDL which worked fine in 0.8.5 is simple failing quietly in 0.15.1.

I'm using MySQL, also upgraded connector to version 8.0.16 and mysql "Ver 14.14 Distrib 5.7.26".
The DDL is printed out in log statements, but simply has no effect on the database and no warnings/errors are issued.

So "CREATE TABLE...", "ALTER TABLE...", etc are failing silently (or not being sent?)

Is there perhaps some new configuration step I've missed?

**Comment by Tapac** [comment]
You run 0.15.1 against an existing database or trying to create a new one from a scratch?

**Comment by ChasDouglass** [comment]
Both, actually.  I found it wasn't working on an existing DB so I created a new one, but it wouldn't create the tables in that one, either.

Updates and inserts against the existing DB are working.

**Comment by Tapac** [comment]
Could you share your mapping which fails on creation?

**Comment by ChasDouglass** [comment]
My apologies.  This turns out to be a forgotten code change from the last time this project was worked.

Trying to reduce the problem to a simple example for you "exposed" the problem.

Thank you for your time.
