### ISSUE TITLE
Mysql dialect does not support expressions as default values

### ISSUE THREAD

**Issue by crazyproger** [JetBrains/Exposed#59]
`supportsExpressionsAsDefault` should be `true` for Mysql

**Comment by Tapac** [comment]
> The DEFAULT value clause in a data type specification indicates a default value for a column. With one exception, the default value must be a constant; it cannot be a function or an expression. This means, for example, that you cannot set the default for a date column to be the value of a function such as NOW() or CURRENT_DATE. The exception is that you can specify CURRENT_TIMESTAMP as the default for TIMESTAMP and DATETIME columns. 
http://dev.mysql.com/doc/refman/5.7/en/data-type-defaults.html

So I guess Mysql doesn't truly support an expressions as columns default, especially comparing to PostgreSQL (https://www.postgresql.org/docs/9.3/static/ddl-default.html)

**Comment by crazyproger** [comment]
Ouch, thank you for clarification, @Tapac. I will create custom ColumnType for this purpose in my case.

**Comment by Tapac** [comment]
You can use `clientDefault{} ` to generate value on client side:
``` object : Table("") {
   val colWithDefault = integer("intCol").clientDefault { Random.nextInt() }
}```

**Comment by crazyproger** [comment]
Thank you for suggestion, but I think some fields(`created`, `modified` in my case) better generate on database, for example with my table works not only kotlin code but also web-app(ruby/php/etc). And to not forget to generate it in _all_ places better to generate it in one-DB.

**Comment by Tapac** [comment]
Then triggers might suite your need, I guess.
