### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by vffuunnyy** [JetBrains/Exposed#594]
```
org.jetbrains.exposed.exceptions.ExposedSQLException: org.postgresql.util.PSQLException: FATAL: out of memory
Подробности: Failed on request of size 12288 in memory context "TopMemoryContext".
SQL: [Failed on expanding args for SELECT: org.jetbrains.exposed.sql.Query@27ec0435]
```

**Comment by Tapac** [comment]
I don't think what this relates to Exposed as it postgresql exception. 
You should try to google for "postgresql out of memory" (like https://www.postgresql.org/message-id/BC53C974C3B9E542BC0A9BD4C5B1168A0E9326E0@NEWMAIL.manord.com)

**Comment by vffuunnyy** [comment]
> I don't think what this relates to Exposed as it postgresql exception.
> You should try to google for "postgresql out of memory" (like https://www.postgresql.org/message-id/BC53C974C3B9E542BC0A9BD4C5B1168A0E9326E0@NEWMAIL.manord.com or https://dba.stackexchange.com/questions/46675/postgresql-out-of-memory-while-trying-to-a-request-of-500mb)

well, I have these settings:

```
max_connections = 20
shared_buffers = 2048MB
temp_buffers = 128MB
work_mem = 128MB
```

**Comment by Tapac** [comment]
Sorry, but I'm not a postgresql expert and never had such exception, moreover it mostly relates to a query you are trying to execute.

**Comment by vffuunnyy** [comment]
> Sorry, but I'm not a postgresql expert and never had such exception, moreover it mostly relates to a query you are trying to execute.

I understand. These are the requests in my app:
```
Members.new {
    userId = uid
    addedAt = Instant.now().toEpochMilli()
    gid = gid_
}
```

```
object Member : IntIdTable() {
    val user_id = integer("user_id")
    val added_at = long("added_at")
    val gid = integer("gid")
}

class Members(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<Members>(Member)

    var userId by Member.user_id
    var addedAt by Member.added_at
    var gid by Member.gid
}
```

maybe someone knows how to fix it?

**Comment by Tapac** [comment]
I don't see a select which might fail, how much data do you have in your table?

**Comment by vffuunnyy** [comment]
> I don't see a select which might fail, how much data do you have in your table?

8027532 rows and 517 MB in Member

**Comment by Tapac** [comment]
You have to increase work_mem I guess

**Comment by vffuunnyy** [comment]
@Tapac ok, thanks, I'll try it

**Comment by vffuunnyy** [comment]
Hm.. It may help somebody with this problem.
