### ISSUE TITLE
Publishing of `exposed-spring-boot-starter`

### ISSUE THREAD

**Issue by patrykpacewicz** [JetBrains/Exposed#595]
It's great that you created an `exposed-spring-boot-starter`. 👍 

In documentation there is gradle dependancy information: 

```
repositories {
  jcenter()
}
dependencies {
  implementation 'org.jetbrains.exposed:exposed-spring-boot-starter:0.15.1'
}
```
but it do not work. 

Have you not forgotten to publish it?

**Comment by Tapac** [comment]
It wasn't released yet as there are some changes which also should be released + one test from a new module still fails.

**Comment by Tapac** [comment]
Published since 0.16.1

**Comment by micaelafmartino** [comment]
It doesn't work with the jcenter repo, there is a problem with the pom I guess. Debug says 

```
[WARNING] The POM for org.jetbrains.exposed:exposed-spring-boot-starter:jar:0.16.3 is missing, no dependency information available
```

The solution was adding 
```gradle
maven { setUrl("https://dl.bintray.com/kotlin/exposed") } 
```

to the gradle's repositories list.

**Comment by Tapac** [comment]
@micaelafmartino , thank you for your attention. Now it should be available on jcenter, please check it.

**Comment by micaelafmartino** [comment]
@Tapac it works now, thank you!
