### ISSUE TITLE
Rollback all sequences when exception within transaction block

### ISSUE THREAD

**Issue by fmgonsalves** [JetBrains/Exposed#597]
I have a transaction block that looks like this: 

```
  transaction(db) {
        EquipmentTable.create()
        VariableTable.create()

        dbi.insertEquipmentFile(equipFile, "System1") // performs a bunch of inserts into EquipmentTable
        dbi.insertVariableFile(varsFile, "System1") // performs a bunch of inserts into VariableTable

        val hms1 = MutableEquipment("HMS1") 
        dbi.insertEquipment(hms1, "System1") // throws an exception
    }
```

EquipmentTable and Variable Table each have a primary autoIncrement primary key "ID column.

The first two lines create some tables which are then (by default) followed by commits.  The third and fourth simply perform some insert statements.  Everything good so far.  The line `dbi.insertEquipment(hms1, "System1")` throws an error since the equipment already exists.

When I check the database, I find that the equipment inserted in lines 3 and 4 were not committed (which is completely fine), however, the auto increment sequences were not reset to 0 (or to the previous value before these insert statements).  Is there a way to reset these sequences?  I am using Postgresql, if that helps.

Thanks

**Comment by fracaron** [comment]
This is by design from postgres (and other databases).
https://www.postgresql.org/message-id/20040420005747.GA19205@wolff.to

**Comment by Tapac** [comment]
@fmgonsalves , databases don't reset auto-increment/sequences as the value could be already incremented by another transaction and a rollback could case a deadlock.
