### ISSUE TITLE
Error from too many registered arguments using Alias

### ISSUE THREAD

**Issue by husnjak** [JetBrains/Exposed#598]
Hello

I am trying to use Alias but it seems that Exposed adds too many arguments which gives me `Column index out of range`.

I want to create this query: 
```
SELECT
    *
FROM
    (
        SELECT
            searches.id,
            searches."name",
            searches.test_dummy,
            ts_rank_cd(
                searches.tsv,
                plainto_tsquery('english', unaccent(?))
            ) + similarity(unaccent(searches.name), ? :: text) as search_rank
        FROM
            searches
    ) as searches
WHERE
    search_rank > 0.2
ORDER BY
    search_rank DESC
LIMIT
    10
```

The code I use looks like this: 
```
val innerQuery = Query(Searches.slice(selectedColumns)).alias("as " + Searches.tableName.toLowerCase())
```
Note, I have to add `as` into the name otherwise the alias does not work, is there a better way? 

The issue seems to be with `registerArguments` in the `Expression.kt` file as it will add 4 arguments where I only need 2, resulting in an exception. 

How should I solve this? Have tried modifying the builder to no avail.

Thanks

**Comment by Tapac** [comment]
First of all, you don't need a subquery here, you could filter the main query (if there is no grouping).
Also, you should not use Query constructor, try to replace it with:
```
val alias = Searches.slice(selectedColumns).selectAll().alias(Searches.tableName.toLowerCase())
val result = alias.select { 
   alias[Searches.searchRank] greater 0.2 
}.orderBy(alias[Searches.searchRank]  to SortOrder.DESC)
.limit(10).toList()
```
