### ISSUE TITLE
How to set isolation level "globaly"?

### ISSUE THREAD

**Issue by StefanHub** [JetBrains/Exposed#599]
In 0.15.1 I was able to do this:

    TransactionManager.manager.defaultIsolationLevel = Connection.TRANSACTION_SERIALIZABLE

With 0.16.1 this no longer compiles because `manager` became `internal`.

How would I do this with 0.16.1?

**Comment by mpe85** [comment]
I had the same problem and my solution is this:

```
val database = Database.connect(...)
database.transactionManager.defaultIsolationLevel = Connection.TRANSACTION_SERIALIZABLE
```

**Comment by StefanHub** [comment]
I found that too! :-)

Is this the way it should be used?

**Comment by Tapac** [comment]
@StefanHub , I've made `TransactionManager.manager` public again in 0.16.2, but @mpe85 advice is fine too especially if you work with multiple Databases in your app.
