### ISSUE TITLE
Getting Connection is closed error using suspendedTransaction/newSuspendedTransaction

### ISSUE THREAD

**Issue by fracaron** [JetBrains/Exposed#601]
I am using ktor with Exposed and I am confused with how to use of the new `suspendedTransaction/newSuspendedTransaction` introduced in 0.16.1.

I am currently using transaction this way 
```
suspend fun <T> dbQuery(block: () -> T): T =
    withContext(Dispatchers.IO) {
        transaction { block() }
    }
```

All my database operations are wrap in `dbQuery` within suspending functions like this:
```
suspend fun delete(id: Int) {
    dbQuery {
        OrganisationTable.deleteWhere { OrganisationTable.id eq id }
    }
}
```

For more complex operation, I would like to be able to call multiple of my suspending database operations within a transaction. Like this:
```
dbQuery {
    val organisation = organisationRepo.getByName(name)  // suspending function 
    organisationRepo.delete(organisation.id)  // suspending function
}
```
In this example, I get an error because the suspending functions are not called from a coroutine. Is there a way to use the introduced `suspendedTransaction/newSuspendedTransaction` to achieve this?
I have tried replacing dbQuery function with this
```
suspend fun <T> dbQuery(block: () -> T): T =
    newSuspendedTransaction(Dispatchers.IO) {
        transaction { block() }
    }
```
But I get a `org.jetbrains.exposed.exceptions.ExposedSQLException: java.sql.SQLException: Connection is closed`. Same thing with `suspendedTransaction`

**Comment by bitkid** [comment]
what i use is
`suspend fun <T> dbTransaction(database: Database, block: () -> T): TransactionResult<T> =
    suspendedTransactionAsync(Dispatchers.IO, database, false) {
        block()
    }`

**Comment by fracaron** [comment]
Thanks for the example! I have tried adding `await()` to your example to avoid to insert await() everywhere.
```
suspend fun <T> dbTransaction(database: Database, block: () -> T): T = 
suspendedTransactionAsync(Dispatchers.IO, database, false) { block() }.await()
```
But it seems to make my tests hang. Something is keeping a database connection open. Any idea on this?

**Comment by bitkid** [comment]
hmm no. it works for me when i use it like this in my ktor routes:

```dbTransaction(database) {
handler.doStuffWithDb()
}.await()```

**Comment by fracaron** [comment]
I was already running my test in `runBloking{  }`
The problem seems to come from nested transactions. I am able to use nested suspending transaction, but only within a standard blocking transaction... 

I am going to do a few more tests on this to try to figure out a solution. But seems like I might have to go back to blocking transactions.

**Comment by fracaron** [comment]
The solution I am using for now, allowing me to execute nested transactions on the IO dispatcher: 
```
suspend fun <T> dbQuery(block: suspend () -> T): T =
        withContext(Dispatchers.IO) {
            transaction { runBlocking { block() } }
        }
}
```

**Comment by Tapac** [comment]
Fixed in 0.16.2, please test it and leave a feedback

**Comment by fracaron** [comment]
Seems to be working!

Quick question on the usage of suspending transaction.
Is it ok to nest multiple `suspendedTransactionAsync` ?

**Comment by bitkid** [comment]
so how is the correct workflow now?

```newSuspendedTransaction(Dispatchers.IO) {
        transaction { block() }
    }```

?

**Comment by Tapac** [comment]
@fracaron , `suspendedTransactionAsync` code will be always executed in a new transaction, otherwise, the outer async block could commit/close transaction earlier than the inner block will be executed.

@bitkid , just `newSuspendedTransaction(Dispatchers.IO) { block() }`.

**Comment by bitkid** [comment]
doesnt work in my case .. i see all kinds of exceptions when i run my test suite

java.lang.IllegalStateException: No transaction in context.
org.h2.jdbc.JdbcSQLTimeoutException: Timeout trying to lock table {0}; SQL statement:
org.jetbrains.exposed.exceptions.ExposedSQLException: java.sql.SQLException: Connection is closed

what did work with 0.16.1 was 
`suspendedTransactionAsync(Dispatchers.IO, database, false) {
        block()
  }`

but in 0.16.2 it doesn't anymore (had to remove the false at the end)

**Comment by Tapac** [comment]
@bitkid , could you submit your test suite somewhere?

**Comment by bitkid** [comment]
it's working now!
