### ISSUE TITLE
Where can I find snapshot builds?

### ISSUE THREAD

**Issue by binkley** [JetBrains/Exposed#603]
I'd like to try out the recently-merged support for nested transactions.  Where can I find snapshot builds published?  I trawled the project Gradle files, and nothing jumped out at me.  Thanks!

----

Motivation: To use many-to-many in the DAO, and assign relationships, it requires multiple transactions.  I'd like to wrap those in an outer transaction, so I can rollback at the end during tests.

**Comment by binkley** [comment]
I'm still interested in snapshot builds.

However, my difficulty seems to have come from https://github.com/JetBrains/Exposed/issues/605.

**Comment by Tapac** [comment]
I added a new section to FAQ [about snapshots](https://github.com/JetBrains/Exposed/wiki/FAQ#q-where-can-i-find-snapshot-builds-of-exposed).
