### ISSUE TITLE
[PostgreSQL] basic transactions throwing errors (This ResultSet is Closed)

### ISSUE THREAD

**Issue by Hamzantal** [JetBrains/Exposed#604]
Hi All, PostgreSQL is giving me a couple of issues, and I'm not sure what the issue is. I have a simple main fuction at the moment with just connects to my database, and a transaction.

The error that I am receiving is ``Caused by: org.postgresql.util.PSQLException: This ResultSet is closed.`. Here is the full [stacktrace](https://hasteb.in/uqosalav.java).

The sample code I use is very simple;
```kt
Database.connect(
    url = "jdbc:postgresql://localhost:5432/library",
    user = "user",
    password = "pass",
    driver = "org.postgresql.Driver"
)

transaction {
    Books.select { Op.TRUE }.forEach(::println)
}
```

As a sanity check (to make sure the driver wasn't a culprit, I tried the following code using the java.sql package, which ran without any issues.

```kt
val connection = DriverManager.getConnection(
    "jdbc:postgresql://localhost:5432/library",
    "user",
    "pass"
)

val query = "select * from books"
val sql = connection.createStatement().apply {
    val rs = executeQuery(query)
    while(rs.next()) {
        println(rs.getString("title"))
    }
}
```

**Comment by jameswenzel** [comment]
I am having this same issue.

**Comment by jameswenzel** [comment]
I fixed this by using the version of `postgres` in the Database/DataSource section of the readme: `compile "org.postgresql:postgresql:42.2.2"`

**Comment by Hamzantal** [comment]
Good catch, I missed that and tried the newest version. I will get home in a couple of hours to confirm it works, and then I'll close this issue. I'll also submit a PR to edit the first line in the README to specify the PostgreSQL version for future programmers facing this issue.
