### ISSUE TITLE
Nested transaction partially commits outer transaction since 0.16.1

### ISSUE THREAD

**Issue by toefel18** [JetBrains/Exposed#605]
The nested transaction commits prior work of the outer transaction when the nested transaction scope ends. A rollback after the nested transaction is ineffective and results in an incorrect state.

Default nested transaction handling seems incorrect after upgrading from 0.14.1 to 0.16.1. 

(I have read https://github.com/JetBrains/Exposed/wiki/Transactions#using-nested-transactions, but it is not thourough)

Consider this nested transaction:
```kotlin 
       transaction {
            Actors.insert {   it[firstName] = "before-dummy"     }
            transaction {
                Actors.insert {   it[firstName] = "inner-dummy"     }
            }
            Actors.insert {   it[firstName] = "after-dummy"     }
            rollback()
        }
```
**Behavior version 0.14.1**
  before-dummy <- rolled back!
  inner-dummy <- rolled back!
  after-dummy <- rolled back!

**Behavior version 0.16.1 with `db.useNestedTransactions = false` (default)**
  before-dummy <- written to database  
  inner-dummy <- written to database
  after-dummy <- rolled back!
Observed behavior: The nested transaction seems to commit the first part (before-dummy) of the outer transaction when it goes out of scope. 
Expected: *it does not commit and leaves committing to the outer transaction* (or less preferred: the inner transaction only commits work in it's own scope).

**Behavior version 0.16.1 with `db.useNestedTransactions = true`**
  before-dummy <- rolled back!
  inner-dummy <- rolled back!
  after-dummy <- rolled back!
This behaves as expected (although one could also expect inner-dummy to be committed!)

Without using `db.useNestedTransactions = true` nested transactions seem broken.

Preferred solution in my opinion would be an extra parameter for `transaction(){}` which specifies the desired transaction propagation. For example:
```kotlin
transaction {
     Actors.insert {}
     transaction(REQUIRES_NEW) {
        // new transaction that commits when out of sope
     }
}
```

A bit like the options provided by Spring https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/transaction/annotation/Propagation.html

**Comment by toefel18** [comment]
Any ideas?

**Comment by Tapac** [comment]
Fixed in 0.16.3.

@toefel18 , I'll think about how to implement propagation in the future releases

**Comment by binkley** [comment]
Hi, `ChangeLog.md` lists this issue as fixed (as stated by https://github.com/JetBrains/Exposed/issues/605#issuecomment-514794493, above).  However, this issue in GitHub is still in Open state.

Should this issue be closed, or is it kept open for discussing propagation?

**Comment by Tapac** [comment]
@binkley , thnx, I just forgot to close an issue.
