### ISSUE TITLE
transaction.connection.catalog must not be null after 0.10.4 release

### ISSUE THREAD

**Issue by jeggy** [JetBrains/Exposed#606]
After upgrading from 0.10.3 to 0.10.4 I'm getting this error: 

```
java.lang.IllegalStateException: transaction.connection.catalog must not be null
```

This only happens after this line change: [https://github.com/JetBrains/Exposed/compare/0.10.3...0.10.4##diff-fe7686cefd0bc6d3c1dd26591a0a46a5L197](https://github.com/JetBrains/Exposed/compare/0.10.3...0.10.4#diff-fe7686cefd0bc6d3c1dd26591a0a46a5L197)

I have created a [repository repoducing this issue on the latest release (0.16.1)](https://github.com/jeggy/kotlin-exposed-bug)

**Comment by pinkfloyds** [comment]
I've had the same problem. You need to check whether DB URL has added a database name.
