### ISSUE TITLE
JOINing `Query` and `Table` or two `Query`s

### ISSUE THREAD

**Issue by sonicarg** [JetBrains/Exposed#607]
Hi! During a project I've been working with Exposed, I ran into a problem converting a SQL query. The sentence I tried to convert (running with no issues at all in the DB is):
```
SELECT socio.grupo, c.m
  FROM socio LEFT OUTER JOIN (
    SELECT grupo, MAX(cuenta_corriente.timestamp) AS m, importe
    FROM cuenta_corriente
    WHERE importe < 0
    GROUP BY grupo
  ) AS c ON socio.grupo = c.grupo
  ORDER BY grupo
```
I managed to _convert_ it into the following Exposed code:
```
val maxDate = Expression.build { CuentaCorrienteTable.timestamp.max() }
val lastPayment =
    CuentaCorrienteTable.slice(
        CuentaCorrienteTable.grupo, maxDate
    ).select {
        CuentaCorrienteTable.importe less (0.0).toBigDecimal()
    }.groupBy(CuentaCorrienteTable.grupo).alias("c")
(SocioTable leftJoin lastPayment).slice(
    SocioTable.grupo, lastPayment.columns[1]
).selectAll().orderBy(SocioTable.grupo).forEach { rr ->
    val lastPayDate = rr[lastPayment.columns[1]]?.toString()?.toLong()
    put(rr[SocioTable.grupo], lastPayDate?.let { DateTime(it) })
}
```
Compilation went successful, but at runtime the expression refused to work with the following log:
`Cannot join with org.jetbrains.exposed.sql.QueryAlias` _as it doesn't have PK (or something)_

As you may see, conversion _is_ exactly the same but, for an unknown reason, it refuses to `leftJoin` an `Table` object with a `Query` object.
The problem was already solved by using other mechanisms, but is there a possible bug not allowing to join a full table with the result of a subquery? Even more: _are subqueries even possible in Exposed?_

Thanks in advance!

**Comment by Tapac** [comment]
Your query is NOT exactly the same, you are missing `AS c ON socio.grupo = c.grupo` part in your query.
```kotlin
SocioTable.leftJoin(lastPayment, { SocioTable.grupo }, { lastPayment[CuentaCorrienteTable.grupo] }).selectAll()
```
