### ISSUE TITLE
Convert from joda datetime to Java datetime

### ISSUE THREAD

**Issue by MohiuddinM** [JetBrains/Exposed#612]
Java datetime is now the default datetime implementation. When will Exposed be converted to the Java implementation?

**Comment by DevSrSouza** [comment]
I believe that Exposed is not targeting just Java 8 and above, and the DateTime implementation was introduced in Java 8 if i'm correctly.

**Comment by wyaeld** [comment]
@Tapac can you clarify what the intentions are here, and if there is any ETA for the change?  Java8 time support is the only thing holding my team back from adopting.

**Comment by Tapac** [comment]
In few next releases, I plan to split Exposed on modules and extract JodaTime related code into a separate module. After that, it will be possible to create an additional module for Java time/ThreeTen implementation.

**Comment by pinkfloyds** [comment]
i'm changed to java8 datetime, #628

**Comment by Tapac** [comment]
Released in 0.18.1
https://github.com/JetBrains/Exposed/wiki/LibDocumentation#exposed-0181-and-higher
