### ISSUE TITLE
How do I map the SQL SMALLINT column type?

### ISSUE THREAD

**Issue by gertvdijk** [JetBrains/Exposed#616]
I've got an existing PostgreSQL database table with a column of type [*smallint*](https://www.postgresql.org/docs/11/datatype-numeric.html#DATATYPE-INT), but how should I map that to an Exposed *Table* column? The [documentation](https://github.com/JetBrains/Exposed/wiki/DataTypes) only lists *integer* (integer) and *long* (biginteger).

Kotlin defines the [`short` primitive type](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-short/index.html#kotlin.Short), but the below fails with `error: unresolved reference: short`:

```
val myCol: Column<Short> = short("my_smallint_col")
```

Using a regular Integer works, but this does not safeguard me from going out of range (`org.postgresql.util.PSQLException: ERROR: smallint out of range`).

**Comment by Tapac** [comment]
Will be fixed in 0.17.3
