### ISSUE TITLE
Batch Insert does not use "multirow VALUES syntax"

### ISSUE THREAD

**Issue by gertvdijk** [JetBrains/Exposed#617]
I'm using Exposed 0.16.3 DSL's batchInsert on a PostgreSQL connection like this:
```
object MyTable : Table() {
    val myCol: Column<Long> = long("mycol")
    val otherCol: Column<Long> = long("othercol")
}

data class InsertItem(val myCol : Long, val otherCol: Long)

val batchInsertObjects = listOf(
    InsertItem(1234L, 3456L),
    InsertItem(1234L, 9999L)
)

transaction {
    MyTable.batchInsert(batchInsertObjects) {
            item: InsertItem ->
        this[MyTable.myCol] = item.myCol
        this[MyTable.otherCol] = item.otherCol
    }
}
```

(The code shown above is inspired by the single-column example from the docs. Please let me know if this approach is not okay.)

## Expected query:

```
DEBUG Exposed - INSERT INTO MyTable (mycol, othercol) VALUES (1234, 3456),(1234, 9999)
```

N.B: using single statement "[multirow VALUES syntax](https://www.postgresql.org/docs/current/sql-insert.html)", for performance reasons.

As also stated in the [Exposed documentation: Batch Insert](https://github.com/JetBrains/Exposed/wiki/DSL#batch-insert), this should be in a **single** statement.

> Batch Insert allow mapping a list of entities into DB raws in one sql statement.

(raws is a typo there?)

## Actual query

As printed in logs:

```
DEBUG Exposed - INSERT INTO MyTable (mycol, othercol) VALUES (1234, 3456)
DEBUG Exposed - INSERT INTO MyTable (mycol, othercol) VALUES (1234, 9999)
```

**Comment by Tapac** [comment]
It's not an Exposed issued but Postgresql jdbc driver impementation.
Please look at `reWriteBatchedInserts` jdbc url parameter. 
https://jdbc.postgresql.org/documentation/94/connect.html

**Comment by gertvdijk** [comment]
@Tapac Thanks for your response!

However, setting `reWriteBatchedInserts=true` as option in the database URL does not seem to work. Am I missing something? Testing locally:

```          
val dbUrl = "jdbc:postgresql://${config.hostName}/${config.database}?reWriteBatchedInserts=${config.rewriteBatchInserts}"
logger.info { "DB URL: '$dbUrl'" }
val dbConnection = Database.connect(dbUrl,
    driver = "org.postgresql.Driver",
    user = config.user, password = config.password)
```

prints:

```
DB URL: 'jdbc:postgresql://localhost/postgres?reWriteBatchedInserts=true'
DEBUG Exposed - INSERT INTO MyTable (mycol, othercol) VALUES (1234, 3456)
DEBUG Exposed - INSERT INTO MyTable (mycol, othercol) VALUES (1234, 9999)
```

**Comment by Tapac** [comment]
As Exposed doesn't know anything about Postgres batch mechanism I guess it logs queries not very well.
Could you check the exact queries with and without `reWriteBatchedInserts` option?
To enable low-level logging please look at https://jdbc.postgresql.org/documentation/head/logging.html

**Comment by gertvdijk** [comment]
Thanks for the hint, I'll verify that later. But if the JDBC driver is rewriting individual INSERTs to multirow-value syntax, then it should already do that without using the batch API (`MyTable.batchInsert`) right?
