### ISSUE TITLE
Column ByteArray should not require a length

### ISSUE THREAD

**Issue by gertvdijk** [JetBrains/Exposed#618]
IIUC, the `Column<ByteArray>` type is mapped to PostgreSQL's [`bytea` column type](https://www.postgresql.org/docs/11/datatype-binary.html). It is variable length and does not even have a length attribute. In Exposed, however I'm required to provide a length as parameter:

    val data: Column<ByteArray> = binary("data", <length-parameter>)

which is then ignored, because I can insert `ByteArray`s with a longer value than specified, at least in Batch Insert. This is all quite confusing for me.

Suggestions:
* make it an optional parameter. (other dialects also don't always require you to specify a length.)
* if specified, validate the data before passing it to the database? (not sure if this is what you want in Exposed, but it seems reasonable as it also validates the type.)
* if specified, *either*
  * produce a log statement that the length specifier is not enforced/handled by this dialect. OR
  * set a [CHECK constraint](https://www.postgresql.org/docs/11/ddl-constraints.html#DDL-CONSTRAINTS-CHECK-CONSTRAINTS) to enforce the maximum length in the database

**Comment by Ingwersaft** [comment]
@gertvdijk, @Tapac, @hichem-fazai: After the merge this can be closed I think :)
