### ISSUE TITLE
id select will throw exception

### ISSUE THREAD

**Issue by zouzg** [JetBrains/Exposed#619]
Any DAO style table, If you used extend LongIdTable("xxxx") or IntIdTable("xxx"), if you select by id, for example, if i have a table like this
```
object User : LongIdTable("user") {
    val name_ = varchar("name", length = 40)
}
```
Then I use below DAO API to select
```
val users = User.select { User.id.greater(100) }.limit(100).toList()
```
It will throw exception like below:
 
![image](https://user-images.githubusercontent.com/3505708/62811315-cd15e080-bb33-11e9-8f12-ece6d28ebc2b.png)

```
Error:(61, 53) Kotlin: None of the following functions can be called with the arguments supplied: 
public final infix fun <T : Comparable<Long>, S : Long?> ExpressionWithColumnType<in ???>.greaterEq(t: Long): Op<Boolean> defined in org.jetbrains.exposed.sql.SqlExpressionBuilder
public final fun <T : Comparable<EntityID<Long>>, S : EntityID<Long>?> ExpressionWithColumnType<in EntityID<Long>>.greaterEq(other: Expression<EntityID<Long>>): Op<Boolean> defined in org.jetbrains.exposed.sql.SqlExpressionBuilder
```

While I not extend the LongIdTable, used our own id field, everythink will be OK.
```
object User : Table("user") {
    val id = long("id").autoIncrement().primaryKey()
    val name_ = varchar("name", length = 40)
}
```

**Comment by Tapac** [comment]
There are no overloaded greater/less functions for EntityID columns yet.
You could use `User.id greater EntityID(100L, User)` instead.

**Comment by zouzg** [comment]
@Tapac Yes, thanks it works. 
But it will confuse user, why not overloaded?

**Comment by Tapac** [comment]
Fixed in master. All functions (greater/greaterEq/less/lessEq) were overloaded.

**Comment by zouzg** [comment]
perfect!
