### ISSUE TITLE
Is exposed support connection pool?

### ISSUE THREAD

**Issue by zouzg** [JetBrains/Exposed#620]
I didn't see any place could config connection pool in exposed, is exposed support connection pool?

**Comment by Tapac** [comment]
You can use any connection pool you like, just prepare a `DataSource` instance and use it in `Database.connect`

You can find example with HikariCP [here](https://thebookofjoel.com/blog/kotlin-ktor-exposed-postgres).

**Comment by zouzg** [comment]
Yes, I used it success now.
