### ISSUE TITLE
Add exists() method on Query to check assert the existence of a query

### ISSUE THREAD

**Issue by fracaron** [JetBrains/Exposed#621]
Suggested Enhancement: 
Adding an `exists()` method on `Query` would allow to efficiently check the existence of a row or group of rows.
Would be the SQL equivalent of `SELECT EXISTS(SELECT 1 FROM table WHERE ...)`

Exemple: 
```FooTable.select { FooTable.id eq 5 }.exists()``` 
would be converted to: 
```SELECT EXISTS(SELECT 1 FROM FooTable WHERE id = 5)```

**Comment by Tapac** [comment]
There is `exists(Query)` function and it looks more idiomatic to SQL when you write code like:
`FooTable.slice(exists(.select { FooTable.id eq 5 }).selectAll()`

**Comment by fracaron** [comment]
I think the suggested enhancement would allow more flexibility since `exists(Query)` would return nothing if the row does not exists. Also in the case of a where condition returning multiple rows, `exists(Query)` would return a `true` value for every row.

`Query.exists()` could allow to return a single boolean in any case.

If you find this suggestion relevant, I could probably make a PR in the next weeks. If not, no problems, I can live with it as it is.

**Comment by ShreckYe** [comment]
I think there can be an alternative to solve both problems: if there is a way to `SELECT` an `Op` directly instead of from a table using `slice`, `exists` doesn't need to be changed and a single boolean will be returned. For example if we call it `selectOp`:
```kotlin
selectOp(exists(FooTable.select { FooTable.id eq 5 }).selectAll()
```

**Comment by Tapac** [comment]
I've added a Dual table to Exposed and now it's possible to write code like:
```sql
val existsOp = exists(FooTable.select { FooTable.id eq 5 }
val result = Table.Dual.slice(existsOp).selectAll().first()
val existsResult = result[existsOp]
```

**Comment by ShreckYe** [comment]
@Tapac It seems not every DB has a "dual" table. Is the going to work for PostgreSQL?

**Comment by Tapac** [comment]
Yes, the "FROM" part will be skiped for PSQL for Table.Dual.

**Comment by damienmiheev** [comment]
It looks quite complex to use.
Why don't to add something like:
`val result: Boolean = FooTable.exists { FooTable.id eq 5 }`

**Comment by Tapac** [comment]
@damienmiheev , because exists can be used as a part of a query as one of a conditions.
Your case can be simplified to:
```kotlin
val notExists = FooTable.select { FooTable.id eq 5 }.empty()
```

**Comment by gringrape** [comment]
@Tapac 
Still, as @damienmiheev mentioned, 
It looks much simpler to use exists method on Table.

For newbies, there's no need to find how to implement `exists`,
if table gives exists method, because it is more intuitive.

How do you think?

If there is nobody to work on this, I would love to contribute.

**Comment by csisy** [comment]
> [Damien (@damienmiheev)](https://github.com/damienmiheev) , because exists can be used as a part of a query as one of a conditions. Your case can be simplified to:
> 
> val notExists = FooTable.select { FooTable.id eq 5 }.empty()

Are you sure it works as expected? In Postgres, the generated SQL looks like `SELECT FooTable.id = 5 FROM FooTable LIMIT 1` and the result is either empty or a single row single column result with a 'boolean' value.

Also, the syntax is a bit different, the `select` function now expects `Expression<*>` objects (ie. columns or expressions like above).
