### ISSUE TITLE
LIKE case insensitive

### ISSUE THREAD

**Issue by WellingtonCosta** [JetBrains/Exposed#622]
How can I perform a select with like case insensitive clause?

**Comment by WellingtonCosta** [comment]
Basically I solved it by just creating an `ilike` extension function of `Op<Boolean>` type. Something like this:

`class InsensitiveLikeOp(expr1: Expression<*>, expr2: Expression<*>) : ComparisonOp(expr1, expr2, "ILIKE")`

and so

`infix fun<T:String?> ExpressionWithColumnType<T>.ilike(pattern: String): Op<Boolean> = InsensitiveLikeOp(this, QueryParameter(pattern, columnType))
`

But I don't guarantee this will work for all relational databases besides PostgreSQL.

**Comment by uuf6429** [comment]
True, this is postgres-specific, however mysql's `like` is also [case insensitive (2nd paragraph)](https://dev.mysql.com/doc/refman/8.0/en/pattern-matching.html), so theoretically, exposed should use `ILIKE` when the db connection is for postgres.

@Tapac what do you think?

**Comment by hennihaus** [comment]
When I use the solution of @wellingtoncosta I just get zero results. Any ideas what I do wrong?

**Comment by hennihaus** [comment]
I used a regular expression as a workaround:

```
class InsensitiveLikeOp(expr1: Expression<*>, expr2: Expression<*>) : ComparisonOp(
    expr1 = expr1,
    expr2 = expr2,
    opSign = "~*",
)

infix fun <T : String?> ExpressionWithColumnType<T>.ilike(pattern: String): Op<Boolean> = InsensitiveLikeOp(
    expr1 = this,
    expr2 = QueryParameter(
        value = pattern,
        sqlType = columnType,
    ),
)
```

**Comment by LhKipp** [comment]
When using the code from [wellingtoncosta](https://github.com/wellingtoncosta), the Kotlin compiler raised a type mismatch error. It's fixed by using `T` as the type of `pattern`, so the code becomes:

```Kotlin
class InsensitiveLikeOp(expr1: Expression<*>, expr2: Expression<*>) : ComparisonOp(expr1, expr2, "ILIKE")

infix fun <T : String?> ExpressionWithColumnType<T>.ilike(pattern: T): Op<Boolean> =
    InsensitiveLikeOp(this, QueryParameter(pattern, columnType))
```
