### ISSUE TITLE
"javax.sql.rowset.serial" not found when using on Android

### ISSUE THREAD

**Issue by krzema12** [JetBrains/Exposed#625]
I'm trying to add a dependency on Exposed to my Android project. I'm getting the following error during build time:

```
/home/piotr/.gradle/caches/modules-2/files-2.1/org.jetbrains.exposed/exposed/0.16.3/8a67e9a777d1b59b84aa435ef2ffc8c817f0966b/exposed-0.16.3.jar:
Error: Invalid package reference in library; not included in Android:
javax.sql.rowset.serial. Referenced from org.jetbrains.exposed.sql.BlobColumnType. [InvalidPackage]
```

How to reproduce: clone my project from this branch: https://github.com/krzema12/Time9/tree/exposed-issue . The latest commit adds a dependency on Exposed and it breaks the build.

Trying to understand the issue:
* I checked Exposed's code and it's about the `SerialBlob` class referenced here: https://github.com/JetBrains/Exposed/blob/4c7a9a464da96c8b2118ac45eaa9e8e0d7986fcf/exposed/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt#L21
* this class and the entire `javax.sql.rowset` package exists in Oracle's API (https://docs.oracle.com/javase/8/docs/api/javax/sql/rowset/serial/SerialBlob.html) and indeed doesn't exist in Android SDK (https://developer.android.com/reference/javax/sql/package-summary) 
* TODO: check if/why it works for other projects that use both Android and Exposed. So far I just found some of such repositories on GitHub, but the fact that they exist doesn't mean that they build and work fine. E.g. this issue #461 is about using Exposed with Android, and the project doesn't build straight away

If the above behavior is a bug in Exposed, would it be somehow possible to avoid using `javax.sql.rowset.serial.SerialBlob` on Android or altogether?

I'm a beginner regarding Android development, so there can be a simple explanation and solution to this issue. In such case, I think that at least Exposed docs should address this issue somehow, to make using Exposed with Android more straightforward.

**Comment by Tapac** [comment]
Should be fixed in 0.18.1. Please check
