### ISSUE TITLE
Changed behavior of transactions in 0.16.x

### ISSUE THREAD

**Issue by KennethWussmann** [JetBrains/Exposed#626]
Hey,
since `0.16.x` the behavior for transactions had a breaking change. 

I created the following project to show what I mean: https://github.com/KennethWussmann/exposed-nested

<hr>

When I create a new `User` in the database in unit tests and try to fetch it within the main source, it's not existing. I used H2 in this test but also tried it with Postgres.
The same scenario was working in `0.15.1`. (You can just switch the version in the repository above and the test passes)

I'm creating a new user like this and calling the function `getAllUsers()` from the main source:

https://github.com/KennethWussmann/exposed-nested/blob/a9ae64f15e642721af9253534b2be68f8e4620d9/src/test/kotlin/me/test/exposednested/ExposedNestedApplicationTest.kt#L11-L21

This is the function from the main source:

https://github.com/KennethWussmann/exposed-nested/blob/a9ae64f15e642721af9253534b2be68f8e4620d9/src/main/kotlin/me/test/exposednested/ExposedNestedApplication.kt#L15-L17

The outcome is, that the User that was created within the test, no longer exists in the main source which makes it hard to prepare test data.

Removing the transaction from the main source here:

https://github.com/KennethWussmann/exposed-nested/blob/a9ae64f15e642721af9253534b2be68f8e4620d9/src/main/kotlin/me/test/exposednested/ExposedNestedApplication.kt#L15

makes the test passing, but that doesn't solve the underlaying problem, because now there is a transaction in the main source missing to run the code when it's deployed.
I tried it with `useNestedTransactions` enabled and disabled with no difference. 

What is the problem here and how can this be solved?

Thank you,
Kenneth

**Comment by Tapac** [comment]
Should be fixed in 0.16.4, please try it.

**Comment by KennethWussmann** [comment]
works thanks
