### ISSUE TITLE
How to handle exception on unique constrain?

### ISSUE THREAD

**Issue by chenzhendong** [JetBrains/Exposed#63]
object PropName : Table("tblProperty") {
    val id = integer("id").autoIncrement().primaryKey()
    val name = varchar("name", 50).uniqueIndex()
}
propNameId = PropName.insert {
                                it[name] = aname
                            } get PropName.id

**I want a logic 
  if name exists 
           return id
  else
           do insert and return id
is there any simple way to write code?**

**Comment by JonLatane** [comment]
Use INSERT IGNORE.

```
fun getPropertyId(name: String) : Int? = PropName.select {
    PropName.name eq "blah"
  }.firstOrNull()?[PropName.id]

fun getOrCreatePropertyId(name: String) : Int {
  PropName.insertIgnore { it[name] = name }
  return getPropertyId(name)!!
}
```
