### ISSUE TITLE
Batched select

### ISSUE THREAD

**Issue by ps-feng** [JetBrains/Exposed#641]
Is there an interest in having a **batch select** functionality within the library? At work my team had this requirement so we rolled out our own implementation, which you can see [here](https://gist.github.com/ps-feng/93c577bb2bb0a64a3134344a9693352e).

It's inspired by Rails' [find_in_batches](https://apidock.com/rails/v5.2.3/ActiveRecord/Batches/find_in_batches) and is an alternative to `fetchSize`, which in the case of MySQL for example uses server-side cursors and requires `useCursorFetch` to be set on the [connector](https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-implementation-notes.html).

If there's such an interest, I can prepare a PR.

**Comment by Tapac** [comment]
Will be available in 0.18.2 but have to add some documentation into wiki
