### ISSUE TITLE
inList does not support multiple columns

### ISSUE THREAD

**Issue by babyfish-ct** [JetBrains/Exposed#643]
Hi

Is it possible to support inList expression for multiple columns? 

like this

.select {
    tuple(Nodes.id, Nodes.version) inList idVersionTuples
}

**Comment by Tapac** [comment]
And how it should works?
` (id = 1 and version = 2) or (id = 3 and version = 4)`
or 
`id in (1,3) and version in (2, 4)`

**Comment by babyfish-ct** [comment]
Yes, your example is right.

but
1. We often do not know the length of the list
2. We also do not want to pull the huge list from remote db server to client side and generate the long sql dyanmically

So is it possible to support it like this

MyTable
    .slice(MyTable.name, MyTable.version, MyTable.description, MyTable.imageBlob)
    select {
        tuple(MyTable.name, MyTable.version) inList 
        wrapAsExpression<Tuple<Long, Int>>(
            MyTable
                .slice(MyTable.name, MyTable.version.max())
                .selectAll()
                .groupBy(MyTable.name)
     )
}

**Comment by babyfish-ct** [comment]
> Yes, your example is right.
> 
> but
> 
> 1. We often do not know the length of the list
> 2. We also do not want to pull the huge list from remote db server to client side and generate the long sql dyanmically
> 
> So is it possible to support it like this
> 
> ```
> MyTable
>     .slice(MyTable.name, MyTable.version, MyTable.description, MyTable.imageBlob)
>     select {
>         tuple(MyTable.name, MyTable.version) inList 
>         wrapAsExpression<Tuple<Long, Int>>(
>             MyTable
>                 .slice(MyTable.name, MyTable.version.max())
>                 .selectAll()
>                 .groupBy(MyTable.name)
>      )
> }
> ```

**Comment by babyfish-ct** [comment]
My last example tells us this feature is important, this feature is supported by another java framework JOOQ, you can found these methods from its javadoc [http://www.jooq.org/javadoc/latest/org.jooq/org/jooq/impl/DSL.html](http://www.jooq.org/javadoc/latest/org.jooq/org/jooq/impl/DSL.html)

```
1. Typesafe API for the row whose field count <= 22
    @Support public static <T1> Row1<T1> row​(T1 t1)
    @Support public static <T1,​T2> Row2<T1,​T2> row​(T1 t1, T2 t2)
    @Support public static <T1,​T2,​T3> Row3<T1,​T2,​T3> row​(T1 t1, T2 t2, T3 t3)
     .... ....
    @Support public static <T1,​T2,​T3,​T4,​T5,​T6,​T7,​T8,​T9,​T10,​T11,​T12,​T13,​T14,​T15,​T16,​T17,​T18,​T19,​T20,​T21,​T22> Row22<T1,​T2,​T3,​T4,​T5,​T6,​T7,​T8,​T9,​T10,​T11,​T12,​T13,​T14,​T15,​T16,​T17,​T18,​T19,​T20,​T21,​T22> row​(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10, T11 t11, T12 t12, T13 t13, T14 t14, T15 t15, T16 t16, T17 t17, T18 t18, T19 t19, T20 t20, T21 t21, T22 t22)

2. Untypesafe API for the row whose field count > 22
    @Support public static RowN row​(Object... values)
    Create a row value expression of degree N > 22.
```

it's used like this

```
List<MyEntity> entities = context
     .select(
         MyTable.NAME, 
         MyTable.VERSION, 
         MyTable.DESCRIPTION, 
         MyTable.IMAGE_BLOB
    )
    .from(MyTable)
    .where(
        DSL.row(MyTable.NAME, MyTable.VERSION).in(
            context
                .select(MyTable.NAME, MyTable.VERSION.max())
                .from(MyTable)
                .groupBy(MyTable.NAME)
        )
    )
    .fetchInto(MyEntity.class)
```

**Comment by Tapac** [comment]
What if only Pair and Triple will be supported at the start?

**Comment by babyfish-ct** [comment]
It think pair or triple is enough :)
