### ISSUE TITLE
sqlite: How to get / use rowid?

### ISSUE THREAD

**Issue by matthjes** [JetBrains/Exposed#644]
Hi,

sqlite itself creates its own id column (rowid) and I would like to use it / get its value. Is there any way I can do this?

I currently have the following table:
```kotlin
object Entries : Table("entry") {
    val id: Column<Int> = integer("rowid").autoIncrement().primaryKey()
}
```
When I try to insert an entry:
```
val entryId = Entries.insert {
} get Entries.id
```
then I get an error stating that the `rowid` cannot be null. It's also no use to remove `autoIncrement()` and `primaryKey()`, what I need is just some kind of mapping from the generated `rowid` to my `id` property.

**Comment by serega100** [comment]
Try `object Entries : IntIdTable(name = "entry", columnName = "rowid")`

**Comment by lwis** [comment]
Exposed generates;

`CREATE TABLE IF NOT EXISTS entry (id INT PRIMARY KEY)`

While it needs to generate;

`CREATE TABLE IF NOT EXISTS entry (id INTEGER PRIMARY KEY)`

In order for SQLite to automatically alias the column to generated ROWID.

Not sure what can be done to fix this.

**Comment by Tapac** [comment]
@lwis , why you think that Exposed generate that? As I can see from code `INTEGER AUTOINCREMENT` should be used for integer autoincrement on SQLite.

**Comment by lwis** [comment]
@Tapac in debug mode Exposed dumps the SQL it's running;

```2019-10-01 07:58:16.277 [DefaultDispatcher-worker-1] DEBUG Exposed - CREATE TABLE IF NOT EXISTS entry (id INTEGER PRIMARY KEY)```

**Comment by Tapac** [comment]
>> While it needs to generate;
>
> `CREATE TABLE IF NOT EXISTS entry (id INTEGER PRIMARY KEY)`

>> Exposed dumps the SQL it's running;
>
> 2019-10-01 07:58:16.277 [DefaultDispatcher-worker-1] DEBUG Exposed - `CREATE TABLE IF NOT EXISTS entry (id INTEGER PRIMARY KEY)`

Looks like Exposed do exactly what you expect, or am I wrong?

**Comment by lwis** [comment]
@Tapac haha sorry, I realised that I put in a workaround for the table creation and forgot to check the paste...

```
object Entry : Table() {
    val id = integer("id").primaryKey()
}

fun init() {
        Database.connect(...)

        transaction {
            SchemaUtils.create(Entry)
        }
}
```

Yields;

```
2019-10-01 10:05:04.824 [DefaultDispatcher-worker-1] [] DEBUG Exposed - CREATE TABLE IF NOT EXISTS Entry (id INT PRIMARY KEY)
```

**Comment by lwis** [comment]
@Tapac will this be fixed?
