### ISSUE TITLE
VARCHAR-Column with specific character set

### ISSUE THREAD

**Issue by StefanLiebig** [JetBrains/Exposed#646]
We use MySQL and we need to create VARCHAR-Columns with the character set "utf8mb4" because "utf8" is only partialy imlemented (https://mathiasbynens.be/notes/mysql-utf8mb4).
Unfortunately, it seems to me that it is not possible to specify a character set altough I can specify a collation.

**Comment by RaySmith-ttc** [comment]
I think it’s not relevant anymore, but it can help someone.

To set the encoding for varchar-columns, you can pass the “collate” parameter for the text or varchar functions in your DAO object:

`val description = text("description", collate = "utf8mb4")`
