### ISSUE TITLE
LEFT JOIN - AND

### ISSUE THREAD

**Issue by PaulMuriithi** [JetBrains/Exposed#647]
I am wondering whether it's possible to do the following:
```
SELECT * FROM users u
LEFT JOIN addresses a ON u.id = a.userId AND a.state = 'A'
...
```

That last bit of `AND a.state = 'A'` is what am wondering how to achieve.

**Comment by Tapac** [comment]
You can use an `additionalConstraint` param, please look at example [here](https://github.com/JetBrains/Exposed/wiki/DSL#join)
