### ISSUE TITLE
Getting the greatest record from the table

### ISSUE THREAD

**Issue by BioRyajenka** [JetBrains/Exposed#650]
Hello!
I created an empty table and trying to make an SQL request which will give me the row with greates `subId` value and with field `name` equals to some value. So I write this
```
val query = Workers.slice(Workers.subId.max()).select(Workers.name eq name)
```
But when I do `Worker.wrapRows(query)`, I get the following error: `IllegalStateException: kotlin.Unit is not in record set`. What is wrong?

My worker classes are:
```
object Workers : IntIdTable() {
    val name = varchar("name", MAX_NAME_LENGTH)
    val subId = integer("sub_id")
     
    init {
        index(true, name)
    }
}

class Worker(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<Worker>(Workers)

    val name by Workers.name
    val subId by Workers.subId
}
```

Also I noticed `k.toList()` contains one element and `k.toList[0].data` is an array of nulls. Seems strange to me

**Comment by Tapac** [comment]
Your query returns max `subId` which on an empty table will be `null`.
To create an entity from Query your Query should contain all entities fields but in your case, it is only `max` expression which unrelated to Worker entity.

**Comment by BioRyajenka** [comment]
Get it. 
Is there any way to wrap result into an int directly? 
Can you please provide and example how to add the rest columns to my request? 
Thank you

**Comment by Tapac** [comment]
```kotlin
val maxIdExpression = Workers.subId.max()
val maxId = Workers.slice(maxIdExpression).select(Workers.name eq name).single()[maxIdExpression]
val maxWorker = maxId?.let { Worker[maxId] }
```

**Comment by BioRyajenka** [comment]
Thanks a lot
