### ISSUE TITLE
ORA-00972: identifier is too long. Oracle 11g

### ISSUE THREAD

**Issue by CrownlessX** [JetBrains/Exposed#654]
I'm trying to create many-to-one relation.
But alwas got issue with "identifier is too long" as exposed automatically creates 
too long foreign key(, but Oracle 11g got limitation - 30 characters.
Could you help me to bypass this issue? 
I saw few issues reported here with such problem/suggestion, but don't know if there are any workaround.

**Comment by Tapac** [comment]
Could you provide sample tables mapping which fails on create?

**Comment by CrownlessX** [comment]
Transaction attempt #0 failed: java.sql.SQLSyntaxErrorException: ORA-00972: identifier is too long
. Statement(s): CREATE TABLE TBL_CONTAINER (ID NUMBER(12) PRIMARY KEY, FK_CUSTOMER_ID VARCHAR(100) NOT NULL, CONSTRAINT **FK_TBL_CONTAINER_FK_CUSTOMER_ID_CUSTOMER_ID** FOREIGN KEY (FK_CUSTOMER_ID) REFERENCES TBL_STATUS(CUSTOMER_ID) ON DELETE CASCADE)

```
object ContainerTable : IntIdTable("TBL_CONTAINER") {
    val customerId = reference("fk_customer_id", StatusTable, onDelete = ReferenceOption.CASCADE)

}

class Container(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<Container>(ContainerTable)

    var customerId by Status referencedOn ContainerTable.customerId
}

class Status(id: EntityID<String>) : Entity<String>(id) {
    companion object : EntityClass<String, Status>(StatusTable)

}

object StatusTable : IdTable<String>("TBL_STATUS") {
    override val id = varchar("customer_id", 100).entityId().primaryKey()
}
```
