### ISSUE TITLE
IllegalArgumentException thrown when List<Deferred<T>>.awaitAll() is used on List<TransactionResult<T>>

### ISSUE THREAD

**Issue by emanguy** [JetBrains/Exposed#658]
Assume `augmentItem(item)` is just a private function which executes 3 queries across various tables and I have nested transactions enabled on the DB.

If I do:
```kotlin
newSuspendedTransaction(Dispatchers.IO) {
  val listOfItems = /* Transaction extension, invokes suspendedTransaction and does a query */
  val results = listOfItems.suspendedTransactionAsync { augmentItem(item) }.awaitAll()
}
```
It will fail on the awaitAll, saying the transaction is already closed.

On the other hand, the following works:
```kotlin
newSuspendedTransaction(Dispatchers.IO) {
  val listOfItems = /* Transaction extension, invokes suspendedTransaction and does a query */
  val results = listOfItems.suspendedTransactionAsync { augmentItem(item) }.map { it.await() }
}
```

I'm 99% certain this is a bug given TransactionResult inherits from Deferred. This occurs on Exposed 1.17.6.

**Comment by Tapac** [comment]
> I'm 99% certain this is a bug given TransactionResult inherits from Deferred. 

You are right. After some debug I faced that only inheritors of `async` could work normally with `awaitAll` while TransactionResult just delegates to `async`. 

I thinking about remove TransactionResult and just use a simple `async` instead. What do you think?

**Comment by emanguy** [comment]
Yeah, that seems to be a good way to move forward. Let me know if I can do anything to help.
