### ISSUE TITLE
Timeout if sql takes more than 2 seconds to execute

### ISSUE THREAD

**Issue by shdatta** [JetBrains/Exposed#66]
Hi, I am using latest version of exposed and I was getting following 
warning WARN 70808 --- [pool-2-thread-1] Exposed                                  : Long query: [2113ms] .

I am OK with my query taking more than 2 seconds to execute. But it looks like this is hard coded in Transaction.kt in variable warnLongQueriesDuration and I get exception. Can you make this configurable or is there any other way around.

Thanks

**Comment by Tapac** [comment]
I've made `warnLongQueriesDuration` an optional, so you have to initialize it implicit if you want to use that kind of a warning.
Before that change will be released you can set this variable to some large value within your `transaction{ }` block to prevent a warning.

**Comment by shdatta** [comment]
Thanks
