### ISSUE TITLE
SQLite autoincrement columns are not created

### ISSUE THREAD

**Issue by ispbox** [JetBrains/Exposed#669]
I tried to create integer autoincremented column via Exposed DSL. In debug I see that SQLite dialect is properly selected, but both variants I tried doesn't work.

This definition:
```
object Users : Table("users") {
    val id = integer("id").primaryKey().autoIncrement()
}
``` 
gives:
```
SQL: CREATE TABLE IF NOT EXISTS users (id INTEGER AUTOINCREMENT NOT NULL, CONSTRAINT pk_users PRIMARY KEY (id))

org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (near "AUTOINCREMENT": syntax error)
```

The same is created without .primaryKey()

Correct SQL in this case should be:
```
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY ASC)
or
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT)
```
according to https://www.sqlite.org/autoinc.html.
Probably SQLiteDialect should be somehow updated?

**Comment by ispbox** [comment]
Does anyone has the same problem?
My current workaround is direct SQL statements:
```
transaction {
           exec("CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY ASC)")
           SchemaUtils.create(/*Other tables without autoincrement*/)
}
```

**Comment by ispbox** [comment]
I found two other possible solutions.
1. Reverse order: 
```
integer("id").autoIncrement().primaryKey()
```
- let autoincrement be before primary key. Not intuitive, but works.

2. Use inheritance from IntIdTable that does the same trick:
```
object Users : IntIdTable("users")
```

**Comment by Tapac** [comment]
Fixed in master and will be available soon.
