### ISSUE TITLE
OptionalReferrersOn is not availible

### ISSUE THREAD

**Issue by Aileron1410** [JetBrains/Exposed#67]
version - 7.4
Entity.kt:  
    infix fun referrersOn(column: Column<EntityID<ID>>) = referrersOn(column, false)

    fun referrersOn(column: Column<EntityID<ID>>, cache: Boolean) = Referrers(column, this, cache)

    fun optionalReferrersOn(column: Column<EntityID<ID>?>, cache: Boolean = false) = OptionalReferrers(column, this, cache)
---------------------------------------------------------------------------------------------------------------
OptionalReferrersOn is realized, but not availible

**Comment by Tapac** [comment]
@Aileron1410 , what do you mean by "not available"?
optionalReferrersOn is not infix function, so you have to use it in usual way:
```
class Foo() : Entity() {
 val bar by Bar.optionalReferrersOn(BarTable.foo) 
}
```

**Comment by Aileron1410** [comment]
thank you, it helps
