### ISSUE TITLE
Does Exposed support dynamic table name?

### ISSUE THREAD

**Issue by taylancapraz** [JetBrains/Exposed#672]
Hi,

I'm developing a spring boot application and need to update the table name according to the configuration.

For example, assume that my tables store user data, and each country has different table. I want to provide company name as environment variable, and expect my app to connect correct table.
ie: table name as turkey_user, germany_user etc. As a general rule, {companyName}_user

I couldn't find a way to do this. Is there anyone who can help me?

**Comment by Tapac** [comment]
You could try something like:
```kotlin
abstract class DynamicTable : Table("") {
    override val tableName: String
        get() = internalTableName
                
    var internalTableName = ""
}
```

**Comment by taylancapraz** [comment]
Thanks for explanation, it worked.
