### ISSUE TITLE
wrong versions published on bintray

### ISSUE THREAD

**Issue by FlorianDold** [JetBrains/Exposed#673]
On bintray, [version 0.17.6](https://bintray.com/kotlin/exposed/exposed/0.17.6) of Exposed is published.  However, the repository does not contain any mention of 0.17.6.

Furthermore, version 0.17.5 in the git repository does not match 0.17.5 on bintray.  If you look at [Table.kt](https://github.com/JetBrains/Exposed/blob/39ab1c1b7883aeeb3085cd6c6db8cdaa6119e17f/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt), the version in the git repo has ` fun blob(name: String): Column<ExposedBlob>`, while the version on bintray still has the older `fun blob(name: String): Column<Blob>`.

**Comment by Tapac** [comment]
0.17.x versions are published and developed in a 0.17.4 branch. At the moment master branch contains upcomming 0.18.1 version
