### ISSUE TITLE
renaming variable in documentation sample leads to code crash 

### ISSUE THREAD

**Issue by pavlov200912** [JetBrains/Exposed#675]
Take SQL DSL sample and rename "object Cities" to "object "object "UsersTable" , you will get 
exception "WARN Exposed - Transaction attempt #0 failed: org.h2.jdbc.JdbcSQLException: Column "CITY_ID" not found; ... "

**Comment by Tapac** [comment]
@pavlov200912, it's because there is also `object Users : IntIdTable()` which will create `UsersTable` table in a database too.
