### ISSUE TITLE
Is filtered count possible?

### ISSUE THREAD

**Issue by izzyreal** [JetBrains/Exposed#681]
I'm trying to express this query in Exposed DSL:
```
select events.id, events.starts_at,
count(participants.user_id) filter (where participants.coordinator = true),
count(participants.user_id) filter (where participants.coordinator = false)
from events left outer join participants on (id = event_id) group by id
```
I currently have this, but I don't know how to do filtered counts:
```
(Events leftJoin Participants)
.slice(Events.id, Events.startsAt, Participants.userId.count())
.selectAll()
```

**Comment by Tapac** [comment]
Is this some specific SQL dialect extension? Standard SQL doesn't support `count ... filter`.
I guess you could workaround it with `sum + if` constuction

**Comment by izzyreal** [comment]
The `filter` clause in conjunction with `count` is mentioned in [this late SQL:2003 draft](http://www.wiscorp.com/sql_2003_standard.zip), see page 529.

I will try your suggested workaround, many thanks. If you have a gist/snippet/example of what `sum + if` looks like in a line of Exposed code, that'd be very helpful.

**Comment by izzyreal** [comment]
Could you provide an example? I can't find anything on a `sum + if` construction.

**Comment by Tapac** [comment]
You may define your own function like this:
```kotlin
fun <T> Expression<T>.countWithFilter(condition: Expression<Boolean>) : Expression<Int> = object : Function<Int>(IntegerColumnType()) {
    override fun toQueryBuilder(queryBuilder: QueryBuilder)= queryBuilder {
        +"COUNT("
        +this@countWithFilter
        +") FILTER (WHERE "
        +condition
        +")"
    }
}
```

**Comment by izzyreal** [comment]
Many thanks, I will do that.
