### ISSUE TITLE
Is there a way to create table objects, data classes and mapping with less boilerplate?

### ISSUE THREAD

**Issue by AdityaAnand1** [JetBrains/Exposed#685]
To add a single new field, I have to carefully add it in three places:

![image](https://user-images.githubusercontent.com/13274079/68925574-48c5a000-07a9-11ea-83e0-0ef6088f07be.png)

Surely there'd be some way to automatically correlate varchars to Strings and integers to Int along with the query returning the results in an easily consumable format? Am I missing something?

**Comment by Tapac** [comment]
Duplicate of #24

**Comment by Tapac** [comment]
@AdityaAnand1 , also, take a look at https://github.com/TouK/krush
