### ISSUE TITLE
How about some documentation?

### ISSUE THREAD

**Issue by AdityaAnand1** [JetBrains/Exposed#687]
🙏 

Would certainly help with adoption. The library is very hard to reason about, I find that I have to frequently resort to looking for examples in other issues/SO questions etc. Some JavaDoc would be great 😁 

![image](https://user-images.githubusercontent.com/13274079/68943394-1d56ab80-07d1-11ea-9d34-f0cb161703e2.png)

**Comment by bog-walk** [comment]
An update about documentation:

We are actively working towards improving KDocs throughout the codebase, as well as enhancing and publishing all Wiki documentation and samples to an Exposed website.

If you're interested, here is a [link](https://blog.jetbrains.com/kotlin/2023/08/exposed-moving-forward/) to the most recent official blog post regarding our plans moving forward.
