### ISSUE TITLE
0.18.1 cannot be used with the Java platform module system (Java 9+)

### ISSUE THREAD

**Issue by mpe85** [JetBrains/Exposed#689]
Some of the exposed modules introduced in 0.18.1 use the same packages multiple times, e.g. `org.jetbrains.exposed.dao` and `org.jetbrains.exposed.sql`.
This prevents 0.18.1 to be used in a project with the Java 9 module system because it does not allow multiple modules to export the same package.

This is the compiler error that is raised:
`error: the unnamed module reads package org.jetbrains.exposed.dao from both exposed.dao and exposed.core`

The package structure must be refactored to make 0.18.x compatible with the JPMS (A package must not be used in more than one module).

**Comment by mpe85** [comment]
I suggest to use these packages instead:

exposed-core:
`org.jetbrains.exposed.core.dao`
`org.jetbrains.exposed.core.sql`

exposed-dao:
`org.jetbrains.exposed.dao`

exposed-java-time:
`org.jetbrains.exposed.javatime.sql`

exposed-jdbc:
`org.jetbrains.exposed.jdbc.sql.statements`

exposed-joda-time:
`org.jetbrains.exposed.jodatime.sql`

exposed-spring-boot-starter:
`org.jetbrains.exposed.spring`

This will resolve the package name clashes.
What do you think?

**Comment by Tapac** [comment]
I was trying something similar yesterday but want to test how much `re-imports` it will require for end-users.

As I'm not very aware of Java 9 module system problems could you tell me if it's ok or not to make:
exposed-core:
`org.jetbrains.exposed.dao.id`

exposed-dao:
`org.jetbrains.exposed.dao`

Will java 9 complain about sub packages with shared path in different modules?

**Comment by mpe85** [comment]
> exposed-core:
> `org.jetbrains.exposed.dao.id`
> 
> exposed-dao:
> `org.jetbrains.exposed.dao`

This is perfectly fine, the JPMS will not complain about it. It have already seen other libraries doing it this way.

**Comment by Tapac** [comment]
Fixed in 0.19.1
