### ISSUE TITLE
Is there a way to automatically get created_at, last_modified_at columns in tables?

### ISSUE THREAD

**Issue by AdityaAnand1** [JetBrains/Exposed#691]

**Comment by prayzzz** [comment]
This should help you:
https://github.com/JetBrains/Exposed/wiki/DAO#auto-fill-created-and-updated-columns-on-entity-change

**Comment by AdityaAnand1** [comment]
Thanks, it's a bit hard to reason about, the whole thing is entwined with the IntIdTable and IntEntity. I still haven't been able to isolate just that part of the logic. A minimal example would make much better documentation.

Just my two cents 😄
