### ISSUE TITLE
Cross Database Queries

### ISSUE THREAD

**Issue by HawkEye4** [JetBrains/Exposed#692]
It is possibile to create a join that involves two different databeses, like in SQL SERVER? Ex: database1.dbo.tableName JOIN database2.dbo.tableName

**Comment by Tapac** [comment]
Duplicate of #145

**Comment by HawkEye4** [comment]
I expressed myself badly, I have a situation where all databases have a prefix, example:

- prefix_databaseName

Now I would like to know if it is possible to dynamically assign that prefix and make queries, since I could have different databases with different prefixes.

**Comment by Tapac** [comment]
@HawkEye4 , you could try https://github.com/JetBrains/Exposed/issues/672#issuecomment-548823576 approach

**Comment by HawkEye4** [comment]
Thanks, that's just what I needed.
