### ISSUE TITLE
DAO update dynamic columns

### ISSUE THREAD

**Issue by byadav-blk** [JetBrains/Exposed#702]
Following is my model,

```
object ExposedUser : Table("user") {
    val id = integer("id").autoIncrement().primaryKey()
   var firstName = varchar("first_name", 150)
    var lastName = varchar("last_name", 150)
    var email = varchar("email", 150).nullable()
}


```

I'll be getting dynamic column name and value that will be updated in the model.
I have filtered the columns that are to be updated,

`val filterColumn = ExposedUser.columns.filter { jsonString.contains(it.name.toCamelCase()) };
`

jsonString contains list of of columns.
filterColumn contains the columns those are to be updated.
Now how can I dynamically select the column and update their values ???

**Comment by Tapac** [comment]
```kotlin
ExposedUser.update { statement ->
   filterColumn.forEach { column -> 
       statement[column] = value
   }
}
```
?

**Comment by bvjebin** [comment]
How to do type casting here based on column types if needed?

**Comment by Tapac** [comment]
Miss to answer, @bvjebin sorry.

You can cast column to Column<Any?> if you are sure that value has proper type.
```kotlin
val filterColumnAndValue : List<Pair<Column<*>, Any?>> = ...
ExposedUser.update { statement ->
   filterColumnAndValue.forEach { (column, value) -> 
       statement[column as Column<Any?>] = value
   }
}
```

**Comment by bog-walk** [comment]
Please reopen this issue if the problem requires more answers.
