### ISSUE TITLE
Add CustomOperator for not-existant SQL binary operators

### ISSUE THREAD

**Issue by gelineau** [JetBrains/Exposed#703]
`CustomFunction` allows to make an exposed `Function` object corresponding to a SQL function.

However, I did not find a way to make an exposed `Function` object corresponding to a SQL binary operator (for example `DIV`).

I added this to my code:
``` 
        // create an Exposed object corresponding to a SQL binary operator
        // Inspired from CustomFunction
        open class CustomOperator<T>(val operatorName: String, _columnType: IColumnType, val expr1: Expression<*>, val expr2: Expression<*>) : Function<T>(_columnType) {
            override fun toSQL(queryBuilder: QueryBuilder): String = buildString {
                append("( ${expr1.toSQL(queryBuilder)} $operatorName ${expr2.toSQL(queryBuilder)} )")
            }
        }
```

Is there a better way of doing?
Should I make a PR to propose my code upstream?

**Comment by Tapac** [comment]
@gelineau , sure, please file a PR, but please check the latest Exposed version, as `toSQL(queryBuilder: QueryBuilder)` was deprecated recently

**Comment by hichem-fazai** [comment]
related to #753 . You can use binary operator (like DIV) this way : ([here](https://github.com/JetBrains/Exposed/pull/753#issuecomment-573457198))

**Comment by gelineau** [comment]
thanks
