### ISSUE TITLE
Not enought documentation

### ISSUE THREAD

**Issue by iamthevoid** [JetBrains/Exposed#706]
Exposed seems to be great, but why there are not Javadoc in sources? It is hard to fetch little crumbs of documentation from google.

**Comment by bog-walk** [comment]
An update about documentation:

We are actively working towards improving KDocs throughout the codebase, as well as enhancing and publishing all Wiki documentation and samples to an Exposed website.

If you're interested, here is a [link](https://blog.jetbrains.com/kotlin/2023/08/exposed-moving-forward/) to the most recent official blog post regarding our plans moving forward.
