### ISSUE TITLE
Trying to use the primary ID as a reference column causes schema creation to try and create the column twice

### ISSUE THREAD

**Issue by Garethp** [JetBrains/Exposed#709]
I've got a use-case where I'm trying to describe an existing database schema where we have a main table and a child table. The primary index of the child table is the join value of the primary index of the main table. In my tests, when I'm running a `SchemaUtils.create`, exposed tries to create the schema with the primary index of the child table twice because I've defined it as a reference column.

The code works fine on an existing schema, but the schema creation itself has an issue.

#### Code to reproduce
```kotlin
import org.jetbrains.exposed.dao.EntityID
import org.jetbrains.exposed.dao.IntEntity
import org.jetbrains.exposed.dao.IntEntityClass
import org.jetbrains.exposed.dao.IntIdTable
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.SchemaUtils
import org.jetbrains.exposed.sql.transactions.transaction
import org.junit.jupiter.api.Test
import kotlin.test.assertEquals

object MainTable : IntIdTable("main", "main_id") {
    val value = varchar("value", 100)
}

class Main(id: EntityID<Int>): IntEntity(id) {
    companion object : IntEntityClass<Main>(MainTable)

    var value by MainTable.value
    val child by Child referrersOn ChildTable.main
}

object ChildTable : IntIdTable("child", "child_id") {
    val main = reference("child_id", MainTable)
    val childValue = varchar("child_value", 100)
}

class Child(id: EntityID<Int>): IntEntity(id) {
    companion object : IntEntityClass<Child>(ChildTable)

    var main by Main referencedOn ChildTable.main
    var childValue by ChildTable.childValue
}

class TestTest {

    @Test
    fun testReference() {
        Database.connect("jdbc:h2:mem:test", driver = "org.h2.Driver")

        transaction {
            SchemaUtils.create(MainTable, ChildTable)

            val main = Main.new {
                value = "main val"
            }

            Child.new {
                this.main = main
                childValue = "child val"
            }

            main.refresh()
            assertEquals(main.child.count(), 1)
            assertEquals(main.child.first().childValue, "child val")
        }
    }
}
```

#### Error Received
```
org.jetbrains.exposed.exceptions.ExposedSQLException: org.h2.jdbc.JdbcSQLSyntaxErrorException: Duplicate column name "CHILD_ID"; SQL statement:
CREATE TABLE IF NOT EXISTS CHILD (CHILD_ID INT AUTO_INCREMENT PRIMARY KEY, CHILD_ID INT NOT NULL, CHILD_VALUE VARCHAR(100) NOT NULL, CONSTRAINT FK_CHILD_CHILD_ID_MAIN_ID FOREIGN KEY (CHILD_ID) REFERENCES MAIN(MAIN_ID) ON DELETE RESTRICT ON UPDATE RESTRICT) [42121-200]
```

#### Expected Behavior
It should only try to create the `CHILD_ID` column once

**Comment by Tapac** [comment]
`IntIdTable` represents Table with auto-increment column which will be auto-created with `columnName`.
In your case, you defined `ChildTable` with one `child_id` integer auto-increment column and another `child_id` column referencing to `ParentTable`. That's why Exposed generate such DDL script.

I guess that you should rename one of these columns (for example, to `val main = reference("main_id", MainTable)`)

**Comment by Garethp** [comment]
Sorry if I didn't make it clear, but the point is that I'm trying to model a pre-existing legacy database. Renaming the column isn't really an option. I agree that in normal, well-normalized databases you wouldn't have a case where the main id of the row is also a reference to another table, but I'd think that this is a case that Expose should be able to handle

**Comment by Tapac** [comment]
Ok, I see. If you don't need an auto-increment column, but just a reference + primaryKey try:
```
object ChildTable : IdTable<Int>("child") {
    val main = reference("child_id", MainTable).primaryKey()
    override val id : EntityID<Int> get() = main
    val childValue = varchar("child_value", 100)
}
```

**Comment by Garethp** [comment]
That works well, thank you

**Comment by newcaiosantos** [comment]
.primaryKey() is deprecated

This worked for me:

```
object Professionals : Table("professional") {
    val id = reference("id", Users)
    override val primaryKey = PrimaryKey(id)
    // ...
}
```
