### ISSUE TITLE
Drop joda-time

### ISSUE THREAD

**Issue by tashburn** [JetBrains/Exposed#720]
The joda-time library is used by Exposed, but joda-time is in maintenance mode and advises switching to the java.time.* classes.

Having joda-time creates the need to convert to/from the native java time classes (e.g. LocalDate, LocalDateTime, ZonedDateTime).

I'd suggest switching to use the java-native time classes now.

**Comment by Tapac** [comment]
There is already support for java time api via a separate module. Please check the documentation: https://github.com/JetBrains/Exposed/wiki/LibDocumentation#exposed-0181-and-higher

**Comment by tashburn** [comment]
Ah! Thanks.

**Comment by BorzdeG** [comment]
use `exposed-java-time` instead of `exposed-jodatime`: https://github.com/JetBrains/Exposed/wiki/LibDocumentation#exposed-0181-and-higher
