### ISSUE TITLE
Is there a way to use Spring Data Sort?

### ISSUE THREAD

**Issue by taylancapraz** [JetBrains/Exposed#730]
Hi, 

I'm developing a Spring Boot application, and I need to let client to sort my list. From client, I get Spring Data Pageable as input, and it includes page number, page size and sort parameters. 

How can I use this object with exposed. I can get Sort object as pageable.sort. But, I cannot use it with exposed. 

Example use of Java pageable with Spring Data without exposed.
https://docs.spring.io/spring-data/rest/docs/2.0.0.M1/reference/html/paging-chapter.html

**Comment by Tapac** [comment]
You can use `limit` + `orderBy` to implement this:
```kotlin
val orderByList = page.sort.map { order ->
    YourTable.columns.single { it.name == order.property } to SortOrder.valueOf(order.direaction.name)
}
YourTable.selectAll().orderBy(*orderByList.toTypedArray()).limit(page.pageSize, page.offset)
```
I wasn't test it but you should get the idea.

**Comment by taylancapraz** [comment]
Thanks for the idea, I solved my problem with your idea. 
In my project, I wrote an extension to Query class, and all my unit tests are passed. 

I'll create a PR soon. 
``` kotlin
fun Query.pageable(page: Pageable, table: Table): Query {
    page.sort.forEach { order ->
        val column = table.columns.firstOrNull { it.name == order.property } ?: throw InvalidOrderParameter()
        val sortOrder = SortOrder.valueOf(order.direction.name)
        val statement = column to sortOrder
        this.orderBy(statement)
    }
    this.limit(page.pageSize, page.offset.toInt())
    return this
}
```
