### ISSUE TITLE
DAO vs DSL, pros and cons?

### ISSUE THREAD

**Issue by AdityaAnand1** [JetBrains/Exposed#735]
It is quite a bit hard to decide which to pick as the examples look extremely similar, would be a great idea to list down specifically the differences between the two approaches.

IMO, the library should offer a single opinionated approach, pick a winner, so to speak.

**Comment by Tapac** [comment]
Both approaches have use for different use-cases, and here comes another one "DAO" (#24).

**Comment by jlengrand** [comment]
I read the mentioned issue and imho the question was left unanswered. I read this article (https://medium.com/@OhadShai/bits-and-blobs-of-kotlin-exposed-jdbc-framework-f1ee56dc8840), which is not perfect and is biased, but gives a good description of the differences.
