### ISSUE TITLE
All DSL Enums are broken after using DAO enum 

### ISSUE THREAD

**Issue by karpovsp** [JetBrains/Exposed#738]
Noticed this after upgrading from 0.9.0 to 0.17.7. 

If an enum is modified using the Exposed DAO, all subsequent updates/inserts that involve enums using DSL will fail with the following exception: `java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Enum (java.lang.String and java.lang.Enum are in module java.base of loader 'bootstrap')`

Here is a code sample to illustrate this issue:

```
enum class TestEnum1 {
    A,
    B
}

object Table1 : IntIdTable("table1") {
    val enum1 = (customEnumeration("enum1", "ENUM('A', 'B')", { value -> TestEnum1.valueOf(value as String) }, { it.name }))
}

class Table1Entity(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<Table1Entity>(Table1)
    var enum1 by Table1.enum1
}

Table1Entity.new {
    enum1 = TestEnum1.A
}

val table1Entity = Table1Entity.find { Table1.enum1.eq(TestEnum1.A) }.single()
table1Entity.enum1 = TestEnum1.B


assertFailsWith<ClassCastException> {
    Table1.update {
        it[enum1] = TestEnum1.A
    }
}
```

**Comment by Tapac** [comment]
What database do you use?

**Comment by karpovsp** [comment]
I tested this on the H2 in-memory DB

**Comment by Tapac** [comment]
Could you please check the problem on the latest Exposed as I add your case to the test and it passed fine?

**Comment by karpovsp** [comment]
I'm using the latest Exposed version (0.17.7)

Notice that test passing means that there is a problem because I'm doing `assertFailsWith<ClassCastException>`

**Comment by Tapac** [comment]
Sorry link to the latest version was broken since the module split. Now it updated and should be referenced to 0.19.3.
https://github.com/JetBrains/Exposed/wiki/LibDocumentation#exposed-0181-and-higher 
Also, might be useful https://github.com/JetBrains/Exposed/wiki/Migration-Guide

I just actualized an existing test which tests different case for customEnumeration

**Comment by karpovsp** [comment]
Thanks! I will try upgrading to 0.19.3 and will post here on whether that helps or not
