### ISSUE TITLE
Could I merge these 2 fun into one to reduce duplicate code

### ISSUE THREAD

**Issue by chenzhendong** [JetBrains/Exposed#74]
The problem is caused by InsertStatement and UpdateStatment have no common parent

fun assgin(it: InsertStatement<Number>, o: JsonObject) {
        val cols = it.table.columns
        for (col in cols) {
            var type = col.columnType.sqlType()
            val idx = type.indexOfAny(listOf(" ", "("))
            type = if (idx > 0) type.substring(0, idx) else type
            if (o.containsKey(col.name)) {
                if (col.name == "hashedPassword") {
                    val p = o.getString("hashedPassword")
                    o.put("hashedPassword", createHashString(p))
                }
                when (type) {
                    "INT" -> it.set<Int>(col as Column<Int>, o.getInteger(col.name))
                    "VARCHAR" -> it.set<String>(col as Column<String>, o.getString(col.name))
                    "DATE" -> it.set<DateTime>(col as Column<DateTime>, formateDate(o.getString(col.name)))
                    "DECIMAL" -> it.set<Double>(col as Column<Double>, o.getDouble(col.name))
                }
            }
        }
    }

    fun assgin(it: UpdateStatement, o: JsonObject) {
        val cols = it.targetsSet.columns
        for (col in cols) {
            var type = col.columnType.sqlType()
            val idx = type.indexOfAny(listOf(" ", "("))
            type = if (idx > 0) type.substring(0, idx) else type
            if (o.containsKey(col.name)) {
                if (col.name == "hashedPassword") {
                    val p = o.getString("hashedPassword")
                    o.put("hashedPassword", createHashString(p))
                }
                when (type) {
                    "INT" -> it.set<Int>(col as Column<Int>, o.getInteger(col.name))
                    "VARCHAR" -> it.set<String>(col as Column<String>, o.getString(col.name))
                    "DATE" -> it.set<DateTime>(col as Column<DateTime>, formateDate(o.getString(col.name)))
                    "DECIMAL" -> it.set<Double>(col as Column<Double>, o.getDouble(col.name))
                }
            }
        }
    }

**Comment by Tapac** [comment]
Maybe something like this can help:
```
fun UpdateBuilder<*>.assign(o: JsonObject) {
    val cols = targets.first().columns
    for (col in cols) {
        var type = col.columnType.sqlType()
        val idx = type.indexOfAny(listOf(" ", "("))
        type = if (idx > 0) type.substring(0, idx) else type
        if (o.containsKey(col.name)) {
            if (col.name == "hashedPassword") {
                val p = o.getString("hashedPassword")
                o.put("hashedPassword", createHashString(p))
            }
            when (type) {
                "INT" -> set(col, o.getInteger(col.name))
                "VARCHAR" -> set(col, o.getString(col.name))
                "DATE" -> set(col, formateDate(o.getString(col.name)))
                "DECIMAL" -> set(col, o.getDouble(col.name))
            }
        }
    }
}
```

**Comment by chenzhendong** [comment]
test your code but failed to compile on 4 set method

[ERROR] Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.0.5:compile (compile) on project capamc-web: Compilation failure: Compilation failure:
[ERROR] Dao.kt:[67,30] Type inference failed: Cannot infer type parameter S in operator fun <S> set(column: Column<S>, value: S?): Unit
[ERROR] None of the following substitutions
[ERROR] (Column<CapturedTypeConstructor(*)>,CapturedTypeConstructor(*)?)
[ERROR] (Column<Int>,Int?)
[ERROR] can be applied to
[ERROR] (Column<*>,Int!)

**Comment by Tapac** [comment]
You should cast col to same type as you want to set, e.g.
```
"INT" -> set(col as Column<Int>, o.getInteger(col.name))
```

**Comment by chenzhendong** [comment]
Thanks for a quick response.  
I try change my code  from assign(it, json)  to it.assign(json) style but it won't compile.
I think it might cause by you define a static method, and "it" is a instance.  Any way to get it work? Could we use reflection to call a static method from a instance?

**Comment by Tapac** [comment]
I'm not sure that I've understand your problem, but that code compiles just fine: 
``` 
fun <T:Any> UpdateBuilder<*>.set(col: Column<*>, value: T?) = set(col as Column<T>, value)

fun UpdateBuilder<*>.assign(o: JsonObject) {
    val cols = targets.first().columns
    for (col in cols) {
        var type = col.columnType.sqlType()
        val idx = type.indexOfAny(listOf(" ", "("))
        type = if (idx > 0) type.substring(0, idx) else type
        if (o.containsKey(col.name)) {
            if (col.name == "hashedPassword") {
                val p = o.getString("hashedPassword")
                o.put("hashedPassword", p?.hashCode()?.toString())
            }
            when (type) {
                "INT" -> set(col, o.getInteger(col.name))
                "VARCHAR" -> set(col, o.getString(col.name))
                "DECIMAL" -> set(col, o.getDouble(col.name))
            }
        }
    }
}

fun usageExample() {
    val table = object : IntIdTable() {
        val foo = text("foo")
        val bar = integer("bar")
    }
    
    table.insert { 
        it[table.foo] = "text"
        it.assign(JsonObject())
    }

    table.update(where = { table.foo eq "text"}){
        it[table.foo] = "text2"
        it.assign(JsonObject())
    }
}
```

**Comment by chenzhendong** [comment]
Works to me now,  some silly typo error.  Thanks a lot
