### ISSUE TITLE
Generify Coalesce function to accept Expression<*>

### ISSUE THREAD

**Issue by Evgen25176542** [JetBrains/Exposed#742]
now we have the next signature of coalesce:
`class Coalesce<out T, S:T?, R:T>(private val expr: ExpressionWithColumnType<S>,
                                 private val alternate: ExpressionWithColumnType<out T>): Function<R>(alternate.columnType)`

and it's OK for columns, but when I need to use it in (i.e. Update statement, SET block), I have to re-write it with CaseWhen. why not generify this function and provide nullable counterpart of stringParam() ?

`val transcriptionCase = CaseWhen<String?>(WordTable.tags)
            .When(stringLiteral(word.transcription ?: "NULL") eq "NULL", WordTable.tags)
            .Else(stringLiteral(word.transcription!!))`
instead of simple
`Coalesce(stringParam(word.transcription), transcription)`

desired SQL:
`UPDATE Word 
 SET transcription=COALESCE(NULL, transcription)
 ...`
current SQL:
`UPDATE Word 
 SET transcription=CASE Word.tags WHEN 'NULL' = 'NULL' THEN Word.tags ELSE 'NULL' END
 ...`

**Comment by Tapac** [comment]
What the case for providing NULL as the first argument for `coalesce`? Or it's just the sample of an expression that could return null?

**Comment by Evgen25176542** [comment]
Yes, first argument in the sample expression returns NULL and it's just an example.
It's better to see that I can't it process NULL 'normally', I have to pass it as String in CaseWhen and check it for nullability in weird manner.
Exposed isn't documented good (for now). And I didn't find any other options for that case in sources.

**Comment by Evgen25176542** [comment]
`nullable counterpart of stringParam()`
And, again. It could help to get rid of involuntary unchecked casts while using other functions when we're sure that column doesn't contain NULL value. i.e. the same CaseWhen():

```
WordTable.tags ~ Column<String?>
stringParam("something") ~ Expression<String>

When(WordTable.tags like "%expr%", Concat("", WordTable.tags, stringParam("str") as Expression<String?>))
```

After **like** operator in SQL I'm sure not to have WordTable.tags == NULL, but I still have to use unchecked cast instead of something like this:
`val concat2 = Concat("", WordTable.tags, stringParam("$updatedTagId#").nullable())`

**Comment by Tapac** [comment]
I still don't get it - why you want to provide NULL as a first parameter in Coalesce as it will be always ignored.

**Comment by Evgen25176542** [comment]
I don't want, it's just a specific case.
It's about application of Coalesce and concise SQL expression. Please consider [this](https://gist.github.com/Evgen25176542/04d1d68a5128a0e34eb75950373da2dc) and tell me what an exposed-idiomatic way to write **fun updateWord(word: Word)**.

**Comment by Tapac** [comment]
@Evgen25176542 ,
```kotlin
Words.update({ Words.name eq word.name }) {
   if (word.transcription != null) {
     it[transcription] = word.transcription
   }        
   it[definition] = word.definition
}
```

**Comment by Evgen25176542** [comment]
SQL-brain, omg 
Thank you
