### ISSUE TITLE
How to update row with DAO?

### ISSUE THREAD

**Issue by AdityaAnand1** [JetBrains/Exposed#749]
There is no `Model.update{}` (as there is for `Models.update{}`.

The docs say you can just do 

`model.whatever = "new field"`

But where to get `model` in the first place?

Can we `Model.get()` it and then change it's fields however we want? (so update is really a SELECT + change to model class fields) And when the transaction is over, the changes will be written to db?

**Comment by Tapac** [comment]
model should be declared as an Entity and then you could change its fields.
Look for [DAO](https://github.com/JetBrains/Exposed/wiki/DAO) section of a wiki
