### ISSUE TITLE
403 when accessing bintray files

### ISSUE THREAD

**Issue by Clintonio** [JetBrains/Exposed#75]
Hello,

I am seeing 403 errors on all of your bintray files, eg:

https://dl.bintray.com/kotlin/exposed/org/jetbrains/exposed/exposed/0.5.0/exposed-0.5.0.pom

There is no message other than "Forbidden!". Are you aware of this and is it intentional?

Thank you,
Clinton

**Comment by orangy** [comment]
Yes, we are aware of it, bintray is rate-limiting our repositories for unknown reason. We are working with their support.

**Comment by Clintonio** [comment]
Thank you for the prompt answer @orangy. Do you have the files hosted else where? If not we'll have to work around this for the time being.

**Comment by orangy** [comment]
No, I don't think we have Exposed hosted anywhere else. For a workaround, you can check out Git repository and install them into local maven.

**Comment by Clintonio** [comment]
It appears to be working again now. Thanks for the help.
