### ISSUE TITLE
defaultExpression() doesn't seem to always work, but clientDefault() does

### ISSUE THREAD

**Issue by AdityaAnand1** [JetBrains/Exposed#754]
I've created a baseTable from which I extend all my other tables to add on a `createdAt` field.

![image](https://user-images.githubusercontent.com/13274079/71763383-5e318d80-2f01-11ea-9d1f-1bcd8061b7e8.png)

However, I've noticed that the createdAt field is often not populated to the current time (time of insertion) when using `defaultExpression`, however, using `clientDefault` does work.

Is there a reason `defaultExpression` might not be working?

**Comment by Tapac** [comment]
What database do you use?
