### ISSUE TITLE
Feature request: Add helper method for creating database

### ISSUE THREAD

**Issue by AdityaAnand1** [JetBrains/Exposed#757]

**Comment by Tapac** [comment]
Fixed in master

**Comment by AdityaAnand1** [comment]
What version would this be available in?

The exposed github page is a little confusing in that the Releases tab (that I instinctively open for any repos to find the latest version and updates) lists a version that is very old. Perhaps it would be a good idea to start adding new updates to the release tab again?

**Comment by Tapac** [comment]
Please refer to [ChangeLog](ChangeLog.md) as gradle release plugin fails to release multi-module projects. I will investigate the possibility to automate publishing releases to GH release page but not right now.

> What version would this be available in?

I think it would be 0.24.1.
