### ISSUE TITLE
UUID field shows up with weird encoding

### ISSUE THREAD

**Issue by AdityaAnand1** [JetBrains/Exposed#758]
![image](https://user-images.githubusercontent.com/13274079/71820164-667dfa00-30b4-11ea-9988-8dd39c98ce1a.png)

Is there a way to enforce utf-8?

**Comment by CharlieTap** [comment]
The actual UUID string goes through a transformation and is actually stored in binary, how its represented visually is not down to this library and in fact down to the application your viewing the table in
