### ISSUE TITLE
"No operations allowed after connection closed." When using with ktor Server

### ISSUE THREAD

**Issue by virusbear** [JetBrains/Exposed#762]
I am trying to develop a small ktor server that receives a post request with a CSV file as multipart and inserts all rows into a MySQL database. Everything works fine except that the second request to the server always crashes with the following stack trace:

```
org.jetbrains.exposed.exceptions.ExposedSQLException: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:48)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:130)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:124)
	at org.jetbrains.exposed.sql.Query.iterator(Query.kt:309)
```

this is the part of the stack trace after the insert is called by exposed.

at first, I created my SQL connection using URL and password, but now I decided to go with javax.sql.DataSource implementation where I just implemented all getConnection overloads.

after some debugging and searching around in the exposed library I found the following piece of code:

```        
private fun doConnect(getNewConnection: () -> Connection, setupConnection: (Connection) -> Unit = {}, manager: (Database) -> TransactionManager = { ThreadLocalTransactionManager(it, DEFAULT_ISOLATION_LEVEL, DEFAULT_REPETITION_ATTEMPTS) } ): Database {
    return Database {
        getNewConnection().apply { setupConnection(this) }
     }.apply {
        TransactionManager.registerManager(this, manager(this))
    }
}
```

Here getNewConnection is only called once and not passed to the transaction manager.

is it possible, that this prevents opening a new connection to MySQL when a previous got closed?

Connection creation:
`val connection: Database = Database.connect(MySqlDataSource())`

MySqlDataSource:
```
    override fun getConnection(): Connection {
        return getConnection("root", "")
    }

    override fun getConnection(username: String?, password: String?): Connection {
        return DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb", username, password)
    }
```

**Comment by Tapac** [comment]
Could you provide a sample of how you use Exposed with ktor?

**Comment by virusbear** [comment]
I actually tried different ways by now. Our current approach looks like follows:

```
fun Application.module(testing: Boolean = false) {

    install(Locations)

    install(Compression) {
        gzip {
            priority = 1.0
        }
    }

    install(ContentNegotiation) {
        gson {
            serializeNulls()
        }
    }

    routing {
        route("/") {
            csv()
        }
    }
}

fun getDatabaseConnection() = Database.connect("jdbc:mysql://localhost:3306/bsw", driver = "com.mysql.jdbc.Driver", user = "root", password = "")
```

fun csv():

```
@Location("/csv")
class CSV

@KtorExperimentalLocationsAPI
fun Route.csv() {
    post<CSV> {
        val db = getDatabaseConnection()
        //Receiving some CSV Data using multipart into stringbuilder "data"

        updateDB(data.toString(), db)

        call.respond(HttpStatusCode.OK)
    }
}

```

fun updateDB():

```
suspend fun updateDB(csv: String, db: Database) {
    newSuspendedTransaction(Dispatchers.IO, db) {
        //Doing inserts, deletes and modifies on database. works fine for first connection
    }
}
```

in this example, we are creating a new connection every time the endpoint is called. But we also tried creating a global constant connection that is reused multiple times. Both of these options did not lead to success.

Important sidenote:
I am working on another project which uses the same approach (More or less same code) and it works there. I did check gradle files, dependency versions and code multiple times, but there are no big differences.

I really don't know, why Exposed does not open a new Connection / closes an already used one

**Comment by Tapac** [comment]
First of all, you don't need to call `Database.connect` multiple times ([info on wiki](https://github.com/JetBrains/Exposed/wiki/DataBase-and-DataSource#working-with-database-and-datasource)

Do you have any other exceptions prior to this one? Do you call `Connection.close()` somewhere in your code?

Is `MySqlDataSource` in the first message your own implementation of a `DataSource`? Please try to use `Database.connect` with url/username/password parameters or setup pooled datasource (e.g. use HikariCP)

**Comment by virusbear** [comment]
I just used `Database.connect` to see if it prevents the error. Before that, I just used one variable holding the reference to the connection globally.

There are no exceptions prior to the mentioned one and I do not close the connection manually.

The MySqlDataSource was implemented just for testing purposes. Before I used just the URL and the username, but this did not work either.

I just tried to use HikariDataSource with the JDBC URL instead of the Datasource Class name as mentioned in the Readme:

> "⚠ The MySQL DataSource is known to be broken with respect to network timeout support. Use jdbcUrl configuration instead."

But this does not work either. on the second HTTP request to ktor the connection is closed and the same exception occurs.

here is one DEBUG message from Hikari after the first request:

`[DefaultDispatcher-worker-3] DEBUG com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Reset (autoCommit) on connection com.mysql.jdbc.JDBC4Connection@43785ed3`

Maybe also helpful information: there is not that much time between the HTTP request. about 10s so it should not be a timeout of the connection. It really does not matter how much time elapses between subsequent calls to the API.

below the code where I initialize the Exposed Database in Global Scope:

```
val ds = HikariDataSource().apply {
    jdbcUrl = "jdbc:mysql://localhost:3306"
    username = "root"
    password = ""
    catalog = "bsw"
    maximumPoolSize = 8

}

val db = Database.connect(ds)
```

**Comment by Tapac** [comment]
If you could share a repo with the project which I can run and check the exception - it will be very helpful.

**Comment by virusbear** [comment]
Unfortunately, I am not allowed to publish the code for the project, but I will try to create an example to reproduce this issue and publish this one.

**Comment by virusbear** [comment]
I just created an example to reproduce this error. You can clone the following repo: [ktorExposedError](https://github.com/virusbear/ktorExposedError.git).
It uses a MySQL server version 10.4.11-MariaDB.

please create a new Schema test for this example to work.

after that simply send a post request without any body to http://localhost:7010/test

the first request works fine and returns 200 OK but the second results in the before mentioned Exception and a 503 error

**Comment by Tapac** [comment]
@virusbear looks like you faced an issue in 0.16.1 which was fixed for a long time ago. See [0.16.2](https://github.com/JetBrains/Exposed/blob/master/ChangeLog.md#0162) changes and consider  an upgrage to the latest version. It might require some additional changes covered [here](https://github.com/JetBrains/Exposed/wiki/Migration-Guide#migrating-from-exposed-017x-and-earlier-to-018).

**Comment by virusbear** [comment]
Thank you for your help. Updating to the newest version did indeed help. 
just really strange why gradle didn't suggest updating to a newer version.
