### ISSUE TITLE
Entity update event not fired when flushing explictly

### ISSUE THREAD

**Issue by mpe85** [JetBrains/Exposed#764]
When doing an explicit `flush()` after an entity update, there is no `EntityChange` with type `Updated` fired for that entity.

See PR: https://github.com/JetBrains/Exposed/pull/763
When the `flush()` is removed and the update on the entity is flushed implicitly at the end of the transaction, the event is fired.

**Comment by Tapac** [comment]
Fixed in 762ba325044d355b35f24640e163fc6d679e8764.
