### ISSUE TITLE
Unresolved reference: datetime

### ISSUE THREAD

**Issue by HawkEye4** [JetBrains/Exposed#765]
I have upgraded from version 0.18.1 to 0.20.1 and now i have the "Unresolved reference: datetime" error.
In have also imported "org.jetbrains.exposed.sql.datetime".

**Comment by ashokgelal** [comment]
Have you installed datetime related modules? https://github.com/JetBrains/Exposed/wiki/LibDocumentation#exposed-0181-and-higher

**Comment by HawkEye4** [comment]
Yes, i installed **exposed-jodatime** module.

**Comment by ashokgelal** [comment]
Dependencies caching issue then?

**Comment by HawkEye4** [comment]
Thanks, definitely a cache issue. I invalidated the Intellij cache and it recommended the new import.
