### ISSUE TITLE
spring-configuration-metadata.json is not located inside exposed-spring-boot-starter.jar

### ISSUE THREAD

**Issue by hirakida** [JetBrains/Exposed#767]
Hello. I use exposed-spring-boot-starter, but `additional-spring-configuration-metadata.json` is not merged into `spring-configuration-metadata.json`. Therefore, “code completion” dosen’t work with `application.properties` or `application.yml` files.

https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-configuration-metadata.html

```
% jar tf exposed-spring-boot-starter-0.20.3.jar
META-INF/
META-INF/MANIFEST.MF
org/
org/jetbrains/
org/jetbrains/exposed/
org/jetbrains/exposed/spring/
org/jetbrains/exposed/spring/DatabaseInitializerKt.class
org/jetbrains/exposed/spring/DatabaseInitializer.class
org/jetbrains/exposed/spring/DatabaseInitializer$Companion.class
org/jetbrains/exposed/spring/autoconfigure/
org/jetbrains/exposed/spring/autoconfigure/ExposedAutoConfiguration.class
org/jetbrains/exposed/spring/autoconfigure/ExposedProperties.class
META-INF/exposed-spring-boot-starter.kotlin_module
META-INF/additional-spring-configuration-metadata.json
META-INF/spring.factories
```

**Comment by Tapac** [comment]
Fixed in master by renaming `additional-spring-configuration-metadata.json` into `spring-configuration-metadata.json`
