### ISSUE TITLE
Making QueryAlias compatible with Query on the same table

### ISSUE THREAD

**Issue by camhashemi** [JetBrains/Exposed#772]
I have two queries that differ in their original `select` statement, but are identical in all subsequent operations. There are a lot of these operations and I would like to re-use them for both queries.

The problem is that one uses a `QueryAlias` in order to perform a subquery, and the other doesn't. Therefore I can't index their columns using the same notation.

Here's an example:
```
fun getQuery(): Query = PetsTable.select { PetsTable.id eq id }
fun getAliasQuery(): Query = PetsTable.select { PetsTable.id eq id }.alias("pets_alias").selectAll()

fun Query.joinOnOwnersTable(): Query =
        adjustColumnSet {
            innerJoin(
                otherTable = OwnersTable,
                onColumn = { ??? },
                otherColumn = { OwnersTable.id }
            )
        }
```

The ??? is where the incompatibility is. For the aliased query, I should use `PetsTable.alias("pets_alias")[PetsTable.id]`. For the other, I should use `PetsTable.id`.

I'm considering several solutions to this problem:
1. use a QueryAlias for all queries. This is hacky and affects the SQL generated.
2. provide the differences as arguments to all subsequent operations. This adds weight to the APIs and doesn't scale well as we add them. It would look like this:

```
fun Query.joinOnOwnersTable(onColumn: Column<*>): Query =
        adjustColumnSet {
            innerJoin(
                otherTable = OwnersTable,
                onColumn = { onColumn },
                otherColumn = { OwnersTable.id }
            )
        }
```

`onColumn` replaces the ??? incompatibility from above.

3. Extending Query in order to carry the required information via polymorphism. I would then replace `Query` with `PetQuery` in all subsequent operations. `PetQuery` would be either the aliases query or the non-aliased query, and would provide the correct columns to use.

Given the problem and some solution ideas, are there any recommendations for solving it?

Given option 3, extending Query, are there any examples of this? I haven't found any in the codebase.

**Comment by camhashemi** [comment]
Another solution seems to be to alias `PetTable` with the same name, so not `.alias("pets_alias")` but `.alias("pets")`. This makes it so I can access all columns using `PetsTable.columnName`.

That said, it's still hacky and seems fragile.

**Comment by bog-walk** [comment]
Since [version 0.53.0](https://github.com/JetBrains/Exposed/blob/main/CHANGELOG.md#0530), it is now possible to customize  queries by extending the `Query` class, with proper copying over of all the original query's stored properties.

Here is [an example](https://jetbrains.github.io/Exposed/deep-dive-into-dsl.html#custom-select-queries) of a use case involving MySQL query index hints in the documentation.
