### ISSUE TITLE
Cannot filter on nullable foreign key reference in DAO+DSL

### ISSUE THREAD

**Issue by lavalamp-** [JetBrains/Exposed#773]
It looks as though the Exposed syntax does not correctly handle the case where you want to `find` or `select` based on a nullable foreign key. I ran into this issue myself and then found the following StackOverflow post where someone else experienced the same thing:

https://stackoverflow.com/questions/59484198/jetbrains-exposed-select-based-on-nullable-reference-column

The example that the StackOverflow user there provides is as follows:

```
object A : IntIdTable("a") {
    val n = varchar("n", 255)
    val x = reference("x", B).nullable()
}

object B : IntIdTable("b") {
    val i = varchar("m", 255)
    val y = integer("y")
}

fun main() {
    connectToDatabase()

    transaction {
        SchemaUtils.createMissingTablesAndColumns(A, B)

        A.select { A.x eq 1 }
    }
}
```

The exception details from running the above are as follows:

```
None of the following functions can be called with the arguments supplied.
Expression<in EntityID<Int>?>.eq(Expression<in EntityID<Int>?>)   where T = EntityID<Int>?, S1 = EntityID<Int>?, S2 = EntityID<Int>? for    infix fun <T, S1 : T?, S2 : T?> Expression<in S1>.eq(other: Expression<in S2>): Op<Boolean> defined in org.jetbrains.exposed.sql.SqlExpressionBuilder
ExpressionWithColumnType<T>.eq(T)   where T cannot be inferred for    infix fun <T> ExpressionWithColumnType<T>.eq(t: T): Op<Boolean> defined in org.jetbrains.exposed.sql.SqlExpressionBuilder
ExpressionWithColumnType<EntityID<Int>>.eq(Int?)   where T = Int for    infix fun <T : Comparable<T>> ExpressionWithColumnType<EntityID<T>>.eq(t: T?): Op<Boolean> defined in org.jetbrains.exposed.sql.SqlExpressionBuilder
```

I'm a bit confused as it looks like the last of these signatures might match the nullable check, but without knowing more about Exposed's internals it's difficult for me to make a judgment call here.

In the StackOverflow post @Tapac offered the following advice:

```
Try to replace reference("x", B).nullable() with optReference("x", B)
```

The author of the post claims to have tried this and it failed. I can confirm that I tried it too and saw the same problem still.

Exposed version is `0.17.7`

**Comment by Tapac** [comment]
Fixed in master will be available on the next release
