### ISSUE TITLE
Microsoft GUID support

### ISSUE THREAD

**Issue by maxtar** [JetBrains/Exposed#777]
We have tables with records type uniqueidenifier. According [documentation](https://docs.microsoft.com/en-us/sql/t-sql/data-types/uniqueidentifier-transact-sql?view=sql-server-ver15) this is a 16-byte GUID. And it has no limits that third and fourth group need to start from specific value. But in [valueFromDB](https://github.com/JetBrains/Exposed/blob/e636a4425d60afa0b887e07a34f96eeb3fd1a352/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt#L369) function checks that it need to match regexp. And in unmatched case it returns new UUID not equals to original.

**Comment by Tapac** [comment]
Fixed in 0.21.1
