### ISSUE TITLE
Non-singleton DB connection

### ISSUE THREAD

**Issue by isaac-weisberg** [JetBrains/Exposed#784]
Are there any plans to have a non-singleton based DB connection management? So that essentially given a table `Users`, you can `Users.usingConnection(conn).*do something*`.

**Comment by Tapac** [comment]
Exposed doesn't operate a `connection` term too much and it's already possible to work with [multiple databases](https://github.com/JetBrains/Exposed/wiki/Transactions#working-with-a-multiple-databases).

**Comment by isaac-weisberg** [comment]
So do the ORM interfaces use the database connection of the transaction that was open last?
Essentially, queries made building from `Users` would usually be executed on some default `db` instance, unless I open a transaction using another `db`, and the implementation magically realizes that there is a transaction open and it should be used instead?

**Comment by Tapac** [comment]
When you call `transaction{}` function it will ensure that another transaction for the same database was not opened in the same thread and then create a new connection to DB.
If it was nested call then the outer transaction/connection will be reused.
