### ISSUE TITLE
SQL script generation helper (and production migration strategies)

### ISSUE THREAD

**Issue by Aditya94A** [JetBrains/Exposed#785]
Right now, I'm using exposed in development mode only.

The schema is changing a lot. I do a deploy, exposed perfectly creates all tables columns etc.

Then, when I have to deploy again, if the schema changes (which is almost always) -> Exposed **stops working** as sometimes database columns are not created (`createMissingTablesAndColumns` seems unreliable at times, an example: I have 4 microservices with their own separate databases running on elastic beanstalk + one RDS, starting up the microservice JARs all at once via Procfile method and I find random new columns missing in db after `createMissingTablesAndColumns` runs successfully)

So, until now, I've just been wiping out databases over and over and letting exposed create them from scratch each time.

Clearly, this cannot work in production.

1. What should be done in production? How to manage schema migration?
2. Would it be possible to add a helper method that simply prints out all raw SQL statements that are generated internally (CREATE TABLE etc.) <- This would be helpful in auto-generating migration scripts using other online tools.
3. Is this a situation where `withDataBaseLock` might be able to help ensure that `createMissingTablesAndColumns` works correctly?

Just trying to get a better understanding of how Jetbrains intends for this to be used in a mature production setup 😁

**Comment by Tapac** [comment]
Please check https://github.com/JetBrains/exposed-intellij-plugin/tree/master/exposed-gradle-plugin
