### ISSUE TITLE
Aggregate functions do not follow precedence rules & imports clunky

### ISSUE THREAD

**Issue by toefel18** [JetBrains/Exposed#787]
See PR  #788

See code at bottom for a complete schema definition.

## Operator precedence is confusing

```kotlin
val commentPopularityScore = ((CommentTable.likes * 2) - CommentTable.dislikes) / 2
```
The executed SQL query is: 
```sql
SELECT "USER".OWNER_TYPE, SUM((COMMENT.LIKES*2-COMMENT.DISLIKES / 2)) FROM COMMENT INNER JOIN "USER" ON "USER".ID = COMMENT.FROM_USER_ID GROUP BY "USER".OWNER_TYPE
```
Which then results in the wrong answer if you expect operator precedence rules to be followed.

In SQLExpressionBuilder.kt code I see:
```kotlin
// THIS SEEMS TO BE MISSING '(' and ')'
class TimesOp<T, S: T>(val expr1: Expression<T>, val expr2: Expression<S>, override val columnType: IColumnType): ExpressionWithColumnType<T>() {
    override fun toQueryBuilder(queryBuilder: QueryBuilder) = queryBuilder { append(expr1, '*', expr2) }
}

// THIS SEEMS TO BE GOOD!
class DivideOp<T, S: T>(val expr1: Expression<T>, val expr2: Expression<S>, override val columnType: IColumnType): ExpressionWithColumnType<T>() {
    override fun toQueryBuilder(queryBuilder: QueryBuilder) = queryBuilder { append('(', expr1, " / ", expr2, ')') }
}
```
Shouldn't all operators include '('  and ')'? Not sure if that would fix it completely but if the operators are applied by Kotlin with the standard precedence rules as defined here https://kotlinlang.org/docs/reference/operator-overloading.html, it should.

## Imports not automatically found

It's hard to use the operator functions like minus, plus, times div, etc. because Intellij does not find them. You have to write the import statement explicitly yourself:
```kotlin
import org.jetbrains.exposed.sql.SqlExpressionBuilder.plus
import org.jetbrains.exposed.sql.SqlExpressionBuilder.div
import org.jetbrains.exposed.sql.SqlExpressionBuilder.minus
import org.jetbrains.exposed.sql.SqlExpressionBuilder.times
```
It took me some time to find them, Is there a simpler way to use them that I am missing?

## avg typed to BigDecimal
`avg()` is typed to BigDecimal even though the columns I am averaging are Long. Is there a specific reason for this? Other aggregate functions such as `sum()` are Long (see sample code below)

## Example code for questions above

```kotlin
object UserTable: Table("user") {
    val id = long("id").autoIncrement()
    val name = varchar("owner_type", 64)

    override val primaryKey = PrimaryKey(id)
}

object CommentTable: Table("comment") {
    val id = long("id").autoIncrement()
    val fromUser = long("from_user_id").references(UserTable.id, onDelete = ReferenceOption.CASCADE)
    val content = text("content")

    val likes = long("likes").default(0L)
    val dislikes = long("dislikes").default(0L)

    override val primaryKey = PrimaryKey(id)
}



val commentPopularityScore = ((CommentTable.likes * 2) - CommentTable.dislikes) / 2

CommentTable
    .innerJoin(UserTable)
    .slice(UserTable.name, commentPopularityScore.avg())
    .selectAll()
    .groupBy(UserTable.name)
    .map { row ->
        UserPopularityScore(
            fromUser = row[UserTable.name],

            // FAILS because type avg() is BigDecimal, if I use sum() it works  
            popularityScore = row[commentPopularityScore.avg()] ?: 0L    
        )
    }
```

**Comment by Tapac** [comment]
The last question not coveted in PR is:
> Imports not automatically found

I'll check if it's possible to make those operators more visible.

**Comment by Tapac** [comment]
@toefel18 , could describe the case where IDEA can't find operators?
I was trying it with simple boolean column and it works without any imports:
```kotlin
val plusExpression = Expression.build {
       XTable.b1 + XTable.b1
}
```

**Comment by toefel18** [comment]
I was not using Expression build, but just:
```kotlin
val plusExpr = XTable.b1 + XTable.b1
```

This also works if you import: 
```kotlin
import org.jetbrains.exposed.sql.SqlExpressionBuilder.minus
```

I wasn't aware of `Expression.build{}`!
