### ISSUE TITLE
BatchDataInconsistentException when trying to insert without mentioning a column which value is defined by a trigger

### ISSUE THREAD

**Issue by ezhaka** [JetBrains/Exposed#790]
Consider a table `Table`. Let's suppose we have a column `auto_column` there, for which a trigger is defined:

```
create definer = root@`%` trigger etag_i_Table
    before insert
    on Table
    for each row
    SET NEW.auto_column = (SELECT GEN_ID());
```

In this case, if I try to do a batch insert via exposed without mentioning an `auto_column`, I get an exception:

```org.jetbrains.exposed.sql.statements.BatchDataInconsistentException Can't add new batch because columns: foo.bar.Table.auto_column don't have client default values. DB defaults don't support in batch inserts```

Beside the fact, it is perfectly okay for MySQL to handle this batch insert. Thus, I need to work around this by setting `batch[auto_column] = 0`.

I suppose `DB defaults don't support in batch inserts` hints that it is intentionally designed this way. Could you explain the intention behind that, please?

**Comment by ezhaka** [comment]
Sorry, I need to describe the problem a bit better, it seems `batch insert on duplicate key update` is not a standard Exposed feature

**Comment by ezhaka** [comment]
Okay, our problem is the following: we tried to implement `batch insert on duplicate key update` on top of `BatchInsertStatement`. We really miss this functionality in Exposed. We did it the following way:

```
class BatchInsertUpdateOnDuplicate(table: Table, private val columnUpdates: List<ColumnUpdate>, ignore: Boolean = false) : BatchInsertStatement(table, ignore) {
    override fun prepareSQL(transaction: Transaction) =
        super.prepareSQL(transaction).withColumnUpdates(columnUpdates, transaction)
}

private fun String.withColumnUpdates(columnUpdates: List<ColumnUpdate>, transaction: Transaction): String {
    val preparedRequestBuilder = StringBuilder(this)

    if (columnUpdates.isNotEmpty()) {
        preparedRequestBuilder.append(" ON DUPLICATE KEY UPDATE ")
        preparedRequestBuilder.append(columnUpdates.joinToString {
            transaction.identity(it.column).let { columnName -> "$columnName = ${it.update(transaction, columnName)}" }
        })
    }

    return preparedRequestBuilder.toString()
}

fun <T : Table, E> T.batchInsertOnDuplicateKeyCustomUpdate(data: Collection<E>, columnUpdates: List<ColumnUpdate>, ignore: Boolean = false, body: T.(BatchInsertUpdateOnDuplicate, E) -> Unit) {
    data.takeIf { it.isNotEmpty() }?.let {
        val insert = BatchInsertUpdateOnDuplicate(this, columnUpdates, ignore)
        data.forEach {
            insert.addBatch()
            body(insert, it)
        }
        TransactionManager.current().exec(insert)
    }
}
```

The problem here is that all this fails miserably when there is a column that has no default value but has a trigger that can set it.

I looked at the implementation of plain `batchInsert` and found out that it has a tricky `try-catch` which executes the statement right away if it sees `BatchDataInconsistentException `:

https://github.com/JetBrains/Exposed/blob/master/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Queries.kt#L115

As far as I understand, it results in the N+1 query to a database instead of a batch insert.

Thus, I have 2 questions: 
1. Is it planned to add `batch insert on duplicate key update` as a first class sitizen to Exposed?
2. Is this validation really necessary? Is it possible to bypass it somehow in order to implement `batch insert on duplicate key update` reusing the current logic?

**Comment by Tapac** [comment]
> Is it planned to add batch insert on duplicate key update as a first class sitizen to Exposed?

Yes, but afaik it only supported by MySQL.
We use such code:
```kotlin
class BatchInsertUpdateOnDuplicate(table: Table, val onDupUpdate: List<Column<*>>) : BatchInsertStatement(table, false) {
    override fun prepareSQL(transaction: Transaction): String {
        val onUpdateSQL = ifTrue(onDupUpdate.isNotEmpty()) {
            " ON DUPLICATE KEY UPDATE " + onDupUpdate.joinToString { "${transaction.identity(it)}=VALUES(${transaction.identity(it)})" }
        }.orEmpty()
        return super.prepareSQL(transaction) + onUpdateSQL
    }
}

private fun <T : Table, E> T.prepareBatchInsertOnDuplicateKeyUpdate(data: List<E>, onDupUpdateColumns: List<Column<*>>, body: T.(BatchInsertUpdateOnDuplicate, E) -> Unit) = data.ifNotEmpty {
    val insert = BatchInsertUpdateOnDuplicate(this, onDupUpdateColumns)
    data.forEach {
        insert.addBatch()
        body(insert, it)
    }
    return@ifNotEmpty insert
}

fun <T : Table, E> T.batchInsertOnDuplicateKeyUpdate(data: List<E>, onDupUpdateColumns: List<Column<*>>, body: T.(BatchInsertUpdateOnDuplicate, E) -> Unit) {
    prepareBatchInsertOnDuplicateKeyUpdate(data, onDupUpdateColumns, body)?.let {
        TransactionManager.current().exec(it)
    }
}

fun <ID : Any, T : IdTable<ID>, E> T.batchInsertOnDuplicateKeyUpdateAndGetIds(data: List<E>, onDupUpdateColumns: List<Column<*>>, body: T.(BatchInsertUpdateOnDuplicate, E) -> Unit): List<ID> {
    return prepareBatchInsertOnDuplicateKeyUpdate(data, onDupUpdateColumns, body)?.let {
        TransactionManager.current().exec(it)
        it.resultedValues?.mapNotNull { it.getOrNull(id)?.value }
    }.orEmpty()
}

FooTable.batchInsertOnDuplicateKeyUpdateAndGetIds(foos, listOf(FooTable.bar, FooTable.baz))  { batch, foo ->
        batch[bar] = foo.bar
        batch[baz] = foo.baz
}
```
