### ISSUE TITLE
Can't load implementation for DatabaseConnectionAutoRegistration

### ISSUE THREAD

**Issue by crazyzjw** [JetBrains/Exposed#792]
Problems encountered in new projects, hope to be resolved

`fun main(args: Array<String>): Unit = io.ktor.server.netty.EngineMain.main(args)

@Suppress("unused") // Referenced in application.conf
@kotlin.jvm.JvmOverloads
fun Application.module(testing: Boolean = false) {
    install(ContentNegotiation) {
        register(ContentType.Application.Json, GsonConverter())
    }
    //连接数据库
    Database.connect("jdbc:mysql://localhost:3306/data?characterEncoding=utf8&useSSL=false"
        ,"com.mysql.jdbc.Driver"
        ,"root"
        ,"123123")

}`

but:
`Caused by: java.lang.ExceptionInInitializerError
	at com.bs.ApplicationKt.module(Application.kt:28)
	at com.bs.ApplicationKt.module$default(Application.kt:23)
	... 24 more
Caused by: java.lang.IllegalStateException: Can't load implementation for DatabaseConnectionAutoRegistration
	at org.jetbrains.exposed.sql.Database.<clinit>(Database.kt:64)
	... 26 more`

**Comment by Tapac** [comment]
Could you check [Modules](https://github.com/JetBrains/Exposed/wiki/LibDocumentation#exposed-0181-and-higher) wiki page and ensure what you add `exposed-jdbc` module as a dependency?

**Comment by FRedEnergy** [comment]
Make sure you're not ommiting `/META-INF/services/` folder from exposed-jdbc.jar during your build process. That folder contains metadata for DatabaseConnectionAutoRegistration loading service which will not work without it.

**Comment by hichem-fazai** [comment]
I was able to reproduce the above error and adding `exposed-jdbc` dependency should resolve the issue.
