### ISSUE TITLE
[Request] a detail readme or wiki about Exposed usage

### ISSUE THREAD

**Issue by douglarek** [JetBrains/Exposed#81]
I am using Exposed in my spring boot project, I love it;

When I use it deeply, I find it difficult;

So would you llike to have a detail readme ?

thanks

**Comment by aurieh** [comment]
To add to that, it would be nice to have documentation covering extension development, for example, I needed support to JSONB, and it was fairly hard and painful to hack together a solution (with all the operators and columntypes) without a handy doc/wiki. Just a lot of trial and error without it, I guess.

**Comment by oshai** [comment]
I started edit the wiki, comments are welcome: https://github.com/JetBrains/Exposed/wiki
