### ISSUE TITLE
Wrong exposed version in Get Statted page in wiki

### ISSUE THREAD

**Issue by Vlad8161** [JetBrains/Exposed#814]
In [Getting Started](https://github.com/JetBrains/Exposed/wiki/Getting-Started) page there is 0.20.1 version of exposed is specified. This version has a bug https://github.com/JetBrains/Exposed/issues/748. Because of this bug a sample on this page does not work, so this is a bit confusing and is hard to google it, especially for newcomers.

**Comment by Tapac** [comment]
Versions in Wiki were actualized
