### ISSUE TITLE
how to realize update table set column = column + 1

### ISSUE THREAD

**Issue by Linuxea** [JetBrains/Exposed#821]
```kotlin
PyqDetailCounterTable.update({PyqDetailCounterTable.pyqId.eq(pyqId)}) {
            it[count] = it[count] + 1
}
```

**Comment by Tapac** [comment]
https://github.com/JetBrains/Exposed/wiki/DSL#update

**Comment by Linuxea** [comment]
> https://github.com/JetBrains/Exposed/wiki/DSL#update

I use the 
```xml
<jetbrains.exposed.version>0.16.1</jetbrains.exposed.version>
```
Maybe this is the reason why I can't increase like upon suggest.
But another question appears when I use 
```xml
<jetbrains.exposed.version>0.21.1</jetbrains.exposed.version>
```
Is it not crazy I can't use the old code?

![image](https://user-images.githubusercontent.com/18577499/75959477-4bcfd200-5ef9-11ea-98ff-9a7697d1f830.png)

**Comment by Tapac** [comment]
https://github.com/JetBrains/Exposed/wiki/Migration-Guide
