### ISSUE TITLE
Update batchInsert wiki page to indicate that `rewriteBatchedStatements` is preferable

### ISSUE THREAD

**Issue by jlengrand** [JetBrains/Exposed#824]
Hi there, 

Not sure if it is expected or not, but I've been banging my head at this for a couple days now. 

I'm playing around with the [imbd datasets](https://datasets.imdbws.com/).

I'm trying to import roughly 100k lines into MySQL. A row is pretty simple : a string as id, a float and an int. 

I have tried both the `insert` and `batchInsert` methods and the actual transaction takes in excess of 45 minutes on my 2018 MBP. 

The code is essentially : 

```
    fun loadData(){
        val nameBasicsReader = File("./datasets/title.ratings.tsv").bufferedReader()
        nameBasicsReader.readLine()
        transaction {
            val lines = nameBasicsReader.readLines()
            TitleRatings.batchInsert(lines){
                val items = it.split("\t")
                this[TitleRatings.tconst] = items[0]
                this[TitleRatings.averageRating] = if (items[1] != Reader.NO_DATA) items[1].toFloat() else null
                this[TitleRatings.numVotes] = if (items[2] != Reader.NO_DATA) items[2].toInt() else null
            }
        }
    }
```

The file itself is compozed of 100k lines, in total 17mb big. 

Is that expected? I would expect this kind of transaction to run under a minute? 

I'm I doing something obviously wrong? 

Most of the actual code is available [here](https://github.com/jlengrand/exposed-imdb/blob/master/src/main/kotlin/loader/TitleRatingsLoader.kt).

I am running mysql inside a docker image. I do understand that this has a cost, but is it expected to have such a slow transaction? 

Thanks!

**Comment by jlengrand** [comment]
I've run the same experiment on a local MySQL instance. The process runs under a minutes. This is not perfect but much more acceptable. 

I'll investigate further what is going on with the Docker instance.

**Comment by jlengrand** [comment]
I'm a little confused. 

I am using `batchInsert` because I want to import a large number of lines at once. 

But when using the logger, I see that the actual SQL seems to be a 100k atomic inserts : 

```
SQL: INSERT INTO TitleRatings (averageRating, numVotes, tconst) VALUES (7.7, 50, 'tt9377124')
SQL: INSERT INTO TitleRatings (averageRating, numVotes, tconst) VALUES (8.8, 13, 'tt9377130')
SQL: INSERT INTO TitleRatings (averageRating, numVotes, tconst) VALUES (8.6, 12, 'tt9377132')
SQL: INSERT INTO TitleRatings (averageRating, numVotes, tconst) VALUES (8.5, 11, 'tt9377134')
SQL: INSERT INTO TitleRatings (averageRating, numVotes, tconst) VALUES (8.2, 9, 'tt9377136')
SQL: INSERT INTO TitleRatings (averageRating, numVotes, tconst) VALUES (6.6, 8, 'tt9377138')
SQL: INSERT INTO TitleRatings (averageRating, numVotes, tconst) VALUES (7.8, 12, 'tt9377140')
SQL: INSERT INTO TitleRatings (averageRating, numVotes, tconst) VALUES (7.6, 8, 'tt9377142')
SQL: INSERT INTO TitleRatings (averageRating, numVotes, tconst) VALUES (7.4, 8, 'tt9377148')
SQL: INSERT INTO TitleRatings (averageRating, numVotes, tconst) VALUES (7.5, 14, 'tt9377150')
SQL: INSERT INTO TitleRatings (averageRating, numVotes, tconst) VALUES (8.8, 5, 'tt9377162')
SQL: INSERT INTO TitleRatings (averageRating, numVotes, tconst) VALUES (7.8, 6, 'tt9377172')
SQL: INSERT INTO TitleRatings (averageRating, numVotes, tconst) VALUES (8.6, 8, 'tt9377188')
SQL: INSERT INTO TitleRatings (averageRating, numVotes, tconst) VALUES (6.8, 112, 'tt9377260')
SQL: INSERT INTO TitleRatings (averageRating, numVotes, tconst) VALUES (7.8, 15, 'tt9377274')
SQL: INSERT INTO TitleRatings (averageRating, numVotes, tconst) VALUES (8.1, 15, 'tt9377276')
SQL: INSERT INTO TitleRatings (averageRating, numVotes, tconst) VALUES (8.4, 8, 'tt9377288')
SQL: INSERT INTO TitleRatings (averageRating, numVotes, tconst) VALUES (7.4, 5, 'tt9377312')
SQL: INSERT INTO TitleRatings (averageRating, numVotes, tconst) VALUES (7.5, 39, 'tt9377320')
SQL: INSERT INTO TitleRatings (averageRating, numVotes, tconst) VALUES (8.0, 57, 'tt9377372')
SQL: INSERT INTO TitleRatings (averageRating, numVotes, tconst) VALUES (7.4, 28, 'tt9377378')
SQL: INSERT INTO TitleRatings (averageRating, numVotes, tconst) VALUES (8.0, 5, 'tt9377388')
SQL: INSERT INTO TitleRatings (averageRating, numVotes, tconst) VALUES (5.9, 16, 'tt9377414')
```

Is that expected? That seems to defy the usage of batch insert (and explains the slowness in docker).

**Comment by jlengrand** [comment]
My issue looks close to https://github.com/JetBrains/Exposed/issues/617

**Comment by jlengrand** [comment]
Alright, using the option `rewriteBatchedStatements=true` drops the execution time by a crazy amount of time. 

I can now process my 100k lines in 20 seconds locally, 30 seconds in Docker. 

It makes sense to use the power of the JDBC Drivers, but the name of the API function confused me to be fair. `batchInsert` sounded like I was gonna do a bulk operation, while actually I am not. 

The option is also not mentioned anywhere in the doc. I have no documentation access. It probably should be listed as note here : https://github.com/JetBrains/Exposed/wiki/DSL#batch-insert

**Comment by jlengrand** [comment]
Something like this would probably make sense : 

```markdown
__NOTE:__ The `batchInsert` function will still create multiple `INSERT` statements when interacting with your database. You most likely want to couple this with the `rewriteBatchedInserts=true` (or `rewriteBatchedStatements=true` option of your relevant JDBC driver, which will convert those into a single bulkInsert.
You can find the documentation for this option for MySQL [here](https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-configuration-properties.html) and PostgreSQL [here](https://jdbc.postgresql.org/documentation/94/connect.html).
```

**Comment by jlengrand** [comment]
Let me know if I can do anything more to help!

**Comment by Tapac** [comment]
@jlengrand , thank you, I had updated wiki with your text

**Comment by jlengrand** [comment]
Cheers! Have a great weekend
