### ISSUE TITLE
Strange Query Behavior Requires Corouting and SuspendedTransaction

### ISSUE THREAD

**Issue by easycheese** [JetBrains/Exposed#825]
I have a query in which I'm trying to pull a single object. Backend is hosted utilizing Micronaut, frontend is Angular.

This code works just fine if I call the API directly utilizing Chrome and a URL. However, when the frontend calls it, it fails with a 'connection is closed' error
```
val result = transaction {
    TableManufacturers.select { TableManufacturers.id eq 1}.first()
}
```

If I run it like this, the code works perfectly fine in both scenarios. 

```
runblocking {
    val result = newSuspendedTransaction {
        TableManufacturers.select { TableManufacturers.id eq 1}.first()
    }
}
```

Is there some reason I need to run the call in a coroutine? It doesn't seem like intended behavior...

**Comment by Tapac** [comment]
Do you make a call from a `suspend` function?

**Comment by easycheese** [comment]
Nope. The only call made before this is to connect to the database

**Comment by Tapac** [comment]
Could you please share a sample project to check?
