### ISSUE TITLE
greaterEq or lessEq with an Expression<Long>

### ISSUE THREAD

**Issue by lucasortigoso** [JetBrains/Exposed#829]
Hi,

How can i use greaterEq or lessEq with an Expression<Long>?

**SubQuery**
` val expDealsCount = wrapAsExpression<Long>(TblDeals.slice(TblDeals.id.count())
                    .select(TblDeals.fooId eq TblFoo.id and (TblDeals.deleted eq false)))`
**Query**
` selectQuery
.slice(*TblFoo.columns.toTypedArray(), expDealsCount)
.andWhere { expDealsCount.[i need do a filter HERE where expDealsCount >= integer] }
.limit(limit, offset)
.orderBy(TblFoo.createdDate to SortOrder.DESC)`

Thanks

**Comment by Tapac** [comment]
Thank you for the report. That will be fixed on the next release (0.22.1).
