### ISSUE TITLE
Could not initialize class xxx_object_table 

### ISSUE THREAD

**Issue by Linuxea** [JetBrains/Exposed#834]
This is my error log:
![image](https://user-images.githubusercontent.com/18577499/76426458-0d00b700-63e6-11ea-9e3f-e2fa3cf9f189.png)

This is my object table <code>UserForbidTalkHistoryTable</code>
```kotlin
object UserForbidTalkHistoryTable : Table("user_forbid_talk_history") {
    val id = long("id").autoIncrement().primaryKey()
    val uid = long("uid")
    val adminId = long("admin_id")
    val platformNo = long("platform_no")
    val phone = varchar("phone", 15)
    val reason = varchar("reason", 200)
    val startTime = datetime("start_time")
    val endTime = datetime("end_time")
    val enable = bool("enable")
    val createTime = datetime("create_time")
    val updateTime = datetime("update_time")
}
```

The error occurs in code
```kotlin
override fun countByUserId(userId: Long): Boolean {
        val now = DateTime(Date())
        // and errors occurs UserForbidTalkHistoryTable.select 
        val count = UserForbidTalkHistoryTable.select {
            UserForbidTalkHistoryTable.uid.eq(userId)
                    .and(UserForbidTalkHistoryTable.enable.eq(true))
                    .and(UserForbidTalkHistoryTable.startTime.lessEq(now))
                    .and(UserForbidTalkHistoryTable.endTime.greaterEq(now))
        }.count()
        return count > 0
    }
```

Something really strange sometimes happens after spring boot starts, but this error may disappear after I restart the spring boot application.
I really don't know why throws such an error.

### my version
![image](https://user-images.githubusercontent.com/18577499/76427773-b5634b00-63e7-11ea-946f-e57ebd991cfe.png)

```xml

<kotlin.version>1.3.40</kotlin.version>
<jetbrains.exposed.version>0.16.1</jetbrains.exposed.version>
```

**Comment by Tapac** [comment]
Is this the same as #704 ?
Could you check the same code with the latest Exposed version?

**Comment by Linuxea** [comment]
I don't think so but I try the latest version, I use 
```xml
 <dependency>
           <groupId>org.jetbrains.exposed</groupId>
           <artifactId>exposed-spring-boot-starter</artifactId>
           <version>0.16.1</version>
  </dependency>
```

When I update to 
```xml
 <dependency>
           <groupId>org.jetbrains.exposed</groupId>
           <artifactId>exposed-spring-boot-starter</artifactId>
           <version>0.21.1</version>
  </dependency>
```


Is it incompatible with the old version?
![image](https://user-images.githubusercontent.com/18577499/76480166-e758c980-6448-11ea-8432-9a58c65a8732.png)

I worry about some other incompatible problem occur.

**Comment by Linuxea** [comment]
https://github.com/JetBrains/Exposed/issues/765

I have already import <code>exposed-spring-boot-starter</code>
Should I import the other four modules too?

```xml
<dependencies>
  <dependency>
    <groupId>org.jetbrains.exposed</groupId>
    <artifactId>exposed-core</artifactId>
    <version>0.22.1</version>
  </dependency>
  <dependency>
    <groupId>org.jetbrains.exposed</groupId>
    <artifactId>exposed-dao</artifactId>
    <version>0.22.1</version>
  </dependency>
  <dependency>
    <groupId>org.jetbrains.exposed</groupId>
    <artifactId>exposed-jdbc</artifactId>
    <version>0.22.1</version>
  </dependency>
  <dependency>
    <groupId>org.jetbrains.exposed</groupId>
    <artifactId>exposed-jodatime</artifactId>
    <version>0.22.1</version>
  </dependency>
</dependencies>
```

And if I should which version be imported?
The version of <code>exposed-spring-boot-starter </code> is latest <strong>0.21.1</strong>,but the other four module is <strong>0.22.1</strong>

**Comment by Linuxea** [comment]
I upgrade to the latest version.
It works fine by the time now in my development environment.

**Comment by Tapac** [comment]
https://bintray.com/kotlin/exposed/exposed-spring-boot-starter/0.22.1 is available.
You have to add only `exposed-jodatime` as a depencency with the same version.

**Comment by Linuxea** [comment]
I sorry but this error appears again.

**Comment by Linuxea** [comment]
I try to add this plugin for every maven module
```xml
<plugin>
        <groupId>org.jetbrains.kotlin</groupId>
        <artifactId>kotlin-maven-plugin</artifactId>
        <executions>
            <execution>
                <id>compile</id>
                <phase>compile</phase>
                <goals>
                    <goal>compile</goal>
                </goals>
            </execution>
        </executions>
</plugin>
```

Just look and see what happen after now.

**Comment by Tapac** [comment]
Could you please attach the whole stacktrace with `NoClassDefFound` (and any other exceptions above and below)?

**Comment by Linuxea** [comment]
When I upgrade the exposed and kotlin to the latest version, this error disappears.
