### ISSUE TITLE
Can't create datetime or timestamp columns

### ISSUE THREAD

**Issue by jwlogemann** [JetBrains/Exposed#842]
Hi,
According to the documentation you can define datetime columns like:
object Users : Table() {
    val id = integer("id").autoIncrement()
    val createdOn = datetime("created_on", length= 50)
    val modifiedOn = datetime("modified_on", length= 50)

But in 0.22.1 this does not seem to be supported. How do I use datetime in Exposed? Or should I just store everything in varchar columns? Which seems strange

**Comment by veyndan** [comment]
Since Exposed 0.18.1, date-time extensions are to be included as a separate dependency. Please consult the [migration guide](https://github.com/JetBrains/Exposed/wiki/LibDocumentation#exposed-0181-and-higher) for further explanation.
