### ISSUE TITLE
why does limit(0) omit LIMIT from the final query?

### ISSUE THREAD

**Issue by camhashemi** [JetBrains/Exposed#845]
[source code](https://github.com/JetBrains/Exposed/blob/master/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt#L454)
 
this means that providing `limit(0)` is equivalent to not calling `limit` at all, which is odd behavior imho.

[At least for MySQL](https://dev.mysql.com/doc/refman/8.0/en/limit-optimization.html), `limit 0` doesn't behave this way.

**Comment by bastman** [comment]
I agree with @camhashemi  .

I find silently ignoring the "limit" clause  weird, if limit is set to a value <1.
I'd favour - to let the underlying db handle this case (e.g. fail).

Currently passing invalid arguments (limit <1) will silently expose all db rows.
This may lead to hard to spot bugs. 
I'd prefer the fail-fast / in-your-face approach.

imho, limit=null would reflect the intention to get all rows without any limit.

What do you think?

**Comment by camhashemi** [comment]
especially with the query builder style, the less custom interpretation between DSL and SQL the better.

passing `null` is one way to signal "no limit", the other way would be to omit the call to `limit` at all.

**Comment by xirc** [comment]
I also agree with @camhashemi @bastman .

I found the behavior when I have written some test cases for my app.
The behavior is not good imho, even if I should write tests.

Here is a sample project.
https://github.com/xirc/exposed-limit-example

**Comment by Tapac** [comment]
Fixed. Will be available in 0.24.2
