### ISSUE TITLE
Table.batchInsert constrained by Any

### ISSUE THREAD

**Issue by brezinajn** [JetBrains/Exposed#847]
in org.jetbrains.exposed.sql Queries.kt there is `fun <T:Table, E:Any> T.batchInsert(data: Iterable<E>, ignore: Boolean = false, body: BatchInsertStatement.(E)->Unit): List<ResultRow>`. Is there any reason why `E` is bound to `Any`? It doesn't seem to serve any purpose.

**Comment by Tapac** [comment]
Could you clarify your expectations? You expect `E:Any?`? How you could insert `null` into table?

**Comment by brezinajn** [comment]
OK, so the Any constraint is to guard against null cases. Totally missed that one :D Thanks for clarification.

**Comment by brezinajn** [comment]
Technically speaking. If you are able to provide meaningful insert statement for null value, handling the null case should be allowed. In same manner as here is no not-null constraint for plain insert.
