### ISSUE TITLE
AliasQuery.selectAll() lost alias columns

### ISSUE THREAD

**Issue by xJoeWoo** [JetBrains/Exposed#850]
```kotlin
object Users : Table("test_user") {
    val name = varchar("name", 32)
}
Users.slice(Users.name, Users.name.alias("name_alias"))
    .selectAll()
    .alias("table_alias")
    .selectAll()
    .prepareSQL(QueryBuilder(false))
```
```sql
SELECT table_alias."NAME" FROM (SELECT TEST_USER."NAME", TEST_USER."NAME" name_alias FROM TEST_USER) table_alias
```

However if using slice, all column will be selected.
```kotlin
val sliceColumns = listOf(Users.name, Users.name.alias("name_alias"))
Users.slice(sliceColumns)
    .selectAll()
    .alias("table_alias")
    .run { slice(sliceColumns.map { if (it is Column<*>) this[it] else this[it] }) } // and a bit strange if mixing Column and Expression to call QueryAlias.get()
    .selectAll()
    .prepareSQL(QueryBuilder(false))
```
```sql
SELECT table_alias."NAME", table_alias.name_alias FROM (SELECT TEST_USER."NAME", TEST_USER."NAME" name_alias FROM TEST_USER) table_alias
```

Here I can see filtering out columns that not exist in source table:
https://github.com/JetBrains/Exposed/blob/50848d672b60581242003ff65ef9c078aa72f058/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Alias.kt#L68

How about add an switch to indicate filtering columns or not?

**Comment by ezhaka** [comment]
Faced with the same problem, is there any workaround?

**Comment by ezhaka** [comment]
I've workarounded it:

```kotlin
private fun QueryAlias.sliceAliasedQuery(): FieldSet {
    return slice(columns + query
        .set
        .fields
        .filterNot { it in query.set.source.columns }
        .filterIsInstance<ExpressionAlias<Any>>()
        .map { this[it] }
    )
}
```

**Comment by bog-walk** [comment]
The source code in `QueryAlias` was changed in [this commit](https://github.com/JetBrains/Exposed/commit/fd5d4bef9baf2b56e722bd3d690071b0dd20ca1f#diff-c6cdd7dafb5652c0c209a461ecc6fc7f40c3a25bb2a11171beec967c78cb98e2).
Confirming that, using current version 0.45.0, the first query generates SQL with all alias query columns selected.

If you also need to access the result rows, the aliases could be extracted to variables first, something like this:
```kt
val nameAlias: ExpressionAlias<String> = Users.name.alias("name_alias")
val tableAlias: QueryAlias = Users.slice(Users.name, nameAlias).selectAll().alias("table_alias")

tableAlias
    .selectAll()
    .map {
        it[tableAlias[nameAlias.delegate]] // if nameAlias were just an Expression, delegate would not be needed
    }
```

If there are any further issues with `QueryAlias`, please consider reporting them on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763).
