### ISSUE TITLE
Getting number of rows inserted from Table.insert or Table.insertIgnore?

### ISSUE THREAD

**Issue by glasser** [JetBrains/Exposed#851]
Sometimes I run Table.insertIgnore and want to know whether I did indeed insert a row (on Postgres).

insertIgnore seems to return the InsertStatement rather than the count of rows:

```
fun <T:Table> T.insertIgnore(body: T.(UpdateBuilder<*>)->Unit): InsertStatement<Long> = InsertStatement<Long>(this, isIgnore = true).apply {
    body(this)
    execute(TransactionManager.current())
}
```

Am I missing some way of getting the return value of execute out of this? Should I just be creating an InsertStatement myself and executing it if I want that?

**Comment by maxwell-carbon** [comment]
+1 to this, the main alternative I see is to execute an additional query first to see if the potentially-conflicting row already exists, but I'd prefer not to do that.

**Comment by Tapac** [comment]
InsertStatement (and all inheritors) will get `insertedCount` field in the next release. The field will contain the inserted rows size provided by the driver.
