### ISSUE TITLE
PrimaryKey Validation detects "Confusion" incorrectly

### ISSUE THREAD

**Issue by chrisjenx** [JetBrains/Exposed#852]
I have two tables that fire this message:

`Confusion between multiple declarations of primary key on event_instance_time_recurrences. Use only override val primaryKey=PrimaryKey() declaration.`

The table does define the primary key override:

```
object EventInstanceTimeRecurrences : UUIDTable("event_instance_time_recurrences") {
    val eventInstanceId = reference("event_instance_id", EventInstances.id, ReferenceOption.CASCADE)

    /**
     * how frequent is the occurrence
     */
    val frequency = varchar("frequency", 5).default("00:15")

    /**
     * Gap between the frequency, i.e. 01:00 x 1 would be every 1hr, 01:00 x 2 would be every other hour.
     */
    val separation = short("separation").default(1)

    override val primaryKey: PrimaryKey = PrimaryKey(eventInstanceId, id)
}
```

And the UUID table:
```
abstract class UUIDTable(name: String = "", pkName: String = "id") : Table(name) {
    val id = uuid(pkName).autoGenerate()
    override val primaryKey: PrimaryKey = PrimaryKey(id)
}
```

Is it because the referenced `EventInstances.id` is the primary key in it's own table? That seems pretty standard to me?

**Comment by hichem-fazai** [comment]
Hi,
This is not because the referenced EventInstances.id is a primary key. You should use lazy declaration for primarykey in super class UUIDTable, like this :
````Kotlin
abstract class UUIDTable(name: String = "", pkName: String = "id") : Table(name) {
    val id = uuid(pkName).autoGenerate()
    override val primaryKey by lazy { PrimaryKey(id) }
}
````

**Comment by chrisjenx** [comment]
Errr, what? Its overridden in the implementation. You shouldn't have to do that.

**Comment by hichem-fazai** [comment]
Yes for end user, it's not a good solution. for instance, you can workarround it like that. 
I'm planning to make change to improve it.
