### ISSUE TITLE
Clarify Docs

### ISSUE THREAD

**Issue by gunslingor** [JetBrains/Exposed#855]
Docs talk about IntEntityID when setting up the record objects, but none of the docs talk about what to do when the ID is a string or composite... doesn't seem possible. Also, when is it appropriate to use table.insert vs. row.new (assuming I can get the later to work). Additionally, how does one do the most efficient batch inserts with this tool, assuming both hard coded with DSL/DAO syntax and from an external CSV or JSON file (assume 1k-10k records)?

**Comment by Tapac** [comment]
You can define your own StringEntityID (and related classes), Exposed doesn't provide them as it not so common case to use string as a primary key.
Please look at [UUIDEntity.kt](https://github.com/JetBrains/Exposed/blob/master/exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/UUIDEntity.kt) and [UUIDTable](https://github.com/JetBrains/Exposed/blob/6514a96c84c197ea516e04a4e2136e5ba1da877c/exposed-core/src/main/kotlin/org/jetbrains/exposed/dao/id/IdTable.kt#L67) as an example.

There is an issue about composite ids (#43), but it's not so easy to implement and not to break a current implementation. Feel free to provide a PR.

**Comment by gunslingor** [comment]
Much appreciated... yeah I need to figure out a way to download github libraries like this and contribute more, I'm just not educated on the right way to go about it.... particularly regarding managing the vast array of source files like this for each of my projects... I get the impression tools like npm, gradle, node and such could help with this but not sure what most people do.
