### ISSUE TITLE
Table alias loses primary and foreign keys

### ISSUE THREAD

**Issue by Benjozork** [JetBrains/Exposed#856]
Exposed version : 0.22.1

When creating an alias from a table : 
```kt
val alias = table.alias("hello")
```
Primary and foreign keys seem to be lost when creating a table `Alias`, which makes `Join::leftJoin` and others not work :

```kt
val oneTable = ...
val someOtherTable = ...
val alias = someOtherTable.alias("hello")

oneTable.leftJoin(alias) // Cannot join with org.jetbrains.exposed.sql.Alias@c1b840c3 as there is no matching primary key/foreign key pair and constraint missing
```

This seems confirmed by line 20 in `Alias.kt` :
```kt
override val columns: List<Column<*>> = delegate.columns.map { it.clone() }
```
and line 10 :
```kt
private fun <T:Any?> Column<T>.clone() = Column<T>(this@Alias, name, columnType)
```

which obviously drops FKs.

Is this intended behaviour ? If so, are there any plans to support this case and make `Join::leftJoin` aware of aliases ?

Thanks,

**Comment by Tapac** [comment]
You have to explicitly provide columns to join when using aliases as it's possible to use the same table multiple times in that case and Exposed could make a wrong desision on which columns to use:
```kotlin 
val oneTable = ...
val alias = someOtherTable.alias("hello")

oneTable.leftJoin(alias, oneTable.id, alias[oneTable.id])
```

**Comment by Benjozork** [comment]
Makes sense, that's what I ended up using, thanks !
