### ISSUE TITLE
UUID columns support

### ISSUE THREAD

**Issue by haizz** [JetBrains/Exposed#86]
Support for UUID columns is broken at the moment.

Problems found so far:

1. Cannot use ```eq``` in ```select ``` with PostgreSQL: ```org.postgresql.util.PSQLException: ERROR: operator does not exist: uuid = bytea``` in runtime.

2. Cannot use ```get``` with ```insert``` because key type is restricted to Number.

**Comment by haizz** [comment]
3. Cannot ```insert``` with PostgreSQL: ```org.postgresql.util.PSQLException: ERROR: column "uuid" is of type uuid but expression is of type bytea``` in runtime

**Comment by Tapac** [comment]
@haizz . Can you provide some examples for whose cases as we have simple test with UUID table and it works fine on Postgresql (see ViaTest.kt)
I'm not aware that postgresql jdbc driver returns UUID as generatedKey, have to check it.

**Comment by haizz** [comment]
Sorry about UUID key, please disregard that because PostgreSQL does not autogenerate UUID keys. 
No. 1 and 3 are still relevant though and make much bigger problem:

```kotlin
object Node : Table("node") {
    val uuid = uuid("uuid").primaryKey()
}

fun test() {
    transaction {
        val key: UUID = UUID.randomUUID()
        Node.insert { it[uuid] = key } // ERROR *
        val result = Node.select { Node.uuid.eq(key) }.toList() // ERROR *
    }
}

// * org.postgresql.util.PSQLException: ERROR: column "uuid" is of type uuid but expression is of type bytea
```

**Comment by Tapac** [comment]
Fixed in master. Will be available on next release.
