### ISSUE TITLE
Missing commas in wiki's DataTypes.md 

### ISSUE THREAD

**Issue by imhanner** [JetBrains/Exposed#862]
In the [DataTypes](https://github.com/JetBrains/Exposed/wiki/DataTypes) article some function calls of `customEnumeration` are missing commas between their parameters. Additionally I suggest removing the unnecessary indentation of the H2- and the MySQL-code-examples.

Unfortunatly I can't push to the wiki's git to create a pull request nor can I attach an updated `DataTypes.md` file here.

**Comment by Tapac** [comment]
@imhanner Thank you for a report. I will make separate repo for wiki soon, but your patch or `.md` will be fine at the moment.

**Comment by Tapac** [comment]
@imhanner , feel free to contribute:
https://github.com/JetBrains/Exposed/wiki/Contributing#how-to-improve-wiki-pages
