### ISSUE TITLE
primaryKey() cancells field's NOT NULL property

### ISSUE THREAD

**Issue by tetianazakhozhaeva** [JetBrains/Exposed#867]
### Case to reproduce:
**val id = long("id").primaryKey()** // Column<Long> - not null

but if to open with DBBrowser for SQLite: this field may accept null values - it becomes
 **id BIGINT PRIMARY KEY** // without **_NOT NULL_** modifier

if to describe field without primary key, it becomes not null as expected:
**val id = long("id")** // Column<Long> - not null
becomes
**id BIGINT NOT NULL** 

What combination of methods should I invoke to set field  **NOT NULL PRIMARY KEY**?

**Comment by Benjozork** [comment]
Most RDMS, including SQLite AFAIK, do not support nullable primary keys, so NOT NULL won't be appended.

Not sure if this is intended behavior in Exposed though.

**Comment by tetianazakhozhaeva** [comment]
Ordinary field
val id = long("id") // Column - not null
becomes
id BIGINT NOT NULL

If I want to allow this field to contain null

*val id = long("id").nullable()*becomes
id BIGINT


Exception of this behavior is setting primaryKey to ordinary field

SQLite supports definitions as PRIMARY KEY NOT NULL.
 My question is about how to implement desired behavior using Exposed lib.

чт, 9 апр. 2020 г. в 00:58, Benjamin Dupont <notifications@github.com>:

**Comment by hichem-fazai** [comment]
Why you need to add `NOT NULL` modifier for your primary key field? 
primarykey field won't accept null values without needing to be declared NOT NULL.

**Comment by Benjozork** [comment]
> Why you need to add `NOT NULL` modifier for your primary key field?
> primarykey field won't accept null values without needing to be declared NOT NULL.

I think SQLite has a bug that they refuse to fix (for compatibility, *sigh*) that makes it possible to input `null` values in PK columns.
