### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by BugsBunnyBR** [JetBrains/Exposed#87]
Hi, could someone point me to the project documentation or at least some github projects using it?

**Comment by Tapac** [comment]
There is no any documentation except samples on [main page](https://github.com/JetBrains/Exposed), but you can check [this blog post](https://spring.io/blog/2016/03/20/a-geospatial-messenger-with-kotlin-spring-boot-and-postgresql) and related project [Geospatial messenger application](https://github.com/sdeleuze/geospatial-messenger).

**Comment by Tapac** [comment]
Please look at [wiki](https://github.com/JetBrains/Exposed/wiki) .

**Comment by Edvinas01** [comment]
Are there any plans to add KDoc for public functions? Having to check the wiki constantly really breaks the flow.
