### ISSUE TITLE
Allow to create multiple Foreign Keys for columns

### ISSUE THREAD

**Issue by olegcherr** [JetBrains/Exposed#870]
In MySQL there is ability to create several Foreign Key Constraints for the same column.

Example:
```sql
CREATE TABLE `table1` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`));

CREATE TABLE `table2` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`));

CREATE TABLE `table3` (
  `id` int NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk1` FOREIGN KEY (`id`) REFERENCES `table1` (`id`),
  CONSTRAINT `fk2` FOREIGN KEY (`id`) REFERENCES `table2` (`id`)
)
```

Are there any plans to implement this feature in Exposed? At the moment `Column` can contain only one `referenceKey`, and `SchemaUtils.createStatements` generates wrong schema.

PS: Thanks guys! Great library :)

**Comment by Tapac** [comment]
Could you specify the use case?
At the moment, Exposed log multiple foreign key with `List of excessive foreign key constraints` as it make an overhead on inserts/updates and don't make a lot of sence (afaik).

**Comment by olegcherr** [comment]
@Tapac It was pretty difficult and strange use case, involving Polymorphic Associations. I dicided to change the architecture, so I no longer need multiple foreign keys. I guess at the moment this PR can be closed since there are no real user cases.
Thanks for reply!

**Comment by CrazyManLabs** [comment]
@olegcherr I have a task, that needs same kind of relation (polymorphic association). Can you share your solution of this task? It'll be great to see, how this is solved "the right way".

**Comment by olegcherr** [comment]
@CrazyManLabs Here is a good explanation on stackoverflow: https://stackoverflow.com/a/441111/4899346
Choose the solution that is best for you.
