### ISSUE TITLE
deadlock in spring boot 2.0 and using hikari cp 

### ISSUE THREAD

**Issue by elluard-doinglab** [JetBrains/Exposed#873]
Hello, 

I've been using exposed in my job

I found some problem in spring boot 2.0 and using hikari cp 

when I use code like below, deadlock is happened.

override fun authenticate(token: String?): AuthTokenRow? {
        val row = token?.let {
            transaction {
                AuthTokenRow.find { ... }
                        .toList()
            }
        }
        return row?.getOrNull(0)
    }

I spent  a lot of my time to solve it. I found some solution 

override fun authenticate(token: String?): AuthTokenRow? {
        val row = token?.let {
            transaction(dataBase) {
                AuthTokenRow.find { ....... }
                        .toList()
            }
        }
        return row?.getOrNull(0)
    }

when I pass the database as a parameter, deadlock isn't happened.

Can you explain me why the deadlock is happened?

**Comment by elluard-doinglab** [comment]
Addtional... 
I use exposed-spring-boot-starter ver 0.22.1

when I don't pass the database as a paramter, I find some log like below

2020-04-12 18:55:41.932 DEBUG 95385 --- [nio-8080-exec-1] o.j.e.spring.SpringTransactionManager    : Switching JDBC Connection [HikariProxyConnection@371268954 wrapping com.mysql.cj.jdbc.ConnectionImpl@4a9c61c9] to manual commit

**Comment by Tapac** [comment]
Could you please update to 0.23.1 and share the whole sample to check if the problem still persists?

**Comment by elluard-doinglab** [comment]
> Could you please update to 0.23.1 and share the whole sample to check if the problem still persists?

It doesn't persist any more. It seems to be fixed at 0.23.1

Thank you for your replying.
