### ISSUE TITLE
Arithmetic operations in select statement

### ISSUE THREAD

**Issue by yerundev** [JetBrains/Exposed#874]
There seems to be no documentation on how to perform arithmetic operations in a select statement using Exposed. Perhaps I missed something.

I am trying to calculate the Bayesian Average of some ratings which would be the following SQL query where **C** and **m** are two BigDecimal values already retrieved from a different query:
`SELECT (AVG(Rating.rating) * COUNT(Rating.id)) / (COUNT(Rating.id) + C) + ((m * C) / (COUNT(Rating.id) + m)) from Rating `

Where I run into trouble is the second part where the two constants need to be divided by the average rating plus **m**.

e.g. (first part left out for brevity)
`Expression.build {
[...].plus(doubleLiteral(C.times(m).toDouble()).div(ratingCount))
}`

This does not work since **ratingCount** is of type **Count** but I'm not sure how else to construct this

**Comment by Tapac** [comment]
You could try to cast Count to Double type:
```kotlin
ratingCount.castTo<Double>(DoubleColumnType())
```

**Comment by yerundev** [comment]
This fails on the call to _div_ with `None of the following functions can be called with the arguments supplied.`
```
doubleLiteral(C.toDouble())
   .times(m)
   .div(ratingCount.castTo<Double>(DoubleColumnType()))
```
where _C_ is of type BigDecimal, _m_ is of type Long and ratingCount is of type Count

**Comment by Tapac** [comment]
Cast should succeed on the latest 0.24.1
