### ISSUE TITLE
table update increment error

### ISSUE THREAD

**Issue by Linuxea** [JetBrains/Exposed#879]
![image](https://user-images.githubusercontent.com/18577499/79430903-3a9bda00-7ffc-11ea-8420-21da3f001b5c.png)

I learn from https://github.com/JetBrains/Exposed/wiki/DSL#update and I got an error.
Thank you very much.

**Comment by Tapac** [comment]
Could you specify Exposed and Kotlin version you use and also `UserPurseTable.goldNum` type?

**Comment by Linuxea** [comment]
Yes. 

<kotlin.version>1.3.70</kotlin.version>
 <jetbrains.exposed.version>0.22.1</jetbrains.exposed.version>

and my table UserPurseTable:
```kotlin
object UserPurseTable : Table("user_purse") {

    val userId = long("uid")
    val goldNum = long("gold_num")
    val diamondNum = double("diamond_num")

}
```

Thank you very much.

**Comment by Linuxea** [comment]
I try to upgrade <code>gold_num</code> from <code>Int</code> to <code>Long</code>
```kotlin
it[UserPurseTable.goldNum] = UserPurseTable.goldNum - goldNum.toLong()
```
but error too.

**Comment by Linuxea** [comment]
some body here?

**Comment by leeroyhero** [comment]
This possible with SqlExpressionBuilder
`OfferTable.update({ OfferTable.id eq orderId }) {
            with(SqlExpressionBuilder) {
                it[followed] = followed + 1
            }
        }`
