### ISSUE TITLE
reWriteBatchedInserts does not work with PostgreSQL

### ISSUE THREAD

**Issue by ekans** [JetBrains/Exposed#881]
I'm trying to use reWriteBatchedInserts with a PostgreSQL database. According to [pgjdbc](https://github.com/pgjdbc/pgjdbc/pull/491) the rewrite is possible only if no return values are requested.

In `InsertStatement.kt`:
```kotlin
    override fun prepared(transaction: Transaction, sql: String): PreparedStatementApi = when {
        // https://github.com/pgjdbc/pgjdbc/issues/1168
        // Column names always escaped/quoted in RETURNING clause
        autoIncColumns.isNotEmpty() && currentDialect is PostgreSQLDialect ->
            transaction.connection.prepareStatement(sql, true)

        autoIncColumns.isNotEmpty() ->
            // http://viralpatel.net/blogs/oracle-java-jdbc-get-primary-key-insert-sql/
            transaction.connection.prepareStatement(sql, autoIncColumns.map { it.name.inProperCase() }.toTypedArray())

        else ->
            transaction.connection.prepareStatement(sql, true)
    }
```
So the prepare statement is always call with `true`.

In `JdbcConnectionImpl`:
```kotlin
    override fun prepareStatement(sql: String, returnKeys: Boolean) : PreparedStatementApi {
        val generated = if (returnKeys)
            PreparedStatement.RETURN_GENERATED_KEYS
        else
            PreparedStatement.NO_GENERATED_KEYS
        return JdbcPreparedStatementImpl(connection.prepareStatement(sql, generated), returnKeys)
    }
```
So every insert requests set `returnKeys` to  `PreparedStatement.RETURN_GENERATED_KEYS`.

The consequence is that the optimization implies by `reWriteBatchedInserts` is not done.

Am I missing something?

ps: I'm using `batchInsert` and I set `reWriteBatchedInserts` to true correctly (I checked it in debug). I also tested some inserts using directly the jdbc api and the rewrite worked (I saw it in postgresql logs).

**Comment by ps-feng** [comment]
I was just searching why `reWriteBatchedInserts` had no effect in my code and this may very well explain it. I'm seeing no difference between having the flag enabled or not.

**Comment by Tapac** [comment]
@ps-feng, your approach applied to master. Will be available in 0.24.1, could you please check that it helps?

**Comment by ekans** [comment]
@Tapac it does not work in my use case: with PostgreSQL I want to make a batch insert into a table with an auto inc column and I don't care about the generated id.

A batch insert which returns the generated ids seems to work with MySQL JDBC driver (see https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-configuration-properties.html) but it does work with PostgreSQL JDBC driver because returning any columns is a condition to not activate the optimization. See https://github.com/pgjdbc/pgjdbc/pull/491#issuecomment-171575491.

So I want to use batchInsert and to ignore the generated keys with PostgreSQL.

I don't see a solution with the current code. Do you confirm it?

**Comment by Tapac** [comment]
@ekans , I added `shouldReturnGeneratedValues` param to `batchInsert`, will be available in 0.24.2

**Comment by ekans** [comment]
@Tapac great!
Do you have a release date?

**Comment by Tapac** [comment]
Today or tomorrow.

**Comment by ekans** [comment]
@Tapac for your information I just tested version 0.25.1 and it works great!
Thanks.

**Comment by tuananh** [comment]
@ekans @Tapac sorry for digging up this issue but i'm having the same problem with latest 1.0.0 release


this is what i have

```
val db = R2dbcDatabase.connect(
        url = "r2dbc:postgresql://$dbHost:$dbPort/$dbName?reWriteBatchedInserts=true",
        user = dbUser,
        password = dbPassword,
    )
```
and 

```kotlin
JobTable.batchInsert(jobs, shouldReturnGeneratedValues = false) { (payload, templateId, scheduledAt) ->
            this[JobTable.payload] = payload
            //
        }
```

the table has an id col that is autoincremental.
