### ISSUE TITLE
Should LocalDate be stored by default in UTC?

### ISSUE THREAD

**Issue by ps-feng** [JetBrains/Exposed#886]
When using `date` as a table column (`Column<LocalDate>`) the value saved to the DB [depends](https://github.com/JetBrains/Exposed/blob/0e00de559d2926bbba67aa38ddc7d4f707345d83/exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/java-time/JavaDateColumnType.kt#L37) on the timezone of the system. This means something like
```kotlin
SomeTable.insert {
    this[date] = LocalDate.parse("2020-01-01")
}
```
will be non-deterministic. The same code will insert a different value depending on the machine where it's run.

My suggestion would be to make dates use UTC by default.

EDIT: it seems this happened because I had created the column via regular SQL as a `timetamptz` (Postgres) so there was a mismatch. Even though `JavaLocalDateColumnType`'s SQL type is `DATE` it continued to work, albeit incorrectly, not sure if this should be a bug or not.

**Comment by adamu** [comment]
I've also encoutered this.

Java's `LocalDate` and SQL's `DATE` are both timezone-free. So there should be no timezone conversion required.

However, `JavaLocalDateColumnType` converts to a `java.sql.Date` using the local timezone. This means that, for example, in UTC+n timezones a `LocalDate` of `1991-01-01` will be stored as `1990-12-01`.
