### ISSUE TITLE
Where IN Clause not working

### ISSUE THREAD

**Issue by Bonythomasv** [JetBrains/Exposed#893]
I was expecting this query to work, But it does not and does not throw any error either.

DB: Postgres

            DeviceRegistrationsTable.deleteWhere { DeviceRegistrationsTable.deviceId.inList( listOf("1","2","3"))}

Actual query works:
delete from device_registrations where device_id in ('1','2','3');

Is there any bug? or am i missing something?

**Comment by Tapac** [comment]
Could you show a whole sample to check?
