### ISSUE TITLE
Add support for LATERAL joins

### ISSUE THREAD

**Issue by NikolayMetchev** [JetBrains/Exposed#899]
Postgres has added support for LATERAL joins:
https://www.postgresql.org/docs/9.4/queries-table-expressions.html

Can we please add support for those types of join to exposed?

**Comment by damien-roche** [comment]
@Tapac is this something you would accept PRs for?

I would really love support for this as would simplify a few of the queries I'm working on.

My plan would be to add a `joinModifier` to the `JoinPart` along with enum `JoinModifier.LATERAL` and then append the modifier here:

https://github.com/JetBrains/Exposed/blob/master/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt#L215
