### ISSUE TITLE
Support for LocalTime

### ISSUE THREAD

**Issue by abishai** [JetBrains/Exposed#900]
I found an issue for support of LocalDate, https://github.com/JetBrains/Exposed/issues/100 but nobody asked for a time support.
https://www.postgresql.org/docs/9.1/datatype-datetime.html#DATATYPE-DATETIME-TABLE

Obviously, time can be stored with timestamp type, but I think it would be nice to have time column type.

**Comment by aivinog1** [comment]
@abishai @Tapac Hello! Does this issue is still present? I see that LocalDateTime is implemented already: https://github.com/JetBrains/Exposed/blob/43d6ab17579e1b52b2831690d5257ca8c56b3549/exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/java-time/JavaDateColumnType.kt#L70

**Comment by abishai** [comment]
This is still present, the issue is about LocalTime.

**Comment by Popeyef5** [comment]
I'm interested in LocalTime support as well!

**Comment by saibotma** [comment]
Why is this closed? This feature is essential.

**Comment by fhoner** [comment]
I'm also very interested!

**Comment by adamu** [comment]
[This](https://github.com/JetBrains/Exposed/issues/100#issuecomment-418229472) comment explained it well:

> Please note that in Java Time, `LocalDate` and `Instant` are used to represent two different concepts. The difference is explained very well in the documentation, but in short, LocalDate is suitable for birthdays, commemorative dates etc, whereas Instant represents a specific point in "universal" time such as a meeting time (across time zones).
> 
> In the case of Postgres, `LocalDate` would be mapped to the `Date` column type, whereas `Instant` would be mapped to `TIMESTAMP WITHOUT TIME ZONE`.
> 
> It would be great to see both of these supported in Exposed.

The current implementation in `JavaDateColumnType` adds a timezone. This is not the correct thing to do for abstract dates such as birthdays, or anything where we want to refer to a *date* not a *point in time*. We should be able to get a Java `LocalTime` into an SQL `DATE` without it going via a `java.sql.Date` object.

For example, if the system timezone is UTC+n, and I create a `LocalDate` of `1991-01-01`, the value that will be put into the column is `1990-12-31`.
