### ISSUE TITLE
error: unresolved reference: jetbrains

### ISSUE THREAD

**Issue by be-rock** [JetBrains/Exposed#907]
Hi, 
I am new to Kotlin and believe that I have all my dependencies resolved however whenever I run the app I am getting an error that looks like may a dependencies issue.  What am I missing?  Thanks in advance.

```kotlin
$ kotlinc src/main/kotlin/MyApp.kt
src/main/kotlin/MyApp.kt:1:12: error: unresolved reference: jetbrains
import org.jetbrains.exposed.sql.*
           ^    
```

```
// src/main/kotlin/MyApp.kt
import org.jetbrains.exposed.sql.*

fun main() {
    println("test")
}
```

```
// build.gradle
plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '1.3.72'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile("org.jetbrains.exposed:exposed-core:0.23.1")
    compile("org.jetbrains.exposed:exposed-dao:0.23.1")
    compile("org.jetbrains.exposed:exposed-jdbc:0.23.1")
    compile group: 'org.xerial', name: 'sqlite-jdbc', version: '3.31.1'

}

compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
compileTestKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
```

`gradlew dependencies` seems to suggest that all dependencies have been resolved.

```
$ ./gradlew dependencies
... 
BUILD SUCCESSFUL in 735ms
1 actionable task: 1 executed     
```

**Comment by Tapac** [comment]
I think the problem is that you use `kotlinc` without providing dependencies. kotlin compiler doesn't use gradle config.
You have to read how to run kotlin app with gradle or just use IDEA and you could just run your main function from it.

**Comment by CommanderTvis** [comment]
You shouldn't compile Gradle projects with `kotlinc`, since it is very uncomfortable to reference all the dependencies in the CLI. 

Use `gradle classes` or `./gradlew classes` to have Kotlin classes compiled.

**Comment by be-rock** [comment]
Thank you both.  `./gradlew classes` worked fine to produce the class file.  Now for the next silly question (i told you i am new to kotlin :)) - how do i run it from the command line?

**Comment by CommanderTvis** [comment]
> Thank you both. `./gradlew classes` worked fine to produce the class file. Now for the next silly question (i told you i am new to kotlin :)) - how do i run it from the command line?

Windows: `gradlew classes`
Linux: `./gradlew classes`

**Comment by be-rock** [comment]
Thanks for your response and sorry that i was not clear.  After I run `./gradlew classes` i see a class file is produced at:

`./build/classes/kotlin/main/foo/bar/baz/MyAppKt.class`

How do execute that from the command line?

**Comment by Benjozork** [comment]
You should run your project using an IDE or using Gradle. Java is not a CLI-friendly programming ecosystem. You will have to deal with `classpath` and other annoying things.

**Comment by be-rock** [comment]
Ok, the missing component was this in my `build.gradle`.  

```
jar {
    manifest {
        attributes 'Main-Class': 'foo.bar.baz.MyAppKt'
    }
}
```

Thanks again!

**Comment by be-rock** [comment]
Adding these 2 lines to `MyApp.kt`:

```
    Database.connect("jdbc:sqlite:/data/data.db", "org.sqlite.JDBC")
    println(db.dialect)
```

Now results in:
```
test
Exception in thread "main" java.lang.NoClassDefFoundError: org/jetbrains/exposed/sql/Database
        at org.example.MyAppKt.main(MyApp.kt:8)
        at org.example.MyAppKt.main(MyApp.kt)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.exposed.sql.Database
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 2 more                                           
```

I'm clearly missing something obvious here.

**Comment by Tapac** [comment]
You still should provide all dependencies with `-cp` if you'd like to use `java -jar`. Or build uberJar/shadowJar with some gradle plugins (https://github.com/johnrengelman/shadow).
