### ISSUE TITLE
TransactionManager.currentThreadManager not always reset with multiple Database.connect calls

### ISSUE THREAD

**Issue by jpenglert** [JetBrains/Exposed#91]
The below test case demonstrates a bug with the `TransactionManager.currentThreadManager ThreadLocal` variable not being reset properly between separate database connections (i.e. Calling `Database.connect()` multiple times in same process). At best this will cause a failure if the underlying DB no longer exists as the test case demonstrates. At worst the transaction will be performed against the wrong DB.

Also, perhaps a separate bug, but heavily related to this, is the `TransactionManager.currentThreadManager` `ThreadLocal` variable will not be reset if Transaction.close() throws an exception in the finally block of `ThreadLocalTransactionManager`:

    finally {
            transaction.currentStatement = null
            transaction.lastExecutedStatement = null
            transaction.close()
            TransactionManager.currentThreadManager.remove()
    }

I believe the lifecycle management of `TransactionManager.currentThreadManager` needs to be reviewed as it seems very fragile and prone to subtle bugs.

Test case (depends on org.xerial:sqlite-jdbc:3.16.1 but any DB should repro the issue):

    import org.jetbrains.exposed.sql.Database
    import org.jetbrains.exposed.sql.transactions.TransactionManager
    import org.jetbrains.exposed.sql.transactions.transaction
    import org.junit.After
    import org.junit.Before
    import org.junit.Rule
    import org.junit.Test
    import org.junit.rules.TemporaryFolder
    import org.sqlite.SQLiteDataSource
    import java.sql.Connection

    /**
     * Demonstrates bug for following sequence:
     *
     * 1. Connect to Database
     * 2. Access Database.url
     * 3. Discard underlying database (e.g. delete file)
     * 4. Connect to Database (with new underlying file)
     * 5. Perform a transaction which fails
     *
     * Example output from running this test fixture (shows test2 performing a transaction against the DB created by test1):
     *
     * test1 url: jdbc:sqlite:C:\Users\jdoe\AppData\Local\Temp\junit6537693933031618377\foo.db
     * test2 url: jdbc:sqlite:C:\Users\jdoe\AppData\Local\Temp\junit1752608586457378159\foo.db
     * TransactionManager: org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager@1375618
     * 2017-01-30 09:48:04,372 [      main] [Exposed] INFO  - Transaction attempt #0: path to
     * 'C:\Users\jdoe\AppData\Local\Temp\junit6537693933031618377\foo.db':
     * 'C:\Users\jdoe\AppData\Local\Temp\junit6537693933031618377' does not exist. Statement: null
     * java.sql.SQLException: path to 'C:\Users\jenglert\AppData\Local\Temp\junit6537693933031618377
     * \foo.db': 'C:\Users\jdoe\AppData\Local\Temp\junit6537693933031618377' does not exist
     * at org.sqlite.core.CoreConnection.open(CoreConnection.java:192) ~[sqlite-jdbc-3.16.1.jar:?]
     */
    class MultipleDatabaseBug {

        @Rule @JvmField
        val folder = TemporaryFolder()

        var db: Database? = null

        @Before
        fun before() {
            val filename = folder.newFile("foo.db").absolutePath
            val ds = SQLiteDataSource()
            ds.url = "jdbc:sqlite:" + filename
            db = Database.connect(ds)

            // SQLite supports only TRANSACTION_SERIALIZABLE and TRANSACTION_READ_UNCOMMITTED
            TransactionManager.defaultIsolationLevel = Connection.TRANSACTION_SERIALIZABLE
        }

        @After
        fun after() {
            // Uncommenting this line will allow "test2" to succeed
    //        TransactionManager.currentThreadManager.remove()
        }

        @Test
        fun test1() {
            printStuff(1)
        }

        @Test
        fun test2() {
            printStuff(2)
            initDb()
        }

        private fun printStuff(test: Int) {
            // Accessing "db?.url" lazily initializes Database.url by calling Database.metadata
            // which first calls TransactionManager.currentOrNull which initializes the
            // TransactionManager.currentThreadManager ThreadLocal value which is never removed if
            // there is no subsequent transaction
            println("test${test} url: ${db?.url}")
        }

        private fun initDb() {
            transaction {
                println("TransactionManager: ${TransactionManager.currentThreadManager.get()}")
                println("Transaction connection url: ${connection.metaData?.url}")
            }
        }
    }

**Comment by jpenglert** [comment]
Using org.jetbrains.exposed:exposed:0.7.5

**Comment by Tapac** [comment]
Thank you for report. I have used your example as test case.
It was fixed and pushed to master. Will be available with 0.7.7 (i guess). 
Also note that TransactionManager.defaultIsolationLevel replaced with TransactionManager.manager.defaultIsolationLevel .
