### ISSUE TITLE
Release tagging

### ISSUE THREAD

**Issue by rorymurphy** [JetBrains/Exposed#913]
It appears there are quite a few versions available on bintray that are not tagged in Github. This makes it more difficult to trace runtime behavior back to its source. Also, in a corporate environment, using open source software often requires documentation, such as proving the specific version has an acceptable license (which can change version to version). Having a tag for each version makes it easier to gather and document this type of info.

**Comment by Tapac** [comment]
Sorry, the tagging is not automated in bintray release plugin so I make it by hands and sometimes forgot to do it. I'll look for a way to automate this.

**Comment by rorymurphy** [comment]
Thanks! The framework is great, and this will make it much easier keep our project version up to date, so it's really appreciated.
