### ISSUE TITLE
Missing cache invalidation for upsert

### ISSUE THREAD

**Issue by betacore** [JetBrains/Exposed#914]
We decided to use the full functionality of Tables and DAOs, working only with DAOs like it is specified. The problem is that we have to upsert multiple objects at the same time which means we also work with upsert statements which we adapted by the BatchInsert. The BatchUpsert works like a charm but if we load some DAOs then upsert them and load them again they do not have the upserted changes because the cache is not invalidated.

I think it could be solved manually when there is a function like DAO.clearCache() to remove all cached entities of the DAO. This would also help for updates which are done by tables or raw sql statements.

**Comment by Tapac** [comment]
Entity cache invalidation implemented in `EntityLifecycleInterceptor` and you have to implement (and register) your own intercepter and make it similar to `UpdateStatement` branch. Or inherit from Exposed UpdateStatement.
