### ISSUE TITLE
Leaking prepared statements

### ISSUE THREAD

**Issue by inikolaev** [JetBrains/Exposed#92]
While running sample application I noticed that statements are not being closed.

Below is modified example where I insert `1,000,000` records using Exposed API and using JDBC `PreparedStatement`s directly. When using JDBC directly I can manually close statements, but with Exposed API I can see a growing number of `PreparedStatement`s in profiler.

Is there any way to manually close statements?

```kotlin
import org.jetbrains.exposed.sql.*
import org.jetbrains.exposed.sql.transactions.transaction
import org.jetbrains.exposed.sql.SchemaUtils.create
import org.jetbrains.exposed.sql.SchemaUtils.drop

object Cities : Table() {
    val id = integer("id").autoIncrement().primaryKey() // Column<Int>
    val name = varchar("name", 50) // Column<String>
}

fun main(args: Array<String>) {
    Database.connect("jdbc:h2:mem:test1;DB_CLOSE_DELAY=-1", driver = "org.h2.Driver")

    transaction {
        create(Cities)
    }

    // Kotlin Expose syntax
    (1..1000000).forEach {
        transaction {
            val saintPetersburgId = Cities.insert {
                it[name] = "St. Petersburg"
            } get Cities.id
        }
    }

    // JDBC syntax
    (1..1000000).forEach {
        transaction {
            val stmt = prepareStatement("INSERT INTO cities (name) VALUES (?)")
            stmt.setString(1, "Moscow")
            stmt.execute()
            stmt.close()
        }
    }

    transaction {
        drop (Cities)
    }
}
```

**Comment by Tapac** [comment]
On exit from transaction {} block there is a Connection.close() method execution, which will close all underlying statements (in common case). Also if DBMS doesn't support multiple opened result sets (e.g. sqlite), last prepared statement will be closed before execution of new one.

I did profile of both parts (Kotlin/JDBC syntax) and can't see much difference in allocation of PreparedStatements and its lifecycle within a heap.

Can you provide profiler snapshot to investigate leaking source?

**Comment by inikolaev** [comment]
I will create snapshots later today. Meanwhile I have a screenshot from YourKit, that is why I started looking into that:

<img width="1004" alt="screen shot 2017-02-05 at 23 45 52" src="https://cloud.githubusercontent.com/assets/7585750/22643070/b2a4b572-ec65-11e6-97ab-ac73782c7307.png">

The point where the graph flattens is when the JDBC syntax starts working and at least it looks like all statements opened by Kotlin are not being closed.

As for multiple opened result sets - is it correct that it has to be supported for all types of statements? Reading documentation [here]( https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#supportsMultipleOpenResults--) it looks like it should only be used for `CallableStatement`. For other types there is a different [flag](https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#supportsMultipleResultSets--), if I understand correctly.

**Comment by Tapac** [comment]
Ouch, you are absolutely right that we used wrong flag to detect when previous statement should be closed.
Strange that H2 driver doesn't close statements while closing connection.

I have change flag to `supportsMultipleResultSets` and now it works like a charm:
![1a8f2d60b4208f1848b75daa5404b7f5](https://cloud.githubusercontent.com/assets/194469/22644821/176b289c-ec75-11e6-9c67-64a7445b98fa.png)

I will push changes and release it soon. Thank you for reporting!

**Comment by inikolaev** [comment]
Glad I could help :)

**Comment by Tapac** [comment]
Fix should be available with 0.7.6 release, please feel free to [check it on bintray](https://bintray.com/kotlin/exposed/exposed/0.7.6)

**Comment by inikolaev** [comment]
@Tapac I'm still getting the same graph, though when I look at snapshot it says that those objects are only accessible via Weak or Soft references. But you had a different graph, how did you get it?

<img width="1026" alt="screen shot 2017-02-06 at 18 24 22" src="https://cloud.githubusercontent.com/assets/7585750/22655699/9b9adbac-ec99-11e6-8f7f-66a9ac13aa28.png">

**Comment by Tapac** [comment]
@inikolaev . Looks like file was missed from commit (-_-). 
Could you, please, test it with latest master before I make new release?

**Comment by inikolaev** [comment]
@Tapac Looks good now!

![screen shot 2017-02-07 at 11 30 52](https://cloud.githubusercontent.com/assets/7585750/22685434/f5b31c46-ed28-11e6-8063-24e0b70301ce.png)
