### ISSUE TITLE
Datetime Mapping issue

### ISSUE THREAD

**Issue by Shashank-Nous** [JetBrains/Exposed#923]
Hello there. I am stuck with the datetime mapping issue. Please help out.

I have the following table definition 

```
object TableName : Table() {
    val id = varchar("id", 32)
    ........
    val transDate = datetime("transdate")
    ..........
}
```
and the `transDate has '0000-00-00 00:00:00' or null `for some rows. I am using **MariaDB** as the database. I use below code to fetch rows

` val query = TableName.selectAll()`

It causes following exception

**java.sql.SQLException: Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp**

**Comment by Tapac** [comment]
Could you investigate how you've got `0000-00-00 00:00:00` as value in database?

**Comment by Shashank-Nous** [comment]
The database is very old one. We are migrating the APIs written in SQL JDBC to use Kotlin Exposed. Is there a way we can fetch the records without updating the database?

**Comment by Shashank-Nous** [comment]
Sounds good. Thanks @Tapac
