### ISSUE TITLE
[Question] How one could implement JOIN with a subquery?

### ISSUE THREAD

**Issue by iVovolk** [JetBrains/Exposed#927]
First of all, thank you for your hard work.
The question is, how to write a query like below using Exposed

```
SELECT *
FROM categories
      LEFT JOIN products ON products.id = (
             SELECT products.id 
             FROM products 
             WHERE products.category_id = categories.id 
             LIMIT 1
     )
LIMIT 10
```
I'd found [related issue](https://github.com/JetBrains/Exposed/issues/248) but it didn't help

**Comment by TheReprator** [comment]
@iVovolk  did you got the solution, if yes please share

**Comment by Tapac** [comment]
There is `eqSubQuery` operator in Exposed, you can use it like:
```kotlin
Categories.join(Products, JoinType.LEFT) {
   Products.id eqSubQuery Products.slice(Products.id).select { Products.id eq Categories.id).limit(1)
}
```
But I think in that case it's more efficient to not use subquery. afaiu the code below will give same result.
```sql
SELECT * 
FROM categories 
   LEFT JOIN products on categories.id = products.category_id
LIMIT 10
```

**Comment by TheReprator** [comment]
@Tapac , thanks for the quick response, then, how can i achieve it with alias?

**Comment by iVovolk** [comment]
@Tapac thahks for the response. Eventually i came up with the similar solution by rewriting my query.  I was asking because in my case the query with a subquery wokrked a bit faster than without. 
Anyway, the proplem is solved! Thanks.

**Comment by Tapac** [comment]
@TheReprator, can you clarify what kind of `alias` do you mean?

**Comment by TheReprator** [comment]
no, i am good with it, we can close the issue now, thanks for the assistance @Tapac

**Comment by Tapac** [comment]
Please provide raw SQL and I'll try to show how to convert it into Exposed DSL
