### ISSUE TITLE
DAO: Decide when to flush the changes

### ISSUE THREAD

**Issue by Shyrogan** [JetBrains/Exposed#931]
Hello,
I've ran into an issue when using Exposed, I've decided to use DAO because they seem intuitive but I want to decide when to flush the changes and store them locally instead of flushing them everytime I set the value.
I need this because I need to store data about a player in and I want to update it only when he disconnects.
Thanks for helping!

**Comment by Tapac** [comment]
You could flush changes manually, but please read an [DAO update](https://github.com/JetBrains/Exposed/wiki/DAO#update) section it describes the way exposed flushes changes.

**Comment by Tapac** [comment]
You could try to accumulate all changes and call provided code just before the end of the user request:
```kotlin
val profilesToUpdate: MutableList<Profile> ...
// Code which changes entities

transaction {
   profilesToUpdate.forEach { 
      Profile.store(it)
  }
}
// end of your code

```

**Comment by Shyrogan** [comment]
That's a wacky solution, it would be nice if we could decide to store the updates for a DAO and then update them using `Profile.update(it)`

**Comment by Tapac** [comment]
What's the difference with the provided code?
You could make your own function which will persist data to the database whenever you need it.

**Comment by Shyrogan** [comment]
I don't know, that's how [Requery](https://github.com/requery/requery) works yet it's made for Java, I just feel like we could trust people who use the library to decide when to update. Just a personal opinion, thanks for answering!
