### ISSUE TITLE
Tests are failing during the build

### ISSUE THREAD

**Issue by Isabek** [JetBrains/Exposed#939]
I just wanted to contribute to this project. Unfortunately, some tests are failing. 

For example MiscTableTest.testInsert01 - for SQL Lite. 

```
Expected :2020-06-03T12:43:50.862881Z
Actual   :2020-06-03T12:43:50.862Z
```

I am trying to build a master branch.

So, as I understood java.sql.Timestamp(long)'s equals compares `nanos` fields. 

I am just wondering only I have this issue?

**Comment by Tapac** [comment]
Could you please specify your environment: OS, JDK ?

**Comment by Isabek** [comment]
Sure, 

JDK: 8.0.252-open
OS: Ubuntu 18.04
