### ISSUE TITLE
DAO one to one reference problem

### ISSUE THREAD

**Issue by Aileron1410** [JetBrains/Exposed#94]
I want to get one to one support, trying to do it like this, but have an exception "java.lang.ClassCastException: java.lang.Integer cannot be cast to org.jetbrains.exposed.dao.EntityID
	at org.jetbrains.exposed.dao.Entity.getValue(Entity.kt:195)
	at User"
Please, help, how can I get a one to one reference?
```Kotlin
object Humans : IdTable<Int>("human") {
	override val id: Column<EntityID<Int>> = Humans.integer("id").autoIncrement().primaryKey().entityId()
	val h = text("h")
}

object Users : IdTable<Int>("user") {
	override val id: Column<EntityID<Int>> = Users.integer("id").primaryKey().entityId() references Humans.id

	val name = text("name")
}

open class Human (id: EntityID<Int>) : IntEntity(id) {
	companion object : IntEntityClass<Human>(Humans)
	var h by Humans.h
}

class User(id: EntityID<Int>) : IntEntity(id) {
	companion object : IntEntityClass<User>(Users){
		fun create(
				name: String
		): User {
			val h = Human.new { h = "h"}
			val res = User.new(
					h.id.value, {
				this.name = name
			})
			return res
		}
	}

	var name by Users.name
	var human by Human referencedOn Users.id
}

fun main(args: Array<String>) {
	Database.connect("jdbc:h2:mem:test", driver = "org.h2.Driver")

	transaction {
		logger.addLogger(SqlLogger())
		SchemaUtils.create(Humans)
		SchemaUtils.create(Users)

		val user = User.create("name")
		val human = user.human
	}
}
```
output:
INFO: CREATE TABLE IF NOT EXISTS HUMAN (ID INT AUTO_INCREMENT PRIMARY KEY, H TEXT NOT NULL)
INFO: CREATE TABLE IF NOT EXISTS "USER" (ID INT PRIMARY KEY, NAME TEXT NOT NULL,  FOREIGN KEY (ID) REFERENCES HUMAN(ID) ON DELETE RESTRICT)
INFO: INSERT INTO HUMAN (H) VALUES ('h')
Exception in thread "main" java.lang.ClassCastException: java.lang.Integer cannot be cast to org.jetbrains.exposed.dao.EntityID
	at org.jetbrains.exposed.dao.Entity.getValue(Entity.kt:195)
	at User

**Comment by Tapac** [comment]
Thank you for reporting. Issue fixed in master and will be released soon. 
Your example used as test case, with minor changes (you can check a bit shorter definition [here](https://github.com/JetBrains/Exposed/blob/8b5887a46536d0b062fd6a02766040b29acf60de/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/EntityTests.kt#L229))
