### ISSUE TITLE
TeamCity builds appear flaky depending on the build agent in use

### ISSUE THREAD

**Issue by KushalP** [JetBrains/Exposed#947]
I recently opened #944  and a few other PRs. I have noticed that the OS of the build agent can impact whether a build will pass or fail.

Note the two builds here: https://teamcity.jetbrains.com/buildConfiguration/Exposed_PullRequests?branch=944%2Fmerge&buildTypeTab=overview&mode=builds#all-projects

The code change run is identical for both build instances, but the Windows build agent fails

**Comment by KushalP** [comment]
I do wonder if it's worth using GitHub Actions for builds and PR feedback for contributors. It gives a lot more visibility in place. Then all of the publish/deploy steps can be kept in TeamCity.

There are also nice actions like this one to make sure the `gradle-wrapper.jar` in use has not been tampered with: https://github.com/marketplace/actions/gradle-wrapper-validation

**Comment by Tapac** [comment]
@KushalP , I had temporary excluded Windows agents as embedded MySQL mxj doesn't work on this OSs. There open issue to replace mxj with something fresh #894.

**Comment by KushalP** [comment]
@Tapac is it worth moving to [docker-compose](https://docs.docker.com/compose/) or [testcontainers](https://www.testcontainers.org/) to drive docker containers with these legacy versions in place?

An alternative is to move away from legacy libraries altogether. It's not clear what the deprecation and support path is for Exposed. Are you intending to support everything forever?

**Comment by Tapac** [comment]
Docker Composed based tests are already [here](https://github.com/JetBrains/Exposed/wiki/Contributing#how-to-run-docker-based-tests) but also there are some embedded tests (h2/sqlite/mysql/postgresql) which run altogether from a single gradle test task. It's worth to move them from embedded implementation to test-containers, but I don't really have much time for this 😭 . It will be great if you could PR such changes!

**Comment by KushalP** [comment]
I'm happy to look into this. @Tapac are you able to configure TeamCity to post the build status to GitHub? I've created to track this #956

**Comment by KushalP** [comment]
I'll then close this, once #956 is setup, as the core issue is documented elsewhere.

**Comment by KushalP** [comment]
Closing this issue, as the PR related to this is now ready for review.
