### ISSUE TITLE
Constant expression to use in slice

### ISSUE THREAD

**Issue by mustafin** [JetBrains/Exposed#955]
I need to make Insert from Select of another table but with hardcoded some fields like 

`Table1.insert(Table2.slice(Table2.field1, Table2.field2, "foo").selectAll())`

Here I need to pass `"foo"` as the third field for `Table1`
Is there anything like constant expression?

**Comment by Tapac** [comment]
Use `stringLiteral("foo")` for that.

**Comment by mustafin** [comment]
Thank you, was searching for this for a while
