### ISSUE TITLE
Configure TeamCity to update GitHub build status

### ISSUE THREAD

**Issue by KushalP** [JetBrains/Exposed#956]
Getting build feedback is useful for everyone on this project. It's easy to understand the state of a given PR with a quick glance.

TeamCity has the following page on this, but it requires a project administrator to do this: https://www.jetbrains.com/help/teamcity/commit-status-publisher.html#

**Comment by Tapac** [comment]
@KushalP, looks like I was able to setup that TC feature, but don't know how to check it.

**Comment by KushalP** [comment]
Maybe push a branch and see if it shows a green tick?

**Comment by KushalP** [comment]
I can confirm that this is working as you can see by the built status on the commits: https://github.com/JetBrains/Exposed/pull/957
