### ISSUE TITLE
Non-Companion EntityClass

### ISSUE THREAD

**Issue by crazyproger** [JetBrains/Exposed#96]
I'm using Exposed dao with `EntityClass`'es. Into one entity I need to pass some data, and this data is available only at runtime(by DI). 
One way I've found is to create child of `EntityClass` with this data injected in constructor. 
But with `EntityClass` parent in _non-Companion_ class definition it throws runtime exception because of this property in `EntityClass`:
```kotlin
private val klass = javaClass.enclosingClass!!
````
And as I see this is only place that prevent using `EntityClass` in this way(am I wrong?)
What you think about moving it to constructor parameters?
I can make PR if you accept this way.

**Comment by Tapac** [comment]
Fixed in related commit in master. If it possible, could you test what it suits your needs before I will publish release?

**Comment by crazyproger** [comment]
@Tapac Big thank you - will check it within a hour!

**Comment by crazyproger** [comment]
Works excellent
