### ISSUE TITLE
how to randomly select rows from a database table

### ISSUE THREAD

**Issue by artharyoung** [JetBrains/Exposed#960]
if i want SELECT * FROM "table name" ORDER BY RANDOM() limit 1

**Comment by Benjozork** [comment]
Exposed seems to support the RANDOM function [here](https://github.com/JetBrains/Exposed/blob/56863e01961ea0eb0cb44c928b73ffecec5ed861/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Function.kt#L53), but I'm not sure I've ever seen that syntax before. You could try that.

**Comment by artharyoung** [comment]
> Exposed seems to support the RANDOM function [here](https://github.com/JetBrains/Exposed/blob/56863e01961ea0eb0cb44c928b73ffecec5ed861/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Function.kt#L53). You could try that.
> 
> Seems to be correct in code :
> ![image](https://user-images.githubusercontent.com/4503241/84956539-70764100-b0c7-11ea-8534-b3d250cf06ad.png)
> And to generate the syntax you want :
> ![image](https://user-images.githubusercontent.com/4503241/84956566-7cfa9980-b0c7-11ea-8ae6-4f41fb74b3ed.png)

thx
