### ISSUE TITLE
Multiple databases with SpringTransactionManager

### ISSUE THREAD

**Issue by paulohenriqu** [JetBrains/Exposed#965]
Hi, I know I can use multiple databases if I use the transaction function, as per the documentation: https://github.com/JetBrains/Exposed/wiki/Transactions#working-with-a-multiple-databases

But I'm using Spring Boot, and my configuration is as follows:
```@Configuration
@EnableTransactionManagement
class DatabaseConfig(
        private val dataSource: DataSource
) {
    @Bean
    fun transactionManager() = SpringTransactionManager(dataSource)
}
```

In that way Spring is the one that manages the transactions.

Is it possible to have multiple datasources and choose the one I want to use with SpringTransactionManager?

**Comment by ravenblackdusk** [comment]
you can qualify your injected DataSource with `@org.springframework.beans.factory.annotation.Qualifier` or set one of your DataSource beans as `@org.springframework.context.annotation.Primary`. but be aware that if you're using `exposed-spring-boot-starter`, `org.jetbrains.exposed.spring.autoconfigure.ExposedAutoConfiguration` is creating the `SpringTransactionManager` bean for you.

**Comment by paulohenriqu** [comment]
Thanks, I don't know if it's the best way, but this configuration worked:

```@Configuration
class Datasource(){
    @Bean(name = ["datasource1"])
    @ConfigurationProperties("spring.primary-datasource")
    @Primary
    fun dataSource(): DataSource? {
        return DataSourceBuilder.create().build()
    }

    @Bean(name = ["datasource2"])
    @ConfigurationProperties("spring.secondary-datasource")
    fun secondaryDataSource(): DataSource? {
        return DataSourceBuilder.create().build()
    }
}

@Configuration
@EnableTransactionManagement
class DatabaseConfig(
        private val dataSource: DataSource, @Qualifier("datasource2") private val secondaryDataSource : DataSource
) {

    @Bean(name = ["tm1"])
    @Primary
    fun transactionManager() = SpringTransactionManager(dataSource)

    @Bean(name = ["tm2"])
    fun secondaryTransactionManager() = SpringTransactionManager(secondaryDataSource)
}

**Comment by bog-walk** [comment]
For further information about using `@Transactional` to specify a transaction manager, please see [the README](https://github.com/JetBrains/Exposed/tree/main/exposed-spring-boot-starter#configuring-additional-transaction-managers) and [the reference docs](https://docs.spring.io/spring-framework/reference/data-access/transaction/declarative/annotations.html). For a more comprehensive guide to setting up this configuration with Spring Boot and Exposed, here's [a user's tutorial](https://medium.com/@inzuael/how-to-use-multiple-datasources-with-springboot-exposed-jpa-6bd705bfe994).

If there are any further issues with using multiple datasources, please consider reporting them on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763).
