### ISSUE TITLE
SizedIterable Int/Long mismatch

### ISSUE THREAD

**Issue by j-mew-s** [JetBrains/Exposed#968]
Hi, I have been trying to upgrade Exposed from 0.21.1 to 0.24.1.

One of the changes is that the return type of count on SizedIterable to be a Long, implying that more than MAX_INT entries might be present. However, the limit() method accepts an Int for the limit, suggesting that only MAX_INT entries can be retrieved.

Is there some reason for this mismatch?

**Comment by Tapac** [comment]
Please read related [comment](https://github.com/JetBrains/Exposed/issues/451#issuecomment-452666776)

**Comment by j-mew-s** [comment]
Ah, thank you, that does explain it. So at present, if I select * from a table with more than Int.MAX_VALUE results I guess I end up with an exception?

This will not affect us for a very long time, it was just a little counterintuitive. However, if you wanted to cater for large data sets where people might potentially return that much data, I suppose you could implement SizedIterable for a list of lists (used only when count > Int.MAX_VALUE) and access element[index / Int.MAX_VALUE][element % Int.MAX_VALUE].

It sounds like an unlikely use case, though - closing this issue.
