### ISSUE TITLE
Creating unique constraint on two or more columns?

### ISSUE THREAD

**Issue by trnchawla** [JetBrains/Exposed#970]
I want to make sure that two column combination are always unique. ex: a customer can have two numbers and a customer can have only one entry for a number. number is primarykey.

object phoneno : Table() {
    val number = varchar("number", 15)
    val owner = varchar("name", 15)
    override val primaryKey = PrimaryKey(number)
    //how to create a unique constraint on number and owner column combined?
}

**Comment by dolgopolovwork** [comment]
https://github.com/JetBrains/Exposed/issues/239

**Comment by trnchawla** [comment]
I found above ticket earlier but am unable to understand how? uniqueIndex("index name") asks for a name that means it is creating different indexes on every column, it is not making sure (number, owner) are unique instead owner and number are unique separately.

**Comment by trnchawla** [comment]
@Tapac @dolgopolovwork can you please let me know if its already there ? can you please give me any example on how to create a unique constraint on two or more columns i.e combination of two or more columns should be unique.

**Comment by Tapac** [comment]
@trnchawla , feel free to check [that test](https://github.com/JetBrains/Exposed/blob/3f0e842e55377c0df733c4407b56de153f4a30cb/exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt#L264)

**Comment by trnchawla** [comment]
Thank you @Tapac  @dolgopolovwork,  it worked. Earlier I could not understood what @dolgopolovwork  was trying to convey.

Simply created an init block and call uniqueIndex.

    init {
        uniqueIndex("indexname", col1, col2)
    }
