### ISSUE TITLE
EnableTransactionManagement on spring boot starter

### ISSUE THREAD

**Issue by AlJuan** [JetBrains/Exposed#976]
Hi guys, I'm starting my first Kotlin + Exposed + Spring Boot app.

First i created a simple rest API with a DB connection using the SpringBootApplication annotation (without using exposed). 
Spring boot automatically imports @EnableTransactionManagement(proxyTargetClass=??) and decides if it has to use CGLib proxies or JDK Dynamic proxies.
When i had that working I added the https://github.com/JetBrains/Exposed/tree/master/exposed-spring-boot-starter dependency. 
 
The exposed starter adds @EnableTransactionManagement but sets proxyTargetClass to false (thats the default), then the application is forced to use JDK Dynamic Proxies. Im not sure if this was intended. I fixed it by adding @EnableTransactionManagement(proxyTargetClass = true) to my main class.

Should we add documentation about it in the readme? Maybe exposed needs proxyTargetClass = false and I'm missing something.

**Comment by userquin** [comment]
These annotation only serves to enable @Transactional interceptor on your
services/repositories and instructs spring to allow these annotations to be
present on interfaces and/or classes. If you set default value  on
proxyTarget, then only @Transactional on classes will be intercepted. If
you need annotate with @Transactional interfaces methods like Repositories
(spring data) you need to set proxyTarget to true and configure AOP or
CGILIB to allow spring create proxy instances at runtime.  Just read the
documentation on these annotation.
There is no need to configure to use AOP or Cgilib if you do not add the
dependencies, in fact, does not matter id you dont use @Transactional
annotation.
Also, i dont undertand why the starter enable these behaviour when depends
on developer strategy.

**Comment by userquin** [comment]
Ok, starter configure the infraestructure to allow inject tx manager used
by exposed on spring infrastructure so you can use @Transactional on your
business logic.
So, proxyTarget depends on your bussiness logic to change it to enable
AOP/Cgilib or none.
