### ISSUE TITLE
How to test repository?

### ISSUE THREAD

**Issue by LookBad** [JetBrains/Exposed#983]
Hi!

I need to know how can I test my repository. For example:
```
class AdminRepositoryImpl : AdminRepository {
    override fun create(builder: AdminParams): Int {
        return transaction {
            Admins.insert {
                it[login] = builder.login
                it[password] = builder.password
                it[createdAt] = DateTime.now()
            }[Admins.id].value
        }
    }
}
```
How can I test it? I use ktor + exposed, so I thought that "withTestApplication" will be work but it doesn't .

**Comment by Tapac** [comment]
You have to setup some embedded database in `@BeforeClass/@BeforeTest` to use it in your test app

**Comment by LookBad** [comment]
Ouu :( You don't support any "test mode" which save data in the memory? This can be very useful.

**Comment by Tapac** [comment]
It won't be possible to use DSL for querying data if it will be just emulation. The best way to test is to use the same database you expect to use in production because all databases have different behavior in different places. 

You could try to use embedded in-memory H2 with required [compatibility mode](http://www.h2database.com/html/features.html#compatibility).

**Comment by LookBad** [comment]
Ok. How does it work in rails? In RoR I can easily test model and methods which provide data.

**Comment by Tapac** [comment]
As I can see from a RoR documentation they just use in-memory SQLite. You can too.
Just call `Database.connect("jdbc:sqlite:file:test?mode=memory&cache=shared")` in place where you setup your test environment. 

But I will think about providing a separate test module.

**Comment by LookBad** [comment]
Hmmm....ok. I didn't know that H2 has "PostgreSQL Compatibility Mode". Ok, I will use H2 in tests. You should add some examples of testing advance queries - people should know how to do it right. Tests are important parts of creating an app.

**Comment by LookBad** [comment]
Should I close this issue?

**Comment by Tapac** [comment]
I think so. I marked issue with `to be documented` and I guess that it should be covered in wiki somehow.

**Comment by TheReprator** [comment]
i want to test the above mentioned insert operation, so i can i make sure, whether database is correctly inserted or not with test with the command, i gave, @Tapac @LookBad

**Comment by hfhbd** [comment]
Depending on your test/use case I use this test function:
```kotlin
@OptIn(ExperimentalContracts::class)
fun dbTest(
    name: String? = null,
    setup: suspend (Database) -> Unit = { },
    test: suspend (Database) -> Unit
) {
    contract {
        callsInPlace(setup, InvocationKind.EXACTLY_ONCE)
        callsInPlace(test, InvocationKind.EXACTLY_ONCE)
    }
    val dbName = name ?: "test${SecureRandom.nextUUID()}"
    val db = Database.connect("jdbc:h2:mem:$dbName;DB_CLOSE_DELAY=-1;", "org.h2.Driver")
    transaction(db) {
        runBlocking {
            setup(db)
        }
    }
    runBlocking {
        test(db)
    }
    TransactionManager.closeAndUnregister(db)
}
```
Remove the "features" you don't use, eg contracts, `suspend`, name etc.
Usage 
```kotlin
@Test
fun createTest() = dbTest(setup = {
    SchemaUtils.create(Places)
}) { db ->
    val controller = PlaceController(db = db)
    controller.create(place1)
    controller.create(place2)
    assertEquals(SimilarResult(null, listOf(place1)), controller.findSimilar(place1.copy(name = "Real")))
}
```
