### ISSUE TITLE
Foreign constraints not getting honored in case of unit test using in memory db

### ISSUE THREAD

**Issue by trnchawla** [JetBrains/Exposed#984]
Am doing unit testing and for that am using in memory db like this.

    fun setup(){
        Config.DB_URL = "jdbc:sqlite:file:test?mode=memory&cache=shared"
        Config.DB_DRIVER = "org.sqlite.JDBC"
        Config.DB_USERNAME = ""
        Config.DB_PASSWORD =""
        db = DataBaseConnection.getDBConn()!!
        TransactionManager.manager.defaultIsolationLevel = Connection.TRANSACTION_SERIALIZABLE
        transaction {
            addLogger(StdOutSqlLogger)
        }
    }

And am testing like this:

    @Test
    fun createCompanyOwnerSimpleTest(){
        transaction {
            DataBaseConnection.createEntities()
            val companyOwner = getCompanyOwner()
            val (created, ownerUUID) = CompanyOwnerApis.createCompanyOwner(companyOwner)
            assert(created == true)
            assert(ownerUUID != null)
            val dbOwnerList = CompanyOwner.select { CompanyOwner.email eq companyOwner.email }
            assert(dbOwnerList.count() == 1L)
            val dbOwner = dbOwnerList.first()
            assert(dbOwner[CompanyOwner.email] == companyOwner.email)
        }
    }

Issue here is that foreign constraints are not getting honored, am able to insert entries which should not be entered but in postgre db foreign constraints are getting honored in exposed framework and transaction is unsuccessfull, what are the changes I need to do in setting up in memory db?

**Comment by trnchawla** [comment]
@Tapac can you please point me to right place?

**Comment by trnchawla** [comment]
@Tapac could you please point me anything wrong with my approach of unittesting?

**Comment by Tapac** [comment]
@trnchawla , sorry for a late reply. 
Could you share an extended sample with both tables/entities mappings and functions as I can't understand the exception should be thrown?

Maybe the problem is in database case-sensitivity but I can't tell for sure.

**Comment by trnchawla** [comment]
object Student : Table() {
    val uuid = uuid("uuid").autoGenerate()
    val name = text("name)
}

object Subject : Table() {
    val uuid = uuid("uuid").autogenerate()
    val student = uuid("studentUUID" references Student.uuid
}

In unit test if I insert a subject like this it should fail:

Subject.insert {
    it[student] = someStudentUUID //this uuid should be part of student table, can't be any random uuid
}

But it is succeeding in unit test cases when am passing studentUUID which is not present in Student table, where am using in memory db as mentioned above.

**Comment by Tapac** [comment]
Could you please check will it fail if you replace:
`val student = uuid("studentUUID" references Student.uuid`
with
`val student = reference("studentUUID", Student.uuid)`
?

**Comment by trnchawla** [comment]
same issue happening, If I see the Table in postgre then foreign constraints are present but unit tests are not honoring those constraints.

**Comment by Tapac** [comment]
@trnchawla, I was not able to reproduce your problem with SQLite.
Which  SQLite version do you use? 
As I can see from the [docs](https://www.sqlite.org/foreignkeys.html#fk_enable) foreign key constraint check wasn't enabled by default on the very old SQLite versions.

**Comment by trnchawla** [comment]
testImplementation "org.xerial:sqlite-jdbc:3.32.3", am using 3.32.2

**Comment by Tapac** [comment]
@trnchawla, Could you share the reproducable sample via gist or place the whole .kt file here?

**Comment by trnchawla** [comment]
@Tapac I will share that in some time.

This is how am setting it up:

class CompanyOwnerApisTest {
    lateinit var db : Database
    @Before
    fun setup(){
        Config.DB_URL = "jdbc:sqlite:file:test?mode=memory&cache=shared"
        Config.DB_DRIVER = "org.sqlite.JDBC"
        Config.DB_USERNAME = ""
        Config.DB_PASSWORD =""
        db = DataBaseConnection.getDBConn()!!
        TransactionManager.manager.defaultIsolationLevel = Connection.TRANSACTION_SERIALIZABLE
        transaction {
            addLogger(StdOutSqlLogger)
        }
    }
}

And for reproduction I am entering data in a row which violates Foreign constraint.

**Comment by joc-a** [comment]
Hi @trnchawla. Please try [this](https://github.com/JetBrains/Exposed/issues/822#issuecomment-688991626).
