### ISSUE TITLE
[Feature Request] Join two tables with multiple columns in one comparison

### ISSUE THREAD

**Issue by DrewKiino** [JetBrains/Exposed#985]
## Use Case

So I have three tables `Pets`, `Races`, `PetRaces` and I want to do the following

```
Pets
id | pet_id 

Races
id | race_id 

PetRaces
id | race_id | position_id | pet_id 
```

**Show me a list of all Pets who have entered a race and won first place along with those who haven't entered a Race.** 

Which essentially means an exclusion of all Pets who have entered a Race and not have won first place.

I have a maybe complex sql statement like this
```sql
select *
from Pets t1
where t1.id not in
(
    select t2.pet_id
    from PetRaces t2
    where t2.id not in
          (
              select t1.id
              from PetRaces t1 inner join
                   (
                       select min(position) position, race_id
                       from PetRaces
                       group by race_id
                   ) t2 on t1.race_id = t2.race_id and t1.position = t2.position # <----- DOUBLE COLUMN JOIN HERE
          )
);
```
Which essentially gives me what I want. The way this works is that there are two subqueries,
1. Show me all first place `pet_ids` -> `1,2` from `1,2,3,4,5`
2. Show me all `pet_ids` not in that list from the same table -> `3,4,5`
3. Show me all `pet_ids` from `Pets` who are not in that list `1,2,6,7,8`

## Current Implementation 

I can only do the following here to my knowledge,

```kotlin
PetRaces.innerJoin(PetRaces, { race_id }, { race_id })
```

So it seems like I can only pass one column definition, I would like to do the following -
```kotlin
PetRaces.innerJoin(PetFaces, { PetRaces.race_id eq PetRaces.race_id and PetRaces.position eq PetRaces.position })
```

I tried doing two inner joins but the logged query statements don't match and are delivering the incorrect results so I believe this feature does not exist yet. Would love to have this.

**Comment by Tapac** [comment]
There is extended `join` version which accepts JoinType, columns to join and additional constraints:
```kotlin
PetRases.join(PetRases, JoinType.INNER) { 
   PetRaces.race_id eq PetRaces.race_id and PetRaces.position eq PetRaces.position 
}
```

**Comment by DrewKiino** [comment]
Oh that’s perfect. You can mark this as closed then. Thank you
