### ISSUE TITLE
How to deliberately fail a transaction?

### ISSUE THREAD

**Issue by trnchawla** [JetBrains/Exposed#987]
I need to abort the transaction, what is the elegant way to doing that? can you please point to me the API.

**Comment by trnchawla** [comment]
currently am throwing SQLException("message"), is that the right way to do it?

**Comment by trnchawla** [comment]
@Tapac is throwing SQLException would be enough or right way?

**Comment by Tapac** [comment]
@trnchawla , it depends on what you want to do thurther - if you don't need to execute code then exception is enougth, otherwise you could call `Transaction.rollback()` to drop the changes and continue the code execution.

**Comment by bog-walk** [comment]
Please consider reopening this issue on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763) if the problem requires more answers or if there are further issues using `Transaction.rollback()`.
