### ISSUE TITLE
No way to disable logging?

### ISSUE THREAD

**Issue by yay** [JetBrains/Exposed#99]
`Statement.executeIn` just does `transaction.monitor.notifyAfterExecution(transaction, contexts, statement)` unconditionally.

Is there are a way to disable these debug messages? I'm writing 1.2GB of data to the database, and it takes forever, presumably because every single insert statement is logged.

**Comment by Tapac** [comment]
Do you use your own log4j configuration or use Exposed default? 
In Exposed log4j.properties there is line `log4j.logger.Exposed=info, stdout` which should prevent from getting log messages in notifyAfterExecution, because Slf4jSqlLogger uses debug level by default.

**Comment by yay** [comment]
Hmm... I have no Slf4 dependency in the project. I had the logback dependency defined in the pom, but not used anywhere in the project. Anyway, I just commented it out, and now I don't get any log messages except:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

which, I guess, is normal? Because the rows are still added to the database.

**Comment by Tapac** [comment]
From Logback site: `Moreover, logback-classic natively implements the SLF4J API `, i guess it means that Exposed uses your logback configuration via slf4j api.

**Comment by yay** [comment]
Indeed, that was the case. Creating a `logback.xml` file and configuring logging level there did the trick. Thanks! However, I notice that insert performance is a lot slower than what I'd expect, even with logging disabled.

It's a really straightforward piece of code, not sure where the bottleneck is.

```kotlin
    transaction {
        for ((exchange, _market) in exchangeToMarketMap) {
            val dateFormat = SimpleDateFormat("yyyy-MM-dd")
            val path = basePath + exchange
            val walker = File(path).walk().maxDepth(1)

            for (file in walker) {
                val _symbol = file.nameWithoutExtension.trim()
                if (_symbol != exchange) {
                    val records = CSVFormat.DEFAULT.withFirstRecordAsHeader().parse(file.reader())

                    records.forEach {
                        val rec = it
                        val _date = DateTime(dateFormat.parse(rec.get(YahooDataColumns.date)))
                        val _open = BigDecimal(rec.get(YahooDataColumns.open))
                        val _high = BigDecimal(rec.get(YahooDataColumns.high))
                        val _low = BigDecimal(rec.get(YahooDataColumns.low))
                        val _close = BigDecimal(rec.get(YahooDataColumns.close))
                        val _adjClose = BigDecimal(rec.get(YahooDataColumns.adjClose))
                        val _volume = rec.get(YahooDataColumns.volume).toLong()

                        DailyQuotes.insert {
                            it[quoteDate] = _date
                            it[symbol] = _symbol
                            it[market] = _market
                            it[open] = _open
                            it[high] = _high
                            it[low] = _low
                            it[close] = _close
                            it[adjClose] = _adjClose
                            it[volume] = _volume
                        }
                    }
                }
            }
        }
    }
```

Sorry, it's probably a different but related question.

**Comment by Tapac** [comment]
I guess DBMS spent a lot of time on PK index rebuilding after each insertion.
You could try to turn this validation off (i.e. for [MySQL](http://stackoverflow.com/a/15501754/813981)) or/and use batch inserts.
Split `records` on chunks of 1000 records and execute on it
```kotlin
DailyQuotes.batchInsert(chunk) { rec -> 
     it[quoteDate] = DateTime(dateFormat.parse(rec.get(YahooDataColumns.date)))
     it[open] = BigDecimal(rec.get(YahooDataColumns.open))
        ...
     }
}
```
