### ISSUE TITLE
How to implement "complex" where condition?

### ISSUE THREAD

**Issue by davioooh** [JetBrains/Exposed#990]
Sorry for the not very specific title for this issue, but I have some doubts about how to correctly implement these two situation using Exposed DSL:

1.  Suppose I need to execute some math operation on a table column to implement the where condition:

    Products.select { Products.quantity * 2 eq 4 }

Is there a way to access a field value inside the lambda expression? Or the only way is to do something like this?

    Products.select { Products.quantity eq 4 / 2 }

2. Suppose I have a datetime field, and in my query I need to check only the date part. I'd like to code some thing similar:

    Orders.select { Orders.deliveryDateTime.toLocalDate() eq LocalDate.now() }

But I cannot tranform the value of `deliveryDateTime `field to implement the check, so I probably need to work with `LocalDateTime`.

 Maybe I'm missing something. Can you suggest the correct way to implement these cases?

**Comment by Tapac** [comment]
> Is there a way to access the current column

What do you mean by `current column`? 

`Products.select { Products.quantity * 2 eq 4 }` 
Should work, why do you want to replace it with `{ Products.quantity eq 4 / 2 }` which is wrong?

>Orders.select { Orders.deliveryDateTime.toLocalDate() eq LocalDate.now() }

You could use `Date` function like:
`Orders.select { Orders.deliveryDateTime.date() eq dateParam(LocalDate.now()) }`

**Comment by davioooh** [comment]
> What do you mean by current column?

Sorry, what I meant was: "accessing field value". An `Int`, in my example. I tried again and it actually works: maybe I had some trouble importing the right packages.

> You could use Date function

Thanks, I did't find this in docs.

Thank you very much.
