### ISSUE TITLE
binary type doesn't honor max length

### ISSUE THREAD

**Issue by neelkamath** [JetBrains/Exposed#993]
The `binary` fixed-length type doesn't seem to honor the provided length: no error is thrown, no warning is logged, and the image isn't even silently trimmed to the specified maximum number of bytes.

Pseudocode for table:
```kotlin
object Images : IntIdTable() {
    private val image: Column<ByteArray> = binary("image", 10)

    fun create(image: ByteArray): Int = transact {
        insertAndGetId { it[this.image] = image }.value
    }

    fun read(id: Int): ByteArray = transact {
        select { Images.id eq id }.first()[image]
    }
}
```
Pseudocode for test:
```kotlin
class ImagesTest : FunSpec({
    test("size") {
        val id = Images.create("wallpaper.jpg") // A file which is too large, say 400,000 bytes.
        println("Size: ${Images.read(id).size}") // Prints 400,000.
    }
})
```

**Comment by Tapac** [comment]
What Exposed version and database do you use?

**Comment by neelkamath** [comment]
Postgres 12.3

Kotlin 1.3.72 + JDK 8 + JVM 13

Gradle 6.5.1 dependencies:
```kotlin
val exposedVersion = "0.26.1"
implementation("org.jetbrains.exposed:exposed-core:$exposedVersion")
implementation("org.jetbrains.exposed:exposed-jdbc:$exposedVersion")
implementation("org.jetbrains.exposed:exposed-java-time:$exposedVersion")
```

**Comment by Tapac** [comment]
There is no client-side validation of length at the moment and PostgreSQL's `bytea` type doesn't have a limit param. That's why there is no exception. 
I will add validation to prevent unexpected value to be written into database.

**Comment by neelkamath** [comment]
Ohh. Thanks.

To me, it looked like the DB would provide validation since the docs don't explicitly state which DBs validate lengths by themselves, and the limitless `binary` type stated in its KDoc:
```
**Note:** This function is only supported by Oracle and PostgeSQL dialects, for the rest please specify a length.
```
Since the limited `binary` type didn't state anything about DB support in its KDoc, I assumed Postgres had limited `binary`s. Perhaps I have misunderstood where such documentation should go, but maybe the limited `binary` type's KDoc should similarly state that Postgres doesn't support it.

**Comment by apprme** [comment]
Is it expected that `select` queries where value in `where` clause exceeds column limit throw the exception as well?

As for me throwing exception on `insert` is better than silently truncating the value. But throwing on `select`... I am not so sure.

```
java.lang.IllegalArgumentException: Value 'impersonate:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJObXBRajJPNmZmZlgyblR2MW5GVFVNIiwicyI6ZmFsc2UsInQiOmZhbHNlLCJpc3MiOiJEZWxpZ2h0ZXggR21iSCIsImV4cCI6MTYwMDA4Mzg2NSwiaWF0IjoxNTk5NDc5MDY1LCJodyI6IjlJUnk5SVZKS2p5aCJ9._0O1bbWxJ8ot7JQnsqoJpqrsg1GZMzUtjNltRAms4Xc' can't be stored to database column because exceeds length (255)
    at org.jetbrains.exposed.sql.VarCharColumnType.notNullValueToDB (ColumnType.kt:541)
    at org.jetbrains.exposed.sql.IColumnType$DefaultImpls.valueToDB (ColumnType.kt:37)
    at org.jetbrains.exposed.sql.ColumnType.valueToDB (ColumnType.kt:71)
    at org.jetbrains.exposed.sql.statements.api.PreparedStatementApi$DefaultImpls.fillParameters (PreparedStatementApi.kt:13)
    at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.fillParameters (JdbcPreparedStatementImpl.kt:9)
    at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core (Statement.kt:53)
    at org.jetbrains.exposed.sql.Transaction.exec (Transaction.kt:129)
    at org.jetbrains.exposed.sql.Query.count (Query.kt:246)
```

**Comment by apprme** [comment]
Interesting that in case of `select` and `VarCharColumnType` it **does not** throw if argument is longer than `VarCharColumnType#colLength`, however it **throws** if it is longer than 255 🤯

```kotlin
  object T : Table("testlength") {
    val id = varchar("id", 5)
    override val primaryKey = PrimaryKey(id)
  }

  @Test
  fun shouldNotThrowWhenAboveLengthInSpec() {
    transaction {
      val s = "0".repeat((T.id.columnType as VarCharColumnType).colLength)
      T.select { T.id eq s }.count()
    }
  }

  @Test
  fun shouldNotThrowWhenAbove255() {
    transaction {
      val s = "0".repeat(300)
      T.select { T.id eq s }.count()
    }
  }
```

**Comment by asule90** [comment]
i still got this issue on postgresql.

![Screenshot from 2021-04-01 18-19-05](https://user-images.githubusercontent.com/10544636/113286797-e1b17880-9316-11eb-96e5-20867942a427.png)
