### ISSUE TITLE
How to use case insensitive regex match in where clause?

### ISSUE THREAD

**Issue by marcoconti83** [JetBrains/Exposed#995]
Hi everyone,
I would like to write a "where" clause using a case-insensitive regex with the DSL.

I can write a case-sensitive regex clause with:

```
Table.select { Table.field regexp filterByText }
```

I can see that [`RegexOp`](https://github.com/JetBrains/Exposed/blob/master/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Op.kt#L285) supports a `caseSensitive` boolean parameter, but I can't figure out how to express that parameter in the above code snippet. Any suggestion?

**Comment by hichem-fazai** [comment]
I can write case-**insensitive** regex like this:

````KOTLIN
Table.select { Table.field.regexp(stringLiteral(filterByText), false) }
````

The problem here is that using `infix regex` function you can't pass `caseSensitive` boolean parameter, so there is the `regexp(pattern, caseSensitive)` method to do the job 😉

**Comment by marcoconti83** [comment]
Thanks @hichem-fazai , that works!
