### ISSUE TITLE
DAO Architecture

### ISSUE THREAD

**Issue by FelixStumvoll** [JetBrains/Exposed#997]
I am currently trying out this library but i'm a bit curious how an architecture with the rich domain model/DAO would look like.
for example i want create a new entity but before i would like to validate the data. in a standard service->dao->db architecture i would do this in the service layer. 
however i'm not quite sure how i would do this with the exposed daos.

**Comment by sunqitao** [comment]
class PersonService {
    companion object{
        fun getTopUser():List<User>{
            val userList = ArrayList<User>()
            transaction {
                val res = Users.selectAll().limit(5)
                res.forEach {
                    userList.add(User(id = it[Users.id],name =it[Users.name],email = it[Users.email] ))
                }
            }
            return userList
        }
    }
}
object Users:Table("user"){
    val id = long("id").autoIncrement()
    val name = varchar("name",length = 64)
    val email = varchar("email",length = 64)
}
data class User(val id:Long,val name:String,val email:String)

**Comment by sunqitao** [comment]
User： entity
PersonService：service
Users ： Dao

**Comment by FelixStumvoll** [comment]
ok so you are splitting up the DAO and the Entity in two seperate classes

**Comment by sunqitao** [comment]
> ok so you are splitting up the DAO and the Entity in two seperate classes

yes

**Comment by bog-walk** [comment]
For future reference, here are links to some opinions on DAO setup and key issues to track regarding DAO entities:

- GH issue #24 
- GH issue #497 
- [EXPOSED-463](https://youtrack.jetbrains.com/issue/EXPOSED-463/Support-for-DTOs-detached-POJO-entities)
