### ISSUE TITLE
Referencing a DAO entity without load

### ISSUE THREAD

**Issue by toth-istvan-zoltan** [JetBrains/Exposed#999]
Hi,

I haven't found it in the documentation, so I would like to ask. Is this correct? Or did I miss something?

Based on [https://github.com/JetBrains/Exposed/wiki/DAO#referencing](https://github.com/JetBrains/Exposed/wiki/DAO#referencing)

My goal is to avoid loading the objects. StarWarsFilm and User in this case.

```kotlin
UserRating.new {
    value = 10L
    film = StarWarsFilm(EntityID(12, StarWarsFilms))
    user = User(EntityID(14, Users))
}
```

**Comment by bog-walk** [comment]
Please reopen this issue if the problem requires more answers.
